### ISSUE TITLE
Deleting blobs - "your view may be out of date"

### ISSUE THREAD

**Issue by darthkurak** [microsoft/AzureStorageExplorer#1012]
Hi. I think this is not a bug per se, but i would categorize this as changed behavior which complicate UX experience.

I don't know what reasons stay behind this, but want to notice, that it's really annoying "feature" and I would love to have a option to disable it.

Previous behavior:
When we did deletion of blobs, the current list of blob was automatically refreshed.

Current behavior:
When we did deletion of blobs, yellow bar came up notifying user that view may be out of date and ask us to refresh it or not. 
User have to click yes, to refresh the current list.

**Comment by jinglouMSFT** [comment]
The main reason we changed to manual refreshing is because we don't want to auto-refresh the view if/when the user has switched to a different operation after having started a long running operation, say uploading, download, or deleting blobs. The auto-refresh would be disruptive in this case.  Down the road we could try to build something more intelligent to detect if we need to auto-refresh or manual refresh, or just make auto-refresh a setting.  But thank you for letting us know your feedback.

**Comment by darthkurak** [comment]
Auto-refresh as setting would be a great. I never (and I'm using Explorer a lot) faced this disruptive behavior. But now - each time, i have to delete something - i have to also manual refresh, which is regress to previous workflow :)

**Comment by craxal** [comment]
As Jing mentioned, auto-refresh could be disruptive to users viewing containers with many blobs in them. A refresh forces the pages to shift around which could disrupt their workflow.

However, we recognize that users such as yourself might just want the list of blobs to refresh! We'll look into getting this fixed. However, this isn't trivial. So that we can better address your concern, how would you expect auto refresh to function? For example, if you were on page 7 of 10 and you deleted a blob, would you expect the view to return to page 1? Or, if you uploaded 100 new blobs, where would you expect the view to go after refresh?

**Comment by Telaran** [comment]
@craxal 
I don't remember how it was solved previous these changes, but as strange as it sounds.. I do miss the "old Auto-Refresh".

As a developer I can imagine how complex (and resource consuming) a solution would be to determine the correct position after a change. Therefore personally I would be satisfied with a simple "Go back to page 1" - Workaround which could be enabled on the settings (label like "Enforce Auto-Refresh to Page 1"). 

Maybe if more important fixes and features are done, it can be considered to add a "correct position after change"-Auto-Refresh behavior.

Just my 2 cents on the topic :wink:

**Comment by craxal** [comment]
@Telaran, this is excellent feedback. Thank you!

Ironically, the "refresh to page 1" behavior wasn't our doing at all. It was just an automatic behavior of the table functionality we use.

**Comment by tomridl** [comment]
I would like to second this request, also really like the old behaviour of auto-refresh after delete.

**Comment by MRayermannMSFT** [comment]
This is fixed! We're back to refreshing automatically by default, and if you liked the old behavior, there's a setting to reenable it. :)
