### ISSUE TITLE
The enabled and visible bindings for actions are not evaluated until context menu or actions panel are opened

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#1040]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190104.2
**Commit:** 6ad194d8
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Expand an ADLS Gen2 account -> Blob Containers -> Create a blob container.
2. Select the blob container and press "F2".

#### Expected Experience: ####
Nothing happens after pressing "F2".

#### Actual Experience: ####
The "Rename" dialog pops up.

**More Info:**
Pops up an error dialog after renaming.

![image](https://user-images.githubusercontent.com/41351993/50679749-beb49300-103f-11e9-8bd0-9cae2828ab82.png)

**Comment by MRayermannMSFT** [comment]
Fix merged into hotfix branch.

**Comment by v-xianya** [comment]
Verified on build 20190108.1. 
1. This issue also reproduces on Window/Linux.
2. This issue doesn't reproduce on MacOS.

**Comment by MRayermannMSFT** [comment]
If you open the context menu and then try to do F2, or open the Actions panel and try to do F2, the bug shouldn't occur. Turns out what's going on is that whether or not an action should be enabled/visible isn't determined for the first time until one of the those two things happen. So I'm going to rename this bug to be that issue.

**Comment by MRayermannMSFT** [comment]
Fix merged into master.
