### ISSUE TITLE
Show an unexpected error when trying uploading a page blob not in a multiple of 512 bytes

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1050]
**Storage Explorer Version:** 1.6.2
**Platform/OS Version:** Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture:** ia32/x64
**Build Number:** 20190108.1
**Commit:** 1d51960b
**Regression From:** Regression from 1.5.0 release (build: 20181026.3)

#### Steps to Reproduce: ####
1. Uncheck 'Use AzCopy for Improved Blob Upload and Download' under Experimental.
2. Expand a non-ADLS account -> Blob Containers -> Create a new blob container.
3. Upload a file as page blob that isn't a multiple of 512 bytes in length to it.
4. Check the Activities.

#### Expected Experience: ####
Show errors like the below:
![image](https://user-images.githubusercontent.com/41351993/50818394-c76bd880-1361-11e9-8949-a9f7b1ab11ef.png)

#### Actual Experience: ####
Show the below error messages in Activities.
![image](https://user-images.githubusercontent.com/41351993/50817212-1fa0db80-135e-11e9-90b0-799cbf008c2b.png)
Detail: {"message":"\"Upload failed unexpectedly after 5 attempt\""}

**Comment by craxal** [comment]
Drilled down into the storage client library and found out they're explicitely throwing an error in a callback instead of passing the error to our callback. Since callbacks are asynchronous, the original try/catch context is lost, and therefore there's no way for us to properly catch and handle it.

@XiaoningLiu, can we get this fixed?

**Comment by craxal** [comment]
We can add a workaround where we check the file size manually.
