### ISSUE TITLE
Unexpected activity in activity log notifying me that I canceled changing access tier

### ISSUE THREAD

**Issue by MRayermannMSFT** [Microsoft/AzureStorageExplorer#108]
**Storage Explorer Version**: 1.1.0 RC ()
**Platform**: Linux
**Architecture**: x64
**Build Number**: 2018501.1
**Commit**: 754b96f7
**Regression From**: N/A

1. Change access tier of a Storage Account
2. Cancel out of the options dialog

I wouldn't expect there to be a notification in the activity log saying that I cancelled changing the access tier. As far as I'm concerned, I haven't started changing it because I never chose a tier to change it to.

**Comment by JakeRadMSFT** [comment]
With our new patterns of pulling things out into job handlers ASAP. I think it's a good idea to let the user know what's happening. Since dialogs occasionally have the tendency to be on different screens etc... I think it's a good idea to show in the Activity log that it's trying to prompt or that the user canceled.

**Comment by MRayermannMSFT** [comment]
Fair enough. 👍
