### ISSUE TITLE
Fail to upload VHD files to premium account using AzCopy

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#1111]
**Storage Explorer Version:** 1.6.2/20190131.3
**Platform/OS Version:** Windows x64/Linux Ubuntu 16.04/MacOS High Sierra
**Architecture:** ia32
**Commit:** 25a1398e
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Make sure the item 'Use AzCopy for Improved Blob Upload and Download' is enebled.
2. Choose one premium account -> Open one blob container.
3. Try to upload one VHD file to the opened blob container -> Check the result.

#### Expected Experience: ####
The VHD file can be uploaded successfully using AzCopy.

#### Actual Experience: ####
Fail to upload the VHD file to premium blob container using AzCopy with the below error.
![image](https://user-images.githubusercontent.com/34729022/52041723-36f67180-2576-11e9-89ca-b67d108225c7.png)
#### More info: ####
1. This issue doesn't reproduce when the item 'Use AzCopy for Improved Blob Upload and Download' is disabled.
2. This issue doesn't reproduce when uploading VHD files to one normal blob container using AzCopy.
3. This issue doesn't reproduce when uploading VHD files to ADLS Gen2 blob container.

**Comment by MRayermannMSFT** [comment]
@v-xuanzh , I'll be merging a change shortly which changes the upload dialog to this for AzCopy:
![image](https://user-images.githubusercontent.com/21112697/52155635-9a48d800-2638-11e9-8c42-2ad6fae70618.png)
For this bug, you'll need to select page blob when uploading to the premium account. Also, I know that this makes this dialog even more confusing/wrong/not true for ADLS Gen2 (since there aren't blob types for ADLS Gen2...), but unfortunately I didn't have time to address that today. I'll get to that while y'all are on vacation. 😄

**Comment by MRayermannMSFT** [comment]
Merged into master.

**Comment by v-xuanzh** [comment]
@MRayermannMSFT Thanks for your updates and sharing. :)
