### ISSUE TITLE
Open Blob 'Folder' Under A Different Account Same Instance Opens in the Original Context

### ISSUE THREAD

**Issue by schellem** [Microsoft/AzureStorageExplorer#1136]
**Storage Explorer Version**: 1.6.2

I'm testing blob access to a test user account all works as expected. If I try to generate a SAS I get an error. If I go to my 'admin' account and attempt to open same storage/blob/folder to generate a SAS I get redirected to the storage/blob/folder under the test account. i.e. the tree UI moves away from my admin account and highlights the folder under the test account. 

Restarting ASE is the only way to be able to open the same storage/blob/folder under another account.

**Expected Experience**
That I connect as the user who's tree I am navigating not one that I may have used prior

**Actual Experience**
Connection context refers to prior user and UI even moves you to that tree

**Comment by craxal** [comment]
@schellem Please look over our [bug template](https://github.com/Microsoft/AzureStorageExplorer/issues/new/choose) and fill it in as precisely as you can. In particular, we need to know your current version and _exact_ repro steps.

**Comment by schellem** [comment]
I am using 1.6.2 and have supplied fairly decent direction already. Sorry but this tool has already wasted enough of my time on this and other bugs it has.

**Comment by MRayermannMSFT** [comment]
Hey @schellem , I think I understand what you're running into. What you can do is either:
1. Right click on the admin account's copy of the container and choose "Open In New Tab".
2. You can close the tab that was opened when you clicked on the user's copy of the container, and then click on the admin's copy of the container to open it.

What's going on is that because they are the "same" container, we'll go to the tab that is already opened for the container. Also, when you change editors, we move the tree view selection to the node that the tab was originally opened from, which explains why you see the tree view selection changing.

If you think this isn't super intuitive/a good design, I'd actually agree with you. We'll try to think about a better way to handle opening the "same" container/file share/etc. from the same subscription, but from a different account.

As for the error you got when generating a SAS, I'm not sure why that might be. If you can share the error (assuming you continue to receive it with your admin account) we can help you figure out what's going wrong.

Anyway, let me know if you're still blocked/my 2 options don't work for you/if you continue to get errors when generating a SAS from your admin account.

**Comment by schellem** [comment]
I'm just testing how we can get users off FTP and use Azure storage as a secure location to pass files around. The SAS generation error only occurred while using the limited access testing account I was working with, I guess I need more than just Storage Blob Contributor rights for creating a SAS.

Our real show stopper with ASE and Azure storage is on the issue I have reported with ASE trashing the internet connection when uploading a large file.

**Comment by MRayermannMSFT** [comment]
That is correct. To generate a SAS you need to have had permissions to list the account's keys. For the trashing issue, let me do some more research about how using the upload side of your network effects the download side. I'll report any findings for that on your other issue.

**Comment by schellem** [comment]
Thanks 
[Here ](https://github.com/Microsoft/AzureStorageExplorer/issues/1099)is link to the network issue

**Comment by MRayermannMSFT** [comment]
Just replied!
