### ISSUE TITLE
Cannot navigate to a deep folder in ADLS by providing folder path

### ISSUE THREAD

**Issue by vishaltmsft** [microsoft/AzureStorageExplorer#1298]
**Storage Explorer Version**: 1.7.1
**Platform/OS**: Windows 10
**Architecture**: x64

**Bug description**
I have a big ADLS account with deep folder structure. I can't directly navigate to, say /local/foo1/foo2/foo3/foo4/ folder directly in the UI. I have manually navigate 4 levels deep to arrive that location. Data Explorer on Azure Portal allows one to provide a folderPath and directly navigate to it.

**Steps to Reproduce**
1. Open a ADLS Folder Account
2. Attempt navigating to a deep folder path

**Expected Experience**
I expect the UX accept a well formed string in the form on /folder1/folder2/folder3 (potentially with a trailing '/') and directly navigate to that location.

**Actual Experience**
The UI blocks that form of navigation. The breadcrumbs control is read-only (and updated by the app). Users can't provide a path to directly navigate to it.

**Comment by caksoylar** [comment]
It is worth noting that URIs with `adl://` prefix are associated with Azure Storage Explorer. This lets you open a specific folder path directly, for instance through the "Run" dialog. However the whole entered path acts like a single folder in the hierarchy, so that the "Up" button goes to the root no matter where you are.

**Comment by craxal** [comment]
Related to #45.
