### ISSUE TITLE
Impossible to make a query that fetch Int64 azure storage table

### ISSUE THREAD

**Issue by workzer** [microsoft/AzureStorageExplorer#1382]
Hey, I've tried to fetch some data using "Microsoft Azure Storage Explorer", one column has the type set to Int64, when I try to fetch anything, I get the error "There is a syntax error in the table query", if I remove some digit to get an Int32, everything works.

I've also tried with a script in javascript using the package azure-storage V2.10.3, and I get a 400 error: **Unrecognized 'Edm.Int32' literal '5454161346626'**

It seems the API try only to manipulate the data as an Int32.
Maybe there is a way from my side to force it as an Int64, but I haven't found anything about it.

Another weird thing is, if I don't set the type, my number 5454161346626 become a Double and I got the same problem as before.

**Comment by StannieV** [comment]
Hi there,

I've just encountered the same problem and found the solution. In order to create a valid query for Int64 numbers, you have to add an '**L**' to the number. Like:

`pn eq '15162' and ts ge 1574726400000L`

Unfortunately, the Microsoft Azure Storage Explorer doesn't add the '**L**' for you, even if you specify the query designer.
