### ISSUE TITLE
Failed to upload to blob container using SAS generated from Office portal

### ISSUE THREAD

**Issue by grundencp** [microsoft/AzureStorageExplorer#140]
**Storage Explorer Version**: 1.0.0

**Platform**: Windows

**Architecture**: ia32

**Build Number**: 20180415.2

**Commit**: 5d603052

**Regression From**: Yes.  0.9

#### Steps to Reproduce: ####

1. Connect to Azure storage using SAS URI provided by Office 365 Security & Compliance portal import pst wizard.
2. Upload .pst file(s) to Local and Attached\Storage Accounts\(SAS-Attached Services)\Blob Containers\ingestiondata\ using drag& drop or Upload button.

Tried with multiple files.
Also detached storage and re-attached storage.

#### Expected Experience: ####
Activities display file upload progress.

#### Actual Experience: ####
Activities displays "Failed to upload '...pst' to ingestiondata/....pst: Forbidden"
```
{
  "name": "StorageError",
  "message": "Forbidden",
  "stack": "Error\n    at Function.StorageServiceClient._normalizeError (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:1189:23)\n    at Object.StorageServiceClient._processResponse (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:736:50)\n    at Request.processResponseCallback [as _callback] (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\lib\\common\\services\\storageserviceclient.js:311:37)\n    at Request.self.callback (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:188:22)\n    at emitTwo (events.js:125:13)\n    at Request.emit (events.js:213:7)\n    at Request.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1171:10)\n    at emitOne (events.js:115:13)\n    at Request.emit (events.js:210:7)\n    at IncomingMessage.<anonymous> (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\azure-storage\\node_modules\\request\\request.js:1091:12)",
  "code": "Forbidden",
  "statusCode": 403,
  "requestId": "38286db1-a01e-00be-451a-e394d1000000"
}
```

**Comment by craxal** [comment]
OK, key phrase is "Office 365 Security & Compliance". I think they made some changes recently to the way they generate their SAS tokens.

Can you provide the SAS token (minus the `sig` part)? More specifically, what are the permissions on the SAS?

**Comment by grundencp** [comment]
Thanks for looking into my issue!

Here is the SAS URL:

https://549349f66ee1493dae58b20.blob.core.windows.net/ingestiondata?sv=2015-04-05&sr=c&si=IngestionSasForAzCopy201805031956015308&sig=...&se=2018-06-03T12%3A32%3A43Z

I’m not sure how to view the permissions on the SAS.  Can you offer any guidance?

Chris Grunden
Systems Engineer
[Description: Description: Description: cid:image001.png@01D16029.B7E6FFF0]
International Medical Group®, Inc.
2960 North Meridian Street
Indianapolis, IN 46208 USA
Direct: 1.317.655.4570
Chris.Grunden@imglobal.com<mailto:Chris.Grunden@imglobal.com>
www.imglobal.com<http://www.imglobal.com/>

**Comment by craxal** [comment]
Ah, so your SAS is associated with an access policy (`si=IngestionSasForAzCopy201805031956015308`). So we're out of luck as far as permissions go.

Storage Explorer does a quick check to see if a blob exists before attempting to upload a file. This check requires List permissions. I dug into some old emails and can confirm that the Office guys dropped List access from the SAS tokens they generate. That's why Office SAS doesn't work anymore.

AzCopy is a very decent command-line alternative to uploading your files using your SAS for the time being. We're currently working on a better upload solution.

**Comment by grundencp** [comment]
Thanks!

It looks like AzCopy is working for me now.

Just FYI, my early attempts (months ago) to use AzCopy for .pst imports failed, which is why I started using Azure Storage Explorer.  I love your tool!  Please keep up the good work.

Chris Grunden
Systems Engineer
[Description: Description: Description: cid:image001.png@01D16029.B7E6FFF0]
International Medical Group®, Inc.
2960 North Meridian Street
Indianapolis, IN 46208 USA
Direct: 1.317.655.4570
Chris.Grunden@imglobal.com<mailto:Chris.Grunden@imglobal.com>
www.imglobal.com<http://www.imglobal.com/>

**Comment by MRayermannMSFT** [comment]
The fix for this was shipped in 1.3.0.

**Comment by SilentSausage** [comment]
Can you confirm if this issue has definitely been resolved?  Using version 1.11.1, same results as the original, response from Log:

 RESPONSE Status: 403 This request is not authorized to perform this operation using this permission.
[f001b0ac-e362-784a-4373-cd4ea72061a5.log](https://github.com/microsoft/AzureStorageExplorer/files/3971692/f001b0ac-e362-784a-4373-cd4ea72061a5.log)

**Comment by craxal** [comment]
@SilentSausage Can you take a good look at the SAS? Does it have an `si` parameter but no `sp` parameter? Is the token expired? If the token only has an `si` parameter, can you ask someone from Office (or whomever is giving you the SAS) what permissions the shared access policy provides?

**Comment by SilentSausage** [comment]
@Craxal - SAS URI Was generated from the O365 Security & Compliance Portal > Information Governance > Import PST Files

URL Appears to be missing an SP Parameter:

sv=2015-04-05
sr=c
si=IngestionSasForAzCopy201912170330312109&sig=tJT7uD%2BY%2Bo5NoSKSlNNX6ZVkLl4jcj0MqOskAN%2FrNzE%3D&se=2020-01-17T02%3A33%3A20Z

So I guess rather than being a Azure Storage Explorer Issue this is an Office 365 Issue perhaps?

**Comment by craxal** [comment]
@SilentSausage The `sp` parameter is optional if the permissions are defined by the shared access policy with ID "IngestionSasForAzCopy201912170330312109". Unfortunately, there's no way I'm aware of to see what permissions that policy supplies unless you have access to see the policy. That's why you'd probably have to ask someone from Office.

**Comment by SilentSausage** [comment]
Just to update I have found a workaround in version 1.11.2. By going to **Edit > Target Azure Stack APIs**  and then restarting, re-adding the SAS URI - I'm able to upload to the blob.

**Comment by craxal** [comment]
@SilentSausage Now that's interesting. Thank you for sharing that.

Does that mean O365 is using a different cloud than public Azure? Are they using an older API version?

**Comment by amontaleone** [comment]
I have been working on this almost allllll day.. @SilentSausage I LOVE YOU MAN!!!

**Comment by JasonYeMSFT** [comment]
@SilentSausage @amontaleone Can you try the same upload with AzCopy from the command line with environment variable `AZCOPY_DEFAULT_SERVICE_API_VERSION=2017-04-17`?

At the point it is hard to determine if it is an AzCopy issue or it is an api version issue. Due to some old AzCopy bugs, we fall back to use old JavaScript code to perform upload. Thus the work around can be based on either using an older api version or not using AzCopy or both.

**Comment by JasonYeMSFT** [comment]
Hit the wrong button.
