### ISSUE TITLE
Always keep loading when trying to open a new instance on mac

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#1437]
**Storage Explorer Version:** 1.8.1
**Build**: 20190605.4
**Branch**: master
**Platform/OS:** macOS High Sierra, Ubuntu 18.04
**Commit:** a7b2b07e
**Regression From:** Previous release 1.8.1

**Steps to reproduce:**
1. Launch Storage Explorer.
2. Go to File -> New Window.
3. Check the result.

**Expect Experience:**

A new window appears.

**Actual Experience:**

Always keep loading.
![image](https://user-images.githubusercontent.com/41351993/58943525-7fd36680-87b2-11e9-8fdc-61e9d5180d19.png)

**More Info：**
This issue doesn't reproduce on windows

**Comment by craxal** [comment]
Verified on my Linux machine. Strange, this only seems to happen with a finished build. Running from source code doesn't appear to have this issue.

**Comment by louisrigot** [comment]
I have the exact same issue on my Mac running Mojave 10.14.5 (18F132), let me know if i can provide additional info. I tried running older versions of the app (1.7.x, 1.6.x), removing the preference files etc. but nothing works.

**Comment by craxal** [comment]
@louisrigot Close any instances of Storage Explorer and open up Activity Monitor on your Mac. Do you see any Storage Explorer or Electron processes running? If so, kill all of those processes and try launching Storage Explorer again.

**Comment by craxal** [comment]
Reproduced in master branch as well, so this is not due to main host changes.

**Comment by v-xianya** [comment]
Hi @craxal Verified this issue on the build master/20190702.3. It doesn't reproduce.

**Comment by craxal** [comment]
@louisrigot Are you still experiencing this issue? What are you trying to do when you attempt to open a second instance (window) of Storage Explorer?

We're using an old proprietary method of app instance management, which admittedly is kinda nasty. We're running a fairly old version of the Electron framework, which has since [added some APIs](https://electronjs.org/docs/all#apprequestsingleinstancelock) that we should leverage.

**Comment by louisrigot** [comment]
@craxal
> @louisrigot Close any instances of Storage Explorer and open up Activity Monitor on your Mac. Do you see any Storage Explorer or Electron processes running? If so, kill all of those processes and try launching Storage Explorer again.

I can't find any Electron or Storage Explorer processes when the app is closed.

> @louisrigot Are you still experiencing this issue? What are you trying to do when you attempt to open a second instance (window) of Storage Explorer?

It seems I misread the issue, my problem is that I basically can't run any Storage Explorer instance at all on my Mac at this point, and this issue seems the closest to what I experience.

I downloaded the latest version of the app (1.90), restarted (since I run a few other electron apps, normally) and made this screen recording before launching any other app. The behavior is still the same as all the other versions:

- I launch the app, the splash screen appears, then disappears, then nothing happens
- I click "New Window", a new instance launches (as you can see in the Dock) and the splash screen appears again
- This time, I see the EULA, I click accept, nothing happens
- I can keep opening new instances of the app, I'll basically always get the EULA then nothing

Screen recording: https://youtu.be/cye-1hr-eiQ

**Comment by craxal** [comment]
@louisrigot Since this is a separate issue, and if you don't find a similar bug, please open a new issue. While you do that, can you try these?
1. Run Storage Explorer from the command line and observe the output.
   ```bash
   Microsoft\ Azure\ Storage\ Explorer.app/Contents/MacOS/Microsoft\ Azure\ Storage\ Explorer
   ```
2. Remove any existing files as described in our troubleshooting guide. Only do this if you're OK with signing in again or don't care about any Quick Access or attachments.

**Comment by craxal** [comment]
@v-xianya I seem to be having trouble reproing with current builds does this still happen? Make sure you kill any other Storage Explorer processes before you try.

**Comment by louisrigot** [comment]
@craxal 
> 1. Run Storage Explorer from the command line and observe the output.

```shell
louis$ Microsoft\ Azure\ Storage\ Explorer.app/Contents/MacOS/Microsoft\ Azure\ Storage\ Explorer
2019-07-08 20:04:51.631 Microsoft Azure Storage Explorer[30303:5821089] *** WARNING: Textured window <AtomNSWindow: 0x7f93336c1d60> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

> 2. Remove any existing files as described in our troubleshooting guide.

This solved my issue, thank you! I backed up what was in `/Users/<your_name>/Library/Application Support/StorageExplorer` if you're interested. Do you still need me to file a new issue?

**Comment by craxal** [comment]
@louisrigot No, I think you're fine. It sounds like persistent files were corrupted, which really scrambles the launch process. That's something we can/should fix, but we already have issues open on those. Glad we could help you get unstuck!

**Comment by v-xianya** [comment]
Hi @craxal .
Verified this issue on the build feature/main-host 20190624.2 **without any other Storage Explorer processes**.
It still reproduces.

**Comment by craxal** [comment]
@v-xianya That's a pretty old build. There's at least one (20190701.2) that's newer.

**Comment by craxal** [comment]
Aha, nailed it!

Since new app instances have clean local storage, we lose any indication that a user has accepted the EULA, so a new instance tries to open the EULA dialog. However, dialogs need to wait for the main window to show to function properly (for some reason). The main window doesn't show until app initialization completes. But the EULA response is part of initialization, thus resulting in a deadlock. A similar problem occurs on Linux. Since Windows never shows the EULA, Windows never locks up.
