### ISSUE TITLE
Error: nothing can be uploaded, please use --recursive to upload directories

### ISSUE THREAD

**Issue by Sripalreddy09** [microsoft/AzureStorageExplorer#1456]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:  

## Additional Context ##
```json
{   "message": "\"failed to perform copy command due to error: cannot start job due to error: nothing can be uploaded, please use --recursive to upload directories.\\n\"" }
```

**Comment by craxal** [comment]
Hi @Sripalreddy09. It is unclear from your initial comments what you are trying to accomplish. In order to investigate your issue further, please edit your comment by adding the following to the appropriate sections:
- The version of Storage Explorer you are using.
- A description in your words of the problem you're encountering. Include the context and a description of what you are trying to accomplish.
- A list of steps that we can follow to encounter the same issue.

**Comment by MRayermannMSFT** [comment]
@Sripalreddy09 , it looks like you're using AzCopy from the error message. Can you try running the upload manually on the command line? You can use the "Copy AzCopy Command to Clipboard" action to get a copy of the command, and then if you download AzCopy v10 you can run the command against it. Let us know if you need help with that!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
