### ISSUE TITLE
AzCopy v10 many warnings in Event Viewer when uploading big files

### ISSUE THREAD

**Issue by hectorgb733** [microsoft/AzureStorageExplorer#1505]
When trying to upload a file of 100 MB or bigger using AzCopy v10 to a BLOB Container in a Storage Account, the file gets uploaded but there are many warnings in Event Viewer with the following message: 
The description for Event ID 0 from source ...\azcopy.exe cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

==> REQUEST/RESPONSE (Try=1/51.1780689s[SLOW >3s], OpTime=51.1780689s) -- RESPONSE SUCCESSFULLY RECEIVED
...

Could you please fix this?
Thank you.

**Comment by JasonYeMSFT** [comment]
Hi,

Can you provide detailed steps on how to reproduce this issue? We don't own AzCopy, but we can help you open an issue at their repo to see if it can be fixed. 

Thank you.

**Comment by hectorgb733** [comment]
Just send a file of more than 100 MB to a BLOB container in an storage account using AzCopy v10 and take a look at the Application logs in Event Viewer. I'm using a SAS Token to connect to the BLOB. The command I'm using would be something like this: cmd.exe /c .\AZCopy\azcopy cp "C:\Temp\_000003_MyTest100MBFileV6.bak" "https://gesxxxxxxxx.blob.core.windows.net/gesxxxxxxx/Core/100MBV6.bak?sv=2018-03-28&sig=Cc3Zxxxxxxxx%3D&spr=https&se=2019-06-26T13%3A14%3A59Z&srt=o&ss=bf&sp=rwl" --log-level ERROR

**Comment by JasonYeMSFT** [comment]
Hi,

Thank you for the additional information. We have opened an issue for the AzCopy team to investigate and address your concern. You can refer to that issue at https://github.com/Azure/azure-storage-azcopy/issues/469.

**Comment by JasonYeMSFT** [comment]
AzCopy has fixed the problem. Closed.

**Comment by AlexG7796** [comment]
Hello.
Sorry, but this is not fixed.
![1](https://user-images.githubusercontent.com/57005342/67574130-8d2dc500-f742-11e9-8052-9f45d565f72a.jpg)
![2](https://user-images.githubusercontent.com/57005342/67574134-9028b580-f742-11e9-928e-fe020d9026e4.jpg)

**Comment by MRayermannMSFT** [comment]
Hey @AlexG7796 , I see that you replied to issue we opened in the AzCopy repo. Thank you for doing that. I'll make sure the AzCopy devs are aware of your continued problems. Once they fix it on their end, we'll take the newer version as soon as we can.

**Comment by ImranNaqvi85** [comment]
![image](https://user-images.githubusercontent.com/67109965/85030690-9edd3600-b132-11ea-82ca-5d8bcbbf85f7.png)
I'm facing this issue

**Comment by jinglouMSFT** [comment]
@ImranNaqvi85 the error said azcopy_windows_amd64.exe can not be found or corrupted in the directory specified.  Have you tried to navigate to that directory to see if the file was there? or try to reinstall Storage Explorer if it's corrupted?  Let use know your findings. Thanks.

**Comment by JasonYeMSFT** [comment]
@jinglouMSFT, the error says the description from the AzCopy executable cannot be found, not the executable file.

@ImranNaqvi85 , since your issue is different from the original one, could you please open another issue so we can investigate and track it? Other than the information in the bug template, it would be great if you can share the full info of the error in your event viewer. Your screenshot is truncated at the bottom.

**Comment by hantou** [comment]
@jinglouMSFT I'm getting similar errors in my customer's environment.

When trying to run "C:\tool\azcopy.exe  sync  .. .." command using AzCopy v10.10.0.  the command was successfully executed. but every time the command is executed, the following error is logged in the event log.
------------------------------------------------------------------------
The description for Event ID:0 in Source:'C:\tool\azcopy.exe' cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer. If the event originated on another computer, the display information had to be saved with the event. The following information was included with the event: ==> REQUEST/RESPONSE (Try=1/272.0018ms, OpTime=272.0018ms) -- REQUEST ERROR HEAD https://stsuzuyoazurefiles001.file.core.windows.net/suzuyo-azurefiles001/pre/urigen/order/log/app-2021-09-09.54.log?se=2050-12-31t12%3A50%3A28z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A50%3A28z&sv=2020-02-10&timeout=901 User-Agent: [AzCopy/10.10.0 Azure-Storage/0.8.0 (go1.15; Windows_NT)] X-Ms-Client-Request-Id: [439bb0f4-ea4f-4820-56c8-4d334b2499b7] X-Ms-Version: [2020-02-10]
------------------------------------------------------------------------


In addition, the following information is recorded in the Azcopy log.
------------------------------------------------------------------------
2021/09/02 05:01:54 AzcopyVersion  10.10.0
2021/09/02 05:01:54 OS-Environment  windows
2021/09/02 05:01:54 OS-Architecture  amd64
2021/09/02 05:01:54 Log times are in UTC. Local time is 2 Sep 2021 14:01:54
2021/09/02 05:01:54 Job-Command sync https://stsuzuyoazurefiles001.file.core.windows.net/suzuyo-azurefiles001/?se=2050-12-31t12%3A50%3A28z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A50%3A28z&sv=2020-02-10 https://stsuzuyoazurefiles001dr.file.core.windows.net/suzuyo-azurefiles001dr/?se=2050-12-31t12%3A53%3A11z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A53%3A11z&sv=2020-02-10 --recursive=true --delete-destination=true --log-level WARNING 
2021/09/02 05:01:54 Number of CPUs: 4
2021/09/02 05:01:54 Max file buffer RAM 2.000 GB
2021/09/02 05:01:54 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2021/09/02 05:01:54 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2021/09/02 05:01:54 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2021/09/02 05:01:54 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2021/09/02 05:01:54 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2021/09/02 05:01:54 Max open files when downloading: 2147483224 (auto-computed)
2021/09/02 05:01:54 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2021-09-02T05:00:51Z or --include-after=2021-09-02T05:00:51Z
2021/09/02 05:01:54 Any empty folders will be processed, because source and destination both support folders
2021/09/02 05:01:54 WARN: [P#0-T#0] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2021/09/02 05:01:54 WARN: [P#0-T#1] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
… …
… … 
2021/09/02 05:01:54 WARN: [P#0-T#63] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2021/09/02 05:01:54 WARN: [P#0-T#46] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2021/09/02 05:01:55 ==> REQUEST/RESPONSE (Try=1/493.4986ms, OpTime=493.4986ms) -- REQUEST ERROR
   GET https://stsuzuyoazurefiles001dr.file.core.windows.net/suzuyo-azurefiles001dr/pre/master?restype=directory&se=2050-12-31t12%3A53%3A11z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A53%3A11z&sv=2020-02-10&timeout=901
   User-Agent: [AzCopy/10.10.0 Azure-Storage/0.8.0 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [5164a769-b19b-45c5-4a85-4d5f9aeecda5]
   X-Ms-Version: [2020-02-10]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Get "https://stsuzuyoazurefiles001dr.file.core.windows.net/suzuyo-azurefiles001dr/pre/master?restype=directory&se=2050-12-31T12%3A53%3A11Z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16T04%3A53%3A11Z&sv=2020-02-10&timeout=901": dial tcp 20.150.10.8:443: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.

goroutine 108 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack(0xc00f3d9620, 0xc01f5b6100, 0x0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0xa5
github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1(0x184a2a0, 0xc006352d20, 0xc005555c00, 0x10, 0x0, 0x0, 0xc00641b340)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0x7a5
------------------------------------------------------------------------
 
What is the cause of this log? Can we ignore it?

**Comment by hantou** [comment]
@JasonYeMSFT I'm getting similar errors in my customer's environment.
When trying to run "C:\tool\azcopy.exe  sync  .. .." command using AzCopy v10.10.0.  the command was successfully executed. but every time the command is executed, the following error is logged in the event log.
------------------------------------------------------------------------
The description for Event ID:0 in Source:'C:\tool\azcopy.exe' cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer. If the event originated on another computer, the display information had to be saved with the event. The following information was included with the event: ==> REQUEST/RESPONSE (Try=1/272.0018ms, OpTime=272.0018ms) -- REQUEST ERROR HEAD https://xxxxxxxxxxxxxxx.file.core.windows.net/xxxxxxxxxxxxxxxxxxxx/pre/urigen/order/log/app-2021-09-09.54.log?se=2050-12-31t12%3A50%3A28z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A50%3A28z&sv=2020-02-10&timeout=901 User-Agent: [AzCopy/10.10.0 Azure-Storage/0.8.0 (go1.15; Windows_NT)] X-Ms-Client-Request-Id: [xxxxxxxxxxxxxxx] X-Ms-Version: [2020-02-10]
------------------------------------------------------------------------

In addition, the following information is recorded in the Azcopy log.
------------------------------------------------------------------------
2021/09/02 05:01:54 AzcopyVersion  10.10.0
2021/09/02 05:01:54 OS-Environment  windows
2021/09/02 05:01:54 OS-Architecture  amd64
2021/09/02 05:01:54 Log times are in UTC. Local time is 2 Sep 2021 14:01:54
2021/09/02 05:01:54 Job-Command sync https://xxxxxxxxxx.file.core.windows.net/xxxxxxxxxxxxx/?se=2050-12-31t12%3A50%3A28z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A50%3A28z&sv=2020-02-10 https://xxxxxxxxxxx.file.core.windows.net/xxxxxxxxxxx/?xxxxxxxxxxxxxx --recursive=true --delete-destination=true --log-level WARNING 
2021/09/02 05:01:54 Number of CPUs: 4
2021/09/02 05:01:54 Max file buffer RAM 2.000 GB
2021/09/02 05:01:54 Max concurrent network operations: 32 (Based on number of CPUs. Set AZCOPY_CONCURRENCY_VALUE environment variable to override)
2021/09/02 05:01:54 Check CPU usage when dynamically tuning concurrency: true (Based on hard-coded default. Set AZCOPY_TUNE_TO_CPU environment variable to true or false override)
2021/09/02 05:01:54 Max concurrent transfer initiation routines: 64 (Based on hard-coded default. Set AZCOPY_CONCURRENT_FILES environment variable to override)
2021/09/02 05:01:54 Max enumeration routines: 16 (Based on hard-coded default. Set AZCOPY_CONCURRENT_SCAN environment variable to override)
2021/09/02 05:01:54 Parallelize getting file properties (file.Stat): false (Based on AZCOPY_PARALLEL_STAT_FILES environment variable)
2021/09/02 05:01:54 Max open files when downloading: 2147483224 (auto-computed)
2021/09/02 05:01:54 ISO 8601 START TIME: to copy files that changed before or after this job started, use the parameter --include-before=2021-09-02T05:00:51Z or --include-after=2021-09-02T05:00:51Z
2021/09/02 05:01:54 Any empty folders will be processed, because source and destination both support folders
2021/09/02 05:01:54 WARN: [P#0-T#0] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2021/09/02 05:01:54 WARN: [P#0-T#1] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
… …
… … 
2021/09/02 05:01:54 WARN: [P#0-T#63] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2021/09/02 05:01:54 WARN: [P#0-T#46] Block size 8388608 larger than maximum file chunk size, 4 MB chunk size used
2021/09/02 05:01:55 ==> REQUEST/RESPONSE (Try=1/493.4986ms, OpTime=493.4986ms) -- REQUEST ERROR
   GET https://xxxxxxxxxxxxxxx.file.core.windows.net/xxxxxxxxxxxx/pre/master?restype=directory&se=2050-12-31t12%3A53%3A11z&sig=-REDACTED-&sp=rwdlc&spr=https&srt=sco&ss=f&st=2021-06-16t04%3A53%3A11z&sv=2020-02-10&timeout=901
   User-Agent: [AzCopy/10.10.0 Azure-Storage/0.8.0 (go1.15; Windows_NT)]
   X-Ms-Client-Request-Id: [xxxxxxxxxxxxxxxxxxx]
   X-Ms-Version: [2020-02-10]
   --------------------------------------------------------------------------------
   ERROR:
-> github.com/Azure/azure-pipeline-go/pipeline.NewError, /home/vsts/go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157
HTTP request failed

Get "https://xxxxxxxxxxxxxx.file.core.windows.net/xxxxxxxxxxxxxxxxxx/pre/master?xxxxxxxxxxxxxxxxxxxxxxxxxxx&timeout=901": dial tcp 20.150.10.8:443: connectex: Only one usage of each socket address (protocol/network address/port) is normally permitted.

goroutine 108 [running]:
github.com/Azure/azure-storage-azcopy/v10/ste.stack(0xc00f3d9620, 0xc01f5b6100, 0x0)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:237 +0xa5
github.com/Azure/azure-storage-azcopy/v10/ste.NewRequestLogPolicyFactory.func1.1(0x184a2a0, 0xc006352d20, 0xc005555c00, 0x10, 0x0, 0x0, 0xc00641b340)
	/home/vsts/work/1/s/ste/xferLogPolicy.go:151 +0x7a5
------------------------------------------------------------------------
 
What is the cause of this log? Can we ignore it?
