### ISSUE TITLE
Auto refresh upon contents change

### ISSUE THREAD

**Issue by ajestrab** [microsoft/AzureStorageExplorer#1526]
Would be nice if the application would automatically refresh instead of having to select either the refresh button or confirm you wish to refresh the view upon making a change.  Why not just trigger a refresh.

**Comment by JasonYeMSFT** [comment]
Hi,
We used to have performance concerns since refreshing the user interface requires obtaining the list of resources from the azure platform, which may be a big traffic if you have many resources in a container. 

However, we are currently working on a configurable setting which allows the user to set whether to auto-refresh the user interface when certain commands finishes.

**Comment by MRayermannMSFT** [comment]
Make sure we are consistent for:
Blob - upload, download, undelete, delete, paste, rename
File - upload, download, paste, delete, rename
Gen2 - upload, download, delete, rename

For uploads and downloads, don't forget JS vs AzCopy
