### ISSUE TITLE
Increase pagination options

### ISSUE THREAD

**Issue by valdearg** [microsoft/AzureStorageExplorer#1527]
**Describe the solution you'd like**
Currently when loading a container which has a large number of blobs, the pagination is automatically handled as below:

If total items in container are less than 1000, the total number of blobs is displayed. 
If the total number of items is over 1000, the most which will be displayed is 1000. To get the number of items you then need to keep going to the next 1000 pages, then keep going until you finally get to the end.

This is incredibly frustrating when you have large number of blobs.

I would therefore like to suggest the following:

1. The total number of blobs is displayed with page numbers. E.g. it would display page 1, 2, 3 then the final 3 pages.

2. Option to increase the amount of items per page.

3. Option to display all items in the container.

I currently use Storage Explorer and Azure Explorer from Redgate together which, by default, will load a list of all items in the container.

**Comment by JasonYeMSFT** [comment]
Hi,
We are now actively working on a configurable setting which will allow you to set the pagination option that fit you best.

**Comment by JKamsker** [comment]
Any updates? @JasonYeMSFT

**Comment by AvivAvital2** [comment]
Any updates?
In case I create a directory, it is only visible if it appears in cache.
Furthermore, clicking the Refresh button discards of all the pages
Having 272 pages (and growing), it is pretty frustrating clicking them one by one every time :(

**Comment by JasonYeMSFT** [comment]
Move to near future so we can prioritize this one earlier.

We haven't worked on this yet because we are still thinking of a balanced solution to this problem. Caching as much data as possible (performance) and synchronizing local cache to be up to date (consistency) are two competing demands. Ideally the feature should be configurable to optimize for performance or consistency.

**Comment by valdearg** [comment]
> Move to near future so we can prioritize this one earlier.
> 
> We haven't worked on this yet because we are still thinking of a balanced solution to this problem. Caching as much data as possible (performance) and synchronizing local cache to be up to date (consistency) are two competing demands. Ideally the feature should be configurable to optimize for performance or consistency.

Did we ever get any further to implementing this? 

It's currently very difficult to do simple things like arrange by date modified as you have to first go through ALL the pages, THEN you can arrange by date modified.

What are the discussions looking like currently? I know that the older Azure Explorer I mentioned will load a number of blobs one by one, so say 1000 blobs at a time and list them. If we could get this as a configurable option it would be great.

If we could get the same on the tree menu when you open a storage container also, so that you just list ALL the blob containers instead of having to keep clicking "load more" over and over again, this would be great. 

Should probably implement natural sorting also, instead of 1_filename, 100_filename, 1000_filename

**Comment by MRayermannMSFT** [comment]
Closing this issue as merged for 1.32. In 1.32, all of the following settings will exist and be supported by blob explorer (normal and gen2), file explorer, and table explorer:

- Global Sort: If enabled, all available data will be loaded when sorting items by column, even if Load All is disabled.
- Load All: If enabled, load more will load all available data instead of just the next batch.
- Load Batch Size: The minimum number of items to load per batch during load more. If set, data will continue loading until at least the configured number of items have been retrieved.
