### ISSUE TITLE
Miss 'Preview' menu on Linux

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1550]
**Storage Explorer Version:** 1.9.0
**Branch:** master
**Build:** 20190711.8
**Platform/OS:** Linux Ubuntu 
**Architecture:** ix64
**Regression From:** Previous release 1.9.0

**Steps to reproduce:**
1. Launch Storage Explorer then check the menu bar.

**Expect Experience:**

The 'Preview' menu shows well.

**Actual Experience:**

No 'Preview' menu shows.
![image](https://user-images.githubusercontent.com/34729022/61112473-82666180-a4be-11e9-9552-c76ca1bcfac0.png)

**Comment by craxal** [comment]
Same root cause as #1551.

On Linux, in order to correct a bug where Electron windows would fail to render, we would simply load the window again. However, because we moved several extension points (settings/configurations) to the main process, loading extensions again from a renderer window would cause extension loading to fail.
