### ISSUE TITLE
Azure Storage explorer  stuck on Loading.. any suggestion

### ISSUE THREAD

**Issue by pankajag** [Microsoft/AzureStorageExplorer#169]
**Storage Explorer Version**: 

**Platform**: 

**Architecture**: 

**Build Number**: 

**Commit**: 

**Regression From**: 

#### Steps to Reproduce: ####

1. 
2.

**Comment by ede0m** [comment]
This is happening for me as well. Trying to connect to blob storage in Azure Storage Emulator. Was working last week before I did a windows update and storage explorer update. 

I am running azure storage emulator from a docker container. 

Just stalls and loads forever when searching through development -> blob storage

**Comment by MRayermannMSFT** [comment]
@ede0m , can you please use this issue for your problem? https://github.com/Microsoft/AzureStorageExplorer/issues/175

And @pankajag , please give us more info!

**Comment by MRayermannMSFT** [comment]
Can you please upgrade/install .NET 4.7.x as @jinglouMSFT suggested, and then try again? Thank you.

**Comment by KapilGuptaECR** [comment]
@MRayermannMSFT : I also have the same issue, but i am able to access some storage account and only some new storage accounts this issue, And after deleting and re-creating with different name it works. So i think .Net version is not an issue here.

**Comment by MRayermannMSFT** [comment]
Hi @KapilGuptaECR , can you be more clear about which issue you are having? Include screenshots (if possible), and detailed information about what you are seeing/how what you are seeing is not what you expect. Thanks!

**Comment by HeliosLHD** [comment]
@MRayermannMSFT 
I'm seeing the same issue on v1.2.0.   We have about 1700 folders in a blob container and it will load the first 1000 or so, but clicking "Load More" before the last load more completes seems to place it into a hang state.  According to task manager is is using 6-8% CPU and 8-9% GPU sitting there with the roving dots spinning.  The only thing that seems to clear it is to do "Refresh" and start from the beginning of 1700 folders again.  Once I click Refresh, and wait for the first 1,000 to load, and click "Load More" ONCE, the remaining folders come in in about 150 count chunks, and will continue loading to the end.

![image](https://user-images.githubusercontent.com/13319992/41468559-6820e88e-7078-11e8-918a-dc8abf5b4d0c.png)
![image](https://user-images.githubusercontent.com/13319992/41468588-85385a1a-7078-11e8-82ef-7b1bfebfdfba.png)

**Comment by craxal** [comment]
Closing this bug as stale. If this continues to be an issue, please let us know, and we can reopen.

**Comment by craxal** [comment]
As I mentioned, the bug became stale. In addition, the original comment does not supply enough information to fully understand the issue.

Is Azure Storage Emulator running? The (Development) node no longer automatically launches Azure Storage Emulator in 1.1.0 and up, because we want to allow users to install and launch any emulator they choose. The (Development) node should still connect to the emulator if the services are configured with their default endpoints.

We haven't quite updated the documentation for that, but we're working on it right now (#270).

**Comment by KapilGuptaECR** [comment]
Hi,

Please find attached e-mail communication on this.

This is highly unexpectable to just close case with out any proper information and I had provided all what you are asking, also screen share the issue.

Thanks!
Best Regards!
Kapil

**Comment by craxal** [comment]
@KapilGuptaECR, I don't think email attachments make it through to GitHub threads. You'll need to paste it in if you feel it's pertinent.

The earlier discussion here mentions the use of Azure Storage Explorer. Have you looked at #175 to make sure this is a different issue? If it's similar, we would encourage you to move the discussion there. If not, you may want to consider opening a new issue, since it will be off topic here.

We're trying to keep our bug reports organized so that we know how to go about addressing them. We don't want threads drifting off topic and referring to bugs that differ from the issue title. We also want other users to easily search existing issues for solutions rather than opening duplicates.

**Comment by Rachitgupta1994** [comment]
I have .Net framework 4.7.1 installed on my windows 7 machine. Still the azure storage explorer doesn't launch. It is perennially stuck on the loading animation. Another suggestion to Microsoft is to please launch an online storage explorer ie as website. Me and my colleagues face a lot of connectivity issues to the azure storage due to proxy servers. If the explorer runs online, we won't face these issues.

**Comment by craxal** [comment]
@Rachitgupta1994, thank you for your suggestion! We encourage you to add your suggestions as separate issues so that we have a much better chance of seeing and tracking it.

@pankajag, @HeliosLHD, @KapilGuptaECR, have you updated to the latest version of Storage Explorer (1.3.0)? Are you still encountering issues? If you reply, please provide detailed steps that reproduce the issue! This will help us help you!
