### ISSUE TITLE
The option 'Auto refresh blob editor' disappears on Application tab of Settings Panel

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#1707]
**Storage Explorer Version:** 1.9.0
**Build:** 20190822.2
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04
**Branch**: master
**Architecture:** ia32/x64
**Language**: zh-CN/ru/de
**Regression From:** Not a regression

**Steps to reproduce:**
1. Launch Storage Explorer using the command '**_StorageExplorer.exe --lang=zh-CN_**'.
2. Open the Setting Panel using 'Settings' icon or 'Edit' -> 'Settings'.
3. Check the 'Application' tab.

**Expect Experience:**

The option 'Auto refresh blob editor' shows well.

**Actual Experience:**

The option 'Auto refresh blob editor' disappears.
![image](https://user-images.githubusercontent.com/34729022/63502424-213f9e00-c500-11e9-8ff0-a3f0e59f0fb4.png)

**Comment by craxal** [comment]
Our neutral language fallback mechanism only works at the file level. We use English strings if a resource file isn't found. This was done because we did not expect any files to have mismatched strings.

We can fix this by always loading the neutral language then overwriting string values from the appropriate language file.
