### ISSUE TITLE
Not all selected Items are deleted

### ISSUE THREAD

**Issue by tspannagel** [microsoft/AzureStorageExplorer#1766]
**Storage Explorer Version**: 1.9.0
**Build Number**: 20190701.8
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**:  no

## Bug Description ##
If I try to delete multiple files in a folder, it takes multiple attempts. For example if there are 100files in the folder. i press ctrl+a, del it says 100files are queued, but between 30-40 files remain in the folder. i press ctrl+a again, and 10-15 files remain. (initially thought it was a pageing problem, but with the second attempt it doesnt look like it.

## Steps to Reproduce ##
Put many parquet files in a folder (around 100)
press ctrl+a, del

## Expected Experience ##
It should delete all selected files. 

## Actual Experience ##
It takes multiple attempts to delete multiple files.

**Comment by craxal** [comment]
@tspannagel Please provide some repro steps. Are you working in a blob container or file share? If blobs, are you using hierarchical namespaces (ADLS Gen 2)?

And just to be sure, can you confirm that one of the items that was definitely selected for delete was not actually deleted? I ask, because it's still possibly a paging issue, because there's a fair amount of bookkeeping that the code needs to keep straight in order for it to function properly.

**Comment by tspannagel** [comment]
@craxal Hi, Yes I'm working with a ADLS Gen2 blob storage. And yes, i can confirm that multiple items selected have not been deleted.

**Comment by JasonYeMSFT** [comment]
We have changed the API we use for ADLS delete in 1.11.0. Could you try if it is fixing the problem?

**Comment by tspannagel** [comment]
@JasonYeMSFT Hi, this fixed the problem! Thanks for the info! it now deletes all selected files.
