### ISSUE TITLE
A problem caused az storage explorer to start with GPU acceleration disabled [macOS]

### ISSUE THREAD

**Issue by masters3d** [microsoft/AzureStorageExplorer#1864]
**Storage Explorer Version**: 1.10.0
**AzCopy Version**: 10.2.1
**Platform**: macOS
**Architecture**: x64 
**Build Number**: 20190912.8 
**Commit**: 3e75e006f 
**Support ID**: c286dcb1-3630-4aa3-6859-88fbbde126a3 

Copyright © 2019 Microsoft. All rights reserved.

## Steps to Reproduce ##

Long running processes. uploaded 3TB image file

## Additional Context ##

![image](https://user-images.githubusercontent.com/6539412/65051925-a3b05780-d91e-11e9-95a3-22e1c66a197f.png)

**Comment by Judyll** [comment]
I am also experiencing this issue on Win10. The below is the version of Azure Storage explorer I am using:

![image](https://user-images.githubusercontent.com/25168961/65189035-71c7fe00-daa2-11e9-8310-83a0c004c8cd.png)

**Comment by craxal** [comment]
@masters3d @Judyll Can you please provide more detailed repro steps? It's not clear what you mean by "long running processes". Did this error occur at launch, or sometime later?

**Comment by Judyll** [comment]
Thanks for replying @craxal . For me, the issue happens during launch:

![image](https://user-images.githubusercontent.com/25168961/65191258-f49e8800-daa5-11e9-8fb1-1250b6e3ea19.png)

I just click OK and forget about it. It does not disrupt any Azure Storage functions I'm using though.

**Comment by craxal** [comment]
@Judyll Interesting, I've never seen this occur on Windows or Mac before. What version of Windows are you running?

@masters3d What version of Mac are you running?

**Comment by Judyll** [comment]
@craxal Here is the version of Windows I am running:

![image](https://user-images.githubusercontent.com/25168961/65191994-4b0cc600-daa8-11e9-942c-2862150e395e.png)

**Comment by masters3d** [comment]
macOS 10.14.6

> Can you please provide more detailed repro steps? It's not clear what you mean by "long running processes". Do you mean to say that the error occurred while uploading a 3TB file? Or did the the error occur at launch? 

I set it to copy a big file. I came back to the machine the next day to see the error. 

>Also, what's the result of the issue? Does it disrupt any long-running tasks, such as a download or upload, of do they continue as normal?

The GUI said that it was still going but then the azcopy cancelled but I am not sure if there are directly related. This was an upload. I ended up retrying using the command line but I like the GUI and prefer to use that if available.

**Comment by bladefist** [comment]
I hit this same error.  I ran the updated software on a Windows 2012 R2 Server, I wanted to see how fast the new AzCopy feature was, as the old copy speed was a big limitation of hosting backups remotely.

Anyway - The download was going, blazing fast, suddenly everything froze, I got kicked off RDP, all of my websites that were using that DB went down, and I was unable to get back on RDP for about 5m.  Once I was able to get back on, I was met w/ the  same dialogu @Judyll posted.  

I don't think the download finished either, once I got on I closed all of it because it was an important server.

**Comment by craxal** [comment]
I think I just spotted the same error this morning. Either it happens after leaving the application running for a while (and I wasn't even doing anything) or it happens when you try to RDP (which I also did once). I'll need to investigate.

@masters3d Are you remoting into your Mac at all? How long does the app/operation run before you get the error message? I assume you had to wake the machine up?

While we look into this, have you tried running AzCopy from the command line for a quick workaround? Storage Explorer lets you copy the command it uses to run your operation so you can try it on the command line yourself.

**Comment by MRayermannMSFT** [comment]
If y'all run Storage Explorer with the gpu disabled, are your downloads/uploads able to finish?

**Comment by masters3d** [comment]
>Are you remoting into your Mac at all?

No
> How long does the app/operation run before you get the error message?

Don’t know. I am not sitting in front of it for the duration. 

> I assume you had to wake the machine up?

No sure. I turned off power nap on the machine and the screen is off and I have to authenticate. 

>While we look into this, have you tried running AzCopy from the command line for a quick workaround? 

Yes but it did not work. My whole experience has been poor. My test file is 3T. Too much effort to get this to work but that is probably another issue. Just give me rsync :) I might have to just go back to Samba shares. Good luck.

**Comment by MRayermannMSFT** [comment]
@masters3d is this problem still repro'ing for you?

**Comment by masters3d** [comment]
I don't have the bandwidth to test this. I haven't used the tool since last year. Please feel free to close as fixed if you believe it has been addressed.
