### ISSUE TITLE
The deleted property doesn’t disappear for one entity 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1873]
**Storage Explorer Version:** 1.10.1
**Build:**[ 20190919.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3064513)
**Branch:** hotfix/1.10.1
**Platform/OS:** Windows 10/ Ubuntu Linux/ macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> Tables.
2. Create a new table -> Add an entity and add a new property.
3. Edit the entity and delete the new added property.
4. Check whether the deleted property disappears or not.

**Expect Experience:**
The deleted property disappears.
![image](https://user-images.githubusercontent.com/54055206/65237710-bc329480-db0d-11e9-9017-ab4b1fb7e1f1.png)

**Actual Experience:**
The deleted property doesn't disappear.
![image](https://user-images.githubusercontent.com/54055206/65237724-c18fdf00-db0d-11e9-9115-ca9b0b72d2c6.png)

**More Info:**
The deleted property disappears after manually refresh.

**Comment by craxal** [comment]
@v-limu What happens if you refresh the table? What happens if you add a property?

Problem here is the column-finding code has already run, and it's not going to remove a column for which all entities don't have a value for a column if found earlier.

Marking as won't fix since Azure is recommending CosmosDB.
