### ISSUE TITLE
Option to display blob containers without virtual folders (flat)

### ISSUE THREAD

**Issue by JakeRadMSFT** [microsoft/AzureStorageExplorer#19]
Storage Explorer Version: 0.9.6

OS Version: Windows 10 (all)

Expected Experience:
Option to display blob containers without virtual folders (flat)

Actual Experience:
No option

**Comment by codefoster** [comment]
What's the status of this issue? I see that it was added to a future milestone on Aug 9, 2018. Does that indicate when it may come to fruition?

**Comment by MRayermannMSFT** [comment]
@codefoster @nulllogicone @ckarras @octocat-mona 

Is listing blobs flat something you usually want (is it your preferred way of viewing blobs), or is it something you want at a specific time temporarily for like a few containers?

**Comment by codefoster** [comment]
Temporary. Usually, it's more convenient to see the directory structure. Occasionally, I'm interested in the attributes (columns) of _all_ of the blobs in a directory including subdirectories. That's the only time I would show them flat.

**Comment by ckarras** [comment]
@MRayermannMSFT  it depends on what storage container I'm accessing. When it's a deeply nested structure, for example the one Azure Stream Analytics creates or some Azure logging/diagnostics components, I would always want a flat view to avoid doing several clicks to reach a specific file.

**Comment by MRayermannMSFT** [comment]
We still have some design decisions to hash out with this feature. I don't think it's going to make our 1.20 release. Moving to 1.21 while we continue to discuss. While we do that though, I have a question for those interested in the feature (@codefoster @ckarras  @ishepherd @BruceForstall).

For this feature, we are at a minimum going to place a control somewhere in the blob/gen2 explorer that will let you toggle viewing the container as flat on and off.

What we'd like to know from y'all is where you would expect/not expect/want/not want such a control to be. Here's a screenshot of the blob explorer as it exists today. Feel free to use that as a reference, and communicate your answer using the colored rectangles if you'd like:
![image](https://user-images.githubusercontent.com/21112697/119178982-3aea7e00-ba23-11eb-8cd0-512ce0c33525.png)
Please be as thorough in your answer as you have time for. Thanks!

**Comment by ishepherd** [comment]
@MRayermannMSFT, my suggestions

* Don't add it to the blue dropdown; it is orthogonal to those options
* Not the green buttons, it does not fit the theme
* Red - Maybe - But this feature might not merit that real estate (to my eyes it's already cluttered up there)

Therefore it could be
* A push-toggle button at the left of the yellow area
* Or hide it away in that orange flyout section (but you might need to rename it as this isn't a "Filter")

Just my 2c

**Comment by ishepherd** [comment]
I'm particularly interested in being able to export a list of all blobs in a way I can munge with text tools (that was my https://github.com/microsoft/AzureStorageExplorer/issues/545)

It looks like you have this already (I can Ctrl+C from the blotter/grid view and Ctrl+V into a text editor, it produces a lot of JSON), if I can get the entire flat listing this way, that would be great.

Anyway you may tell me that use case is better for Azure CLI or Powershell.

**Comment by codefoster** [comment]
This feature harkens to the View settings in Windows Explorer that allow you to show/hide hidden files and show file extensions. That's under a View tab group. Storage Explorer doesn't have multiple tab groups at this point, but if we could afford a single "View Settings" button on the ribbon that could drop down and allow for showing Structured or Flat, that seems it would make sense. It's a very valuable feature when you need it, but I wouldn't be using it so often, so I don't know that it deserves a place front and center in the UI.
Or perhaps you add it to the orange area and combine the concept of structured/flat view with the concept of filtering. They're both view settings essentially. In that case, I suppose you'd need to rename the Filter Panel to the View Settings Panel or something like that.

**Comment by codefoster** [comment]
This feature harkens to the View settings in Windows Explorer that allow you to show/hide hidden files and show file extensions. That's under a View tab group. Storage Explorer doesn't have multiple tab groups at this point, but if we could afford a single "View Settings" button on the ribbon that could drop down and allow for showing Structured or Flat, that seems it would make sense. It's a very valuable feature when you need it, but I wouldn't be using it so often, so I don't know that it deserves a place front and center in the UI.
Or perhaps you add it to the orange area and combine the concept of structured/flat view with the concept of filtering. They're both view settings essentially. In that case, I suppose you'd need to rename the Filter Panel to the View Settings Panel or something like that.

**Comment by ckarras** [comment]
Hi @MRayermannMSFT,

The location where I would look for such an option would be in the toolbar, with a dropdown to switch between views. For example, something like this mockup:

![image](https://user-images.githubusercontent.com/11079586/119563652-d195a280-bd75-11eb-8ea9-209cbfe1b7a3.png)

**Comment by MRayermannMSFT** [comment]
@ishepherd 

> I'm particularly interested in being able to export a list of all blobs in a way I can munge with text tools (that was my #545)
> It looks like you have this already (I can Ctrl+C from the blotter/grid view and Ctrl+V into a text editor, it produces a lot of JSON), if I can get the entire flat listing this way, that would be great.
> Anyway you may tell me that use case is better for Azure CLI or Powershell.

Ah ya I can help you with that. So here's my tips for you:

1. Select the blobs you want to export their names of. If you want to do every blob, you can either use ctrl/cmd+a (which selects all in current page) or go to the toolbar and do either "select all in current page"/"select all in cache". So to do literally every blob in the container you would need to keep clicking "Load more..." until there's nothing left to load, then use the toolbar to select all in cache.
2. You can then right click on any of the selected blobs and click "Copy Url", that will copy the URL of all those blobs to your clipboard, new line separated. As a not, in the upcoming release (1.20) we're adding a "Copy Path" so that will copy just the path (aka the blob's real/full name).

Hopefully that helps you.

**Comment by ishepherd** [comment]
Thanks @MRayermannMSFT - that sounds fine and logical

> Do you mind sharing exactly what it is you do with the blob names you are munging? I'm curious to understand how storage explorer fits into your workflow.

We sometimes use the blob storage as "large attachments" for database records or queue messages or etc.

* We encode useful IDs (e.g. customer ID) into the path
* Attributes like *size* are interesting too - Derive statistics on the typical blob sizes

So if we can pull out a listing we can use classic unix-ish commands `grep`/`cut`/etc to find blobs to investigate or to generate statistics

Honestly CLI tools are a better fit for this. Less constrained on number of blobs and can be plugged into command pipelines.

**Comment by BruceForstall** [comment]
@MRayermannMSFT Thanks for reaching out. I'm no UI guru, but the proposal above by @ckarras makes good sense to me.

**Comment by MRayermannMSFT** [comment]
@BruceForstall @ishepherd @ckarras @codefoster quick question for y'all.

While implementing this we've run into an interesting scenario. When listing flat it is now possible to select blobs which are in different virtual directories. For example you can select the blobs:

- a/b/foo.txt
- a/bar.txt
- g/h/i/j/wat.txt
- cool.txt

When listing hierarchically doing this isn't possible, because you are only able to select things which are all in the current folder you are viewing, thus they are in the same folder.

This is a problem because if you do a selection which is made up of blobs which are in different virtual directories, we are unable to construct an AzCopy command for downloads/copies that would result in the selected blobs ending up at the destination as just the files.

So for the above selection example, if you wanted to copy those to the root of some other container, there is not a way have the result of the copy be that the root of the other container has the blobs:

- foo.txt
- bar.txt
- wat.txt
- cool.txt
 
That's the behavior we initially aimed for because that's how our copies/downloads work when you select individual blobs in hierarchical mode. We don't preserve the directory structure above the blobs you transferred, we only transfer the files themselves.

So there's 2* ways we can address this. When listing flat we can:
1. Disable copy and download if your selection is made up of blobs which are in different virtual directories
2. Allow copy and download, but the virtual folder structure of what you are copying is preserved at the destination (aka, copy and download work differently when listing flat)

Right now we're going with **solution 1**. We want the result of copies and downloads to be consistent across listing modes. But we did want to solicit y'all's feedback on this issue and get your take on it.

- Is copying/downloading blobs in different virtual directories something you had envisioned doing when listing flat?
- Are you ok with the limitation I described above?
- If not, how strongly are you not ok with it/how much does it affect your intended use of listing flat?

\* Yes there is a 3rd solution which is "AzCopy should add this capability", but for now we do not have a guarantee that will happen. Making it happen involves solving/deciding what should happen if the selection contains blobs with the same basename. For example:
- a/b/foo.txt
- c/d/foo.txt
If you want to chime in on that then feel free to do so. 🙃

**Comment by BruceForstall** [comment]
I haven't used the copy functionality. My main hope is that I'll be able to get a flat view, sort by Last Modified time, multi-select (across many different virtual folders), and delete.

IMO, it seems like it would be natural from a user perspective to want to be able to multi-select from the flat view and copy to a single target folder. If that's not possible, then preventing it (to allow for allowing it later in a more generalized UI), and delaying that generalization to a future version, makes sense (as long as it's made clear to the user why something is prevented).

**Comment by MRayermannMSFT** [comment]
@BruceForstall

> My main hope is that I'll be able to get a flat view, sort by Last Modified time, multi-select (across many different virtual folders), and delete.

Thankfully there are not any blockers to doing deletes while listing flat as far as we can tell at this time. :)

**Comment by MRayermannMSFT** [comment]
This has been merged for 1.21.0. The toggle for flat is going to be in the orange box:
![image](https://user-images.githubusercontent.com/21112697/128090353-9bbd082e-96eb-4a89-94cb-199ec5137c69.png)
So it can be toggle on and off on a container by container basis.

For those who want it always on by default, we'll be trying to squeeze in a global setting if we have time.
