### ISSUE TITLE
Show a wrong translation for one prompt message on 'Manager Access' dialog

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#1910]
**Storage Explorer Version:** 1.10.1
**Build:** [20190925.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3080492)
**Branch:** master
**Platform/OS:** Windows 10/ Ubuntu Linux 18.04/Mac OS High Sierra
**Language:** Chinese(zh-TW)
**Architecture:** ia32/x64

**Steps to reproduce:**

1. Launch Storage Explorer using the command 'StorageExplorer.exe --lang=zh-TW'.
2. Expand one ADLS account -> Blob Containers.
3. Create a new blob container -> Right click it and select the 'Manager Access...' action.
4. Check the poped up dialog.

**Expect Experience:**
The message 'No UPN or Object ID specified.' shows '未指定 UPN 或物件識別碼。'.

**Actual Experience:**
The message 'No UPN or Object ID specified.' shows '未指定 UPN 或物件識3別碼。'.
![image](https://user-images.githubusercontent.com/54055206/65593541-46be3c80-dfc3-11e9-926f-3766dbaab8e1.png)

**More Info:**
This issue also reproduces for blobs.

**Comment by lukaschal** [comment]
Fixed by this commit at 9/9/2019.

https://devdiv.visualstudio.com/DevDiv/_git/StorageExplorer/commit/d70fe603388f472ddb14fb93d2f04ce85388385f?_a=compare&path=%2Floc%2Floc%2Fzh-Hant%2Fsrc%2Fcomponents%2Fse-adls2-extension%2Fresources%2FManagePosixAcl.json.lcl

File: loc\en\src\components\se-adls2-extension\resources\ManagePosixAcl.json
ID: 0; "ErrorNoId"
SRC: No UPN or Object ID specified.
TGT: 未指定 UPN 或物件識別碼。

**Comment by lukaschal** [comment]
@v-limu Is this still repro ?

**Comment by v-limu** [comment]
Hi @lukaschal This issue has been fixed on build [20191017.3](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3150956). So we close it.
