### ISSUE TITLE
Error downloading folder containing subfolder and file with same name

### ISSUE THREAD

**Issue by sidec15** [microsoft/AzureStorageExplorer#200]
**Storage Explorer Version**: 1.1.0
**Platform**: Windows/Linux
**Architecture**: ia32
**Build Number**: 20180507.1
**Commit**: bcc8990d
**Regression From**: 

#### Steps to Reproduce: ####
Download a folder containing different subfolders

#### Expected Experience: ####
I will expect that the folder and its content is correctly and recursivelly downloaded.

#### Actual Experience: ####
When I try to download a folder containing others folder, sometime it fails because it cannot create one of the sub-folders. This is caused by the presence of a file (of 0 byte) with the same name of the sub-folders. I saw that this file always exists near to a folder but I don't know the reason.

I'm trying to download a persisted Spark Dataset, maybe this is the main problem because I saw that if I upload on Azure Blob Storage a folders with sub-folders, no empty file is created near the folders.

The error detail is attached on the issue.
[error.txt](https://github.com/Microsoft/AzureStorageExplorer/files/2023053/error.txt)

**Comment by craxal** [comment]
Does deleting the 0 byte files solve your issue? What's the size/depth of the folder you're downloading? Are there a lot of these 0 byte files in your blob container? How are blobs normally uploaded to this container?

**Comment by sdecri** [comment]
- Yes
   - The structure of the folder I tried to download is:

   speed-pattern-output-dir
   |
   |-- temporization.rim
   |
   |-- temporary_attributes.net
   |
   |-- speeds
       |
       |-- transportModeName=equivalent
           |
           |-- dayTypeName=MONDAY
           |   |
           |   |-- part-00000-6614088f-87ff-4afe-a69b-49574deaad54.att
           |
           |-- dayTypeName=WEDNESDAY
               |
               |-- part-00001-6614088f-87ff-4afe-a69b-49574deaad54.att

   -

   The 0 bytes are always present if the file is created using the
Spark functionalities (DataframeWriter), I saw that if I manually
upload a folder no 0 byte file is created. But I also saw that the
default container created for an HDIsight cluster has these 0 bytes
file.

   -

   Both using Azure Storage Explorer and Spark functionalities.



BR
Simone

**Comment by sdecri** [comment]
Hi Craig,
I did the following:

   - I created an empty container
   - I created in the container a folder named test.txt (because is not
   possible to create a file named test.txt/test.txt, with the slash in the
   name)
   - I uploaded in the folder an empty file called test.txt
   - I uploaded in the container a file called test.txt (at the same level
   of folder test.txt)

No further 0 byte file was created empty file is created.

I check in the portal the 0 byte files are showed also there.

It seems to me that these 0 byte files a related somehow with the HDIsight
service.

BR
SImone

**Comment by craxal** [comment]
OK, let's recap the facts:
- You have a blob container with a folder-like structure.
- Within each directory, there exists a 0-byte file whose base name matches the name of an existing subdirectory.
- Attempting to download any of these directories fails. This is because, when attempting to download a subdirectory, the corresponding 0-byte file has already been downloaded. The local FS can't have a file and subdirectory with the same name.
- These 0-byte files are not manually uploaded. They are possibly auto-generated by an HDInsight service.

Since this sounds like an external problem, and not a Storage Explorer problem, I'm going to close this issue. I'll see if I can get in contact with some people to figure out where these files are coming from. Any more info you discover will be very helpful.
