### ISSUE TITLE
Various dialogs are not or have portions that are not localized

### ISSUE THREAD

**Issue by craxal** [microsoft/AzureStorageExplorer#2002]
**Storage Explorer Version**: 1.11.0 (prerelease)
**Build Number**: 20191002.6
**Platform/OS**: All

- [x] Generate SAS ("Local")
- [x] Access Policies ("Local")
- [x] Set Container Public Access Level
- [x] New Folder (ADLS Gen 2)
- [x] Delete (ADLS Gen 2)
- [x] "Unable to retrieve child resources"
- [x] File Share Connection ("[drive letter]")
- [x] Connect ("Add an Azure Account", "use a storage account and name")
- [x] Copy Conflict
- [x] Break Lease
- [x] Set Access Tier

Feel free to break this up into individual issues as necessary.

**Comment by lukaschal** [comment]
Looks like hard-coded strings. Few examples below.

 parameters: {
                        title: "Set Container Public Access Level",
                        message: "Choose the access level for container '" + containerName + "':",
                        options: [
                            { title: "No public access", value: "off" },
                            { title: "Public read access for container and blobs", value: "container" },
                            { title: "Public read access for blobs only", value: "blob" }

https://devdiv.visualstudio.com/DevDiv/_git/MicroBuildTest?path=%2Fmac%2FMicrosoftAzureStorageExplorer%2FMicrosoft%20Azure%20Storage%20Explorer.app%2FContents%2FResources%2Fapp%2Fout%2FCloudHub%2Fjs%2FProviders%2FStorageExplorer%2FActions%2FBlobActions.js&version=GBmaster


            loadChildrenPromise.then(null, (err: Error) => {
                this._showError(
                    err,
                    "NodeViewModel.GetChildren",
                    "Unable to retrieve child resources.");
            });

            return loadChildrenPromise;
        });

https://devdiv.visualstudio.com/DevDiv/_git/CloudExplorer?path=%2Fsrc%2FCloudHub%2Fts%2FCloudExplorer%2FUI%2FNodeGroupViewModel.ts&version=GBmaster

**Comment by JasonYeMSFT** [comment]
- [x] Generate SAS ("Local")
- [x] Access Policies ("Local")
- [ ] Set Container Public Access Level - Localizable, waiting for translation
- [x] New Folder (ADLS Gen 2)
- [ ] Delete (ADLS Gen 2) - Localizable, waiting for translation
- [ ] "Unable to retrieve child resources" - Localizable, waiting for translation
- [ ] File Share Connection ("[drive letter]") - Strings are translated. There is a bug of loading resource strings
- [ ] Connect ("Add an Azure Account", "use a storage account and name")
- [ ] Copy Conflict - Fileshare are localizable, waiting for translation, blobs will use a different localizable conflict dialog
- [ ] Break Lease - Localizable, waiting for translation
- [x] Set Access Tier, the options are by design not translated, other parts are done

**Comment by JasonYeMSFT** [comment]
I verified that we have added all the strings for these dialogs. @lukaschal Please make sure that the translations are complete.

**Comment by lukaschal** [comment]
@JasonYeMSFT 

Set Container Public Access Level - On translation
Delete (ADLS Gen 2) - Not occurs in localizable resources for now
 "Unable to retrieve child resources" - On translation
 File Share Connection ("[drive letter]") - Not occurs in localizable resources for now
 Connect ("Add an Azure Account", "use a storage account and name") - Not occurs in localizable resources for now
 Copy Conflict - Not occurs in localizable resources for now
 Break Lease - Localized now

**Comment by MRayermannMSFT** [comment]
Verified.
