### ISSUE TITLE
A11y_AzureToolsStorageExplorer_Configure CORS Settings _Keyboard:Among 5 CORS rules,Not able to edit and delete the CORS rules from 2 to 4 using keyboard . 

### ISSUE THREAD

**Issue by nirmalsahoo** [microsoft/AzureStorageExplorer#2098]
GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS2.1.1;#Keyboard; #Win32; 

Environment Details:
Application Name: Azure Tools Storage Explorer
Application Version: 1.10.0
Windows10

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to "Open Connect dialog" pane and Sign in to Azure.
3. Go to "Manage Accounts" pane and Select the subscriptions you will use. Once selected, click on "Apply" button.
4. Navigate to "Blob Containers" of the selected subscription, right click and Select "Configure CORS Settings" and hit enter
5. Check whether the keyboard user able to edit the CORS rule from 2 to 4th one.

**Actual:**
Among 5 CORS rules,Not able to edit and delete the CORS rules from 2 to 4 using keyboard .

**Expected:**
Keyboard focus should  go to delete and edit and will be able to delete and Edit the data for selected items.

**UserImpact**:
Keyboard user will not able to edit and delete the selected data.

**Comment by MRayermannMSFT** [comment]
@Radha2019 @Charanrajkb @nirmalsahoo @Suraj1200499 @vinodbk197

Please verify whether or not this bug was fixed to your satisfaction in the latest release of Storage Explorer. You can obtain that release from https://www.storageexplorer.com

If the bug has not been fixed to your satisfaction, please:
- Explain how did the fix not meet your expectations.
- Tell us exactly how we can meet your expectations. If there is more than one way to do so, feel free to list the different ways.

**Comment by nirmalsahoo** [comment]
@MRayermannMSFT Verified on version 1.12.0 and the issue is no longer reproduced,hence close this bug.

**Comment by fsteffi** [comment]
GithubTags:#Closed;

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-StorageExplorer-Win32-Sep2019;
