### ISSUE TITLE
Export data selecting CSV will still export typed.csv

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/AzureStorageExplorer#2104]
When you export data and you select CSV as the file type, the file is still exported as a typed.csv file. This is because when you select CSV, the filename still ends with .typed. Storage explorer will therefor still export typed.csv. When you remove the .typed from the end of the filename, a proper CSV file is exported.

**What I expect:**
When you selected CSV as filetype, the filename should not end with .typed. Therefor the file is saved as a proper CSV file.

**Comment by MRayermannMSFT** [comment]
Investigate. If just removing the extension is enough, then won't fix.

**Comment by nielsvdc** [comment]
While you're at it, also try the following:

1. Click the export button. The default filename is [tablename].typed.csv
2. Change the "Save as type" to *.csv. The default filename is [tablename].typed.csv
3. Change the "Save as type" to *.typed.csv. The default file name is [tablename].typed.typed.csv
4. Repeat steps 2 and 3.
5. .typed is added every time you repeat the steps.

That's not how it should be working.

**Comment by jinglouMSFT** [comment]
SE behavior is a bit weird in 1.12.0 Released bits. 
- The default name is "TableName.typed.csv" and we save the type
- If selecting to save as "(Comma delimited)(*.CSV),  we  only remove the .csv extension, but not the .typed.  But we should remove ".typed.csv" from the file name and save the file as .CSV without the type.  IF manually removing ".typed.csv", we do save the file without the type
- In the export dialog, change "Save as type" to ".typed.csv", we wipe out everything in the name field.  User will have to type in the entire file name and extensions.  At this point, no mater which "Save as type"  you select, you will have to type everything in manually.

This is pretty annoying but mostly cosmetic. Since Azure Table is no longer  being in active development mode,  I'd vote won't fix.

**Comment by craxal** [comment]
As observed, Storage Explorer uses the ".typed.csv" to determine whether it should save type annotations or not, and that's all. The dialog is a system dialog, so the behavior seen here is not something that can be altered. Having a "sub-extension" obviously isn't something the system dialog was meant to handle.

There are two ways to fix this:
1. Use a proper differentiating extension, such as ".tcsv"
   - **Pros**: Quick and easy fix
   - **Cons**: Programs that recognize .csv might not recognize or open .tcsv" files correctly. Excel, for example, doesn't identify columns correctly.
2. Introduce a setting or dialog that allows the user to choose whether they want to export type annotations
   - **Pros**: No need for a different file extension, cleaner experience.
   - **Cons***: Requires new UI and localization (dialog is the most expensive of the two).

**Comment by jstawski** [comment]
Hello, using version 1.19.1 for Mac and exporting without typed.csv still exports with the types.

**Comment by jstawski** [comment]
Never mind, I just found the setting to turn it off:

![image](https://user-images.githubusercontent.com/873800/121087205-21329000-c7b2-11eb-8d3f-bcbaa88977eb.png)
