### ISSUE TITLE
Right-clicking table entities for delete selects two rows

### ISSUE THREAD

**Issue by cliffeby** [microsoft/AzureStorageExplorer#2107]
**Storage Explorer Version**: 1.10.1 
**Build Number**: 201990919.2
**Platform/OS**:  Windows 10? 
**Architecture**:   x64? 
**Regression From**:  no

## Bug Description ##
When you right click to delete a table row, the selected and the mouse located rowsare highlighted.  Confirming the delete only removes the initially selected row as it should, but the warning message with two rows identified is misleading.

## Steps to Reproduce ##
1. Right click any row in a table and select delete

## Expected Experience ##
highlight only one selected row or use a bold color for the selected row.

**Comment by JasonYeMSFT** [comment]
Could you please give more detailed steps to reproduce the bug?

**Comment by cliffeby** [comment]
Sorry had these details in html comments.

**Comment by cliffeby** [comment]
Replied on GitHub

**Comment by JasonYeMSFT** [comment]
Could you please attach a screenshot or a recording showing the bug you are describing? We are having trouble reproducing this issue.

**Comment by cliffeby** [comment]
See attached screenshot

**Comment by MRayermannMSFT** [comment]
We don't see a screenshot. You need to paste it directly into your github comment. Attaching it to your email reply won't work.

**Comment by cliffeby** [comment]
Hope this works

https://1drv.ms/u/s!AgsEoWikEEW_le19RToQG0_G0_syyw?e=ulfXsF

**Comment by MRayermannMSFT** [comment]
Thanks. We understand the issue and will look into getting this fixed.

**Comment by craxal** [comment]
Unable to reproduce this issue on 1.14.2. When I try right-clicking an item different than the current selection, the current selection is set to that item as expected.

@cliffeby Can you reproduce on the latest version (1.14.2) of Storage Explorer?

@v-xianya Can you try reproducing this issue as well?

**Comment by cliffeby** [comment]
![ASE073020a](https://user-images.githubusercontent.com/1431998/88995915-d9053000-d2b9-11ea-9a82-075a7aca7c9e.png)
I still get the same behavior but less consistently.  About half the time only one line is highlighted.  When only one line is highlighted and then deleted, a new cell is highlighted at the top of the page.  The jump and highlighting is disconcerting/unexpected.  @craxal  @v-xianya

**Comment by cliffeby** [comment]
[IMG_3752.zip](https://github.com/microsoft/AzureStorageExplorer/files/5008693/IMG_3752.zip)

This is a video showing both issues.

**Comment by craxal** [comment]
@cliffeby The jump to the top of the page is by design. All of our editors do that.

As far as the double-selection is concerned, I finally got it to repro. I think I know what's happening. The Delete command, of course, opens a confirmation dialog before proceeding. There's often a (very) short delay between when the command is triggered and the dialog opens. During that delay, the editor can still respond to UI events. In this case, a few things are happening:

- The table loses focus. This results in the selected row changing from dark blue to light blue.
- The UI handles a mouseover at the current location of the cursor. This results in the row under the cursor also being colored light blue.
- The editor UI is blocked as soon as the dialog opens, so the editor doesn't change any hover states.

It just so happens the colors we use for row hover color and row unfocused/selected states are the same color, which is probably where the confusion is coming from. In reality, only one item is selected. If you cancel the confirmation dialog, you should notice the UI update the row hover.

Two possible solutions:
- We have a different style for row hover and row unfocused/selected states.
- Indicate the number of entities that will be deleted in the confirmation dialog.

@jinglouMSFT @MRayermannMSFT @JasonYang-MSFT Thoughts?

**Comment by cliffeby** [comment]
@craxal   @jinglouMSFT @MRayermannMSFT @JasonYang-MSFT 

Regarding options, I'd prefer style/color difference as long as it's obvious which is going to be deleted..  For the second possible solution, if the confirmation dialog notes one row to be deleted and two are highlighted, which one is it? 

Regarding standard editor behavior, I'm not sure why a jump to the top of the page is desired.  Why would I want to go to the top of a page?  Could you imagine that behavior in VSCode, Excel or Word?

**Comment by craxal** [comment]
@cliffby We try to emulate behaviors observed in File Explorer on Windows or Finder on Mac. Both File Explorer and Finder move the selection to the next item when deleting, so that's something we can look into. If could please open a separate bug for that, we'd greatly appreciate it!
