### ISSUE TITLE
Logon Twice

### ISSUE THREAD

**Issue by johnstaveley** [microsoft/AzureStorageExplorer#2114]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: <Win 10
**Architecture**: x64
**Regression From**:  

## Bug Description ##
I logon to my personal subscription account using 2 factor authentication. I am told I logon successfully. I try to access the subscription and I get the error message 'Unable to retrieve child resources. Details: [()]'. I logon again as above and I can now access my subscription. I have to do this every single time I logon

## Steps to Reproduce ##
As above

## Expected Experience ##
Logon once, access resources in subscription 

## Actual Experience ##
I have to logon twice every single time.

**Comment by MRayermannMSFT** [comment]
@johnstaveley , this is a known/occasional issue. Our current auth library has some issues around MFA which sometimes you require to authenticate twice as you are seeing. To be clear, at no point you are blocked, correct?

**Comment by johnstaveley** [comment]
I am not blocked but it is not sometimes. It is every single time.

**Comment by MRayermannMSFT** [comment]
Gotcha. Well, we're looking to move to a new auth library pretty soon here, and in an upcoming version of Storage Explorer we plan on shipping a setting that allows people to switch to using that library. We have a private build (which includes the setting) available now though that we're distributing to see if it can help anyone who has recent issues. I know you're not blocked, but if you'd like to give the build a try and see if it resolves your MFA problems, you're totally welcome to. 

You can download the private build here:
- Windows: https://aka.ms/storageexplorer/msal/windows 
- Mac: https://aka.ms/storageexplorer/msal/macos 
- Linux: https://aka.ms/storageexplorer/msal/linux 

To enable the new auth library, go to Settings (gear icon) -> Application -> Sign-in -> Microsoft Authentication Library (Preview), and then click the checkbox and restart. 

Since this is a private build, we do not recommend using it long term, or on production data.

Let us know if the build resolves your issue. Thanks!

**Comment by MRayermannMSFT** [comment]
Going to go ahead and close this as we're shipping 1.11.1. If you run into any problems please let us know via a new issue.
