### ISSUE TITLE
Each language setting should be in its own language

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#2148]

**Comment by JasonYeMSFT** [comment]
There are still translated strings for the language settings.
e.g. 英语 in zh-Hans/Shell.json

**Comment by craxal** [comment]
@v-xianya Can you verify that the language settings are the same for all languages, please?

**Comment by v-xianya** [comment]
Hi @craxal  
Verified this issue on the build 20191101.5. 

For English, the language setting show the application language.
For other 17 languages, each language setting is in its own language.

**Comment by craxal** [comment]
@v-xianya Can you clarify, please? I'm not sure what you mean when you say English shows the "application language" and the others show "in it's own langauge".

Just to make sure we're on the same page, the expected behavior is the language options should be the same and look like the image below for ALL languages (the exception being the one labeled "Use system language")

![image](https://user-images.githubusercontent.com/3473026/68038294-d2904c00-fc86-11e9-9aa7-601a569b5abc.png)

**Comment by v-xianya** [comment]
Hi @craxal Please see the details from belows.
1. The language option 'English' should be in 'English' not 'French'😊
![image](https://user-images.githubusercontent.com/41351993/68106155-ad683b80-ff1b-11e9-9b42-89d14e866390.png)
2. We verified this issue in the build 20191102.1. And found the language option 'English' displays the same for All language. BUT, We found the language option **'Use system language'** displays the same for All language.(This example is in French), Could you help to take a look? Thanks a lot.
![image](https://user-images.githubusercontent.com/41351993/68106987-53b54080-ff1e-11e9-8ca9-24f7b4997e75.png)

**Comment by craxal** [comment]
@v-xianya Looks like you have better eyes than me. 😊 Looks like "Anglais" has been changed back to "English" in the release, though. But, I think the translators mistakenly "untranslated" the system language option. I'll open a separate bug for that.

**Comment by v-xianya** [comment]
Hi @craxal Got it. Thanks for your updates!
