### ISSUE TITLE
Unable to reenter credentials, missing Chrome extension

### ISSUE THREAD

**Issue by mochr** [microsoft/AzureStorageExplorer#2167]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Windows 10
**Architecture**: ia32 on a x64 computer
**Regression From**:  It was working in a previous version, sometime between aug. 2018 and july 2019, but I do not know the version number.

## Bug Description ##
I am prompted to reenter my credentials for my account, but after writing the password, approving on my Microsoft Authenticator app, writing my password once more, I get the error message "You can't get there from here".

Error message:

> You can't get there from here
This application contains sensitive information and can only be accessed from:
Devices or client applications that meet <my company> management compliance policy.
Since you're using Chrome, you need to install this extension. You must be on Windows 10 version 1703 and above. Please click here for details. Alternatively, you can use Microsoft Edge or Internet Explorer to access this application.

My Chrome browser has the extension "Windows 10 Accounts" installed, but I am not able to install that in Azure Storage Explorer.

## Steps to Reproduce ##
1. Click Manage Accounts
2. Click Reenter credentials
3. Enter the password
4. Approve on Microsoft Authenticator app
5. Enter password once more
6. Get the error message "You can't get there from here"

## Expected Experience ##
Expected to be approved after entering credentials.

## Actual Experience ##
Still get a prompt to reenter my credentials, but I am still logged in.

## Additional Context ##
I am trying to sign in with an enterprise account linked to Windows, and as mentioned my Chrome browser is managed by my organization with the extensions "Windows 10 Accounts" and "My Apps Secure Sign-in Extension" installed.

**Comment by monkeyclass** [comment]
Same issue here. This is even though the account I am using for accessing Azure has been excepted from the security policy that states that only Edge, IE or Chrome with the extension can be used.

**Comment by jinglouMSFT** [comment]
This likely needs the conditional access support we are currently working on.

**Comment by MRayermannMSFT** [comment]
Hi there! In an upcoming version of storage explorer, we're going to be offering a setting to try out a new auth library. This library includes support for additional sign in scenarios, and we believe that includes resolving this issue. Before we release that version though, would you be willing to try a private build which includes that setting?

If yes, then you can download the private build here:
- Windows: https://aka.ms/storageexplorer/msal/windows 
- Mac: https://aka.ms/storageexplorer/msal/macos 
- Linux: https://aka.ms/storageexplorer/msal/linux 

To enable the new auth library, go to Settings (gear icon) -> Application -> Sign-in -> Microsoft Authentication Library (Preview), and then click the checkbox and restart. 

Since this is a private build, we do not recommend using it long term, or on production data.

Let us know if the build resolves your issue. Thanks!

**Comment by monkeyclass** [comment]
Thanks for the build. I can now access the storage explorer with the user-account signed-in to windows. However, as we are using separate accounts for Azure administration (let's call it admin-account), this does not work without signing in as that user on Windows.

In the build you sent Edge opens up and asks which account you want to sign in with. Even if I put my separate admin-account credentials in, it signs me in with the user-account signed in to Windows.

**Comment by MRayermannMSFT** [comment]
Yes, that sounds right. With how we currently use MSAL on Windows, we will launch Edge. We do this because Edge has special hooks into the operating system that make certain types of conditional access possible. But, as you have discovered, if you are domain joined and if you try to sign into a different account that is part of the same domain, Edge will just use the domain joined account. Thank you for letting us know this is a scenario you rely on though, that's helpful feedback, because now we can modify our usage of MSAL to support it. 

To do that, I think when we switch to using MSAL by default, we'll let you pick between using edge or your default browser (such as Firefox or Chrome). So if you don't need the conditional access support but you do need to sign into multiple accounts in the same domain, you could choose "default browser" instead of Edge. Make sense? 🙃

**Comment by MRayermannMSFT** [comment]
Going to go ahead and close this as we're shipping 1.11.1. If you run into any problems please let us know via a new issue.

**Comment by monkeyclass** [comment]
@MRayermannMSFT, makes perfect sense and would be really amazing if it will be possible to choose a default browser. Thanks for the help!
