### ISSUE TITLE
The Properties dialog allows to add properties for an ADLS Gen2 archived blob

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2184]
**Storage Explorer Version:** 1.10.1
**Build:** [20191031.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3199751)
**Branch:** rel/1.11.0
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container which contains blobs.
3. Select one blob on archived access tier.
4. Right click it and select 'Properties...'.
5. Try to add properties then click Save -> Check the result.

**Expect Experience:**
Not allow to add properties.

**Actual Experience:**
1. Allow to add properties.
2. An error log message occurs after clicking Save.
![image](https://user-images.githubusercontent.com/41351993/67951756-12274b80-fc27-11e9-9097-63c0656d5292.png)

**Comment by craxal** [comment]
Won't fix. We're not in the practice of restricting operations based on permissions or state unless it can lead to confusing outcomes for the user. In this case, it's clear to the user that they can't modify properties because of the blob's access tier (I'm assuming that that's the error message shown when clicking Details).
