### ISSUE TITLE
Unable to authenticate on Ubuntu 19.04

### ISSUE THREAD

**Issue by geoffery66** [microsoft/AzureStorageExplorer#2198]
**Storage Explorer Version**: 1.10.1
**Build Number**: 20190919.2
**Platform/OS**: Linux Ubuntu 19.04
**Architecture**:  x64
**Regression From**:  n/a

## Bug Description ##
Unable to authenticate with azure account. Error msg: 
"Unable to sign in: AADSTS50097: Device authentication is required.
 Trace ID: f8fd8ed6-257d-4a60-809d-096054d30200
 Correlation ID: 8672cba6-22b2-40e8-a8df-d839c31e004c
 Timestamp: 2019-11-01 23:39:02Z"

However, I have authenticated on my phone with my fingerprint using the authenticator app with a prompt authentication success

## Steps to Reproduce ##
1. Installed azure storage explorer from snap:
   - https://snapcraft.io/storage-explorer
2. Connect password manager
   - snap connect storage-explorer:password-manager-service :password-manager-service
   - creation success
3. Start Azure Storage Explorer
   - under account management, 
   - select add an account, 
   - select sign in with azure account, 
   - sign in using the pop up window.
   - input username and password,
   - select authenticate with phone device
   - I get notification on my phone 
   - I authenticate with my finger print, phone prompts success
   - pop up window in azure storage explorer goes away
   - I get the error msg:
> Unable to sign in: AADSTS50097: Device authentication is required.
>  Trace ID: f8fd8ed6-257d-4a60-809d-096054d30200
>  Correlation ID: 8672cba6-22b2-40e8-a8df-d839c31e004c
>  Timestamp: 2019-11-01 23:39:02Z
> 

## Expected Experience ##
authenticate successfully with my microsoft acount

## Actual Experience ##
I performed a successful 2FA but the error message requires device authentication

## Additional Context ##
zecai@microsoft.com

**Comment by MRayermannMSFT** [comment]
Hi there! In an upcoming version of storage explorer, we're going to be offering a setting to try out a new auth library. This library includes support for additional sign in scenarios, and we believe that includes resolving this issue. Before we release that version though, would you be willing to try a private build which includes that setting?

If yes, then you can download the private build here:
- Windows: https://aka.ms/storageexplorer/msal/windows 
- Mac: https://aka.ms/storageexplorer/msal/macos 
- Linux: https://aka.ms/storageexplorer/msal/linux 

To enable the new auth library, go to Settings (gear icon) -> Application -> Sign-in -> Microsoft Authentication Library (Preview), and then click the checkbox and restart. 

Since this is a private build, we do not recommend using it long term, or on production data.

Let us know if the build resolves your issue. Thanks!

**Comment by geoffery66** [comment]
Hi Matthew!

I'd love to try the new build. Having storage explorer would really improve QoL for me

Thanks for the e-mail!!

________________________________

**Comment by MRayermannMSFT** [comment]
Going to go ahead and close this as we're shipping 1.11.1. If you run into any problems please let us know via a new issue.
