### ISSUE TITLE
Device Certificate was not found for Cert Authorities

### ISSUE THREAD

**Issue by leewalk** [microsoft/AzureStorageExplorer#2232]
{
  "message": "\"Device Certificate was not found for Cert Authorities:OU=82dbaca4-3e81-46ca-9c73-0950c1eaca97,CN=MS-Organization-Access,DC=windows,DC=net\""
}

**Storage Explorer Version**: 1.11.0
**Build Number**: 20191105.2
**Platform/OS**: Windows Server 2012 R2
**Architecture**: x64
**Regression From**:  unknown - works on WS16 and Win10

## Bug Description ##
When AAD Conditional Access policy is enabled to request but not require device auth on WS12R2, the following error occurs:

{
  "message": "\"Device Certificate was not found for Cert Authorities:OU=82dbaca4-3e81-46ca-9c73-0950c1eaca97,CN=MS-Organization-Access,DC=windows,DC=net\""
}

## Steps to Reproduce ##
1. WS12R2 server joined to Redmond domain
2. Download and install Azure Storage Explorer
3. Follow first-run wizard to add Azure account
4. Authenticate and then see error
Note: this works on WS16 (which automatically registers device in AAD - WS12R2 does not register device in AAD).

## Expected Experience ##
Auth should succeed.

## Actual Experience ##
{
  "message": "\"Device Certificate was not found for Cert Authorities:OU=82dbaca4-3e81-46ca-9c73-0950c1eaca97,CN=MS-Organization-Access,DC=windows,DC=net\""
}

**Comment by MRayermannMSFT** [comment]
Hi there! In an upcoming version of storage explorer, we're going to be offering a setting to try out a new auth library. This library includes support for additional sign in scenarios, and we believe that includes resolving this issue. Before we release that version though, would you be willing to try a private build which includes that setting?

If yes, then you can download the private build here:
- Windows: https://aka.ms/storageexplorer/msal/windows 
- Mac: https://aka.ms/storageexplorer/msal/macos 
- Linux: https://aka.ms/storageexplorer/msal/linux 

To enable the new auth library, go to Settings (gear icon) -> Application -> Sign-in -> Microsoft Authentication Library (Preview), and then click the checkbox and restart. 

Since this is a private build, we do not recommend using it long term, or on production data.

Let us know if the build resolves your issue. Thanks!

**Comment by craxal** [comment]
Per private discussion, this problem has been fixed.
