### ISSUE TITLE
The property ContentMD5 allows to edit

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2235]
**Storage Explorer Version:** 1.11.0
**Build:** [20191106.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3218228)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 19.04/macOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container which contains blobs.
3. Select one blob then open its Properities dialog.
4. Check the ContentMD5 textbox.

**Expect Experience:**
It doesn't allow to edit.

**Actual Experience:**
It allows to edit.
![image](https://user-images.githubusercontent.com/41351993/68376685-f7ebf100-0183-11ea-8015-071500e62877.png)

**More Info:**
1. This issue doesn't reproduce for one HNS blob.
2. This issue reproduces for files under one file share.

**Comment by craxal** [comment]
@MRayermannMSFT Is this field supposed to be editable? For HNS enabled accounts, the SDK returns a `Uint8Array`, which is decoded from the base-64 encoded string retrieved from Azure. Because of that, I disabled being able to edit it. I don't think we should be letting users edit the MD5 hash for regular blobs either...at least until we have a better scenario planned out?

**Comment by MRayermannMSFT** [comment]
I'm fine either way.

**Comment by MRayermannMSFT** [comment]
Let's make it read only for now and figure out a better experience around editing sensitive properties. And if people need it to be writable earlier than that, then we can just ship undoing making it read only.

**Comment by craxal** [comment]
Merged with commit 5ff2fb66.
