### ISSUE TITLE
Storage Explorer GPU Error

### ISSUE THREAD

**Issue by eosho** [microsoft/AzureStorageExplorer#2277]
**Storage Explorer Version**:  latest version

## Bug Description ##
when using storage explorer the following error is displayed first launching storage explorer
![image](https://user-images.githubusercontent.com/10321481/69083389-018d1880-0a10-11ea-8ce0-d3198bfb5b5f.png)

Tried running the  "--disable-gpu" switch.  However, when the application ran it crashed with the following error:
![image](https://user-images.githubusercontent.com/10321481/69083413-0d78da80-0a10-11ea-94b1-abd8b2d9a557.png)

System info:
![image](https://user-images.githubusercontent.com/10321481/69083462-25505e80-0a10-11ea-9f40-5be5028e7eef.png)

**Comment by mchenx** [comment]
can we have a setting that can set disable-gpu to true instead of running with --disbale-gpu everything launch it, vs code recently added this feature ~

**Comment by craxal** [comment]
@eosho Are you by chance trying to run Storage Explorer on a VM, or are you remoting into the machine that has Storage Explorer? Can you give us some info about the system and GPU running Storage Explorer? Knowing more about your system may help us test a proper fix.

Very possible the cause is explained by electron/electron#5297.

**Comment by JasonYeMSFT** [comment]
Hi all, we have made a fix based on @craxal's finding and produced a private build. Could you please try it to see if the problem is solved?

* Windows - https://aka.ms/gpu-crash/windows
* macOS - https://aka.ms/gpu-crash/macOS
* Linux - https://aka.ms/gpu-crash/linux

You can pass the `--diable-gpu` from the command when starting Storage Explorer (we internally call the function for you). If you wish to save this option, you can access the `appState.json` file under the appData folder and add `"disableGpu": true` after the `"lastWindowState"` property.

* Windows - `%APPDATA%` (usually `C:\Users\<your user name>\AppData\Roaming\StorageExplorer`)
* macOS - ~/Library/Application Support/StorageExplorer
* Linux - `$XDG_CONFIG_HOME` or `~/.config`

Once it is set, Storage Explorer will disable gpu every time it starts.

**Comment by Meekohi** [comment]
Hey I am still getting this in the newest version:
![image](https://user-images.githubusercontent.com/10985/148314175-24347bcb-574b-476f-830a-066d2efa9d23.png)

Should I open a new issue, or was there some explanation for this one about what's going on? It only happens when I try to move an Azure Storage Explorer from one monitor to another.

**Comment by craxal** [comment]
@Meekohi I think it would be best to open a new issue, as this one has been closed for a while, and it sounds like you have more details to add. Be sure to give us details about your system and steps you followed to reproduce the problem.
