### ISSUE TITLE
A11y_AzureToolsStorageExplorer_Settings_DataExplorers_ScreenReader: VoiceOver unnecessarily reading the line as heading level 2.

### ISSUE THREAD

**Issue by Suraj1200499** [microsoft/AzureStorageExplorer#2311]
GitHubTags: #A11y_AzureToolsStorageExplorer; #A11yMAS; #A11YTCS; #DesktopApp; #MAS1.3.1;  #VoiceOver; #Mac;  

**Environment Details:**
Application Name: Azure Tools Storage Explorer
Application Version: 1.11.0
MAC Version: Catalina 10.15 

**Repro Steps:**
1. Launch Storage Explorer
2. Navigate to Setting menu on left pane and click on it.
3. Navigate to Data Explorers on right pane and click on it.
4. "Data Explorers" screen gets opened.
5. Start Voice Over and navigate using the tab key.
6. Observe the Voice Over announcement.

**Actual:**
Separator bar (Non-interactive element) receives keyboard focus, and is announced via screen reader as "heading level 2".

**Expected:**
User should not be able to navigate to this separator bar.

**UserImpact:**
When VoiceOver users navigate to 'Data Explorers' dialog, keyboard focus moves to the separator bar and VoiceOver announces, 'heading level 2' for the bar which can confuse them

**Comment by MRayermannMSFT** [comment]
Jason merged a fix into master.

**Comment by MRayermannMSFT** [comment]
@Radha2019 @Charanrajkb @nirmalsahoo @Suraj1200499 @vinodbk197

Please verify whether or not this bug was fixed to your satisfaction in the latest release of Storage Explorer. You can obtain that release from https://www.storageexplorer.com

If the bug has not been fixed to your satisfaction, please:
- Explain how did the fix not meet your expectations.
- Tell us exactly how we can meet your expectations. If there is more than one way to do so, feel free to list the different ways.

**Comment by Suraj1200499** [comment]
@MRayermannMSFT Verified this issue in Microsoft Azure Tools Storage Explorer Application Version: 1.12.0, this issue is no longer reproduced. Hence Closing the bug.

**Comment by fsteffi** [comment]
GithubTags:#Closed;

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-StorageExplorer-Mac-Sep2019;
