### ISSUE TITLE
The value for one of the HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by renansouza-dev** [microsoft/AzureStorageExplorer#2318]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  Can't say.

## Bug Description ##
Copy a remote container always fails when paste.

## Steps to Reproduce ##
Select a remote blob container -> right mouse click -> copy blob container -> select root icon blob container (emulator) -> right mouse click -> paste blob container.

## Expected Experience ##
Successfully paste a blob container.

## Actual Experience ##
Copying 'documents/x.document' to 'documents/x.document': The value for one of the HTTP headers is not in the correct format. RequestId:9a85af76-233c-4dbf-893e-5123f67b27aa Time:2019-11-22T11:47:42.9866547Z

## Additional Context ##
Copy command -> 
{"CloudHub.Azure.Storage.BlobContainer":{"connection":{"type":"blobContainer","container":"x","serviceEndpoint":"https://x.blob.core.windows.net/","credentials":[{"type":"auth","accountId":"x:x","tenantId":"x"},{"type":"key","accountName":"x","accountKey":"x=="}]},"connectionString":"DefaultEndpointsProtocol=https;AccountName=x;AccountKey=x==;BlobEndpoint=https://x.blob.core.windows.net/;QueueEndpoint=https://x.queue.core.windows.net/;TableEndpoint=https://x.table.core.windows.net/;FileEndpoint=https://x.file.core.windows.net/;","containerName":"x","accountUri":"https://x.blob.core.windows.net","sasToken":"sv=2018-03-28&ss=b&srt=co&sp=rl&se=2019-11-29T11%3A48%3A40Z&sig=x"}}

**Comment by MRayermannMSFT** [comment]
@renansouza-dev , can you attach the azcopy log to this issue? You can find it in `C:\Users\username\.azcopy`. Or if you have Storage Explorer still open, there's a link at the end of the failed message.

**Comment by JasonYeMSFT** [comment]
@renansouza-dev , what MRayermannMSFT said doesn't apply to this scenario because the container copy for emulators doesn't involve AzCopy. It has been using the same code for this scenario for a long time and we need to investigate what the bug is. 

Could you please provider information of the remote blob container you are trying to copy and the emulator? What type of storage account is the container in (e.g. v1, v2, classic, premium)? How are you connecting to that container (e.g. sign-in, from key attached account, SAS attached, attached with Azure AD? Which and what version of the emulator are you using.

**Comment by renansouza-dev** [comment]
Hi, @JasonYeMSFT the remote blob container is a Storage (general purpose v1) Standard and hosted on East US 2 with Locally-redundant storage (LRS). I´m using classic sign-in over my corporate e-mail account and using Windows Azure Storage Emulator 5.10.0.0.

**Comment by JasonYeMSFT** [comment]
I can reproduce this issue with 5.10.0.0. We haven't changed the code for a while. If this was working in a previous version of emulator (e.g. 5.9.0.0), there must be some changes done on the emulator side. Could you please contact the emulator team to see what is going on? If you don't know who to contact, we can help you find someone in charge.

**Comment by renansouza-dev** [comment]
@JasonYeMSFT is this repository https://github.com/Azure/azure-storage-net?

**Comment by JasonYeMSFT** [comment]
@renansouza-dev, unfortunately it is difficult to find who is in charge of Azure Storage Emulator. As far as I know, it is officially recommended for people to use [Azurite](https://github.com/Azure/Azurite) instead of the Azure Storage Emulator for local emulation. It definitely has better support. I'll get back to you if I can find some one in charge of the Azure Storage Emulator.

**Comment by JasonYeMSFT** [comment]
I have confirmed that Azure Storage Emulator is being deprecated. Azurite is the future for emulators.
