### ISSUE TITLE
Create permissions in SAS key give "Failed to start transfer:Insufficient credentials." In Storage Explorer.

### ISSUE THREAD

**Issue by DEOGH** [microsoft/AzureStorageExplorer#2325]
**Storage Explorer Version**:1.11 and 1.11.1
**Build Number**: 1.11 and 1.11.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
After creating a SAS token with List, Read, and Create permissions, we are unable to upload files using Storage Explorer.

## Steps to Reproduce ##
1. Create SAS token with List, Read, and Create permissions for Blob Service, Container, and Object.
2. Connect to storage using connection string created in step 1.
3. Attempt to upload file.

## Expected Experience ##
File should upload.

## Actual Experience ##
Failed to start transfer: Insufficient credentials.

**Comment by JasonYeMSFT** [comment]
You need at least the "write" permission to perform the upload. See https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas for detailed explanation of how permissions work.

**Comment by DEOGH** [comment]
Testing with powershell, using AZcopy, Create works fine and works exactly as described in those articles.  It just does not work from Storage Explorer.  Not sure where you are getting that you need "write" and "create".  Create prevents overwriting files and does exactly that using AZCopy in powershell.

**Comment by JasonYeMSFT** [comment]
@DEOGH, currently we require "read", "write", "list" permissions to perform an AzCopy transfer because most of our use cases involve checking resource conflicts and potentially overwriting the resource. These extra permissions saves us the effort to go back and forth when the request run into problems.

We can add a smarter way to use AzCopy though, which is to just assume the SAS token you are having is sufficient. However, due to the service limitation, it means that the AzCopy will behave differently. For example, using "rcl" permission, you can only upload non-existing blobs to the storage, any conflict will just make it fail. Using "wl" permission, you will lose the capability of content detection and some integrity checking. 

Does this sounds like a good feature to you?

**Comment by JasonYeMSFT** [comment]
As pointed by #2291, this is a regression since our old code provides a fine-grained permission control.

**Comment by DEOGH** [comment]
That sounds like it would do the trick.  Thank you

**Comment by JasonYeMSFT** [comment]
Sounds good, let me add a work item to track this feature request instead.
