### ISSUE TITLE
Is this due to cert sniffing?

### ISSUE THREAD

**Issue by shilawat** [microsoft/AzureStorageExplorer#2337]
Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: XXXXX, Error: {
  "name": "Error",
  "message": "unable to get local issuer certificate",
  "stack": "Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

**Comment by MRayermannMSFT** [comment]
Yes? Someone on your network or machine. Is decrypting your HTTPS traffic/adding on custom certs to your network requests. Due to Storage Explorer's current design, those certs aren't trusted, so our networking requests fail. If you have those certs you can let Storage Explorer know they are trusted by getting a  Base-64 encoded X.509 (.cer) copy of the cert, and going to Edit -> SSL Certificates -> Import Certificate, and adding that cert there.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.

**Comment by shilawat** [comment]
Sorry
Should have confirmed. It was the same issue
