### ISSUE TITLE
Copy file to same location

### ISSUE THREAD

**Issue by ohadbitt** [microsoft/AzureStorageExplorer#2352]
I would like to simply copy a file to the same location it is in

Just like regular file system that u get a new file named File(copy) ... 

The only workaround i see is to download the file and upload with different name

**Comment by JasonYeMSFT** [comment]
Copy a file to itself may result in undefined behavior depending on which API you use to perform the copy. We have seen cases where your data gets lost because the backend works by creating an empty blob at the destination and then copy from source. If source and destination are the same, you lose all your data at the first step. Download and upload don't have this issue.

We have changed our rename to clone now so it basically does what you want.
