### ISSUE TITLE
A default DFS endpoint is required

### ISSUE THREAD

**Issue by ElectricLlama** [microsoft/AzureStorageExplorer#2376]
**Storage Explorer Version**: 1.11.1
**Build Number**: Don't know I had to uninstall it
**Platform/OS**: Windows 2012 R2 Datacenter
**Architecture**: x64
**Regression From**:  This works fine in version 1.10.1

## Bug Description ##
When entering ADLSGen2 URL into "Attach with Azure AD" window, this message appears: "Invalid URL A default DFS endpoint is required"

## Steps to Reproduce ##
1. "Connect To Azure Storage"
2. "Add A resource via Azure Active Dreictory"
3. Login
4. Resource Type: Blob container (ADLS Gen2)
5. Enter URL
6. Message appears, can't go next

## Actual Experience ##
Resource should connect

## Additional Context ##
-We use a proxy
-We are using ADLS Gen2 with a private endpoint

**Comment by ElectricLlama** [comment]
So I'm going to guess that https://<accountname>.dfs.core.windows.net will work, but https://<accountname>.<our privateendpointdns> will not.

**Comment by v-xianya** [comment]
@ElectricLlama 
1. In previous versions of Storage Explorer. It allows to use a blob endpoint to attach ADLS Gen2 containers.
2. Since version 1.11.0. It requires a DFS endpoint (such as "myaccount.dfs.core.windows.net") to attach ADLS Gen2 containers. 

You can get the more information from **Release Notes Known Issues section**😊

**Comment by MRayermannMSFT** [comment]
@ElectricLlama , ADLS Gen2 in Storage Explorer does not support custom storage endpoints. For now you will need to give us your DFS endpoint when attaching the container.
