### ISSUE TITLE
Storage Explorer shows critical error when renaming a file in an attached file share

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2407]
**Storage Explorer Version:** 1.11.1
**Build:** [20191206.5](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3301659)
**Branch:** dev/marayerm/electron7/packaging
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous build ([20191206.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3299462))

**Steps to reproduce:**

1. Launch Storage Explorer.
2. Expand a storage account -> File Shares.
3. Create a new file share -> Upload one file to it -> Use SAS to attach the file share.
4. Open the attached file share -> Try to rename the file.
5. Check the result.

**Expect Experience:**
Succeed to rename the file.

**Actual Experience:**
Storage Explorer crashes.
![image](https://user-images.githubusercontent.com/54055206/70517376-7a951100-1b73-11ea-9635-4c3e0a9be96d.png)

**Comment by craxal** [comment]
The error occurs after the copy has completed when querying for the delete retention policy before deleting. The call to `getServiceProperties` itself throws an error (should have passed it to the callback). According to the documentation, only the account owner is supposed to be able to call this API, meaning a SAS connection is likely incapable of getting the retention policy.

@v-limu Are you sure this is a regression? Does this also reproduce on a master build?

**Comment by v-limu** [comment]
Hi @craxal Thanks for your update!
This issue is a regression and it doesn't reproduce on master build (20191206.2)

**Comment by craxal** [comment]
@v-limu The previous build is based on a different branch than the one listed here. Furthermore, I've confirmed this issue occurs in the previous release (1.11.1); although the error message does not pop up, activity never completes once the copy is done. Therefore, this is not a regression.

The problem occurs because we try to get the delete retention policy for a file share, which doesn't work, because that's only valid for blob containers. The older client SDK handles errors like this in a weird way; they throw errors like this instead of passing them to our callback, which really messes with the proper propagation of errors.

**Comment by v-limu** [comment]
Hi @craxal Got it. Thanks for your share.

Activity log  never completes when renaming one file under one attached file share on **master branch**. It is related to: [2318](https://github.com/microsoft/AzureStorageExplorer/issues/2381)
