### ISSUE TITLE
 Add support for NTLM proxies

### ISSUE THREAD

**Issue by hirtanak** [microsoft/AzureStorageExplorer#245]
Many enterprise customers still use NTLM authentication via proxy. 
Could you please consider to add this feature, when you want for enterprise users to assist more?
I can tell me (MSFT employee) the actual name of users...

**Comment by craxal** [comment]
We've actually considered this a long time ago. Due to certain dependencies we need, there are certain networking limitations we're just stuck with. These limitations are such that working with an NTLM proxy just isn't going to work. 

- [`request` documentation](https://www.npmjs.com/package/request#proxies)

  Used to request account information from Azure management endpoints. `request` doesn't support NTLM proxies.

- [Azure Storage Client Library for Node.js documentation](https://github.com/Azure/azure-storage-node)

  Used for everything else Azure. Also uses `request`, so they have the same limitation.

- [Electron `net` module](https://electronjs.org/docs/api/net)

  Electron's upgraded alternative to Node's default HTTP/HTTPS modules, which supports NTLM proxies. If we could drop our dependency on Azure Storage Client Library for Node.js, we could switch to this module. But obviously, we can't do that!

Unless some significant improvements have been made in the last few months, it would take some considerable work and time to rework our infrastructure to use modules that can handle NTLM proxies.

**Comment by MRayermannMSFT** [comment]
In version 1.20 of Storage Explorer, we will be introducing the beginnings of support for NTLM proxies!

This support is coming as part of the addition of a new option for proxy: "Use System Proxy".

The system proxy option will, in short, have Storage Explorer make HTTP requests via the Chromium networking stack. This will enable, among other features, NTLM proxy support. That said, this feature will being in a preview state. Not all of Storage Explorer's features are in a state where they can take advantage of this new feature. We will be continuing to work on that. You can roughly track the progress of that work, with these issues:
- https://github.com/microsoft/AzureStorageExplorer/issues/4475
- https://github.com/microsoft/AzureStorageExplorer/issues/4474
- https://github.com/microsoft/AzureStorageExplorer/issues/4483

Finally, AzCopy does not yet support NTLM proxy. We are working with the AzCopy team to get support there as well. We'll give updates on that effort here: https://github.com/microsoft/AzureStorageExplorer/issues/4553
