### ISSUE TITLE
Unable to login to Azure Government

### ISSUE THREAD

**Issue by KentVo-Veritas** [microsoft/AzureStorageExplorer#2468]
**Storage Explorer Version**: 1.11.1
**Build Number**: 20191121.1
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  This is the very first time to login (no previous version is tried)

## Bug Description ##

Following is the error message when I tried to login. After excepting my password, it went through but it had the error.

Subscriptions for the follwowing tenants could not be retrieved:
Tenant Id: 70889911-4781-455a-be50-67374e134267, Error: {
  "name": "Error",
  "message": "unable to get local issuer certificate",
  "stack": "Error: unable to get local issuer certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)\n    at ZoneDelegate.invokeTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:275:35)\n    at Zone.runTask (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:151:47)\n    at TLSSocket.ZoneTask.invoke (C:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\zone.js\\dist\\zone-node.js:345:33)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket._finishInit (_tls_wrap.js:631:8)",
  "code": "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"
}

## Steps to Reproduce ##

Attempted multiple times to login with the same result.

**Comment by jinglouMSFT** [comment]
Someone on your network or machine is decrypting your HTTPS traffic/adding on custom certs to your network requests. Due to Storage Explorer's current design, those certs aren't trusted, so our networking requests fail. If you have those certs you can let Storage Explorer know they are trusted by getting a Base-64 encoded X.509 (.cer) copy of the cert, and going to Edit -> SSL Certificates -> Import Certificate, and adding that cert there.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.
