### ISSUE TITLE
Function to rename folder disappeared after an update

### ISSUE THREAD

**Issue by felyperennan** [microsoft/AzureStorageExplorer#2504]
**Is your feature request related to a problem? Please describe.**
There was a feature where the user could press F2 to rename a folder, now the only option is "clone with a new name"

**Describe the solution you'd like**
It would be good to have the Rename folder function back. 

**Describe alternatives you've considered**
Copying with a new name and then deleting the old folder, but it's not optimal.

**Additional context**

**Comment by JasonYeMSFT** [comment]
Hi, we recently decided to change the behavior from "rename" to "clone" after careful consideration. 

Since our rename is copying data to the new destination and then deleting the original ones, it can lead to a tricky situation where half the data are copied and deleted while the rest fails due to maybe network error. Some user has attempted to delete the destination folder and retry rename, being unaware that he is losing the data that has been successfully copied.

We need to re-design the rename feature and eliminate the potential risk before bringing it back.

**Comment by felyperennan** [comment]
I see, it makes sense now;
Is it not about time the Azure Storage had a "RENAME" or "MOVE" verb/operation so that we wouldn't need to copy and then delete, I'm seeing questions about azure's lame way of renaming from 2012 here.

**Comment by MRayermannMSFT** [comment]
Making a rename/move API available is something we're discussing with the platform team. For now though, what Jason said is correct.
