### ISSUE TITLE
Allow Copy/Paste (Duplication of existing row)

### ISSUE THREAD

**Issue by leroibeukes** [microsoft/AzureStorageExplorer#2547]
Sometimes I have to 'clone' a row of data on the table view , to do this I have to export , update the file and then re-import. 

This is painful as sometimes I just need to change a partition key or some other column.

Could you please explore adding this feature (perhaps as a right-click on a row).

This would help us a lot.

Thanks

**Comment by craxal** [comment]
@leroibeukes Since entities require unique partition/row keys, we'd need some way for you to specify the new key. How do you envision the flow of cloning an entity? Right-clicking and selecting a command menu is a good first step. From there we could go in several different directions:
- **Option 1: Auto-generate** - Storage Explorer could try auto-generating the new keys. This could be difficult to get right, as the conventions for keys could be different for every table. In addition, would you expect the new entity to be in the same partition? Is there a pattern for the new keys you'd expect, such as "rowkey-1" or "rowkey-copy1"?
- **Option 2: Dialog** - Storage Explorer could open an entity dialog and let you specify the new keys. The dialog could also show you the properties being copied and even let you tweak the values for the copied entity. This would require more inputs.

Ultimately, the question is, do you want a click-once experience, or a more controlled experience?

**Comment by craxal** [comment]
We opted for a more controlled approach with a dialog similar to the Add Entity and Edit Entity dialogs, except the keys are editable and the other properties are readonly. This change has been merged and should be available in 1.26.0. Once that version becomes available, try it out and leave any feedback you might have.
