### ISSUE TITLE
The layout of Clone dialog is unfriendly for one blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2572]
**Storage Explorer Version:** 1.12.0
**Build:** [20200122.8](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3407621)
**Branch:** master
**Platform/OS:** Windows 10/ Linux Ubuntu 18.04/ MacOS High Sierra
**Architecture:** ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Expand one Non-ADLS Gen2 storage account -> Blob Containers.
2. Select one blob container and right click it -> Click 'Clone with New Name...'.
3. Check the layout of Clone dialog.

**Expect Experience:**
The layout of Clone dialog is friendly.
![image](https://user-images.githubusercontent.com/41351993/72962144-73a62300-3dee-11ea-8f29-92a407db92ff.png)

**Actual Experience:**
The layout of Clone dialog is unfriendly.
![image](https://user-images.githubusercontent.com/41351993/72962194-9c2e1d00-3dee-11ea-8a9b-8d221b2c5459.png)

**More Info:**
1. This issue doesn't reproduce for one file share.

**Comment by craxal** [comment]
It appears that the spacers are sized before the CSS styles have been applied by the rendering engine, which means the title height is actually larger before it's styled. That's where the extra space is coming from. We likely didn't encounter this problem before, because most of our titles stay on one line regardless of styling.

Since we're doing away with this dialog at some point, I'll just adjust the width a bit.
