### ISSUE TITLE
Got error "UnexpectedCancel"

### ISSUE THREAD

**Issue by renqianluo** [microsoft/AzureStorageExplorer#2680]
Hi, when I upload data to a blob container, it failed with error
{
  "message": "\"UnexpectedCancel\""
}
Could you help check this? Thanks

**Comment by JasonYeMSFT** [comment]
We cancel the AzCopy job scheduled by us if we encounter internal errors. Can you provide more information such as:
1. What OS are you on?
2. What Storage Explorer version are you using?
3. Which type of authentication are you using for the blob container (e.g. sign-in, Azure AD, SAS)?
4. What is the path of your local file and the destination of your upload?
5. Are you consistently seeing all uploads fail or just on some files?

Thanks

**Comment by renqianluo** [comment]
@JasonYeMSFT Thanks for your reply. I have fixed that. It is due to the permission issue.

**Comment by pbabahajur** [comment]
Hi, how did you solve it? What permission do you require? In my case, I have been uploading files, however, just during the upload it failed and now it's giving the "UnexpectedCancel" error.

**Comment by cool-aquarian** [comment]
I was facing same error.
But it was because of insufficient available quota in file share.
I was able to copy after increasing the storage quota.

**Comment by alexander7567** [comment]
For me, it was because of a setting I had set when I created the Storage Account. In "Configuration", under "Permitted scope for copy operations", I had mine set to "From storage account in the same Azure AD tenant". Even though I was copying within the same subscription and everything, it wouldn't let me copy with this same error. I had to change it to "From any storage account". As soon as I changed that, it worked.
