### ISSUE TITLE
Disk unable to download

### ISSUE THREAD

**Issue by waltburton** [microsoft/AzureStorageExplorer#2709]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by waltburton** [comment]
It looks like none of the text I entered to the template posted.

![image](https://user-images.githubusercontent.com/62071612/76443689-d8164500-6390-11ea-98bc-9500188c04f9.png)


Bug Description - successful for one disk upload, but not another disk.  Multiple attempts have all failed.

Steps - Opened Storage Explorer, selected VHD to download, gets to completion point but then fails to finish the disk download.
Have also created snapshot of the problem disk and converted to a managed disk.  this download also failed.

Expected experience is a successful download.

Actual experience is this disk fails to download

Additional Context - Azure hosted servers were breached with malware and infected files on disk do exist (or at least suspected).  Trying to download VHD to take into an air gapped lab environment to diagnose and attempt recovery of files.

**Comment by jinglouMSFT** [comment]
From your description, this looks like the download failed because of the MD5 check. We recently learned that we should not be checking the MD5 hash for disk VHDs. Starting in 1.13.0 we will not be doing that. For now though, you can go to Setttings -> Transfers -> AzCopy -> Check MD5 and change the option to be "No check".  Please give it a try and if it still doesn't work, we probably will want to take a look at the log file. You can find the log file on C:\users\user_name\.azcopy.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response.

**Comment by waltburton** [comment]
Thanks.
I had responded that disabling MD5 did work.  But looks like my reply never posted.

Walt Burton  Sr. Systems Engineer  Paradise Canyon Systems
Direct 847.380.3365  Cell 847.910.1334
walt.burton@paradisecyn.com<mailto:walt.burton@paradisecyn.com>
