### ISSUE TITLE
All accounts are removed when removing the first signed-in account with MSAL enabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2746]
**Storage Explorer Version:** 1.12.0
**Build**: [20200322.2](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3573346)
**Branch**: master
**Platform/OS:** Windows 10
**Architecture**: ia32
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**
1. Launch Storage Explorer (make sure MSAL setting is applied).
2. Add two different accounts.
3. Try to remove the first signed-in account  -> Check the result.

**Expect Experience:**
The first signed-in account is removed.

**Actual Experience:**
Both of the accounts are removed.

**Comment by MRayermannMSFT** [comment]
@v-xianya can you please email me the contents of "C:\Users\yourname\AppData\Local\.IdentityService\StorageExplorerV2AccountStore.json"

Before removing any accounts, and after all accounts been removed? Also, tell me which account you manually removed. Thanks!

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT  The email is sent. Check it, please!😁

**Comment by MRayermannMSFT** [comment]
@v-xianya thanks for the help. Unfortunately this behavior is....by design, at least for our auth library it is.

Basically, the accounts y'all added are considered "personalization accounts". That's a VS term, and it means an account that roams VS settings, licensing, and other VS things. The behavior of the auth library is that after an account is removed, if no personalization accounts exist, all accounts are removed.

I've opened a bug against the auth library team for them to change this behavior. https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1088200

So unfortunately there's nothing we can do about this for now. I'll move this issue to the next milestone.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
Thank you for the sharing. But one thing is confusing.😓😓
If this behavior is by design. why it does not reproduce in previous release (1.12.0)? Is there any update for the auto library?

**Comment by MRayermannMSFT** [comment]
The library must have regressed.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT 
On the latest build 20211102.7.  also reproduce on the release version 1.21.3.
Select 'Integrated Sign-in',
Sign in two accounts -> Remove one of the account -> Then both accounts are removed.

**Comment by v-xianya** [comment]
This issue doesn't reproduce on the build 20220605.1. So, we are going to close it.
