### ISSUE TITLE
The access tier shows next to blob snapshots

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2766]
**Storage Explorer Version:** 1.13.0
**Build**: [20200328.6](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3591516)
**Branch**:  rel/1.13.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ macOS High Sierra
**Architecture**: ia32/x64
**Regression From:** Previous release(1.12.0)

**Steps to reproduce:**

1. Select a storage account -> Blob Containers.
2. Create a new blob container -> Upload one blob to it -> Create snapshot for the blob -> Manage Snapshots.
3. Check whether the access tier shows next to the snapshot or not.

**Expect Experience:**
No access tier shows next to the blob snapshot.

**Actual Experience:**
The access tier shows next to the blob snapshot.
![image](https://user-images.githubusercontent.com/54055206/77902719-3a89a380-72b4-11ea-9cdc-844688c30826.png)

**More Info:**
This issue still reproduces after manually refresh.

**Comment by JasonYeMSFT** [comment]
The change is caused by using v12 blob SDK to list blobs, which used to be v2 SDK. It turns out that the new behavior is providing more accurate information than before. It is possible for snapshots to have access tiers and it can be different from the base blob's access tier. In Portal, the view snapshot view also have the "access tier" column and displays the access tier for each snapshot, active or not. 

Thus the new behavior is better by design.
