### ISSUE TITLE
Provide a way to disable telemetry collection

### ISSUE THREAD

**Issue by avishnyakov** [microsoft/AzureStorageExplorer#2846]
**Is your feature request related to a problem? Please describe.**
Cannot find a way to disable telemetry, the AppInsights, and avoid hitting dc.services.visualstudio.com urls.

**Describe the solution you'd like**
A flag or env variable to opt-out from telemetry similar to az cli
> https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration?view=azure-cli-latest#cli-configuration-values-and-environment-variables

**Describe alternatives you've considered**
Searching Google and GitHub issues and releases to find how to disable telemetry. 

**Additional context**

**Comment by jinglouMSFT** [comment]
You can turn off telemetry collection from the Telemetry Settings dialog under the Help drop down menu.

**Comment by MRayermannMSFT** [comment]
As jinglouMSFT said, you can disable telemetry via the help menu:
<img width="395" alt="image" src="https://user-images.githubusercontent.com/21112697/82235364-7372eb80-98e7-11ea-9f80-b9808e4effb6.png">
Going to go ahead and close this since it's gone a month without activity. Please open a new issue if you having any new issues. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing now.
