### ISSUE TITLE
The version of the update notification should be 1.2.0

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#288]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: All
**Architecture**: ia32/x64
**Build Number**: 20180611.3
**Commit**: e00d7640
**Regression From**: Previous release

#### Steps to Reproduce: ####
1. Launch Storage Explorer using the following command: ".\StorageExplorer.exe --add-update-group=CTI".
2. Check the version of the update notification.

#### Expected Experience: ####
It displays as 1.2.0.

#### Actual Experience: ####
It still displays as 1.1.0.
![notification](https://user-images.githubusercontent.com/34729022/41278493-77ea72fa-6e19-11e8-8315-141e1fa63325.png)

**Comment by MRayermannMSFT** [comment]
Hey @v-xuanzh , I checked this morning, and the test case you are referencing says that the version number should be 1.1.0. So this is a non-issue.

**Comment by v-xuanzh** [comment]
Hi @MRayermannMSFT , I'm a little confused about this issue. The Storage Explorer v1.2.0 has been released in last week(Build number: 20180605.1). Why it still displays 1.1.0 in the update notification when checking for updates?

**Comment by MRayermannMSFT** [comment]
Because I specifically made the notification for the test case use 1.1.0. Doing so lets me make sure that the test case is actually working. The test case is not only testing Install Now/Install on Close/View Release Notes, but also verifying that we can send updates to specific groups and that the version number we display is pulled from the update service correctly.

**Comment by v-xuanzh** [comment]
I see. Thanks for your updates. :)
