### ISSUE TITLE
DatePicker on Shared Access Signature creation can be incremented to an invalid date

### ISSUE THREAD

**Issue by thefrooh** [microsoft/AzureStorageExplorer#2884]
**Storage Explorer Version**: 1.12.0
**Build Number**: 20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Don't know, just noticed it recently.

## Bug Description ##
When creating a Shared Access Signature on a block blob, you can specify the expiry date. There you have the option to select an invalid date, e.g. April 31st by slecting the day component and clicking on the incrementing button. 

## Steps to Reproduce ##
1. Open any blob container
2. Right click on any blob and click on Get Shared Access Signature
3. On the expiry time input field, highlight the day value.
4. Keep clicking on the up arrow to increment the expiration day until an invalid day of month (e.g. April 31st.)

## Expected Experience ##
I should not be able to increment the value to an invalid date.

## Actual Experience ##
I can increment the value to an invalid date. The input validation on losing focus works fine, so in the end I'm not able to create a shared access signature.

**Comment by MRayermannMSFT** [comment]
Hey @thefrooh , since the validation is correctly failing this isn't too big of a concern. Also, we're using the vanilla date-time picker that chromium/Electron provides, so we cannot easily fix the control to prevent it from letting you do as described. Therefore, we're going to go ahead and won't fix this issue.
