### ISSUE TITLE
The descriptions of actions on queues context are different from before

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2900]
**Storage Explorer Version:** 1.13.0
**Build**: [20200428.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681243&view=results)
**Branch**: master
**Platform/OS:**  Windows 10/ Linux Ubuntu 18.04
**Architecture**: ia32/ x64
**Regression From:** Previous release(1.13.0 & 1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Select one queue -> Check the actions on its context menu.

**Expect Experience:**
The descriptions of actions on queues context are same as before.

**Actual Experience:**
The descriptions of actions on queues context are different from before.
![image](https://user-images.githubusercontent.com/41351993/80452878-c21d0d80-8959-11ea-86eb-bf241e508f5d.png)

**More Info:**
The action 'Refresh' is removed.

**Comment by craxal** [comment]
@v-xianya After discussing with the team, we've decided on the following:
- "Open New Tab" will be changed to "Open in New Tab". The is preferable, because it sounds a little more clear about what the action does, and it follows the phrasing used in most browsers.
- "Manage Access Policies..." will be changed to "Manage Stored Access Policies...". This is the term used in the Azure documentation, and it helps clarify the difference between the access policies used by ADLS Gen 2 blob containers.
