### ISSUE TITLE
An extra action 'Copy Direct Link' shows for one queue on Linux platform

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2901]
**Storage Explorer Version:** 1.13.0
**Build**: [20200428.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3681243&view=results)
**Branch**: master
**Platform/OS:** Linux Ubuntu 18.04
**Architecture**: ia32/ x64
**Regression From:** Previous release(1.13.0 & 1.12.0)

**Steps to reproduce:**
1. Expand one storage account -> Queues.
2. Select one queue -> Check its context menu.

**Expect Experience:**
No 'Copy Direct Link' action shows.

**Actual Experience:**
An extra action 'Copy Direct Link' shows
![image](https://user-images.githubusercontent.com/41351993/80457025-2d1e1280-8961-11ea-9338-d829cf5fba0f.png)

**Comment by craxal** [comment]
@jinglouMSFT @MRayermannMSFT @JasonYeMSFT My understanding is we did not turn on direct links for Linux, because Linux did not have a standard way for registering apps to handle custom protocols, is that right? @JasonYeMSFT pointed out, however, that we can still generate direct links on Linux even if we don't support actually using them on Linux. What do y'all think? Should I remove the command or leave it in as a "new" feature?

**Comment by jinglouMSFT** [comment]
@craxal  That's correct.  We don't support deep link on Linux.  
If we don't support using the deep links on Linux, what can people do with the deep links we generate?  Using them on Windows, Mac?  It's definitely a "new" feature.
