### ISSUE TITLE
Files not filtering based on Modified Date

### ISSUE THREAD

**Issue by ramire-cc** [microsoft/AzureStorageExplorer#2913]
**Storage Explorer Version**:  1.12.0
**Build Number**:  20200116.10
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:   Not sure, Issue is only observed right now.

## Bug Description ##
 New items are saved in a blob container but when we click on "Modified Date" column to show today's files, they're not showing. We do a manual search on search box and we see the file we're looking for.

## Steps to Reproduce ##
Stated in description.

**Comment by MRayermannMSFT** [comment]
@ramire-cc how many files are in your container? If it is more than 1000, it is possible that clicking on last modified may not show you what you want. 

The server does not let us list blobs by last modified, so when you click on the column, you are only sorting what we have so far pulled from the server. So, to get your file to show up, you'll need to click Load More in the bottom right until all blobs are loaded and then column sort.

**Comment by ramire-cc** [comment]
Hi Matthew,

Thank you for your response and I did your suggested steps and saw sorted files by modified date now.

Is there a better or quicker way to load all the pages instead of going to the very last page just for all files to be loaded?

Is this issue also a known problem that’s being fixed?

Will appreciate further assistance on this. Thank you!

Regards,

[Image]
Ramir Enriquez
Cloudster Connect


a:
Australia, The Philippines, India
w:
www.cloudsterconnect.co<http://www.cloudsterconnect.co/>  e: RamirE@cloudsterconnect.co<mailto:RamirE@cloudsterconnect.co>

**Comment by ramire-cc** [comment]
Hello Matthew,

May I have an update about the raised issue about sorting 1000+ files?
Just want to know if there's a quicker way to do this instead of loading all pages?
In my case, I had to load 30+ pages to sort everything accordingly.

I'll appreciate your response. Thanks for the support so far.

**Comment by MRayermannMSFT** [comment]
@ramire-cc Right now there is no faster way for you to "load all" other than clicking load more multiple times. That experience is something we've been thinking about, but for now I have nothing concrete to share.

The limitation of the server to give us blobs listed by things other than alphabetical order is something that the platform team is aware of, but as far as I know there are no immediate plans to address the limitation.

It sounds like your issue is mitigated though, so I'm going to go ahead and close this issue. Thanks!
