### ISSUE TITLE
No dialog pops up when using an existing name to create one queue

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#2932]
**Storage Explorer Version:** 1.13.0
**Build**: [20200504.7](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3700661&view=results)
**Branch**: master
**Platform/OS**: Windows 10/ macOS Catalina / Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Previous release(1.13.0)

**Steps to reproduce:**

1. Expand one storage account -> Queues.
2. Create one queue -> Using an existing name to create one new queue.
3. Check the result.

**Expect Experience:**
A dialog pops up.
![image](https://user-images.githubusercontent.com/54055206/81160831-2d4f8b00-8fbd-11ea-95b0-83f372a57ac8.png)

**Actual Experience:**
No dialog pops up.

**Comment by craxal** [comment]
The queue service is returning a code 204, which apparently means success? That sounds like a potential bug in the service. I'll need to follow up with them.

**Comment by craxal** [comment]
The platform team has explained that, when a queue with matching name exists, the service compares the new queue request's metadata with the existing queue. A proper error is only returned if the metadata is different. Since Storage Explorer doesn't create queues with metadata, this outcome is very likely to happen.

@XiaoningLiu Is this response known to the client library? In other words, does the client library handle this case intentionally in some way? Do you have recommendations, or is this something we should fix?
