### ISSUE TITLE
The new created folder in one tab doesn't auto display in others opened tabs with same file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#2943]
**Storage Explorer Version:** 1.13.0
**Build**: [20200507.4](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3708219&view=results)
**Branch**: dev/marayerm/electron/8
**Platform/OS:** Windows 10/ macOS Mojave/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one storage account -> File Shares.
2. Create a new file share -> Open two tabs for it.
3. Select one tab and create a new folder.
4. Open another tab -> Check whether the new folder displays or not.

**Expect Experience:**
The new folder displays well.

**Actual Experience:**
1. The new folder doesn't display.
2. The new folder displays after clicking refresh.

**More Info:**
This issue doesn't reproduce for one ADLS Gen2 blob container.

**Comment by craxal** [comment]
@v-xianya In step 4, when you say "Open another tab", are you referring to the second tab that was already opened, or do you mean open a new third tab?

**Comment by v-xianya** [comment]
@craxal Sorry for the confusion😓.
"Open another tab" refers to the second tab that was already opened.

**Comment by craxal** [comment]
@v-xianya Thanks. This is expected behavior. Editors do no communicate between each other. Therefore, if you add a new folder in one tab, there's no way for the other tab to know there is a change and needs to update. Marking this is as by design.

**Comment by v-xianya** [comment]
@craxal Thanks for the updates. But for one ADLS Gen2 container, When creating one folder in one tab, the new created folder displays in the other tab. Could you help to clarify this behavior?

**Comment by craxal** [comment]
@v-xianya After creating a new folder, we raise an event that the ADLS Gen2 editors are listening for. When the event is received, they refresh their views. This only happens if the connection info matches the info associated with the editor. In your case, you had two editors that had the same connection info. So, when you created a folder, both editors received the event.

While this does seem inconsistent with regular blobs, I do not consider either case a bug. The dev team can discuss further, but I'm going to keep this closed as by design until we decide otherwise.
