### ISSUE TITLE
Copying Azure blob container folders with colon in name results in name with %3A instead

### ISSUE THREAD

**Issue by zmarty** [microsoft/AzureStorageExplorer#2971]
In an Azure container I have a folder called "sr:season:66441". If I drag and drop that folder to my local Windows machine, that folder ends up with this name: sr%3Aseason%3A66441

**Comment by jinglouMSFT** [comment]
This is because ':' is not a valid char for folder or file names on Windows.  So it's been encoded.

**Comment by zmarty** [comment]
I know. Couple of questions:
- Can't we replace it with a better character?
- Is this still a limitation if I run the app on Linux?

**Comment by MRayermannMSFT** [comment]
@zmarty `%3A` is the URI encoding value for `:`. Currently URI encoding is the scheme we use for encoding chars which are invalid for your OS. For Linux, `:` won't be encoded. You'll see it appear as normal, since on Linux it is not invalid to have it in file name/path.

We will not be changing away from using URI encoding.

Does that all make sense?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response.
