### ISSUE TITLE
Unable to add values to a newly added property in Azure Tables

### ISSUE THREAD

**Issue by dvaco-dba** [microsoft/AzureStorageExplorer#2982]
**Storage Explorer Version**: 1.13.0
**Build Number**: 20200430.5
**Platform/OS**: Windows 7 (Don't ask...)
**Architecture**: ia32
**Regression From**:  N/A (only tested in the latest version)

## Bug Description ##
Hi, I just experienced very similar issues to what has been discussed in detail [here](https://github.com/microsoft/AzureStorageExplorer/issues/356). I'm not sure if this is confusion on my part, or if there is an issue, but I've been unable to find any documentation on this so I'm reaching out here. Thanks in advance. 

In an ADLS Gen 2 Table, I added a property to a random entity expecting it to create a new "column" for all the "rows" in the table, and quickly learned that is not how this works. Okay, read a bunch of articles on docs.microsoft.com and am up to speed. I then wrote a query in Storage Explorer that returned only the entities that need this new property for a new project I'm working on. In the result set I see the new property there (even though I never added it to these entities), and they all have a value of _null_, but when I right click > Edit... or double click an entity I don't see the property in the Edit Entity window, and am unable to assign it a value.

With the above in mind, how do you add values to a new property? If I can see it in the result set with a _null_ value, then why is it missing from the Edit Entity window where I need to assign it a value? Is it because I never really added this new property to these particular entities? If so, is the expectation that we need to click the "Add Property" button for each entity in question, and add a property with the exact same name to assign it a value? When I do that, it adds a second property with the same name and then I have one that's _null_ and one that has a value... and both appear in the drop down for "Field" in the Query editor, among other places.

If the above is true, then is there a way to add a new property to every entity in a table and assign it an initial value? Similar to creating a new column in an existing SQL table and giving it a default value for all records in the table. This seems like it would make Azure Tables much easier to work with when you have to add new properties.

Any assistance you can provide is greatly appreciated.

## Steps to Reproduce ##
1. Add a new property to a random entity in an Azure Table.
2. Write a query that returns results that DO NOT include the entity you added the property to in step 1.
3. Note that the new property shows in the results grid with a _null_ value, despite not adding this property to any of these entities.
4. Right click an entity or double click to Edit.
5. Note that the new property seen in step 3 is not present in the Edit Entity window.

## Expected Experience ##
I would expect that if a new property is visible in the results of a query with a _null_ value (even if you never added that property directly to those particular entities) then you should be able to edit the entity and assign that property a value.

## Actual Experience ##
I am unable to edit _null_ values for new properties as they do not display in the Edit Entity window. Only option is to add another property with the same name, but then I get duplicate properties where one is _null_ and the other has a value.

**Comment by craxal** [comment]
@dvaco-dba Here's hoping I can answer your questions!

> I added a property to a random entity expecting it to create a new "column" for all the "rows" in the table, and quickly learned that is not how this works. Okay, read a bunch of articles on docs.microsoft.com and am up to speed.

As I'm sure you've discovered, Azure Tables are _not_ SQL tables. They are scheme-_less_. That means the idea of a "column" in an Azure Table is somewhat of a false idea. Not all entities have the same set of properties, and entities that have properties with the same name could even be different data types.

> If the above is true, then is there a way to add a new property to every entity in a table and assign it an initial value? Similar to creating a new column in an existing SQL table and giving it a default value for all records in the table.

In light of the above, sadly, there isn't really an easy way to choose a default value for new properties or apply any sort of change to all properties in a table. In the past, we thought about treating tables in a more SQL-like manner, but we realized adding client-side behavior over Azure was too error-prone.

> How do you add values to a new property? If I can see it in the result set with a null value, then why is it missing from the Edit Entity window where I need to assign it a value? Is it because I never really added this new property to these particular entities? If so, is the expectation that we need to click the "Add Property" button for each entity in question, and add a property with the exact same name to assign it a value?

Yes, that's correct. Displaying Azure Table data in a tabular format is useful, but as mentioned above, the idea of "columns" in an Azure Table is a bit misleading. Storage Explorer keeps a list of "discovered" properties as Azure lists them and turns these into columns in the data table.  A "null" value means the entity in Azure does not have a property of that name. When you open that entity for editing, that's why you don't see that property there. You need to click "Add Property" and give it a value to actually add that property to the entity.

> When I do that, it adds a second property with the same name and then I have one that's null and one that has a value... and both appear in the drop down for "Field" in the Query editor, among other places.

Not entirely sure what the query editor is doing, but the actual columns in the data table should reflect the change accurately. You don't see duplicate columns, do you?

**Comment by dvaco-dba** [comment]
@craxal Thank you for taking the time to review my issue and reply in detail! I see now where I got things mixed up in my testing. When I went to edit the entity and add the property with the same name, I added it as the default 'string' data type, which is different than the original (boolean). As you said, you can have two properties with the same name but different data types, and that is why I was seeing it duplicated everywhere. I just tested again, this time with the correct data type, and everything is behaving as you described. I'm all set now, so I'll close this out. Thanks again for your time!
