### ISSUE TITLE
Allow auto delete of files with snapshots

### ISSUE THREAD

**Issue by AtomicNibble** [microsoft/AzureStorageExplorer#3062]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to delete a folder that has files inside with snapshots. Currently I must locate all files with snapshots, view snapshots delete them, then delete said file which is really slow.

**Describe the solution you'd like**
A option in the delete logic for auto snapshots removal, some sort of checkbox?

Thanks.

**Comment by MRayermannMSFT** [comment]
Hey @AtomicNibble, in our latest update, 1.13.0/1.13.1, we added the ability to delete snapshots when you retry a delete:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/21112697/83436813-65e35880-a3f3-11ea-8f4e-eec1b1b47215.png">

I understand you'd probably want to be able to start the delete with this enabled, but since snapshots are normally used for backup purposes, we wanted to make sure the user was always confirming that, yes, they really do want to delete snapshots.

**Comment by AtomicNibble** [comment]
No that works great for me!

I was already on 1.13.0 but did not think to click retry.

Thanks.
