### ISSUE TITLE
Updating Table record with DateTime fields changes DateTime due rounding.

### ISSUE THREAD

**Issue by Rambalac** [microsoft/AzureStorageExplorer#3095]
Version: 1.13.1
AzCopy Version: 10.4.2

Platform: Windows
Architecture: ia32 
Build Number: 20200515.1 
Commit: b846b853c 
Support ID: 086db33f-1126-975f-8257-42893ba673d8 

## Bug Description ##
Modification of Table record that contains DateTime fields changes DateTime fields due lose of precision.

## Steps to Reproduce ##
Create a record using .NET SDK with string and datetime fields. DateTime set to Utcnow.
Retrieve record using SDK. DateTime field Ticks are exactly as original instance.
Update string field using Storage Explorer. No DateTime fields get changed in UI.
Retrieve record using SDK again. DateTime field Ticks does not match previous Ticks.

## Expected Experience ##
DateTime field Ticks should not be changed.

## Actual Experience ##
DateTime field Ticks get changed due rounding.

**Comment by craxal** [comment]
This is likely due to the difference in date representations between the .NET framework and JavaScript. JavaScript date objects only have millisecond precision. The Azure Client Library for Node returns EDM.DateTime property values as JavaScript date objects. There appears to be a a way to customize the format of entity objects, so we may be able to fix this. However, this is pretty low-level in the code, so we'd have to be very careful we don't break something else.

**Comment by craxal** [comment]
A team is working on a modern version of the client library for Azure tables. I've verified that we'll be able to get the necessary response without deserialization/precision loss. When the library is ready, we will look into integrating the new library.
