### ISSUE TITLE
The Expiration date displays local time in 'Connection Summary' dialog although select UTC time zone when creating SAS

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3123]
**Storage Explorer Version:** 1.14.0
**Build**: 20200618.2
**Branch**: rel/1.14.0
**Platform/OS:** Windows 10/ macOS Catalina / Linux Ubuntu 18.04
**Architecture**: ia32/x64
**Regression From**: Not a regression

**Steps to reproduce:**
1. Select one non-adls gen2 storage account then right click it -> Click 'Get Shared Access Signature...'.
2. Select 'UTC' Time zone (Notice the Expiry time) -> Click 'Create' -> Copy the connection string to clipboard -> Click 'Close'.
3. Open connect dialog -> Click 'Use a connection string' -> Click 'Next'.
4. Paste the copied connection string -> Click the 'Next'.
5. Check the Expiration date.

**Expect Experience:**
Display the UTC time.

**Actual Experience:**
Display the Local time.

**Comment by MRayermannMSFT** [comment]
@v-xianya , in the create SAS dialog, choosing between local and UTC time is merely a convenience feature. The time which is ultimately stored in the SAS is a UTC time.

Then in the connect dialog, that UTC time is taken and is displayed in local time. We do that because we think that when a user is attaching something a local time is most relevant to them.
