### ISSUE TITLE
Unable to load attached Storage Account. Error: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by uscagr** [microsoft/AzureStorageExplorer#3133]
**Storage Explorer Version**: 1.13.1
**Build Number**: 20200515.1
**Platform/OS**: Windows
**Architecture**: ia32
**Regression From**:  I belive it was working but not sure if it is this version or previous one

## Bug Description ##
when I try to click on the storage account it shows up the above error  
## Steps to Reproduce ##
Expand Local & Attached
Click storage account

## Expected Experience ##
Once you click on the account it should show the folder structures and files

**Comment by JasonYeMSFT** [comment]
@uscagr, this is caused by the data stored for local attachments being corrupted. Could you please try the steps in the troubleshooting guide to locate and clear the corrupted data? [troubleshooting guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined). We were able to locate one possible cause of it, which was us reaching the Windows credential manager capacity. If you have a lot of items in your credential manager. Please consider removing some unused entries.

Unfortunately there are still unknown causes for this issue. If the troubleshooting steps don't work, please consider scheduling some time with us so we can help you debug the issue.

**Comment by ibuda** [comment]
I had the same issue but after updating to 1.14.0 version, the issue disappeared.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response from original issue opener. Please open a new issue if you are continuing to have problems.
