### ISSUE TITLE
In data table, consecutive whitespaces in queue messages are condensed into one

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3134]
1. Add a message to a queue, message contents:
```
a  a    a      a
```
2. View the message in the queue

Expected:
Message shows as 
```
a  a    a      a
```

Actual:
Message shows as `a a a a`

**Comment by JasonYeMSFT** [comment]
It is due to our CSS property `white-space: nowrap`
![image](https://user-images.githubusercontent.com/39359541/101423210-67fc0780-38ad-11eb-93e4-6c1a43a0f35b.png)

If set to `white-space: pre`, it would look like
![image](https://user-images.githubusercontent.com/39359541/101423168-4c90fc80-38ad-11eb-90bb-52f6197d8193.png)
