### ISSUE TITLE
Queue messages are shown raw in the data table

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#3135]
In 1.13 and earlier, we would apply a base64 decoding to messages in the data table. In 1.14 we're just showing their raw UTF8 value.

**Comment by v-xianya** [comment]
Hi @craxal @MRayermannMSFT 

We verified this issue on build 20200624.3.
For Base64 encode message, message text shows expected in the data table.
 
For UTF8 encode message, message text shows as messy code in the data table. The behavior like below:
1.  Add message with content '中文',  the message in data table shows:
![image](https://user-images.githubusercontent.com/41351993/85509649-eed36580-b628-11ea-965c-e6dcb3dc1dac.png)

2. Add message with content'12345', the message in data table shows:
![image](https://user-images.githubusercontent.com/41351993/85509686-001c7200-b629-11ea-802a-67be90ea0a45.png)

3. Add message with content 'english', the message in data table shows:
![image](https://user-images.githubusercontent.com/41351993/85509591-d9f6d200-b628-11ea-8bc8-1ab32945e56a.png)

**Comment by craxal** [comment]
@v-xianya In all versions prior to 1.14.0 we always attempted to decode using Base64 in the data table. This was changed at one point to leave strings unencoded (UTF-8). However, it's unclear which encoding most users use, and changing the default would likely look strange for users not expecting it. This bug was logged to make sure we revert to the previous behavior.
