### ISSUE TITLE
Notifications bar blocks tab access

### ISSUE THREAD

**Issue by ahippie** [microsoft/AzureStorageExplorer#3148]
When Storage Explorer displays a message, the message is displayed directly over the top of the tabs at the top of the app. There doesn't appear to be any way to move it or to configure it. It shows up whenever the app has a message to display and will show up again repeatedly if you close the message.

The messages are extremely intrusive. It would be ideal if there were a small notifications icon similar to the way Visual Studio tells you there is a message to be read. Put it up in the menu bar and highlight it when there are messages versus popping it right on top of the work surface.

In the image below, hiding underneath the message about an updated version is a tab with query results. If there is more than one tab, you wouldn't know because you can't see them.

![image](https://user-images.githubusercontent.com/13965367/85873453-fc523200-b785-11ea-9651-4ae3c51f2801.png)

**Comment by MRayermannMSFT** [comment]
@ahippie you can dismiss the bar using "Close" or by choosing to update (which is what I'd prefer 😋). Is there some reason you don't want to upgrade?

**Comment by ahippie** [comment]
This was one example. I actually selected Install on Close in this case. There are various popups that display. The most intrusive are related to the case where I have added access to items that require a login I don't typically use. When the login expires, there is a popup displayed. It displays multiple times in a session prompting me to login to that account. The point is that the messages is intrusive and demands attention in order for me to do my work. I keep having to hit close or some other action. Messages shouldn't demand and prevent work unless you take an action.

**Comment by MRayermannMSFT** [comment]
> Install on Close

Good stuff.

> The point is that the messages are intrusive and demand attention in order for me to do my work. I keep having to hit close or some other action. Messages shouldn't demand and prevent work unless you take an action.

That's actually why we use that style of notification for certain things (though I will admit, maybe some stuff which is using it today shouldn't be). We currently have three ways of letting users know about things, and how we use them depends on how critical we deem the message:
- If we think the thing is something the user needs to know about but maybe not handle literally right that second, we'll put it up there. The bar doesn't block you from doing everything, but since it's up at the top, and covers up some of the UI, chances are the user will notice it, read it, and decide what they want to do about it.
- If the thing is something which the user probably doesn't need to take action on immediately or even ever, or if it is purely the result of some user initiated action, then we'll put it in the Activities panel. That let's the user get to it when they're ready, which isn't a big deal given what the thing is.
- If it's critical that the user does something about the thing, we'll put it in a blocking dialog. This forces the user to have to deal with it now.

 For your example of "When the login expires, there is a popup displayed", for most people, that's something they would want to take action on right away. We need to make sure they notice that the credentials have expired. If it they miss that, then they might get confused about why things aren't working. 

For you, if you aren't actively using a login and you don't want to reenter your credentials, then I'd recommend logging out of that account. If it is that the credentials have only expired for one of the account's tenant, a tenant you don't really care about....then I'll admit I don't have a good answer for you right now. 😐 I'll try to think some more about what you've said though.
