### ISSUE TITLE
new version 1.14.0 , foreach error 

### ISSUE THREAD

**Issue by rosponda57** [microsoft/AzureStorageExplorer#3184]
When using search in explorer i gen an error: 

"An unexpected error occurred:
TypeError: Cannot read property "forEach' of undefined
...........
"

![image](https://user-images.githubusercontent.com/41154552/86718353-4b6c5280-c023-11ea-8d2b-14da047472b7.png)

**Comment by RussKie** [comment]
Got the same using the latest version.

**Comment by jinglouMSFT** [comment]
Thanks for reporting the issue. I've tried to reproduce the issue with several scenarios I could think of based on the screenshot from above. I couldn't reproduce the issue however with version 1.15.1.  The screenshot above seemed to search in the Tables, but the error message came from CosmosDB (DocumentDB).  Do you use same file names in DocumentDB as in Tables?  
Could you please help narrow down the scenarios that have caused this error to happen?  That would be very helpful.  Thanks.

**Comment by RussKie** [comment]
All I did was install the app from https://azure.microsoft.com/en-us/features/storage-explorer/, and ran it.
I added my MS account via "Add and Azure Account" (Azure env), and started browsing through what was available to me. At some point I decided to search for a resource using the search box:
![image](https://user-images.githubusercontent.com/4403806/93167661-6f0af200-f764-11ea-83af-fdc5f89d5835.png)

The search resulted in the error.

**Comment by RussKie** [comment]
Like this:
![image](https://user-images.githubusercontent.com/4403806/93167892-f5bfcf00-f764-11ea-8073-d0abe31c3ef6.png)

I could speculate, if a search produces no results (for whatever reason, including time outs) it returns null (or undefined in JS-speak), which causes the error.

**Comment by jinglouMSFT** [comment]
I tried couple of more times last night to repro the issue.  I ran into a different issue however.  While investigating the issue, we decided to patch the ComosDB issue you ran into. Your issue was a regression after we updated Node.js.  
We do have a fix for the issue you ran into.  If you are interested, we can give you a private build to try and help us verify the fix.
At the meantime, to unblock you and if you don't use CosmosDB, you can go to the Settings page to uncheck CosmosDB.  That way, you will not run into the forEach error.  
Let us know if you are interested in the private.

**Comment by RussKie** [comment]
Thank you. I'm good at this point (I have no real use for the tool atm), so I can wait for an official update.

**Comment by jinglouMSFT** [comment]
Sounds good.  Thanks.

**Comment by rosponda57** [comment]
"uncheck CosmosDB" works well - thank's for the help.
