### ISSUE TITLE
SAS "List" permission?

### ISSUE THREAD

**Issue by jzonthemtn** [microsoft/AzureStorageExplorer#3196]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  I don't know what the last version I had was.

## Bug Description ##
What happened to the `List` permissions for SAS URLs? It used to be an option but it is not now. It is still referenced as needed by [Get shared access signature URI for your VM image](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/get-sas-uri). Those instructions are how we used to add/update Partner Central VHDs.

## Steps to Reproduce ##
1. Follow the steps on the [Get shared access signature URI for your VM image](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/get-sas-uri) page to try to generate a SAS URL. Notice there is no `List` permission.

## Expected Experience ##
The documentation and the application are consistent.

## Actual Experience ##
The required `List` permission is either re-added or the documentation is updated.

## Additional Context ##
Trying to manually add the `l` permission to the SAS URL doesn't work in Partner Central as it says it can't access the VHD.

**Comment by JasonYeMSFT** [comment]
You will need to explicitly generate a container level SAS from the container node in the tree view instead of from the explorer.

We found it misleading to expose container level SAS from the explorer because either the list permission doesn't apply if you are generating a blob level SAS or the SAS grants access to items beyond you selection.
