### ISSUE TITLE
June 2020 (Version 1.14.0) Quick Access Loading ... f-o-r-e-v-e-r

### ISSUE THREAD

**Issue by DonFrazier** [microsoft/AzureStorageExplorer#3220]
**Storage Explorer Version**: 1.14.0
**Build Number**: 20200624.3
**Platform/OS**: Windows 10
**Architecture**: x64?
**Regression From**:  previous version

## Bug Description ##
QuickAccess shows the spinning animation and Loading ... instead of the things I used to be able to quickly access.

## Steps to Reproduce ##
Launch Storage Explorer

## Expected Experience ##
The previous version experience where my favorites appeared 

## Actual Experience ##
![image](https://user-images.githubusercontent.com/47017616/87157292-e870fa80-c272-11ea-88fc-94c2c64351f9.png)

## Additional Context ##
I reported this before so it's probably something easy to fix if now making Explorer far less useful.

**Comment by JasonYeMSFT** [comment]
If you wait for a while, does the nodes eventually show up? We show all quick access items together when they all finished/failed loading. If some resource is timing out, it will block showing other nodes. If the nodes eventually show up, those who fail to load will be displayed as "broken nodes". You can remove them from quick access so that they don't block loading next time. It would also be great if you can tell us what type of resources they are so that we can investigate why they are broken after the upgrade.

If the loading technically takes forever, please open the dev tools (Help -> Toggle Developer Tools) to see if there is any error message in the console. Let us know if this is the case and if there is any error so we can investigate our Quick Access loading logic.

**Comment by DonFrazier** [comment]
I'm not sure how long a "while" is but today it is loading.  I have 7 pages of this message: 

DevTools failed to parse SourceMap: file:///C:/Program%20Files%20(x86)/Microsoft%20Azure%20Storage%20Explorer/resources/app/out/app/renderer/E:/A/_work/89/s/src/components/se-string-crypto/dist/StringCrypto.js.map


Several:
C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\index.js:57 Specifying view model modules in dialog configurations is deprecated. See 'HelloWorldView.ts' in the 'se-extension-example' package for an example of how to setup MVVM dialogs.

and a handful of:

14272 (Provider) >>> Loading 'C:\Program Files (x86)\Microsoft Azure Storage Explorer\resources\app\out\app\renderer\providers\StorageProvider'

Since I can't repro today, it's ok to close.  Looks like the previous issue though.  Maybe showing the spinning circle around the 10  things in my quick access list that I care about most would be more helpful for me as the user.  Then it would be clearer which one is taking longer to load.

A way to avoid listing the 30+ azure subscriptions that I never user would also be nice.
