### ISSUE TITLE
I have to login 3 times every time

### ISSUE THREAD

**Issue by LeifAndreasOberg** [microsoft/AzureStorageExplorer#3240]
Everyone in my team have to login 3 times every time we use the software.
It says that our user needs to be verified. We do it 3 times and then we can login as usual. Frustrating!

**Comment by alexpilon666** [comment]
Bumping this up as we have the same issue.
I'm either a member or guest of multiple tenants, and due to the admin rights I have, I'm required to use 2FA.
Every single account requires me to login 2-3 times...No joke, it takes me about 10-15 minutes to authenticate to all my tenants....simply to add or remove a subscription from my list, or because my token expires at some point.
And since we have Okta as our IdP, I have to 2FA twice per request: Okta, and MS authenticator.

Please fix this ASAP, this is unusable.

**Comment by s0ar** [comment]
Same here, a simple private account, only one subscription with a storage account. I need to enter password and verification code 3 times to be able to use the storage explorer.
This is really annoying, are there any work arounds/settings i can change?

**Comment by MRayermannMSFT** [comment]
@s0ar @alexpilon666 @LeifAndreasOberg  I think what we're doing for #460 solves this issue. So I'm going to close this as duplicate. Please read through that thread, try the latest private build, and give us your feedback. If there are still problems related to auth/account mgmt, we can look into making new issues for those things. Thanks!
