### ISSUE TITLE
Unable to retrieve child resources.  Details: ["Error:Unable to retrieve authentication token."]

### ISSUE THREAD

**Issue by saranshgoel** [microsoft/AzureStorageExplorer#3244]
Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

**Comment by jeromewir** [comment]
I'm also having this issue

This message is shown when opening Azure storage explorer.
I already accessed storage explorer with success in the past and I can't use it any more cause the message is shown and no window is opened after that.

Tried to update to latest 1.14.2 and the issue is still there.

Mac OSX Catalina (10.15.5 (19F101))

![image](https://user-images.githubusercontent.com/5878807/88798576-6440d180-d1a5-11ea-94ec-b4940454d11b.png)

**Comment by lucferbux** [comment]
I have the same Issue. 

Version 1.14.2 and macOS Catalina 10.15.6.

Screenshot:

<img width="521" alt="Screenshot 2020-08-11 at 13 48 19" src="https://user-images.githubusercontent.com/16117276/89893854-6c533500-dbd9-11ea-8ad6-c9661c8502ed.png">

**Comment by StfBauer** [comment]
The same issue even in dark mode. Please fix it. Same version as @lucferbux 

<img width="549" alt="image" src="https://user-images.githubusercontent.com/5503835/92621762-88272500-f2c4-11ea-8ecd-e96ebd3f1b6e.png">

**Comment by AartBluestoke** [comment]
same issue:
![image](https://user-images.githubusercontent.com/1892829/93838223-4044cc80-fccc-11ea-86f9-9069f214d9e9.png)

![image](https://user-images.githubusercontent.com/1892829/93838243-4dfa5200-fccc-11ea-80e0-76ddfc49605f.png)

**Comment by MRayermannMSFT** [comment]
For all facing this issue, if you are not using Disks, then you should be able to work around this issue by going to Settings -> Services -> Disks, and un checking the checkbox. If are you trying to use Disks, please try removing and re-adding your Azure account. If that doesn't work then let me know.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of responses. For anyone still having problems, please open a new issue. Thanks.
