### ISSUE TITLE
Wrong files are deleted

### ISSUE THREAD

**Issue by joappleMSFT** [microsoft/AzureStorageExplorer#3250]
**Storage Explorer Version**: 1.14.1
**Build Number**: 20200711.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Yes

## Bug Description ##
I selected 31 files, right-clicked and chose "Delete", and the wrong 31 files were deleted.

## Steps to Reproduce ##
1.) Write to Blob from Spark.
2.) Attempt to delete the zero byte files in a directory.

## Expected Experience ##
Zero byte files should be deleted (ideal), or at least deleting them should be a no op (previous experience).

## Actual Experience ##
When writing to Blob, Spark creates zero byte files with the same name as the "real" folder names. These can be deleted in the Azure Portal, but not in the Storage Explorer desktop app. With a new version of the app installed, I decided to test if it can delete these empty files now. The outcome is worse than before: now it deletes the actual folders!

1.) I have a directory with 31 folders with data:
![image](https://user-images.githubusercontent.com/68284142/87680931-04314080-c74c-11ea-8bda-aac58c87f24d.png)

2.) The directory also has 31 empty files, an annoying Spark+Blob artifact:
![image](https://user-images.githubusercontent.com/68284142/87681014-1ad79780-c74c-11ea-8d40-85aecf68c1b6.png)

3.) I selected the 31 empty files and chose "Delete":
![image](https://user-images.githubusercontent.com/68284142/87681069-33e04880-c74c-11ea-8b3c-65aa614a1365.png)

4.) The actual folders were deleted and the 0 B files remained:
![image](https://user-images.githubusercontent.com/68284142/87681101-465a8200-c74c-11ea-8847-603a7a811c79.png)

## Additional Context ##
None.

**Comment by JasonYeMSFT** [comment]
@joappleMSFT If I guess correctly, those 0 byte blobs are stub blobs to represent the folders, which have the metadata "hdi_isFolder=true". If it is the case, it is by design to delete the actual folder when deleting their stub blobs (the blob with the same name and the "hdi_isFolder=true" metadata). You are supposed to treat these blobs as the folders themselves. Having only the 0 byte stub blob deleted without deleting the folders will create an invalid state with respect to the Spark data structure.

Regarding why those 0 byte stub blobs aren't deleted, there is a known bug about deleting such blobs in batch. The current workaround is to single select and delete them one at a time. We are working with AzCopy to get this bug fixed.

**Comment by joappleMSFT** [comment]
Hmm. If that's true, is it better to not show them at all? It makes it very easy to shoot yourself in your foot.
Note that when you copy a directory with them, the copied folder either doesn't have them or they are hidden.
Just my $0.02!

**Comment by MRayermannMSFT** [comment]
>  Note that when you copy a directory with them, the copied folder either doesn't have them or they are hidden.

@JasonYeMSFT please investigate this. We might need AzCopy to support this.

As for hiding the stub files, this isn't something we'd look to do right now.

**Comment by MRayermannMSFT** [comment]
@joappleMSFT we are not able to repro the stub files not being copied. Can you please connect with @JasonYeMSFT over teams and show him what you're talking about? If you can't find him in teams then I'd suggests looking at my org chart.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. In the future, we'll be hiding these 0 byte blobs by default. See #3314
