### ISSUE TITLE
I am creating directories but they are getting disappeared if I don't save some file in it. Why so?

### ISSUE THREAD

**Issue by bhatt-yash** [microsoft/AzureStorageExplorer#3266]
**Storage Explorer Version**: 
**Build Number**: 
**Platform/OS**: 
**Architecture**: 
**Regression From**:

**Comment by MRayermannMSFT** [comment]
@bhatt-yash I'll assume you're working in a Blob Container. If not, let me know.

The reason it goes away is because for Blobs, folders are virtual. This means that they don't really exist. Storage Explorer treats /'s in Blob names as delimiters which indicate the existence of a folder. So if there are no blobs with the name /a/b/<something else> then Storage Explorer won't show folders "a" and "b". So when you make a new folder you'll need to put something in it to preserve its existence. The new folder dialog talks about this as well.

**Comment by bhatt-yash** [comment]
Yes I am working in a blob container, but I want to create a directory using R commands in databricks, so that I can put my data files in it. How can I do that if I can't make a folder without having a file in it?

**Comment by jinglouMSFT** [comment]
If you are working with Blobs, folders/directories are virtual, meaning they don't exist.  Storage Explorer just uses the '/' to visually display them as folders.  This is why when you try to create a folder, the creation experience is different from the normal folder creation experience. As a workaround in your case, you can try to first upload an arbitrary file/blob with the folder structure you want from within Storage Explorer to force the folder to be created, then using R commands in databricks.  Or, as an alternative, consider enabling the HNS feature in your storage account to benefit from the real folder structure. This is the Azure Data Lake Services (ADLS gen2) referred in the Storage Explorer.  It's basically the same as the regular Blobs but with real folder structures. Cost is different so do your research if costing is a concern before using ADLS Gen2. Also, File Shares also supports folder structures, which is also an alternative.  If you are using R, it sounds like ADLS Gen2 is a more appropriate approach IMO.  If you have to stick with the regular Blobs, then you will have to work around the virtual folder fact.  This is the service limit, not a Storage Explorer limit.  Hope this is informative.

**Comment by bhatt-yash** [comment]
Yes, it was really helpful. Thanks a lot.
