### ISSUE TITLE
Storage Explorer issue in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by JaviBonilla** [microsoft/AzureStorageExplorer#3294]
**Storage Explorer Version**: 1.14.2
**Build Number**: I have no access to the UI
**Platform/OS**: openSUSE Tumbleweed
**Architecture**: x64
**Regression From**:  -

## Bug Description ##
The program automatically closes when executed in the terminal or keeps executing but no UI is shown.

## Steps to Reproduce ##
1. I installed it using Snap and the following instructions.
https://snapcraft.io/install/storage-explorer/opensuse

2. Execute the following command in the terminal: `storage-explorer`
This message appears: `No protocol specified`

It closes or keeps executing but no UI is shown.

**Comment by MRayermannMSFT** [comment]
@JaviBonilla are there any other messages? Or literally just only "No protocol specified"?

**Comment by JaviBonilla** [comment]
@MRayermannMSFT Literally just only "No protocol specified", can I provide any other information to track this issue?

**Comment by MRayermannMSFT** [comment]
Are you connecting over SSH/X11? Or is this your local running OS?

**Comment by JaviBonilla** [comment]
It is my local running OS

**Comment by JaviBonilla** [comment]
@MRayermannMSFT Now, it is working. I deleted the default password keyring in Seahorse, so it was created again when executing the storage explorer for the first time.

**Comment by dirkackerman** [comment]
I had the same issue only with OpenSUSE Tumbleweed running KDE instead of GNOME. I've tried:

- Running Storage Explorer from snap packages and get the same error as reported by @JaviBonilla above
- Downloading the tar.gz and executing Storage Explorer locally for both 1.13.1 and 1.14.2. They both bring a modal over the splash screen stating "Microsoft Azure Storage Explorer requires a password manager service to keep your data safe, but your system does not appear to have one installed. Please make sure you have the right packages installed before launching the application again."
- I've tried to clear the wallet in KWallet
- I've installed (and again removed) gnome-keyring

Following the fix above it is only when installing with gnome-keyring and seahorse that Storage Explorer will launch (I am now going to retry it via snap). Yet this does not seem to be listed as dependencies? I've also come across #2635 (which was what led me to this thread).

Should gnome-keyring and seahorse be dependencies and would it not be possible to make this optional or to swap it out for kwallet?
