### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by ariefalibwl** [microsoft/AzureStorageExplorer#3308]
**Storage Explorer Version**: 
1.4.2
**Build Number**: 
**Platform/OS**: 
Windows 10
**Architecture**: 
x64
**Regression From**:  

## Bug Description ##

Unable to retrieve child resources.

Details:
["Error:Cannot find module '@azure/storage-queue'\nRequire stack:\n- C:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\node_modules\\se-queue-extension\\dist\\Clients\\QueueClient.js\n- C:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\node_modules\\se-queue-extension\\dist\\index.js\n- c:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\out\\app\\providers\\Provider.js\n- c:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js","Error:Cannot find module '@azure/storage-blob'\nRequire stack:\n- C:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\Clients\\BlobContainerClient.js\n- C:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js\n- c:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\out\\app\\providers\\Provider.js\n- c:\\users\\arisyed\\appdata\\local\\programs\\microsoft azure storage explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js"]

**Comment by JasonYeMSFT** [comment]
@ariefalibwl Could you help us check the following things?

- In directory "C:\Users\arisyed\appdata\local\programs\Microsoft Azure Storage Explorer\resources\app\node-Modules\", could you find a directorie named "@azure"? If so, open it and could you see two directories named "storage-queue" and "storage-blob" in them?
- Do you select the "install for all user" or "install for yourself" when installing?

**Comment by JasonYeMSFT** [comment]
@ariefalibwl Could you please try installing 1.14.0 to see if the issue still reproduces? I made some code change in 1.14.1 to the module loading logic. It would be good to know if it is relevant. Thanks.

**Comment by MRayermannMSFT** [comment]
I have additional troubleshooting steps to help out. These are intended to be used with Storage Explorer 1.14.2.

## Try patching Storage Explorer to fix what we think is the problem
First, we have a theory to what the issue is. I have a patch for you to try applying to the product:

0. Close Storage Explorer
1. Download this file: [NodeProcessHostProxy.txt](https://github.com/microsoft/AzureStorageExplorer/files/5087442/NodeProcessHostProxy.txt)
2. After downloading, change the extension to `.js`.
3. Move the file to `<Storage Explorer install location>\resources\app\out\app\node`. You should be prompted to overwrite an existing file. Say yes.
4. Try using Storage Explorer

## Get us values from process explorer
If the above doesn't work, then please:
1. Install Process Explorer: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
2. Open Process Explorer
3. Open Storage Explorer
4. Open notepad
4. Get to the point of the error message
5. Switch over to Process Explorer
6. Sort by names and look for all of the Storage Explorer processes

For each process:
1. Right click -> properties
2. Look under image for the "Command line" field (see below picture)
3. If in the command line field there is "nodeModuleRoots=", then copy and paste the value of command line field into a new line in notepad (feel free to redact any personal info in the file paths)
4. Attach that file to a reply here
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/21112697/90457452-6a451680-e0b0-11ea-9b17-1383d8369964.png">

**Comment by MRayermannMSFT** [comment]
Merging this with #3326
