### ISSUE TITLE
Unable to expand a subscription (module not found)

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/AzureStorageExplorer#3326]
**Storage Explorer Version**:1.14.2
**Platform/OS**: Windows 10 x64
**Regression From**:  
I don't know, this is the first time I've used the app

## Bug Description ##
Unable to view containers in a subscription

## Steps to Reproduce ##
Open storage explorer
Pick a subscription
expand it

Unable to retrieve child resources.

Details:
["Error:Cannot find module 'tslib'\nRequire stack:\n- I:\\apps\\storageexplorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\index.js\n- i:\\apps\\storageexplorer\\resources\\app\\out\\app\\providers\\Provider.js\n- i:\\apps\\storageexplorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js"]

**Comment by shueybubbles** [comment]
I tried using both "just for me" and machine-wide install options. Same result for both.

**Comment by JasonYeMSFT** [comment]
This means a library named "tslib" is not found. Could you go to directory "I:\apps\storageexplorer\resources\app\node_modules" to see if there is a folder named "tslib" in it? If it is there, there might be some corner case bugs in our path resolution logic. By the way, the location you are installing Storage Explorer is not the default location (e.g. machine wide C:\Program Files (x86)\Microsoft Azure Storage Explorer). Could you please try installing it at the default location and see if the issue still reproduces?

**Comment by shueybubbles** [comment]
```
I:\apps\storageexplorer\resources\app\node_modules>dir tslib
 Volume in drive I is NewBins
 Volume Serial Number is 7EDE-F233

 Directory of I:\apps\storageexplorer\resources\app\node_modules\tslib

07/30/2020  01:49 PM    <DIR>          .
07/30/2020  01:49 PM    <DIR>          ..
07/15/2020  09:17 PM               824 CopyrightNotice.txt
07/15/2020  09:17 PM               655 LICENSE.txt
07/15/2020  09:17 PM             2,242 package.json
07/15/2020  09:17 PM             3,454 README.md
07/15/2020  09:17 PM             2,714 tslib.d.ts
07/15/2020  09:17 PM                36 tslib.es6.html
07/15/2020  09:17 PM            10,274 tslib.es6.js
07/15/2020  09:17 PM                32 tslib.html
07/15/2020  09:17 PM            13,204 tslib.js
               9 File(s)         33,435 bytes
               2 Dir(s)  392,727,842,816 bytes free
```
I can try the default location. I usually avoid using the default because my C drive is a smallish SSD and it's nearly full.

**Comment by shueybubbles** [comment]
Works fine with the default location

**Comment by MRayermannMSFT** [comment]
@shueybubbles are you ok with having Storage Explorer installed on your C: drive or do you want us to keep investigating this?

If you'd like us to figure out what's going wrong, then I'd ask you to reinstall on your I: drive by uninstalling, re-downloading the installer, and then rerunning the installer.

Couple of extra questions as well:

- When you install on your I drive, are you doing that by changing the install path in the installer or by copy and pasting from C: -> I:?
- Is I: a local drive or a network drive?

**Comment by shueybubbles** [comment]
I: is a local drive. I try to install apps on it because my C drive is small. 
I just type the path into the edit control and click Next. 
![image](https://user-images.githubusercontent.com/2224906/89297408-c7ad8200-d631-11ea-9ef2-fa459199d3ce.png)

uninstall/download/reinstall led to the same error.
For now I can live with the default location but I imagine I'm not the only person who installs to other folders.

**Comment by krishjag** [comment]
I have been long time user of the storage explorer and started getting this error after updating to 1.14.2.

Storage Explorer Version:1.14.2
Platform/OS: Windows 10 x64
Regression From: After I updated the storage explorer to the above version.

Install location: Default (C:\Program Files (x86)\Microsoft Azure Storage Explorer)

![image](https://user-images.githubusercontent.com/24848674/89606048-111ded00-d83d-11ea-9f2e-def7fc904d1f.png)

I have been working around this by uninstalling and re-installing the storage explorer every time I get this error.

**Comment by MRayermannMSFT** [comment]
@krishjag when you say:
> I have been working around this by uninstalling and re-installing the storage explorer every time I get this error.
Are you implying that after some period of time an install of 1.14.2 that was working, stops working?

**Comment by MRayermannMSFT** [comment]
I have additional troubleshooting steps to help out.

## Try patching Storage Explorer to fix what we think is the problem
First, we have a theory to what the issue is. I have a patch for you to try applying to the product:

0. Close Storage Explorer
1. Download this file: [NodeProcessHostProxy.txt](https://github.com/microsoft/AzureStorageExplorer/files/5087442/NodeProcessHostProxy.txt)
2. After downloading, change the extension to `.js`.
3. Move the file to `<Storage Explorer install location>\resources\app\out\app\node`. You should be prompted to overwrite an existing file. Say yes.
4. Try using Storage Explorer

## Get us values from process explorer
If the above doesn't work, then please:
1. Install Process Explorer: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
2. Open Process Explorer
3. Open Storage Explorer
4. Open notepad
4. Get to the point of the error message
5. Switch over to Process Explorer
6. Sort by names and look for all of the Storage Explorer processes

For each process:
1. Right click -> properties
2. Look under image for the "Command line" field (see below picture)
3. If in the command line field there is "nodeModuleRoots=", then copy and paste the value of command line field into a new line in notepad (feel free to redact any personal info in the file paths)
4. Attach that file to a reply here
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/21112697/90457452-6a451680-e0b0-11ea-9b17-1383d8369964.png">

**Comment by anmmok** [comment]
> 1. Close Storage Explorer
> 2. Download this file: [NodeProcessHostProxy.txt](https://github.com/microsoft/AzureStorageExplorer/files/5087442/NodeProcessHostProxy.txt)
> 3. After downloading, change the extension to `.js`.
> 4. Move the file to `<Storage Explorer install location>\resources\app\out\app\node`. You should be prompted to overwrite an existing file. Say yes.
> 5. Try using Storage Explorer

I had exactly the same issue after installing storage explorer into the custom path. 
The solution above has worked fine for me.

**Comment by krishjag** [comment]
> @krishjag when you say:
> 
> > I have been working around this by uninstalling and re-installing the storage explorer every time I get this error.
> 
> Are you implying that after some period of time an install of 1.14.2 that was working, stops working?

Yes, that's correct.

**Comment by krishjag** [comment]
@MRayermannMSFT 
I applied the suggested patch and the storage explorer is working now. Thanks!

**Comment by MRayermannMSFT** [comment]
Closed several issues as duplicates and linked them to this one. If you're coming from those and have tried the patch or any of the other steps we've recommended, let us know how it went! Right now we plan on shipping that patch in 1.15.
