### ISSUE TITLE
Another Unable To Retrieve Child Resources Error when Expanding

### ISSUE THREAD

**Issue by nedwardsesha** [microsoft/AzureStorageExplorer#3345]
**Storage Explorer Version**: 1.14.2
**Build Number**: 20200715.2
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Was working in all previous versions

## Bug Description ##
Like others on here I get met with an Unable to Retrieve Child Resources Error in the new version I have checked for Environment variable and there are no proxy variables. Also Edit -> Configure Proxy is set to "Do not use proxy" Also verified thru Azure Portal that I am Contributor on storage account. 

Error Message:

Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationFailure</Code><Message>This request is not authorized to perform this operation.\nRequestId:75ded136-d01e-0060-3b8a-6a3a39000000\nTime:2020-08-04T18:10:37.5704788Z</Message></Error>"]

## Steps to Reproduce ##
Open up storage account
Expand Blob Containers

## Expected Experience ##
Blob(s) shown in Azure Data Explorer and allow for normal browsing of Blobs

## Actual Experience ##
The error message above.

## Additional Context ##
Recently updated to 1.14.2

**Comment by JasonYeMSFT** [comment]
@nedwardsesha The error says you don't have sufficient permission to list the resources. How are you connecting to your resources (e.g. signed-in, attached storage account via key or SAS)? What RBAC role or permission you have that you are aware of?

**Comment by nedwardsesha** [comment]
Connecting to resource via signed in account, it can browse to other storage accounts just not this particular one which is the main one used. 

I have Contributor/Storage Account Contributor Permissions on the resource and Owner on the Subscription

I have an older version of Azure Storage Explorer (1.12.0) on another machine with the same credentials I can browse.

**Comment by JasonYeMSFT** [comment]
@nedwardsesha I don't recall us making changes that would affect the authentication. Could you check if you are losing the ability to list storage account keys in Storage Explorer across the upgrade? To check that, you can select the problematic storage account node and look at the properties panel (bottom left corner), looking for the "Primary Key" field. You can also check the Storage Explorer settings, see if you checked the Services -> Storage Accounts -> Disable Usage of Keys. We added that setting in 1.13.0 so that might explain why it used to work in 1.12.0 but not after that.

**Comment by JasonYeMSFT** [comment]
I have forwarded your request id to look for the service log. It turns out that for that problematic storage account, your administrator have set some security policy that only grant access from a certain group IP addresses, which your machine doesn't belong to [storage network security doc](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security). The cause of the error has nothing to do with Storage Explorer version. That explains why on another machine you can access the resource.

**Comment by stephenplant** [comment]
Also just got this issue using my Visual Studio Enterprise subscription:

Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

Other accounts seem to be working OK.

**Comment by nedwardsesha** [comment]
Adding my ip to the firewall seemed to take care of it. Thanks!
