### ISSUE TITLE
File Shares dont allow to load

### ISSUE THREAD

**Issue by SoftwareRat** [microsoft/AzureStorageExplorer#3373]
**Storage Explorer Version**: 1.14.2 
**Build Number**: 20200715.2
**Platform/OS**:  Windows 10
**Architecture**: x64
**Regression From**:  It worked before reinstallation of Windows 10

## Bug Description ##
If i want to get access to my file shares i get this:
Unable to list resources in account due to inadequate permissions. Permission to list containers or to list account keys is required.

Contact your subscription administrator to resolve this issue.

## Steps to Reproduce ##
1. Go to File Shares
2. Done.

## Expected Experience ##
My files should show.

## Actual Experience ##
It dont load.

## Additional Context ##
Nope, please fix it.

**Comment by MRayermannMSFT** [comment]
@SoftwareRat because file shares do not support data plane RBAC access you have the following options for accessing them:
- Obtain an RBAC role which allows you to list account keys. If you do this and wish to keep using blob/queues via RBAC, you can disable key usage for those under Settings -> Services -> Storage Accounts -> Disable Usage of Keys
- Attach your storage account or file share with a SAS.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having issues please open a new issue.
