### ISSUE TITLE
Cannot explore container

### ISSUE THREAD

**Issue by xiaowuhu** [microsoft/AzureStorageExplorer#3378]
**Storage Explorer Version**: 1.14.2
**Build Number**: 
**Platform/OS**: Windows 10
**Architecture**:  x64

## Steps to Reproduce ##
1. install and open for the first time
2. connect to a container with valid connection string
3. explore the container

Unable to retrieve child resources.

Details:
["Error:Cannot find module '@azure/storage-queue'\nRequire stack:\n- D:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-queue-extension\\dist\\Clients\\QueueClient.js\n- D:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-queue-extension\\dist\\index.js\n- d:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js\n- d:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js","Error:Cannot find module '@azure/storage-blob'\nRequire stack:\n- D:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\Clients\\BlobContainerClient.js\n- D:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-blob-extension\\dist\\src\\index.js\n- d:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js\n- d:\\Program Files (x86)\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js"]

**Comment by gantta** [comment]
Same issue for me. First time install and connected to my storage account with access key.

Unable to retrieve child resources.

Details:
["RestError:request to https://<accountName>.core.windows.net/?include=metadata&comp=list failed, reason: getaddrinfo ENOTFOUND <accountName>.blob.core.windows.net"]

**Comment by JasonYeMSFT** [comment]
@gantta Since the error you are seeing is different from the original one, please open another issue so we can investigate and track it there. The discussion here will be focusing on the original issue.

@xiaowuhu Could you please try installing 1.14.0 to see if the issue reproduces? I have made some changes to the node module loading logic. It would be good to know if that might be relevant. Thanks.

**Comment by xiaowuhu** [comment]
I have another computer installed 1.14.0 and it works well.

**Comment by JasonYeMSFT** [comment]
Could you please try the same computer? That would be more convincing since at this point not everyone is seeing this issue. If it involves different machines, the cause might be some machine specific configuration instead of the change.

**Comment by xiaowuhu** [comment]
now on the original machine, the storage explorer is 1.14.0, it can works well.
![image](https://user-images.githubusercontent.com/19218188/90452734-72896a00-e121-11ea-842c-e1379eeda06a.png)

**Comment by MRayermannMSFT** [comment]
I have additional troubleshooting steps to help out.

## Try patching Storage Explorer to fix what we think is the problem
First, we have a theory to what the issue is. I have a patch for you to try applying to the product:

0. Close Storage Explorer
1. Download this file: [NodeProcessHostProxy.txt](https://github.com/microsoft/AzureStorageExplorer/files/5087442/NodeProcessHostProxy.txt)
2. After downloading, change the extension to `.js`.
3. Move the file to `<Storage Explorer install location>\resources\app\out\app\node`. You should be prompted to overwrite an existing file. Say yes.
4. Try using Storage Explorer

## Get us values from process explorer
If the above doesn't work, then please:
1. Install Process Explorer: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
2. Open Process Explorer
3. Open Storage Explorer
4. Open notepad
4. Get to the point of the error message
5. Switch over to Process Explorer
6. Sort by names and look for all of the Storage Explorer processes

For each process:
1. Right click -> properties
2. Look under image for the "Command line" field (see below picture)
3. If in the command line field there is "nodeModuleRoots=", then copy and paste the value of command line field into a new line in notepad (feel free to redact any personal info in the file paths)
4. Attach that file to a reply here
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/21112697/90457452-6a451680-e0b0-11ea-9b17-1383d8369964.png">

**Comment by MRayermannMSFT** [comment]
Merging this with #3326
