### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by rawatsudhir1** [microsoft/AzureStorageExplorer#3386]
**Storage Explorer Version**: 1.14.2
**Build Number**: 
**Platform/OS**: windows 10
**Architecture**: x64
**Regression From**:  No

![image](https://user-images.githubusercontent.com/32550309/90078408-e958e880-dd58-11ea-9e24-af94e84800a5.png)

## Bug Description ##
Unable to retrieve child resources.

Details:
["Error:Cannot find module 'tslib'\nRequire stack:\n- D:\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\se-managed-disks-extension\\dist\\src\\index.js\n- d:\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\providers\\Provider.js\n- d:\\Microsoft Azure Storage Explorer\\resources\\app\\out\\app\\node\\NodeProcessHostProxy.js"]

**Comment by JasonYeMSFT** [comment]
Similar to #3326. Unfortunately we haven't figured out what is causing this. Could you please help us by doing the following things?
1. Check if a "tslib" directory does exist at `D:\Microsoft Azure Storage Explorer\resources\app\node_modules\`. If it doesn't, it clearly explains the error.
2. Try uninstall and re-install Storage Explorer at the default location (e.g. `C:\Program Files (x86)\Microsoft Azure Storage Explorer`. One user from #3326 said that Storage Explorer works for him from the default location. However, I have tried installing Storage Explorer at my D drive and didn't see this issue.
3. If none of the above gets any finding, could you please try installing an older version like 1.14.0 or older. There was some code change to the module loading. It would be good to know if it is relevant.

We are seeing multiple people running into this issue recently, it would be very appreciated if you can help us figure out the cause so we can fix the bug. Thanks.

**Comment by MRayermannMSFT** [comment]
I have additional troubleshooting steps to help out.

## Try patching Storage Explorer to fix what we think is the problem
First, we have a theory to what the issue is. I have a patch for you to try applying to the product:

0. Close Storage Explorer
1. Download this file: [NodeProcessHostProxy.txt](https://github.com/microsoft/AzureStorageExplorer/files/5087442/NodeProcessHostProxy.txt)
2. After downloading, change the extension to `.js`.
3. Move the file to `<Storage Explorer install location>\resources\app\out\app\node`. You should be prompted to overwrite an existing file. Say yes.
4. Try using Storage Explorer

## Get us values from process explorer
If the above doesn't work, then please:
1. Install Process Explorer: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
2. Open Process Explorer
3. Open Storage Explorer
4. Open notepad
4. Get to the point of the error message
5. Switch over to Process Explorer
6. Sort by names and look for all of the Storage Explorer processes

For each process:
1. Right click -> properties
2. Look under image for the "Command line" field (see below picture)
3. If in the command line field there is "nodeModuleRoots=", then copy and paste the value of command line field into a new line in notepad (feel free to redact any personal info in the file paths)
4. Attach that file to a reply here
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/21112697/90457452-6a451680-e0b0-11ea-9b17-1383d8369964.png">

**Comment by MRayermannMSFT** [comment]
Merging this with #3326
