### ISSUE TITLE
'Retention Days' are inconsistent between the editor and Properties window

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#341]
**Storage Explorer Version**: 1.2.0
**Platform/OS Version**: Windows10/ MacOS High Sierra /Linux Ubuntu 16.04
**Architecture**: x64
**Build Number**: 20180622.1
**Commit**: d667aec0
**Regression From**: Not a Regression

#### Steps to Reproduce: ####
1. Right click 'Blob Containers' node and select 'Configure Soft Delete Policy' to enable soft delete.
2. Refresh to make sure the configuration is updated, delete one blob, then check 'Retention Days' under 'Deleted blobs'.

#### Expected Experience: ####
'Retention Days' are consistent between the editor and Properties window.

#### Actual Experience: ####
'Retention Days' are inconsistent between the editor and Properties window.
![number](https://user-images.githubusercontent.com/34729092/41843099-28e3b534-785c-11e8-8ea6-df4cfd9d242a.png)

**Comment by JasonYeMSFT** [comment]
The "Retention Days" field in the properties panel indicates how many days will a blob be preserved after it gets deleted. The "Rentention Days" field in the editor indicates how many days will the blob be preserved after today (e.g. 0 on the last day of the retention period). It is by design to be 1 day less than the configured "Retention Days" when it gets deleted.

**Comment by v-dantch** [comment]
Got it. Thanks for your share.
