### ISSUE TITLE
Pre-filter Orgs to support in Storage Explorer to avoid multiple reauthentications

### ISSUE THREAD

**Issue by softcraftsman** [microsoft/AzureStorageExplorer#3411]
**Is your feature request related to a problem? Please describe.**
As a CSA, I belong to many orgs. When one of those orgs require a reauthentication. SE cycles over ALL orgs and demans that I put in credentials. With MFA that can be a VERY long time.

**Describe the solution you'd like**
Provide an optional selection of orgs to choose.

**Describe alternatives you've considered**
Pin a default org.  Let me select orgs by tabs ???

**Additional context**

**Comment by MRayermannMSFT** [comment]
@softcraftsman thanks for opening an filling out the issue template! 😃

We are very aware of this issue, and we've been working with the owners of our auth library to get this capability prioritized. Our current vision is to have sign in only sign you into your home tenant. Signing in to any other tenants will be an explicit choice, and when you make that choice is when you'll be prompted for MFA (or any other conditional access policies).

Right now we're tracking this work with: https://github.com/microsoft/AzureStorageExplorer/issues/2742

I know that issue is currently in our "future" milestone, but it is definitely a priority to get this point of dissatisfaction figured out. Please watch that issue for updates. I'm going to go ahead and close your issue as a duplicate.
