### ISSUE TITLE
An error pops up when uploading blobs to the original blob container with the 'Public Read Access' is off which has been connected to public blob container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3417]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200818.4
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**
1. Expand one storage account -> Blob Containers.
2. Select one blob container -> Set its property 'Public Read Access' to **'container'.**
3. Attach it via 'Connect to public blob container'.
4. Change the property 'Public Read Access' to **'off'**  for the original blob container.
5. Open the original blob container -> Upload blobs to it -> Check the result.

**Expect Experience:**
No error pops up.

**Actual Experience:**
1. The blob is uploaded successfully.
2. An error pops up.
![image](https://user-images.githubusercontent.com/54055206/90500717-d80b4400-e17d-11ea-8b3b-7a4b3c88b8f5.png)

**More Info:**
1. This issue also reproduces for the actions 'Clone' / 'Change Access Tier' / 'Delete' / 'Acquire Lease'.
2. This issue still reproduces after manually refreshing.
3. This issue doesn't reproduce after restarting Storage Explorer.

**Comment by MRayermannMSFT** [comment]
Ok so here's the reason for this:
- You have a tab open from the attached container node. This tab does not have access to any credentials. We'll call this tab **A**.
- You have a tab open from the normal container node. This tab does have access to credentials. We'll call this tab **B**.

When you do an upload to a container, we'll refresh any tabs that are open for that container. So both tabs **A** and **B**. Since the container had public access turned off though, tab **A** is going to fail to refresh. That's why you see the infobar error.

We could probably try to work on this a bit, but for now, I'd consider this scenario and edge case, so I'm going to won't fix this specific bug.
