### ISSUE TITLE
No file shows in the destination directory after downloading one non-current version 

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3431]
**Storage Explorer Version:** 1.15.0-dev
**Build**: 20200820.5
**Branch**: master
**Platform/OS:** Windows 10/ CentOS 7.6.1810 (Core) / MacOS Catalina
**Architecture**: ia32/x64
**Regression From:** Not a regression

**Steps to reproduce:**

1. Expand one Non-ADLS Gen2 storage account (make sure the blob versioning and soft delete are enabled) -> Blob Containers.
2. Create a new blob container -> Upload one blob to it -> Delete the blob.
3. Switch to 'Active blobs and blobs without current' view.
4. Download the non-current version to the specified destination directory.
5. Check whether the non-current version shows in the destination directory.

**Expect Experience:**
The non-current version shows in the destination directory.

**Actual Experience:**

1. Show a successful activity log.
![image](https://user-images.githubusercontent.com/54055206/90747457-842a6780-e303-11ea-83a1-f747556eca2b.png)

2. No non-current version shows in the destination directory.

**More Info:**
This issue doesn't reproduce for the multiple non-current versions.

**Comment by JasonYeMSFT** [comment]
The bug is that we were incorrectly trying to download the non-existent current version. For you information, when downloading a  single previous version, in the activity log, the source file name will have its versionId included. e.g.
`Transfer of 'version/Leasd.txt (2020-08-19T18:09:44.1472053Z)' to 'C:\Users\vlimu\Documents\version\New folder' complete (used SAS)`

If the versionId is not there in the activity when downloading a single previous version, it is already a bug.

**Comment by v-limu** [comment]
Verified on build 20200821.5. The version id shows in the activity log when downloading a single version and the file shows in the destination directory. So close it.
![image](https://user-images.githubusercontent.com/54055206/90846642-26e1f500-e39b-11ea-97dc-798b70fb1760.png)
