### ISSUE TITLE
All my blob containers are appearing empty with the latest update

### ISSUE THREAD

**Issue by micbil** [microsoft/AzureStorageExplorer#3512]
I had installed the latest update today and attempted to connect to my  Blob Container. However upon connecting all the files and subfolders are not appearing. This is occurring across all my Blob Containers:

![image](https://user-images.githubusercontent.com/15811422/91749040-c52d4200-eb75-11ea-981f-26bf050f5818.png)

I need to be able to access them to pull down files/builds from our development teams. Can you please assist?

Michael

![image](https://user-images.githubusercontent.com/15811422/91749150-e8f08800-eb75-11ea-9aff-a5c0cfc614fc.png)

**Comment by micbil** [comment]
Other staff are able to access this location and see the files on the Blob Containers. So something with this update has broken my ability to access files/folders on storage.

**Comment by MRayermannMSFT** [comment]
@micbil I think we see what the problem is.

We recently updated how we handle folders with no names. These folders can be identified in a url by looking for consecutive /'s, like `myaccount.blob.core.windows.net/container/a/b//d/file.txt`.

In your screenshot, it looks like there's a double slash in the url you used to attach the containers:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/21112697/91750102-610b7d80-eb77-11ea-868a-042a259ca768.png">
Can you try:
1. copy that url into notepad
2. detach the container
3. remove the double slashes from the url
4. reattach using that url

**Comment by micbil** [comment]
Hey Matthew,


I think I figured it out, I was adding connections for each sub location instead of from the root https://dtsmcg.dfs.core.windows.net/teams/<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdtsmcg.dfs.core.windows.net%2Fteams%2FBehaviour&data=02%7C01%7Cmicbil%40microsoft.com%7C26e5af3e429947ea64dd08d849ed33db%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637340630417178034&sdata=I8LNDhtd%2F4mo1OQn23iKl4%2B5nQcpMdukyDD7fnD1gec%3D&reserved=0>

Once I connected to the root it solved the issue.

Thanks for the help!

Michael
