### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by royrojas** [microsoft/AzureStorageExplorer#3576]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: windows
**Architecture**: x64 ia32
**Regression From**:  

## Bug Description ##
Error showing CosmosDB data

## Steps to Reproduce ##
Add cosmo db with string to Azure Storage Explorer

**Comment by insomniacc** [comment]
I dont know if what I have is the same issue described here since there's not much detail other than the error.
However. I was attempting to add a new table to an Azure CosmosDB (TableAPI), during which something happened and focus was taken away from my window, I lost the opportunity to name the DB and now, whenever I attempt to list/view my tables in the explorer, it throws the following error:

![image](https://user-images.githubusercontent.com/10046621/126462943-7c3fd706-7351-4805-8707-79ace46ace8b.png)

The main issue here is that 1. the same error is being thrown for everyone that uses azure storage explorer, and 2. I cannot see the presumably bad/half created table entry in the web ui / portal. - which means i cannot resolve or fix this.

**Comment by aliuy** [comment]
Azure Storage Explorer support for Azure Cosmos DB has been discontinued as of v1.24.0. We recommend users to use Azure Cosmos DB’s Data Explorer, which can be found in [Azure Portal](https://portal.azure.com/) or as a stand-alone version in http://cosmos.azure.com/ for the best Azure Cosmos DB experience. You can also find additional Azure Cosmos DB tooling here: [Azure Cosmos DB Tools](https://developer.azurecosmosdb.com/tools)
