### ISSUE TITLE
Can never complete re-authentication

### ISSUE THREAD

**Issue by richardhauer** [microsoft/AzureStorageExplorer#3608]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Win 10
**Architecture**: x64
**Regression From**: no

## Bug Description ##
I *always* have to re-authenticate accounts.  I have access to a lot of tenants - maybe 20.  Some of them are related to my kids school who use federated auth for the parent portal.  When I attempt to "re-authenticate" I have to enter my password 11 times, approve 9 popups on my phone and respond to 2 SMS challenges. This process can take about 5 minutes.

Even still, presumably because I have limited access to some of those tenants, and some are AD B2C and have no subscriptions or resources, the message that "one or more accounts requires authentication" never goes away.

I appreciate that, technically, the software is trying to log me into all the tenants, and so I have to get new tokens for all the tenants. But perhaps, if it had asked me which tenants I was interested in, I would have picked just the one. Or perhaps the tool could just collect my username/password and ROPC me into the all my tenants.

## Steps to Reproduce ##
1. Have access to lots of tenants, some just AD, some B2C, some with lots of subscriptions and some with none.
2. Try to log in - get frustrated

## Expected Experience ##
Not get prompted for the same information 42 times

## Actual Experience ##
Get prompted for the same information 42 times

**Comment by MikeYeager** [comment]
I have the same issue, although I sometimes do eventually get it to show everything logged in. It would be great if I could choose which tenant(s) I want to log into. I rarely need to log into more than two at a time. I don't really care about the rest. In addition to Richard's issue, I have 2 emails and each of them has multiple tenants. One tenant requires I enter a code and that one pops up every other time I try to log in. So for that particular account I have to enter the code over a dozen times. Also, it doesn't say which tenant I'm logging into in the login dialogue, so I often can't tell which tenants I'm successfully logged into and which I'm not. Otherwise, this is a GREAT tool! Thank you.

**Comment by timoklimmer** [comment]
+1 - I have the same issue. There is too many irrelevant tenants I have to login before I can login into the tenant I need to use.

**Comment by MikeYeager** [comment]
I have found that switching to Microsoft Authentication Library (under Settings --> Application --> Sign-in has made the experience better, but still not optimal. After switching, you have to sign into all of your accounts one, but the sign-ins required after that are reduced quite a bit, at least for me.

**Comment by MRayermannMSFT** [comment]
@MikeYeager  @timoklimmer @richardhauer I think what we're doing for #460 solves this issue. So I'm going to close this as duplicate. Please read through that thread, try the latest private build, and give us your feedback. If there are still problems related to auth/account mgmt, we can look into making new issues for those things. Thanks!
