### ISSUE TITLE
Unable to retrieve child resources.

### ISSUE THREAD

**Issue by payalpatel-source** [microsoft/AzureStorageExplorer#3644]
Unable to retrieve child resources.

Details:
["Error:Unable to retrieve authentication token."]

**Comment by SaberDynCD** [comment]
Unable to retrieve child resources.

Details:
This request is not authorized to perform this operation.
RequestId:XXXXXXXX-XXXX-XXXX-XXXX-XXXXXX000000
Time:2020-10-08T03:31:45.3481966Z

**Comment by MRayermannMSFT** [comment]
@payalpatel-source can you please try:

1. Make sure all of your accounts are in a good state/don't need to be reauthenticated. To check, go to the account panel -> look at your accounts, if any say to reenter credentials, then do so
2. If you continue having issues despite doing that, then go to Settings -> Services -> Disks and uncheck the checkbox, then restart storage explorer

@SaberDynCD please open a separate issue since your error message is different. Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response by original issue opener. For anyone still having this problem, please try the advised steps, and then if you are still blocked, please open a new issue. Thanks.
