### ISSUE TITLE
Cannot access blob

### ISSUE THREAD

**Issue by fishtoo** [microsoft/AzureStorageExplorer#3693]
Unable to retrieve child resources.

Details:
["FetchError:request to https://outputstorage.blob.core.windows.net/?include=metadata&comp=list failed, reason: connect ETIMEDOUT 52.239.236.228:443"]

**Comment by MRayermannMSFT** [comment]
@fishtoo this looks like Storage Explorer is trying to connect to a proxy and failing. Do you have proxy settings set:

- At the app level? You can verify by checking Settings (gear icon on the left hand side) -> Application - > Proxy.
- At an OS level via environment variables? To verify this, look for environment variables HTTPS_PROXY or HTTP_PROXY.

**Comment by michelvankessel** [comment]
funny enough it is not trying to connect to a proxy in my case, but is should. I had to add the proxy to the system:

netsh winhttp set proxy proxy:port

But I also have the same proxy defined in the settings. Why does Blob storage access not follow the application proxy settings?

**Comment by MRayermannMSFT** [comment]
@michelvankessel what version of storage explorer are you using?

Do you know what all that command does? Is it possible that for the machine you are on, without running that command, the proxy address was blocked? As far as our testing can show, setting the app proxy settings will result in storage explorer using that proxy address.

**Comment by MRayermannMSFT** [comment]
@michelvankessel we just read your comment on another issue. Can you try accessing queues without having run the netsh command?

**Comment by michelvankessel** [comment]
For some reason it didn't work immediately. the steps I took
- open storage explorer (first time)
- add Azure AD account from dialog, account is added but cannot list subscriptions, 
message": "connect ETIMEDOUT 13.69.114.0:443", which makes sense, because I don't have a proxy set.
- Set proxy and apply settings. This will show my subscriptions
- At this point I can scroll most storage objects, but as soon a I reach Blob Containers I get the "unable to retrieve child objects"
reason: connect ETIMEDOUT 40.118.73.185:443" < it seems the proxy is not used for Blob Containers and Files Shares. Queues and tables don't seem to generate errors
- At this point I have to restart/reload the application to get the new proxy settings going

Funny enough, disabling the proxy settings does have an immediate effect on browsing storage objects.

the specific order that generates the issue, is adding AAD account without proxy and setting the proxy later. 

note: the netsh settings was not the solution, but restarting/reloading the app was.

**Comment by JasonYeMSFT** [comment]
@michelvankessel 
> the netsh settings was not the solution, but restarting/reloading the app was.

This makes sense since our current proxy setting system don't propagate proxy settings to all process and require a full restart. Storage Explorer will be able to propagate proxy settings without restarting since 1.17.0.

**Comment by JasonYeMSFT** [comment]
We did some rework on our proxy features in 1.20 and 1.21, which includes dynamically propagating updated proxy settings in Storage Explorer so that a full restart is no longer needed. Please try upgrade to 1.21.
