### ISSUE TITLE
Editing path and pressing enter results in download of currently selected file

### ISSUE THREAD

**Issue by abrugh** [microsoft/AzureStorageExplorer#3708]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: ia32
**Regression From**:  

## Bug Description ##
If you edit the path by double clicking and changing the path, from something like `this/is/a/path/2020-10-04` to `this/is/a/path/2020-10-05` and press enter, whatever file was selected in the view below the path bar will start downloading, as if you'd pressed enter on it.

## Steps to Reproduce ##
* Navigate into a storage account with a few possible valid paths
* Edit the path manually 
![image](https://user-images.githubusercontent.com/49671/96912713-03512e80-1460-11eb-8252-f8a2eff509b8.png)
* if you change the example path to read `xxx/xxx/2020-10-05` and press the Enter key on your keyboard, 2020-10-04.0.csv.gz starts downloading but the view does change to `xxx/xxx/2020-10-05` as well.

## Expected Experience ##
The path changes and no files are downloaded.

## Actual Experience ##
The selected file in file view is downloaded as well as the path and file view changing.

## Additional Context ##
I've only really tried this with Gen2 enabled storage account, I don't know if this happens with other storage types.

**Comment by craxal** [comment]
@abrugh I have tried this with an ADLS Gen2 account, but I can't get any files to download. Does this reproduce consistently for you?

If you're comfortable working with the developer window, can you do the following to help us get some more info:

1. Open Storage Explorer and navigate to the blob container and folder in which you're encountering the problem.
2. Press F12 to open the developer window.
3. Click the Sources tab, press Ctrl+P, enter "Fileystems/Commands/DownloadCommand.js" and press enter.
4. Look for line 78 and drop a breakpoint there (should be a return statement that looks something like this)
   ```js
   DownloadCommand.prototype.doExecute = function () {
     return __awaiter(this, void 0, void 0, function () {
       var selectedItems;
   ```
5. Follow your repro steps with the address bar as below.

If a file download is triggered, the command should be executed and hit the breakpoint. If you can share your call stack with us, that would be very helpful.

**Comment by craxal** [comment]
@abrugh Thanks for jumping onto a call and reproing for me. I still wasn't able to repro on my end, but here's what I think is happening:

1. User presses Enter. Since the address bar has focus, it triggers the address bar input's `keydown` event handler.
2. The event handler updates the address bar and calls `FlobListViewModel.navigateToItem()` twice (not sure why it's called twice).
3. The first call updates the table as expected. The second call follows a different code path (because the "new" path is identical to the "old" one) and forces focus to change to the data table.
4. The user releases Enter. Since the data table has focus, it triggers the table's `keyup` event handler.
3. The event handler attempts to open the currently selected item (the first item in the table).

The interesting thing is we discovered a side effect from holding down Enter then releasing once the table reloads: the path navigates backwards to the original location.

It sounds to me like the easiest solution is to change which events we're attaching event handlers to. We should attach to the same events in order to avoid "cross contamination" like this. I also think we should avoid forcing focus to the data table, since this can be disorienting for accessibility reasons.

**Comment by craxal** [comment]
@abrugh I still can't repro this on my end, but it looks like we made some code changes about 3 months ago that avoids giving focus to the data table in this case. Does this still happen for you on 1.17.0?

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still have this issue, please open a new issue instead.
