### ISSUE TITLE
Encounted unexpected error

### ISSUE THREAD

**Issue by mikenewman1** [microsoft/AzureStorageExplorer#3712]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: MacOS 10.15.7

## Bug Description ##
`TypeError: Cannot read property 'forEach' of undefined`

## Steps to Reproduce ##
Just browsing through my Azure storage

## Actual Experience ##
Attached screenshot popped up
<img width="1733" alt="error" src="https://user-images.githubusercontent.com/13053391/97012621-07d81e80-1516-11eb-96a5-8ec707b537eb.png">

**Comment by MRayermannMSFT** [comment]
@mikenewman1 this is due to a bug in the feature set for CosmosDB. If you are not using cosmos db, then you can work around this issue by going to: Settings (gear icon on the left) -> Services -> CosmosDB -> uncheck the checkbox, and then restart Storage Explorer.

If you are a user of CosmosDb and you need to leave it on, let us know.

**Comment by MRayermannMSFT** [comment]
1.16.0 has been shipped, it includes a fix for this issue.
