### ISSUE TITLE
Can't not link azure account  ,click  no response

### ISSUE THREAD

**Issue by t105362506** [microsoft/AzureStorageExplorer#3715]
![image](https://user-images.githubusercontent.com/54572002/97129170-343fa500-1779-11eb-94c3-890101ba189a.png)

click add new account , no response

tool version V1.15.1

**Comment by t105362506** [comment]
![image](https://user-images.githubusercontent.com/54572002/97130203-b204b000-177b-11eb-8f5b-a78bb0f1cdcc.png)


Not available ,Keep stuck on this screen

**Comment by MRayermannMSFT** [comment]
@t105362506 in your 1st post you have a screenshot of the app window, but then in your 2nd you have the splash window. Are you now unable to get past the splash screen?

If you are still able to get to the app window, can you please:

1. try clicking on the plug icon (above the gear icon) on the left hand side of the window
2. go to Help -> Toggle Developer Tools -> Console, and look for any red text. If there is, then take a screenshot of the red text and share it here.
![image](https://user-images.githubusercontent.com/21112697/97207153-e88bfc00-1776-11eb-959c-b2beeaad6f79.png)

**Comment by t105362506** [comment]
@MRayermannMSFT  

Now I can’t even enter the window

Run Microsoft Azure Storage Explorer.exe but haven't response

**Comment by MRayermannMSFT** [comment]
@t105362506 so how far are you getting? Just to the splash window, or does nothing pop up?

**Comment by MRayermannMSFT** [comment]
@t105362506 regardless of your answer to that question, I think likely the issue is related to our auth library/the process that manages that. Can you do the following for me?

1. Delete ~/.ServiceHub/logs
2. Open ~/Library/Application Support/StorageExplorer/settings.json (if the file doesn't exist, create it with the contents just as `{ "application.signIn.verboseLogging": true }`.
3. Assuming you didn't have to make the file, add `"application.signIn.verboseLogging": true,` to the beginning of the file, after the `{`
4. Try running Storage Explorer
5. Give it a few minutes
6. Zip up ~/.ServiceHub/logs
7. Attach the zip here

Thanks!

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.
