### ISSUE TITLE
failed: error: UnexpectedQuit (used Azure AD, discovery not completed)

### ISSUE THREAD

**Issue by linyu220** [microsoft/AzureStorageExplorer#3739]
**Storage Explorer Version**:   1.10.0/ 1.15.0
**Build Number**: 
**Platform/OS**:  windows 10 x64
**Architecture**:  x64
**Regression From**:   

## Bug Description ##

Can't download and upload file from Azure storage server , 
failed: error: UnexpectedQuit (used Azure AD, discovery not completed)
But same account login other computer , it download and upload normal 

## Steps to Reproduce ##

select file to download , it will received error message 

## Expected Experience ##

Download/upload successful 

## Actual Experience ##

occur error : failed: error: UnexpectedQuit (used Azure AD, discovery not completed)

## Additional Context ##

Tried reinstall Azure storage App ,Reset , Reload , issue still occur in my PC , when i change a new PC , issue gone ,

**Comment by linyu220** [comment]
Error message 
{
  "message": "\"UnexpectedQuit\""
}

**Comment by JasonYeMSFT** [comment]
@linyu220 There is an AzCopy log in its logs directory (C:/Users/username/.azcopy). Could you clear the directory, reproduce the failed transfer and share the log file with us? The log file already have credentials redacted. 

Given that the error only occur on one PC, it may be related to firewall setting. Does the storage account you are accessing have firewall enabled? Is your computer within the allowed IP range?

**Comment by saurabh2335** [comment]
@JasonYeMSFT ,
Did we got any resolution here? I am also getting same exception, I have also tried with different version(Old and latest), still no luck, And surprisingly, It was working before, only recently this issue occurred. 
Please suggest any resolution for this.

**Comment by JasonYeMSFT** [comment]
@saurabh2335 Unfortunately no resolution so far. We use AzCopy's output to show the error. The "Unexpected quit" will be shown when AzCopy fails to give a legitimate output before quitting. Please try to get the log file or use "Copy command to clipboard" and run the command on command line using AzCopy to see what the actual error is.
You can download AzCopy from here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10#download-azcopy

**Comment by saurabh2335** [comment]
@JasonYeMSFT,
I only got this details in project explorer. 
```
{
  "message": "\"UnexpectedQuit\""
}

```An in AzCopy, it is not returning any error
Command which i used in AzCopy
`azcopy.exe copy "https://*****/data-dct/UAT3/database/cpspms/adhoc/id/archive/360_Adhoc_0062232050_100074288_1589448361697.CSV?sig=***********************&st=2020-11-05T14%3A44%3A00Z&se=2020-11-06T15%3A44%3A00Z&sv=2017-04-17&spr=https%2Chttp&sp=racwdl&sr=c" "C:\Users\*****\New folder\360_Adhoc_0062232050_100074288_1589448361697.CSV" --overwrite=prompt --check-md5 FailIfDifferent --from-to=BlobLocal --recursive;`

**Comment by JasonYeMSFT** [comment]
@saurabh2335 I believe it is caused by your sas resource type "sr=c". Please try creating a SAS with at least "sr=co".

**Comment by saurabh2335** [comment]
@JasonYeMSFT , Also tried with sr=co, still no output.
This might be because I tried to login with SAS url with sr=c and I copied the command from "Copy AzCopy Command to Clipboard"
I also tried to login with account name and key, still getting the same error.

**Comment by JasonYeMSFT** [comment]
@saurabh2335 Could you share the command when using account name and key? Also, could you do me a favor to add an argument "--output-type=json" to the end of the command and share the json output with us?

For account level SAS, we expect you to choose "Use a connection string" to connect to the storage account with account level SAS. If your resource type is "c", we don't allow you to move forward. The SAS url is usually used for connecting with a container level SAS.

**Comment by saurabh2335** [comment]
This command I got with account name and account key, but still no output.

`$env:AZCOPY_CRED_TYPE = "Anonymous";
$env:AZCOPY_CONCURRENCY_VALUE = "AUTO";
./azcopy.exe copy "https://**********.blob.core.windows.net/data-cps/*****/activityfile/ID/archive/activity_file_0000110005_1192735_20200723071953.csv?sv=2019-10-10&se=2020-12-05T18%3A37%3A10Z&sr=c&sp=rl&sig=HanAPNgvk1uE8PxbtW%2BekKl%2F6JLuZvRHXs704tPNxZM%3D" "C:\Users\s*****\New folder\activity_file_0000110005_1192735_20200723071953.csv" --overwrite=prompt --check-md5 NoCheck --from-to=BlobLocal --recursive --output-type=json;
$env:AZCOPY_CRED_TYPE = "";
$env:AZCOPY_CONCURRENCY_VALUE = "";`

**Comment by JasonYeMSFT** [comment]
Are you saying that there is no output at all? Like when you execute the command, the command line looks like:
```
user$ azcopy cp ......
user$
```

If that is the case, could you schedule a call with us so we can investigate it together? You can send your preferred way of contact to sehelp at microsoft dot com.

**Comment by saurabh2335** [comment]
@JasonYeMSFT,  I think we are one step closer to resolution,

I downloaded AzCopy 32 bit(previously using 64 bit), Now at least I am getting  some output, 

So I tried below command in AzCopy (without any parameter), files is downloaded successfully,
`azcopy.exe copy "https://*********.blob.core.windows.net/****/database/activityfile/ID/archive/activity_file_0000110005_1192735_20200723071953.csv?sv=2019-10-10&se=2020-12-05T18%3A37%3A10Z&sr=c&sp=rl&sig=*******" "C:\Users\**********\New `folder\activity_file_0000110005_1192735_20200723071953.csv";`

but for previous command I got this error '**Error: couldn't parse "json;" into a "OutputFormat"**', that means it is not working with command that I got from Storage Explorer.

I also tried with '--overwrite=prompt;' from AzCopy, got error like "**failed to parse user input due to error: couldn't parse "prompt;" into a "OverwriteOption"**"

Also same with other parameter from original query I got the parsing error.

**Comment by saurabh2335** [comment]
@JasonYeMSFT , I think it has something to do with that parameter which are part of query from Storage Explorer (Same with AzCopy), as it is not able to parsed that and failing in between. But not sure why it occurs recently.

**Comment by JasonYeMSFT** [comment]
@saurabh2335 Good to know that the command itself works. The error you mentioned is caused by AzCopy thinks "json;" or "prompt;" are the argument value instead of "json" and "prompt". The ; is used to separate commands. Not sure why it happens since the cmd tool should be able to tell and exclude it when passing arguments to the executable. The only way I can reproduce is to pass the argument like **--overwrite="prompt;"**. Removing the ; may help mitigate this issue. At the moment, if AzCopy doesn't work in Storage Explorer, please try to use the command line to workaround we look into it. 

Also are you using "Command Prompt" instead of powershell? That cmd tool has this problem

**Comment by linyu220** [comment]
@JasonYeMSFT Because it prevent download and upload file from Azure storage . and the Azure storage work normal at other PC . 
So I try to reinstall image and Azure storage , issue gone ,

**Comment by saurabh2335** [comment]
@linyu220 , Can you please elaborate the meaning of reinstall image? Because I also tried reinstall Azure Storage several times, but it doesn't works in my case.

**Comment by linyu220** [comment]
@saurabh2335 I get this failure in my surface studio 2 .And I also try to reinstall Azure storage explorer 1.10 or 1.15.1 when issue happen . Issue still happen 
I try to reinstall customer image for my set .  It work normal now.

**Comment by MRayermannMSFT** [comment]
@saurabh2335 you said that running on command line using 32 bit AzCopy worked, but it doesn't look like you did it with --output-type=json. Can you try it again with that option? Also, Jason asked:

Are you saying that there is no output at all? Like when you execute the command, the command line looks like:
```
user$ azcopy cp ......
user$
```

Is that indeed the case when you try to use 64 bit AzCopy?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of responses. For the future, if you're having issues doing an upload or download, we recommend:

- try running the transfer on the command line using the command from the "Copy AzCopy Command to Clipboard" action
- if that works, but you still want to use Storage Explorer in the future, then we'll ask you to do these troubleshooting steps:
   - provide us the log file from "Goto AzCopy Log File"
   - run the transfer on the command line, but add `--output-type=json` to the command

If y'all are still having problems, please open a new issue. Thanks!
