### ISSUE TITLE
Blob Access via AAD Group Not working

### ISSUE THREAD

**Issue by mwgroenewald** [microsoft/AzureStorageExplorer#3748]
**Storage Explorer Version**: 1.15.1
**Build Number**: 20200902.9
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  Unknown

## Bug Description ##
When a user has Reader and Storage Blob Data Contributor roles assigned via Azure AD **Group** Membership he is unable to access the blobs using AAD Auth. This however works when he has the roles directly assigned on the Storage Account, just not via the Group for some reason.

## Steps to Reproduce ##
1. Add User directly to storage account with two quoted roles.
2. Test access via Storage Explorer. - Access works
3. Add Group to storage account with quoted roles.
4. Add user to Group.
5. Test access via Storage Explorer. - Access fails

## Expected Experience ##
Access should be allowed as per direct User Assignment

## Actual Experience ##
Unable to retrieve child resources.

Details:
["RestError:﻿<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.\nRequestId:23d578e4-501e-0022-7659-b32841000000\nTime:2020-11-05T09:51:37.8939879Z</Message></Error>"]

![image](https://user-images.githubusercontent.com/22740744/98225454-64e3c380-1f5d-11eb-86a0-808e52289337.png)

## Additional Context ##
Storage Account has no network restrictions. Access to the Blobs via the Portal works using Group assignment and AAD Auth.

**Comment by JasonYeMSFT** [comment]
The error says the given role doesn't allow getting delete retention policy which we passes to our container nodes. We are working on a SDK migration for getting delete retention policy. Once that's done, I will double check your scenario to see if it is resolve. Ideally speaking, failing to get delete retention policy shouldn't block accessing the blob containers. I will try to unblock the code path even if a delete retention policy is not available.

**Comment by JasonYeMSFT** [comment]
I did some investigation and it turns out that we aren't blocking the node loading due to getting the delete retention policy. That is to say, the request for listing containers failed with unauthorized error. Most likely this is a service side issue. Unfortunately we don't have access to the service logs.

Could you please open a support ticket [link](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest) with information to the storage account you are having problem with and a request ID of failed call. The support engineers can check the log and figure out why it returns the error. 

Thanks.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you are still having issue, please open a new one instead.
