### ISSUE TITLE
Keep consistent behavior between in Activities and Editor when pasting one append blob to ADLS Gen2 container

### ISSUE THREAD

**Issue by v-limu** [microsoft/AzureStorageExplorer#3880]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201210.6
**Branch**: rel/1.17.0
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04 / MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Upload one append blob to it.
3. Copy the append blob then paste it to one ADLS Gen2 blob container.
4. Check whether the behavior is consistent between in Activities and Editor.

## Expected Experience ##
Keep consistent behavior between in Activities and Editor when pasting one append blob to ADLS Gen2 container.

## Actual Experience ##

1. The activity log is failed.
![image](https://user-images.githubusercontent.com/54055206/101749071-477bb980-3b08-11eb-8d56-4aa0fd4fb566.png)
2. The append blob displays in the editor after manually refreshing.

**Comment by MRayermannMSFT** [comment]
Did some digging into this. The way AzCopy is implemented, the error does not occur until after they've initially created the new blob. But since appending to a blob isn't supported, it isn't until they try to do an append that the operation fails. The log file is pretty clear about this:
`A required feature for this operation is not enabled on the account.. When Appending block from URL. X-Ms-Request-Id: 14871ad7-001e-007b-08de-e9fde8000000`
Going to go ahead and mark this as by design. We can revisit if a customer thinks otherwise.
