### ISSUE TITLE
The applied subscription and its resources show normally when the azure account expired

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#3891]
**Storage Explorer Version:** 1.17.0
**Build Number:** 20201211.10
**Branch:** rel/1.17.0
**Platform/OS:** Windows 10
**Architecture:** ia32
**Regression From:** Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Sign in with an azure account -> Select one subscription and apply it (Make sure 'MSAL' is disabled).
2. Open the local file 'C:\Users\<your username>\AppData\Local\.IdentityService\AccountStore.json' ->Change the field 'Stale' from 'false' to 'true'.
3. Go back to Storage Explorer -> Click 'Manage Accounts' icon (The azure account expired).
4. Click the 'Apply' button -> Check whether the applied subscription and its resources disappear.

## Expected Experience ##
The applied subscription and its resources disappear.

## Actual Experience ##
 The applied subscription and its resources show normally.

## Additional Context ##
This issue also reproduces when 'MSAL' is enabled (changing the field 'Stale' from 'false' to 'true' in local file 'C:\Users\<your username>\AppData\Local\.IdentityService\StorageExplorerV2AccountStore.json').

**Comment by MRayermannMSFT** [comment]
I am going to mark this as by designed.
1. The subscriptions still appear in the tree view because those are cached.2
2. You can still browse for resources because this test case doesn't actually expire the account. It's faking the expiration of an account. In reality, the account isn't expired and we can still get tokens for it.
