### ISSUE TITLE
Some filters on CosmosDB are not showing results at all

### ISSUE THREAD

**Issue by arsuceno** [microsoft/AzureStorageExplorer#3907]
I'm having these problems in some cases, using version 1.16.0. I think is related with the number of results. For example, this UseIntegrityCheck = true filter doesn't return any result when there are documents which match the pattern:
![image](https://user-images.githubusercontent.com/1771956/102337243-87bcbb00-3f92-11eb-92be-f94d22304670.png)

However, if I change condition to false it works OK:
![image](https://user-images.githubusercontent.com/1771956/102337442-c2beee80-3f92-11eb-8ce3-32a52c81d5ff.png)

Is there any limit for filtering?

**Comment by southpolesteve** [comment]
What happens when you click "load more" in the first screen shot? The query API for cosmos may return empty pages. Its possible your query results are just very sparse. Additionally:

The Cosmos team recently deprecated our integration with Azure Storage Explorer. [Here is the full deprecation notice from the 1.15.1 Storage Explorer release notes:](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.15.1)

> The Azure Cosmos DB integration with Storage Explorer has been deprecated. Any existing functionality will not be removed for a minimum of one year from this release. Users should use the Azure Portal, the Azure Portal desktop app, or the standalone Cosmos Explorer instead – all of which contain many new features that aren’t currently supported in Storage Explorer. Additionally, the Azure Cosmos DB team has also open sourced the data explorer project and will be investing in their own desktop tooling at a later date. Please keep an eye on their repository for more information. 

Currently, we are not prioritizing new features or bug fixes for Cosmos in Azure Storage Explorer. If you the issue you are reporting also applies to the Azure Portal or https://cosmos.azure.com, please file an issue in [our open source Cosmos Explorer repo](https://github.com/Azure/cosmos-explorer)
