### ISSUE TITLE
Bad ContentType when uploading blazor wasm app on a blob

### ISSUE THREAD

**Issue by alexdess** [microsoft/AzureStorageExplorer#3947]
**Storage Explorer Version**: 1.17.0
**Build Number**: 20201211.10
**Platform/OS**: Windows 10
**Architecture**:  x64
**Regression From**:  -

## Bug Description ##

The blazor.webassembly.js file should have the Content Type "application/wasm" but it has "application/javascript".

## Steps to Reproduce ##
1. Upload the file blazor.webassembly.js on a blob
2. Check the set Content Type

## Expected Experience ##
![image](https://user-images.githubusercontent.com/8177780/103409884-1c194700-4b69-11eb-9f9f-9749ee16c77b.png)

## Actual Experience ##
![image](https://user-images.githubusercontent.com/8177780/103409928-4f5bd600-4b69-11eb-89b4-45a2aace918c.png)

## Additional Context ##
Would the bug rather come from AzCopy?

**Comment by MRayermannMSFT** [comment]
For Windows, AzCopy determines the content type by looking at values in your registry. We're unsure if you can set a different content type for `.webassembly.js` though since that file extension consists of the two parts...

In the past, others have had success with the instructions at this link: https://stackoverflow.com/questions/3442607/mime-types-in-the-windows-registry

You might have to do some more searching for your special case though.

@alexdess the content type is controlled

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you need more help with this issue you might want to go to the AzCopy GitHub repo.

https://github.com/Azure/azure-storage-azcopy
