### ISSUE TITLE
Show Filter Panel or equivalent filtering capability in Explorer missing in versions above v1.16.0

### ISSUE THREAD

**Issue by gphsv** [microsoft/AzureStorageExplorer#4179]
Version: 1.18.1 
Build number: 20210304.5 
Platform: Windows 
Architecture: ia32 
Worked in version: 1.16.0 

## Bug Description ##
"Show Filter Panel" button (or equivalent filtering blob name filtering capability) is missing in version 1.17.0 and 1.18.1.

## Steps to Reproduce ##
1. Open Storage Accounts in Explorer tree
2. Open Blob Containers in Explorer tree
3. Choose (click on) a Blob Container
4. The corresponding Explorer pane opens to the right, and shows folders/blobs, but no "Show Filter Panel" is shown to the right of the Blob path input box shown above the folder/blobs listing. That functionality does not seem to be available elsewhere (e.g. either in the buttons at the top of the Explorer, or via the View menu).

## Expected Experience ##
Need to be able to filter the Explorer display to show files with certain file name prefixes -- although it would be preferable to be able to filter files using standard Windows Explorer wildcards (e.g. ? or *) or even regular expressions.

## Actual Experience ##
Choose a Blob Container. The "Show Filter Panel" / "Hide Filter Panel" button is not visible next to blob path text box on UI (under the top row of action buttons that includes "Folder Statistics" and "Refresh") as expected (as it was in v1.16.0).

## Additional Context ##
Access to Blob Container is via SAS and the storage is ADLS Gen2 if that makes any difference.

**Comment by jinglouMSFT** [comment]
"Show Filter Panel" is never there for ADLS Gen2.  The functionality under "Show File Panel" is only available for regular Blobs.

**Comment by gphsv** [comment]
Well it's the same Blob Container and if it's viewed with Azure Storage Explorer v1.16.0 then the "Show Filter Panel" functionality is available but in v1.18.1 it's not. Should I submit a feature request?

**Comment by jinglouMSFT** [comment]
@gphsv "Show Filter Panel" has never been implemented for ADLS Gen2. Is it possible that you have the same container name under different storage accounts?  Or you have turned on the HNS flag on your account?  The reason "Show Filter Panel" isn't there for ADLS Gen2 is because the service itself doesn't have the support of the features. If some day the service provides the functionality I am sure we will add them to Storage Explorer. But please feel free to submit a feature request if you'd like.  Thanks.
