### ISSUE TITLE
Revisit the logic for showing Posix ACL warning for files

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#4302]
**Storage Explorer Version**: 1.18.1

## Bug Description ##
When creating new files in a HNS directory, the inherited Mask and Named User/Group permission may lead to a warning.

## Steps to Reproduce ##
1. On a parent directory, set the Mask permission to be RX. Set the Group permission to be RX. There will be no warning on the parent's ACL.
2. Go into that directory, upload a file.
3. View the ACL of the uploaded file. On the file, the Mask have R permission while the Group have RX permission and we show a warning.

## Additional Context ##
We need to figure out

- If the permission inherited may have issues suggested by the warning
- If not, we should hide the warning in this type of scenarios

**Comment by MRayermannMSFT** [comment]
Have reached out to someone internally about discussing this....

**Comment by MRayermannMSFT** [comment]
Had a great talk with an ACL expert on the service side! Some recommendations for us:
- Move away from a warning symbol -> use an (i) instead. When these situations happen it is usually a user choice/by design behavior. Warning is therefore too strong.
- Have better linking to documentation about what to do in this situation.

Let's take these recommendations in 1.21!
