### ISSUE TITLE
Cannot access storage account

### ISSUE THREAD

**Issue by salliesaint23** [microsoft/AzureStorageExplorer#4323]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**:
**Regression From**:  Yes

## Bug Description ##
When I click on my storage account (which has a link icon with a red x on top of it, to the left of the site name), I get an error that says "Unable to load attached Storage Account. Error: Cannot read property 'version' of undefined."

## Steps to Reproduce ##
Double click storage accounts dropdown
Double click name of storage account

## Expected Experience ##
I should be able to access the media within this site to upload assets/documents.

## Actual Experience ##
When I click on my storage account (which has a link icon with a red x on top of it, to the left of the site name), I get an error that says "Unable to load attached Storage Account. Error: Cannot read property 'version' of undefined."

**Comment by JasonYeMSFT** [comment]
@salliesaint23 This may be due to the connection data is accidentally corrupted in the local credential manager. We have a section describing how to workaround this issue [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#error-occurred-while-adding-new-connection-typeerror-cannot-read-property-version-of-undefined).

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are continue to encounter this problem and would still like help.
