### ISSUE TITLE
Bad position of popup windows on multiple monitors configuration (sometime make popup invisible)

### ISSUE THREAD

**Issue by flyingoverclouds** [microsoft/AzureStorageExplorer#4343]
**Storage Explorer Version**: 1.18.1
**Build Number**: 20210304.5
**Platform/OS**: Windows 10
**Architecture**: x64
**Regression From**:  No.

## Bug Description ##
If you have multiple monitors attached to your computer, storage explorer popup windows does not appear center on the storage explorer windows, but center in the global area (global bounding box) including all the monitor. In some case, popup are not visible or partially truncated on another monitor. 
If the monitors are configured with different DPI (my case), the popup open using the DPI of the main storage explorer windows and can be ridiculous small on high DPI monitor. 

## Steps to Reproduce ##
Test the application on a desktop with multiple monitor. 
See my professional setup here (screen 1 is my ms corp lenovo X1 high dpi monitor) : ![image](https://user-images.githubusercontent.com/4788686/115051173-d2b4f380-9edc-11eb-828a-8bd93ed5a492.png)
Open Storage explorer, move it to screen 2 (standard dpi monitor)
Run an action that open a popup (for example, renaming a blob, uploading a blob already existing, . . . ).
The popup will open at extreme bottom right area of screen 1 , using standard DPI on a high dPI screen (and thus unreadable). Only the left part of the popup is visible (the hidden  part is out of screen)

## Expected Experience ##
A popup windows should open centered on the window where the user made the action triggering the popup.
(= centered top on the storage explorer window)

## Actual Experience ##
![bug_storage_explorer](https://user-images.githubusercontent.com/4788686/115052253-06dce400-9ede-11eb-929d-b8cda386ba3c.jpg)

## Additional Context ##
don't hesitate to contact me for more detailed information or test.

**Comment by MRayermannMSFT** [comment]
Hi @flyingoverclouds

I have [a build](https://storageexplorerpublish.blob.core.windows.net/privatebuilds/dialog-logging/StorageExplorer-ia32.exe) with some additional logging to try and figure out what is going on with your display setup and this bug.

If you could please:

1. Install the build
2. Repro the issue
3. Go to Help -> Open Logs Directory
4. Look for a file with a name similar to `main.log`
5. Attach that file to a reply to this issue
6. Take screenshots of your display settings in Windows so that we can see things like resolution, display scaling, arrangement, etc. of each display

Thanks. :)

**Comment by MRayermannMSFT** [comment]
Oh, and of course, let me know what monitor you opened storage explorer on and what window the dialog opened on.

**Comment by JasonYeMSFT** [comment]
Closing due to lack of response. If you still run into this issue, please open a new one instead.
