### ISSUE TITLE
The search box of one item is not reset after unchecking its subscription

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4374]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210423.2
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Previous release (1.18.1)

## Steps to Reproduce ##
1. Sign in one Azure account -> Check one subscription.
3. Click 'Open Explorer' -> Right click one subscription -> Click 'Search From Here'.
4. Go to 'ACCOUNT MANAGEMENT' panel -> Uncheck the subscription -> Click 'Open Explorer'.
5. Check whether the search box is reset.

## Expected Experience ##
The search box is reset.
![image](https://user-images.githubusercontent.com/41351993/115835621-0cd84500-a449-11eb-90e4-8c92e8fb3893.png)

## Actual Experience ##
The search box is not reset.
![image](https://user-images.githubusercontent.com/41351993/115839504-4e6aef00-a44d-11eb-90e7-e4d3539e3b20.png)

## Additional Context ##
1. This issue also reproduces for items under the subscription.
2. Display 'Nothing to display' after clicking 'X' button on the search box.
3. The 'EXPLORER' panel hangs.
![image](https://user-images.githubusercontent.com/41351993/115835713-2a0d1380-a449-11eb-852b-af71c4e0dbbc.png)

**Comment by MRayermannMSFT** [comment]
Other odd behavior: if you add check subscriptions while searching or scoped they will show up in the tree, regardless if they are search results or not.

**Comment by v-xianya** [comment]
If uncheck subscriptions while searching or scoped, other existing checked subscriptions will show up in the tree, regardless if they are search results or not.

**Comment by MRayermannMSFT** [comment]
Hi @v-xianya, so I have finished work on this issue. Let me make clear the resolution for the various problems discussed here:

1. Unchecking a subscription after doing "search from here" on it leading to a "Nothing to display" message that can't be gotten rid of: after unchecking the subscription and then going back to the tree, the subscriptions is removed (expected), the path is still in the search box (expected), the quick access node shows up (going to make this expected), and if you click the "X" to cancel the scoping, the tree is restored/no longer scoped (fixed/expected)
2. Checking a subscription while the tree is scoped or searched will result in the subscription being added to the tree, regardless if it matches the scoped path/search query: we are going to treat this as expected behavior.
3. Unchecking a subscription/s while searching or scoped, will result in all checked subscriptions showing up in the tree, regardless if they are search results or not: we are going to treat this as expected behavior.

Here's the like criteria we're using for these to determine if these behaviors are "expected" or "bugs":
1. If the tree is not scoped/searched, then checking/unchecking subscriptions should result in them being added/removed.
2. If the tree is not scoped/searched, then checking/unchecking subscriptions may result in things which wouldn't normally show up in the scoping/search results to show up.
3. When clearing a scope path/search query, the tree should always return to normal.

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Thank you for the detailed clarification👍
Verified this issue on the latest build 20210524.7. Fixed.

Also, could you please help to confirm the below two things according the [comments](https://github.com/microsoft/AzureStorageExplorer/issues/4374#issuecomment-847406719) ?
1. For the 1 in discussion, you mentioned **Unchecking a subscription after doing "search from here" on it leading to a "Nothing to display" message that can't be gotten rid of:**  Actually, we do not see the message 'Nothing to display' on the build 20210524.7
2. For the 2 in criteria, is there a mistake in the if condition description? -------If the tree is **not** scoped/searched.

**Comment by MRayermannMSFT** [comment]
> Actually, we do not see the message 'Nothing to display' on the build 20210524.7

Yes...? That is the first build with my fix for this. I'm not sure I understand your 1st thing.

> For the 2 in criteria, is there a mistake in the if condition description? -------If the tree is not scoped/searched.

Oh yep, that's definitely a typo. Fixed!

**Comment by v-xianya** [comment]
@MRayermannMSFT thank you for the comments.
For the first question, I maybe misunderstand what's your meaning.
The current expected behavior is that the '"Nothing to display' message no longer displays, right?
