### ISSUE TITLE
The 'Search by prefix' box is reset after clicking 'Apply Filters'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4379]
**Storage Explorer Version**: 1.19.1
**Build Number**: 20210425.1
**Branch**: hotfix/1.19.1
**Platform/OS**: Windows 10/ Linux Ubuntu 16.04/ MacOS Catalina
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
 1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
 2. Select one blob container then open it -> Open its 'Filter Panel'.
 3. Type some characters in the 'Search by prefix' box -> Select 'Tag Filters'.
 4. Click 'Apply Filters' -> Check the 'Search by prefix' box is not reset.

## Expected Experience ##
The 'Search by prefix' box is not reset.

## Actual Experience ##
The 'Search by prefix' box is reset.

**Comment by JasonYeMSFT** [comment]
This is due to a trade off between whether to preserve tag filtering result after switching back to the prefix mode. Imagine this scenario. 

1. User enters a prefix "A" which performs a prefix search.
2. Switches to tag filter mode and performed a filtering, which brings the filter results.
3. Switches back to the prefix mode. 

If we don't clear the prefix search, we would have to re-apply prefix search and overwrite the filter results. Otherwise it would leave the app in an inconsistent state where thee data doesn't match the active prefix value. I'll bring this up within the team to re-visit the design and see if there is anything we can do on this suggestion.

**Comment by JasonYeMSFT** [comment]
Most of the team actually think it should preserve the prefix input and clear the filter results. However, this is not very critical so we will wait for more customer feedback until taking action.

**Comment by v-xianya** [comment]
This issue doesn't reproduce on the New Filter panel [20210728.1]. So we are going to close it.
![image](https://user-images.githubusercontent.com/41351993/127253432-150fc1d7-765d-4f41-8ea6-ee7de6c1ec7a.png)

**Comment by MRayermannMSFT** [comment]
Neat!
