### ISSUE TITLE
Disable remove when Container has Blob

### ISSUE THREAD

**Issue by yujeny** [microsoft/AzureStorageExplorer#4384]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I can remove ~~storage account~~ blob container even when the container has blob.

### Desired Solution

When container has Blob, the container should not be removed through Storage Explorer.

**Comment by jinglouMSFT** [comment]
This is an expected behavior. If you don't want to delete the container, chose NO when the warning dialog is shown.  The reason of this design is because there are times users want to bulk delete all blobs in a container by just deleting the whole container.  Azure Portal offers the same behavior and the design.  If the user doesn't want to accidentally delete the container, you can put a lease on it so it can't be deleted.
