### ISSUE TITLE
Keep a consistent behavior for the 'Split' action between blob containers tab and 'Settings' tab

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4457]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210513.1
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**How found**: From running test case
**Architecture**: ia32/x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open one blob container -> Right click the tab.
2. Click 'Split' -> Click 'Split' again.
3. Open 'Settings' -> Right click the 'Settings' tab.
4. Click 'Split' -> Click 'Split' again.
5. Check whether the behaviors are consistent.

## Expected Experience ##
The behaviors are consistent.

## Actual Experience ##
The behaviors are inconsistent.
1. For the blob container, there are only two tabs.
2. For 'Settings', there are three tabs. 
![image](https://user-images.githubusercontent.com/41351993/118112386-83001400-b417-11eb-8526-33c0075369e0.png)

## Additional Context ##
1. For the 'Release Notes' tab, the 'Split' action can open several tabs.
2. For one 'file share/queue/table/resource group' tab, the 'Split' action can only open one tab.

**Comment by JasonYeMSFT** [comment]
This is by design at the moment. Our storage resource editors are using an old pattern that we have stopped using which has our internal logic for checking existing panels. Release notes, settings, and ADF extension tutorial use the new panel API to show contents. In the long run, we need to make the panel contributor provide the implementation of duplicate checking.

**Comment by v-xianya** [comment]
On rel build 20220421.6. For 'Settings' and 'Release Notes', there is no duplicated split tab.
