### ISSUE TITLE
Folders aren't displayed until switching pages when there are >1000 blobs at the root level

### ISSUE THREAD

**Issue by mscbevan** [microsoft/AzureStorageExplorer#4461]
Rough reproduction steps based on our current data:

1. Create a storage container with blobs in folders named 'a', 'h', and 'z' at the root level
2. Note blob folders 'a', 'h', and 'z' are visible in Azure Storage Explorer
3. Add many hundreds of blobs to the root level with names from GUIDs - e.g., 0001.bin, 0002.bin, ...
4. Switch to a different output container and back again
5. Note that folders 'h' and 'z' are not displayed, and refreshing or navigating around folders, changing sort, filters, etc. doesn't help
6. Also note that it shows: "Showing 1 to 100 of 1,000 cached items"
7. Click the buttons at the bottom of the pane to go to the end of the pages of cached items
8. Note that the number of cached items goes up - for me, "Showing 1 to 100 of 1,234 cached items"
9. Go back to the first page
10. All the blob folders are now visible

We've just noticed this in the current version, but it may have been around for longer; potentially this is the first time we've had lots of blobs at the root level.

**Comment by MRayermannMSFT** [comment]
Hey @mscbevan this is basically/unfortunately by design. Because of how Azure returns blobs to us, we cannot immediately load all folders at once as you would expect. In reality, you may have to load more (clicking on that button at the bottom of the page), and then return back to page 1 to see all your folders. We have an existing issue for addressing this and similar problems. Please refer to that issue for more info/details/updates. #1527
