### ISSUE TITLE
The folder path which is copied from the address bar doesn't end with a slash

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4485]
**Storage Explorer Version**: 1.20.0-dev
**Build Number**: 20210524.3
**Branch**: main
**Platform/OS**: Windows 10/ Linux Ubuntu 18.04/ MacOS Big Sur 11.3
**Architecture**: ia32/x64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create one folder -> Open the folder.
3. Copy the folder path through the address bar.
4. Check whether the folder path end with a slash.

## Expected Experience ##
The folder path end with a slash.

## Actual Experience ##
The folder path doesn't end with a slash.

## Additional Context  ##
This issue doesn't reproduce for blobs.

**Comment by craxal** [comment]
@v-xianya This is by design. The code is explicitly written to handle paths differently between blobs and files. The reason is because the blob and file APIs interpret paths a but differently. In addition, since blob containers don't have real folders, we need a way to determine whether a path is referring to a a folder or a file for the purposes of upload/download.

@JasonYeMSFT I think you're more familiar with the nuances of the paths and the slashes. Do you have any additional comments?

**Comment by JasonYeMSFT** [comment]
@craxal is correct. For blobs, the trailing slash is for us to tell that it is a directory. For file share, there is no ambiguity on whether the path is pointing to a file/directory so a trailing slash is not necessary. Unlike blob APIs, File Share APIs don't take paths with trailing slash so it will be more useful if we don't add the trailing slash.
