### ISSUE TITLE
Unable to list resources in account

### ISSUE THREAD

**Issue by Quipepeo** [microsoft/AzureStorageExplorer#4486]
Unable to list resources in account due to inadequate permissions. Permission to list containers or to list account keys is required.

Contact your subscription administrator to resolve this issue.

**Comment by Quipepeo** [comment]
Also, note the message on top of the screen: 

This request is not authorized to perform this operation using this permission. RequestId:754df184-f01e-008f-7cdf-502ebc000000 Time:2021-05-24T20:54:49.8988300Z

**Comment by apjanke** [comment]
I am having the same issue, with Azure Storage Explorer 1.19.1, AzCopy Version 10.10.0, Build Number 20210425.1, downloaded just now, on macOS 10.14.6.

```
Unable to retrieve child resources.

Details:
This request is not authorized to perform this operation.
RequestId:62b0b749-801a-000b-54e1-5072f7000000
Time:2021-05-24T21:09:02.4875321Z
```

![image](https://user-images.githubusercontent.com/2618447/119408133-3936e980-bcb3-11eb-8cb2-922587a984b8.png)

I selected "Subscription" for what to sign in to, signed in apparently successfully with my account, and I can see multiple Subscriptions in the Explorer. Under these Subscriptions, I can expand them to see a bunch of Storage Accounts. But when I expand any resource type under some of these Storage Accounts, I get a similar error.

I am quite certain the Microsoft account I am signed in with has permissions to view these resources: it has Owner rights on the whole Subscription, and is the original creator of most of these storage accounts and resources under them. I have successfully used Azure Storage Explorer before with this Microsoft account and these storage accounts, on different machines.

Happy to share additional details if you contact me directly.

**Comment by apjanke** [comment]
Okay, I think I feel like a moron: all the storage accounts where I'm getting this error have their Networking configured to have private endpoints, and the ones which are working have public endpoints ("accessible from all networks"), and I'm not VPNed in to our Azure network environment on this machine. Guess this is actually working as designed, and the error message is just a little hard to interpret? (I would have expected an error message about a network connection failure like "no route to host" or "no endpoint available" instead of a request permissions error, I guess?)

So, maybe PEBKAC in my case?

**Comment by JasonYeMSFT** [comment]
@Quipepeo Does apjanke's comment answers your question?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having problems, please either open a support ticket from the portal, or open a new issue here. Thanks.
