### ISSUE TITLE
I am not able to see Azure storage blobs inside containers on portal but it's working from Azure storage explorer. also the Azure storage explorer preview on portal couldn't see the blobs inside containers.

### ISSUE THREAD

**Issue by Parag-Sonne** [microsoft/AzureStorageExplorer#4525]

**Comment by MRayermannMSFT** [comment]
@Parag-Sonne so to double check, you can access your resources in desktop Storage Explorer, but not via any of the portal experiences?

If yes then, is there a reason you need to be able to use portal in addition to desktop Storage Explorer?

Finally, how are you accessing your containers in desktop Storage Explorer? Did you:

- sign in and enumerate accounts under your subscription?
- attach a storage account directly?
- attach a container directly?

**Comment by Parag-Sonne** [comment]
Hi,

I actaully need this to set stored access policies on containers from portal. And also trying to use some scrips on the blob.

And in desktop storage explorer, i just sign and enumerate accounts under subscription. It works well there

**Comment by MRayermannMSFT** [comment]
> I actaully need this

What is this?

> I actaully need this to set stored access policies on containers from portal.

You can set stored access policies using desktop Storage Explorer. Right click on containers click "Manage access policies".

> also trying to use some scrips on the blob

What do you mean by scrips/scripts?

> And in desktop storage explorer, i just sign and enumerate accounts under subscription. It works well there

Ultimately, it sounds like desktop storage explorer is working well and your issue is with portal. So in that case you'll need to open a support ticket. You can do this by going to the portal and clicking on the "?":
![image](https://user-images.githubusercontent.com/21112697/121938589-d90af480-cd00-11eb-991f-1fc199508d3f.png)

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you still need help, please either open a support ticket from the portal, or open a new issue here.
