### ISSUE TITLE
The 'File Changes Detected' dialog pops up when executing 'open a blob -> edit it -> click any part of Storage Explorer'

### ISSUE THREAD

**Issue by v-xinda** [microsoft/AzureStorageExplorer#4598]
**Storage Explorer Version:** 1.20.0-dev
**Build Number:** 202100618.7
**Branch:** rel/1.20.0
**Platform/OS:** MacOS Big Sur 11.4
**How Found:** Exploratory testing
**Architecture:** x64
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Create a blob container -> Upload a blob to it. 
2. Open the blob -> edit it (Don't save and close it).
3. Click any part of the storage explorer.
4. Check whether the 'File Changes Detected' dialog pops up.

## Expected Experience ##
The 'File Changes Detected' dialog doesn't pop up.

## Actual Experience ##
The 'File Changes Detected' dialog pops up.
![Screen Shot 2021-06-21 at 6 38 47 PM](https://user-images.githubusercontent.com/57662131/122749442-f2431080-d2bf-11eb-95bb-7529537b715c.png)

## Additional Context ##
1. This issue doesn't reproduce on Windows and Linux.
2. This issue doesn't reproduce without editing file after opening it.

**Comment by MRayermannMSFT** [comment]
@v-xinda when your file is opened, is it being opened in TextEdit?
![image](https://user-images.githubusercontent.com/21112697/122804571-eda93880-d27c-11eb-9d38-5aec72e644ab.png)
If so then this is by design. TextEdit has a feature where it will auto save after losing focus. Please let us know what program the file is being opened in.

**Comment by v-xinda** [comment]
@MRayermannMSFT  The file is opened in TextEdit.

**Comment by v-xinda** [comment]
@MRayermannMSFT  Because it's by design, so I close it.
