### ISSUE TITLE
The deleted blobs disappear after deleting it from 'Active and deleted blobs' for one attached blob container with soft delete enabled

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/AzureStorageExplorer#468]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows 10/MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32/x64
**Build Number**: 20180724.4
**Commit**: 2605f1c9
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one account then enable soft delete for the 'Blob Containers'.
2. Attach one blob container which contains one blob at least using SAS under the account.
3. Expand the Local & Attached > Storage Accounts > (SAS-Attached Services) > Blob Containers nodes and open the attached blob container.
4. Switch to 'Active and deleted blobs' on the opened editor -> Delete one blob then check whether it displays with strikethrough.

#### Expected Experience: ####
The deleted blob displays with strikethrough.

#### Actual Experience: ####
The deleted blob disappear and it will display well after refreshing the editor.

**Comment by JasonYeMSFT** [comment]
Yes, this is an unideal behavior. However, we can't make it update according to the delete policy because a SAS attached blob container has no permission to fetch the delete policy for the storage account it belongs to. We won't fix this for the 1.4.0 but we will collaborate with the platform team if the users blame us for this.

**Comment by v-limu** [comment]
This issue has been fixed on build [20190927.10](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3091851). So close it.
