### ISSUE TITLE
Azure Storage Explorer installation problem

### ISSUE THREAD

**Issue by ElshanCh** [microsoft/AzureStorageExplorer#4691]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19

### Architecture

x64

### Platform

Windows

### OS Version

windows 10

### Bug Description

after finishing the installation of the Azure storage explorer, on the panel of successful installation I launch the program and it works ok, but if i quit the Storage explorer and if i want to rerun it I cannot find the Storage explorer on my pc, and i should again restart from reinstallation process 

### Steps to Reproduce

1.Install the Storage Explorer
2. auto launch it after installation
3. quit the programm

### Actual Experience

after finishing the installation of the Azure storage explorer, on the panel of successful installation I launch the program and it works ok, but if i quit the Storage explorer and if i want to rerun it I cannot find the Storage explorer on my pc, and i should again restart from reinstallation process. Bellow on photo i illustrate that there is no application of the Storage explorer on my pc after installation, there is only storageexplorer.exe file that i actually have run already

![image](https://user-images.githubusercontent.com/79973254/126125568-c702cd8c-8a78-4a61-9f28-e739649f3a1c.png)

**Comment by MRayermannMSFT** [comment]
@ElshanCh
1. What happens if you click the .exe you pointed to with your red arrow? Based on the file name, it looks like that is probably the .exe used to run the app.
2. Have you tried restarting your computer?
3. Where did you download the installer from?
4. Assuming restarting does not work can you try uninstalling and then reinstalling? To uninstall, you can go to the application's install directory, and then running the unins000.exe. Alternatively you can uninstall by going to Windows settings > Apps, finding Storage Explorer, and then uninstalling it.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this problem and still want help please open a new issue. We'll also still want the answers to our original questions. Thanks.
