### ISSUE TITLE
The value of the 'Last Modified' displays duplicate on Mac

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4749]
**Storage Explorer Version**: 1.21.0-dev
**Build Number**: 20210803.3
**Branch**: main
**Platform/OS**: MacOS Big Sur 11.4
**Architecture**: x64
**How Found**: From running test cases
**Regression From**: Previous release (1.20.1)

## Steps to Reproduce ##
1. Launch Storage Explorer on Mac.
2. Restore the 'Dates & Times' to default if it has been customized. [On Mac -> Click 'System Preferences...' -> Click 'Language & Region -> Advanced... -> Select 'Dates' and 'Times' respective and apply 'Restore Default'.]
3. Expand one storage account -> Blob Containers.
4. Select a blob container -> Observe the value of the 'Last Modified' on the properties panel.
5. Check the value shows well.

## Expected Experience ##
The value shows well.

## Actual Experience ##
The value shows duplicate.
![image](https://user-images.githubusercontent.com/41351993/127977484-cd493be2-f50d-4a71-a36d-67f12b5174ba.png)

## Addition Info ##
This issue also reproduces for Last Modified in date columns on blob explorer.
![image](https://user-images.githubusercontent.com/41351993/127977412-acef176a-9080-4a8c-a3c9-e395b41115e4.png)

**Comment by craxal** [comment]
Oh, I think it's because we're setting up `NSDateFormatter` incorrectly. We're setting Both the date _and_ the time styles fo `NSDateFormatterShortStyle`, which doesn't play nicely when also setting a format string. But silly me, I didn't realize `NSDateFormatter` already supported Language & Region preferences, so there's no reason to dip into the preferences ourselves.
