### ISSUE TITLE
Pressing Enter in the path bar while an item is selected in the explorer panel appends the item's name to the current path then navigates

### ISSUE THREAD

**Issue by munael** [microsoft/AzureStorageExplorer#4777]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Platform

Windows

### OS Version

Win10 21H1

### Bug Description

Entering a path in the path bar then pressing Enter sometimes (always?) appends the currently selected item in the explorer panel to the path.

### Steps to Reproduce

1. Go somewhere.
2. Select an item in the Explorer panel.
3. Click on the pathbar to edit.
4. Enter a new path.
5. Press Enter.

### Actual Experience

Path navigated to is `{my_path}/{selection_name}` instead of `{my_path}`.

**Comment by MRayermannMSFT** [comment]
@craxal let's get this fixed, I can repro this every now and then and it is SO annoying.

**Comment by craxal** [comment]
Related to #3708?

**Comment by craxal** [comment]
@munael @MRayermannMSFT I'm looking into this as best I can, but I'm not having luck reproducing right now, which makes testing a fix very difficult. Can either of you provide some more info? Answers to a few of these questions may be helpful in isolating the issue:
- Can you provide more precise repro steps?
- Does this occur on platforms other than Windows?
- Does this occur in classic blob containers, ADLS Gen2 containers, file shares, or all of the above?
- Does this happen if you press Tab instead of Enter?
- Does it matter if you select a blob/file or a folder?
- Does the size of the current/intended destination folder seem to have any effect on whether the issue occurs?

**Comment by munael** [comment]
@craxal -

- I've seen this happen more consistently _after_ copying and pasting a file between different folders in the same blob (at least; I just haven't tried other stuff).
- Happens when you've highlighted a folder. If you've highlighted a file, the file starts downloading when you press enter and the path you entered is entirely discarded.
- Everything tried on standard and premium blob containers of the normal kind (that is, I can't find any special names like "ADLS" or such in the description).
- Haven't tried on anything but Windows (in fact, couldn't get ACE to run on Xubuntu 18.04 :/ ).
- Doesn't happen when you press Tab (yay!) or when you click away from the path bar (which I'd been doing until now...).
- Doesn't seem related to size of file or folder contents or their quantity.

**Comment by craxal** [comment]
I'm able to reproduce this in previous versions (sort of) but not in current internal builds, so this may already be resolved. Once we release 1.21.0, feel free to comment here or open a new issue if you're still running into this problem.
