### ISSUE TITLE
SystemFormat doesn't work properly on build targeting Arm64 Windows 10

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#4799]
When running build targeting Win10 Arm64, report error:  "systemFormat.node is not a valid win32 application".

**Comment by MRayermannMSFT** [comment]
Cannot repro this. If I had to guess, this was caused by either a Node issue, a Windows issue, or not having the right build tools installed. If it was the last one then here's my advice...

Since VS is only available for non-ARM, I think it is defaulting to installing the x64/x86 C++ tooling. So what you'll want to do is:
1. Install the normal C++ workload for VS
2. After that is done, go to individual components and filter by "C++"
3. For every C++ component, see if it is x64/x86 specific
4. If it is, then check to see if there is an ARM64 equivalent and install it

Ultimately, that led to me installing the following components:
- MSVC v142 - VS 2019 C++ ARM64 build tools (Latest)
- C++ ATL for latest V142 build tools (ARM64)
