### ISSUE TITLE
Some Storage Accounts are not able to be opened

### ISSUE THREAD

**Issue by artmymx** [microsoft/AzureStorageExplorer#4823]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Regression From

None

### Architecture

i86

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Some Storage Accounts are not able to be opened.

![Azure_Storage_Explorer_Error](https://user-images.githubusercontent.com/15419756/130068135-163381ed-8d1b-4fc0-9f03-6f016ee0bc22.jpg)

### Steps to Reproduce

1. Launch Storage Explorer
2. Try to display a specific account, like xxxxxx14599(ADLS Gen2)

### Actual Experience

Almost all Accounts are being able to be opened, blob containers and so on but some specific ones are not able to be displayed

### Expected Experience

I should be able to open the Account to see the different options

### Additional Context

![Azure_Storage_Explorer_Error](https://user-images.githubusercontent.com/15419756/130068521-6b77a2bc-aa62-463e-b2a7-b5dd940be345.jpg)

**Comment by MRayermannMSFT** [comment]
@artmymx are you able to expand the account when **not** viewing it as a search result?

**Comment by JasonYeMSFT** [comment]
I probably know why that specific storage account is not expandable. From what I learned, when we search for resources, we match the node and show their ancestors, even if the ancestors aren't matched with the search string. However, for a matched node that has children, we don't make it expandable if there is no child in it that matches the search string.

For example, in your screenshot, "14599" matches the storage account node named "wes06tedala14599" but doesn't match any of its children so we don't make it expandable. However, for other nodes, including group nodes that doesn't match "14599", they are included in the result and expandable because there is some children that matches "14599".

A workaround for now is to right click and add that node to Quick Access. I kinda think this is a bug.

**Comment by MRayermannMSFT** [comment]
> A workaround for now is to right click and add that node to Quick Access. 

You can also select the node, then quit search. The node should then be selected in the tree once the search results go away (I think).

**Comment by JasonYeMSFT** [comment]
We had some issues supporting expanding storage accounts without matching children so this behavior is by design.
