### ISSUE TITLE
Getting an error as "Unable to retrieve child records" while listing file in a blob container 

### ISSUE THREAD

**Issue by imvjsai** [microsoft/AzureStorageExplorer#4827]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.20.1

### Architecture

x64

### Storage Explorer Build Number

20210720.10

### Platform

Windows

### OS Version

Windows10

### Bug Description

Hi There,

Looking forward for your support. Highly appreciate your quick response!

We have a requirement to download bulk files from a BLOB in a one of our StorageAccount. Hence, we downloaded Azure storage explorer. While trying to access BLOB container, we are getting an error as "Unable to retrieve child records". 

I have verified if i have Storage Blob Data Reader from azure portal. I can see it exist. By checking similar issues, i tried to delete AppData->Roaming->AzureStorageExplorer files and also tried re-installing Storage explorer. But it still didn't work. 

Any suggestion is highly appreciated. Kindly let me know if any details required.

Kind Regards,
Vijay

### Steps to Reproduce

1. Launch Storage explorer 
2. Connect to our Subscription.
3. Navigate to your Storage account and try to list the files in your Blob container.

### Actual Experience

Same as mentioned in Bug description above, getting error while expanding files list from our Blob container

### Expected Experience

Have to list the files present in BLOB container.

**Comment by JasonYeMSFT** [comment]
@imvjsai Is your computer using a proxy to connect to the internet?

**Comment by imvjsai** [comment]
> @imvjsai Is your computer using a proxy to connect to the internet?

Thanks for your response. I'm not using proxy to connect to internet.
![image](https://user-images.githubusercontent.com/46667105/130192050-0403b38d-81e8-4a50-895f-0afe92328eef.png)

**Comment by imvjsai** [comment]
@JasonYeMSFT 
Thanks for your response. I'm not using proxy to connect to the internet. 
![image](https://user-images.githubusercontent.com/46667105/130192387-7a9a6751-8361-4fa3-b152-fe6e6945464b.png)

**Comment by kipperbush-lendus** [comment]
Also ran into this today, freshly installed the app.
![image](https://user-images.githubusercontent.com/85566177/130225067-ed63ba0c-9899-4329-8bc6-b32554a41504.png)

No proxy
![image](https://user-images.githubusercontent.com/85566177/130225162-01a2d65a-4f6a-404f-ba18-a735ceaf8f46.png)

**Comment by JasonYeMSFT** [comment]
@kipperbush-lendus You are connecting to a storage emulator supposed to run on your local machine. This is the typical error when you don't have your local emulator started. Could you check if you have started your emulator?

**Comment by imvjsai** [comment]
@JasonYeMSFT Could you please suggest for my issue?

**Comment by JasonYeMSFT** [comment]
@imvjsai I remember in your previous screenshot you are connecting to a public Azure storage endpoint. The "local certificate error" is usually caused by a misconfigured server (proxy server or the Azure server itself). Since you aren't using one, I don't have a good answer on what goes wrong right now. If you have access to other Azure storage accounts in your subscription, you may try exploring data in them and see if the error reproduce on every one of them. That would hint on whether this might be something wrong with that storage account.

**Comment by imvjsai** [comment]
@JasonYeMSFT Thanks Jason. Under my same subscription, i am able to access another Storage account BLOB without issue. As you see below, BLOB that highlighted in red is unable to access and thrown the error. Could you please suggest what factors can be compared within these two storage accounts?

![image](https://user-images.githubusercontent.com/46667105/130270876-2126cf76-a504-434c-9b7d-3eeac67217ef.png)

![image](https://user-images.githubusercontent.com/46667105/130271394-bcd17b40-dc06-4bcc-8d9f-4ca73f302e1d.png)

**Comment by JasonYeMSFT** [comment]
Try to see if you can list the containers of that storage account in https://portal.azure.com and if you can find anything helpful at https://portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview.

If nothing helps, you can open a support request and give the following information
- The storage account having this issue
- The error message
- You are not using a proxy
- It only happens on this specific storage account (indicating that this might be a service issue)
- If you can list resources on Portal or not
- The original error is found in Storage Explorer

I believe someone on the service side will check if there is any issue on the service. If they believe the problem is actually in Storage Explorer they will transfer the issue back to us.

**Comment by imvjsai** [comment]
@JasonYeMSFT I'm able to list the containers from https://portal.azure.com/. I will open a support request as you suggested. 

Thanks for the help and guidance provided. With this I'm closing this task.
