### ISSUE TITLE
An error info 'The specified container does not exist' prompts when clicking 'Open Secondary Location' for one new created blob container

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#4858]
**Storage Explorer Version:** 1.21.0-dev
**Build Number:** 20210829.9
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture:** ia32\x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Create one storage account which has GRS enabled -> Blob Containers.
2. Create a new blob container -> Right click the blob container -> Click 'Open Secondary Location'.
3. Check whether no error info prompts.

## Expected Experience ##
No error info prompts.

## Actual Experience ##
An error info prompts.
![image](https://user-images.githubusercontent.com/87792676/131317279-4d371873-961f-4dea-b3d1-6e2ea00cd975.png)

**Error info:**
`The specified container does not exist. RequestId:9ec96f69-a01e-00e5-1d80-9db311000000 Time:2021-08-30T09:25:31.6845576Z`

## Additional Context ##

1. This issue reproduces 8-9 times when trying 10 times.
2. This issue reproduces 100% for one new created account.

**Comment by craxal** [comment]
@v-kellyluo I've encountered this issue as well. This is because there is an expected delay between when the container is created and when the secondary location is created. If you wait a few seconds (for new containers), the issue goes away. Since there isn't much we can do about the delay, and I don't expect many users to want to open the secondary location for new containers very often, I don't think this needs a fix.
