### ISSUE TITLE
Retiring CosmosDB 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#4915]
Per CosmosDB team plan, retiring its support in Storage Explorer.

**Comment by avalanchis** [comment]
The only part of the app I ever used and they retired it.

**Comment by jinglouMSFT** [comment]
@avalanchis Estefani from the CosmosDB team is monitoring this thread. Please feel free to voice your feedback.

**Comment by dotnetprofessional** [comment]
> There is a replacement for this feature??? It was really useful to have all the resources in one place!

Honestly the two options provided as 'alternatives' are dreadful. I mean seriously they are (censored), they are slow, hard to navigate and just overall dreadful. I'm not sure why such a horrible decision was made, most likely political as it makes not technical sense. This is called Azure Storage Explorer, and last time I checked, CosmosDb was storage!!! Seriously if the portal is good enough, for Cosmos then why isn't it good enough for other storage accounts and queues etc. Answer, because its not its too damn slow for a developer to use. Its fine if you're just doing a one off, but if you're actually developing and switching between multiple accounts, its dreadful.

Can we install an old version of the tool as this has literally made this version useless to me. In case I wasn't clear I'm not happy with the update.

**Comment by StefArroyo** [comment]
Hi @dotnetprofessional,

Thank you so much for feedback on our desktop tooling, we appreciate the time you have taken to share your concerns. We are actively working on an alternative solution using Azure Data Studio, a unified desktop tooling experience exclusively for Azure databases. In the meantime, you can continue to use the following options:  [version 1.21.3 of Azure Storage Explorer](https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.21.3) which integrates with Azure Cosmos DB, the [Azure Portal](https://portal.azure.com/), [Azure Portal desktop app](https://portal.azure.com/App/Download) or the standalone [Azure Cosmos DB Explorer](https://docs.microsoft.com/en-us/azure/cosmos-db/data-explorer).

**Comment by Denisjc** [comment]
Based on the record of the retirement of tools and the utter disregard of what developers say.  It is little surprise that no one is reading this thread and no one cares.  Ah well we just uninstall your tools and build our own, and to quote Bender "with blackjack ... etc"
