### ISSUE TITLE
The original tab is closed after pasting a file share 

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4961]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20210923.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Select one file share -> Open it by clicking 'Open'.
3. Clone the file share -> Check whether the original tab is still opened.

## Expected Experience ##
The original tab is still opened.

## Actual Experience ##
The original tab is closed.

## Additional Context ##
1. This issue also reproduces for copy & paste action.
2. This issue also reproduces for tables.
3. This issue doesn't reproduce for blob containers.

**Comment by JasonYeMSFT** [comment]
This issue share the same cause of #2815. For some reason we are closing the source container and selectively not opening the new container in the explorer in our legacy v2 code path. This doesn't make sense. The expected behavior should be

"When pasting/cloning a container, the source explorer stays opened (if already opened) and the a new explorer for the destination opens."

I am going to close this issue as dup and start tracking #2815.
