### ISSUE TITLE
Keep consistent behaviors between pasting one empty folder and more than one empty folder against file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#4969]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20210924.14
**Branch**: hotfix/1.21.2
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.4
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share-> Create three new empty folders (**f1, test1, test2**).
3. Copy the folder **test1** then paste it into the folder **f1**.
4. Observer the activity log.
5. Back to the root -> Select the two folders **test1** and **test2**.
6. Copy the two folders then paste them into the folder **f1**.
7. Observe the activity log.
8. Check whether the behaviors are consistent.

## Expected Experience ##
The behaviors are consistent.

## Actual Experience ##
The behaviors are inconsistent.
![image](https://user-images.githubusercontent.com/41351993/134801819-49dfaad2-0860-4b22-9db5-a46a04ff485c.png)

## Additional Context ##
1. For ADLS Gen2 blob containers, always display '0 items transferred' regardless of how many empty folders are pasted.
2. Related issue [3193](https://github.com/microsoft/AzureStorageExplorer/issues/3193).

**Comment by MRayermannMSFT** [comment]
Let's understand why the numbers are different and open a bug against AzCopy if needed.

**Comment by JasonYeMSFT** [comment]
For single folder copy, the AzCopy command looks like
cp root/src/* somewhere/src/

And since root/src/ is empty, AzCopy thinks there is nothing to copy and exits.

For multiple folder copy, the AzCopy command looks like
cp root/* somwhere/

with list of files as:
src1/
src2/

AzCopy lists under root and founds the two folders and thus creates the two folders.

I think for us, this is a low priority bug. If the folder to copy is empty, the user can always create the folder at the destination instead.

**Comment by JasonYeMSFT** [comment]
This work needs a new AzCopy flag planned for their next release.

**Comment by JasonYeMSFT** [comment]
For file share, the activity now includes the directory in the job summary (e.g. 1 item if copying an empty directory, etc.). For blob/gen2 the behavior will remain the same (e.g. 0 item if copying an empty directory, 2 items if copying 2 empty directories) because the AzCopy flag doesn't work for blob.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Verified this issue on the build main 20220926.1. The current behavior as below
1. For file share, display the correct number when copying empty folders for file share.
(1 item if copying an empty directory, 2 items if copying 2 empty directories) 
2. For ADLS Gen2 blob container.
(0 item if copying an empty directory, 0 items if copying 2 empty directories) 




BTW, Is there a typo in (e.g. 0 item if copying an empty directory, 2 items if copying 2 empty directories)
> For file share, the activity now includes the directory in the job summary (e.g. 1 item if copying an empty directory, etc.). For blob/gen2 the behavior will remain the same (e.g. 0 item if copying an empty directory, 2 items if copying 2 empty directories) because the AzCopy flag doesn't work for blob.

**Comment by JasonYeMSFT** [comment]
Oh, sorry there is a typo. For gen2 and blob, empty directories will be ignored.

**Comment by v-xianya** [comment]
@JasonYeMSFT 
Thank you for the response, The behaviors are the same as the comments. Will close this issue.
