### ISSUE TITLE
It would be better to add a warning 'Blob name must be different' in the 'Clone and Rehydrate' dialog

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/AzureStorageExplorer#5031]
**Storage Explorer Version**: 1.22.0-dev
**Build Number**: 20211008.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.5
**Architecture**: ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Bug Description ##
There is an incorrect error message **'This operation is not permitted on an archived blob'** when executing 'Clone and Rehydrate' for one archive blob without changing the destination blob name.

## Steps to Reproduce ##
1. Expand one non-ADLS Gen2 storage account -> Blob Containers.
2. Create a blob container -> Upload one blob.
3. Update the access tier to 'Archive' -> Right click the blob.
4. Click 'Clone and Rehydrate' -> Observe the 'Destination blob name' part.
5. Check whether there is a warning 'Blob name must be different'.

## Expected Experience ##
There is a warning 'Blob name must be different'.
Like the clone dialog:
![image](https://user-images.githubusercontent.com/41351993/136519434-edc6b1c0-011a-40d5-b9ca-adf361f5d18f.png)

## Actual Experience ##
There is no warning.
![image](https://user-images.githubusercontent.com/41351993/136519043-4a74b086-9d37-4327-90a8-1555a1eadde7.png)

## Additional Context ##
There is a failed activity log when executing 'Clone and Rehydrate' without changing the destination blob name.
![image](https://user-images.githubusercontent.com/41351993/136519298-9a3233a8-7e5b-42a8-9f31-482bd8b96ecf.png)

Error details:
`
	 "name": "RestError",
  "message": "This operation is not permitted on an archived blob.
`

**Comment by v-xianya** [comment]
@JasonYeMSFT when executing 'Clone and Rehydrate' for one archive blob without changing the destination blob name.
Display the error message 'This operation is not permitted on an archived blob', The error message doesn't make sense to me. Could you help to take a look on this?

**Comment by JasonYeMSFT** [comment]
This is an unexpected service error given that the documentation says "You can perform a copy operation to promote a version blob over its base blob". I asked the service team to see if this is actually supported.

**Comment by JasonYeMSFT** [comment]
There are 3 different scenarios so I'll re-cap every one with what I know so far:
- I have turned on the "same name" validation in all situations. No matter if the source is an archived base blob or version, it must use a different name instead. So the error in the 1st screenshot shouldn't be seen anymore because the user won't be able to send such requests.
- The success in screenshot 2 is expected. Once a new name is given, the source can be copied and rehydrated to be the new blob).
- Unfortunately the service doesn't support directly rehydrating a blob version. So the error is also expected. The only way to rehydrate an archived blob version is to clone and rehydrate it to a new online blob.
