### ISSUE TITLE
Miss the action 'Search From Here' for the '(Emulator - default Ports) (Key)' node

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5114]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211031.1
**Branch:** main
**Platform/OS:**  Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32
**How Found:** From running test cases
**Regression From:** Previous release (1.21.2)

## Steps to Reproduce ##

1. Launch Storage Explorer -> Expand 'Local & Attached -> Storage Accounts'.
2. Right click '(Emulator - Default Ports)(Key)' node.
3. Check whether the action 'Search From Here' displays on the context menu.

## Expected Experience ##
The action 'Search From Here' displays on the context menu.
![image](https://user-images.githubusercontent.com/87792676/139646013-dd1b379c-27bb-4ae1-ae3e-e02977c36124.png)

## Actual Experience ##
No action 'Search From Here' displays on the context menu.
![image](https://user-images.githubusercontent.com/87792676/139646136-cc27e827-c475-4077-9a40-814f619c9d26.png)

## Additional Context ##

1. This issue also reproduces for Blob Containers/ Queues/ Tables.
2. The emulator blob/ queue/ table cannot be searched.

**Comment by MRayermannMSFT** [comment]
I inadvertently disabled this when I marked emulator nodes as not supporting deep search. I did that because we didn't want  emulator nodes to be explored during search, as it could cause the "emulator not started" dialog from popping up. Leaving "search from here" while still preventing the exploration of emulator nodes during search isn't going to be trivial. So for now we're going to mark this regression as be designed.
