### ISSUE TITLE
An info bar prompts when opening/creating an emulator table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5128]
**Storage Explorer Version:** 1.22.0-dev
**Build Number:** 20211102.2
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6
**Architecture:** ia32\x64
**Emulator Version:** Azurite 3.14.3
**How Found:** From running test cases
**Regression From:** Previous release (1.21.3)

## Steps to Reproduce ## 

1. Install and run Azurite 3.14.3 -> Launch Storage Explorer.
2. Expand 'Local & Attached -> Storage Accounts -> (Emulator - Default Ports)(Key)' -> Tables.
3. Create a table -> Check whether no info bar prompts.

## Expected Experience ##
No info bar prompts.

## Actual Experience ##
An info bar ’Cannot connect to http://127.0.0.1:10002/devstoreaccount1/vfvr() while allowInsecureConnection is false‘ prompts.
![image](https://user-images.githubusercontent.com/87792676/139827134-9cd9fdfd-f0c6-4aba-926e-3c604f3a9782.png)

**Comment by craxal** [comment]
@v-kellyluo Looks like this is due to some differences in the table SDK vs the other SDKs. We have to explicitly allow HTTP connections when creating the client object.

Please note that, while testing a fix, the timestamps for entities in an Azurite table will look like "[object Object]". This is due to a bug in the SDK (Azure/azure-sdk-for-js#18543), so I need to wait on a fix before I can progress further on this issue.

**Comment by craxal** [comment]
@joheredi determined this to be a bug in Azurite and filed Azure/Azurite#1162.

**Comment by v-xianya** [comment]
Verified on the main build 20211116.4. Fixed.
