### ISSUE TITLE
Can't access containers after upgrade due to "Cannot read property 'DeletedTime' of undefined"

### ISSUE THREAD

**Issue by MisterDoug99** [microsoft/AzureStorageExplorer#5131]
After upgrading to 1.21.3, clicking on some containers displays "Cannot read property 'DeletedTime' of undefined" and won't show any folders in the container.

**Comment by MRayermannMSFT** [comment]
@MisterDoug99 do you know if these containers are in an ADLS Gen2 account? If they are then you would see (ADLS Gen2) next to the account node:
![image](https://user-images.githubusercontent.com/21112697/140799829-d285f37e-1b79-468b-b870-e94dc81c1093.png)
Or if you have attached the container you would see that next to the name of the container itself.

**Comment by MisterDoug99** [comment]
Yes, they are in an ADLS Gen2 account.

**Comment by JasonYeMSFT** [comment]
The Properties field is missing in the list response. I will relax the code that access that field optionally.

**Comment by JasonYeMSFT** [comment]
We have released 1.22.0 which includes the fix to this bug.

**Comment by pwehland** [comment]
This repro's on 1.25.1

**Comment by JasonYeMSFT** [comment]
@pwehland We were told that the service issue was fixed in a previous major release except for pre-prod storage accounts. Are you using a pre-prod storage account? We are heavily relying on the service to return us the properties of the blobs/directories otherwise quite a few features won't work in Storage Explorer. If you can capture a Fiddler trace demonstrating the fact that the service is not returning the properties correctly, we can create a support ticket to the service team to investigate.

Here is instructions on how to get a fiddler trace https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2204#network-logs
