### ISSUE TITLE
User mode installer

### ISSUE THREAD

**Issue by roxxette** [microsoft/AzureStorageExplorer#5133]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Install without admin

### Desired Solution

Need user mode installer

### Additional Context

I don't think it's mandatory for admin permission. I transferred everything in 'C:\Program Files (x86)\Microsoft Azure Storage Explorer' and it to a new vm. Seems ASE works fine without installation.

**Comment by MRayermannMSFT** [comment]
@roxxette the first time you install you should be offered the option to do a user or admin install. However if you have already installed as admin you will no longer get that choice. In order to see the choice again you will need to run uins000.exe in 'C:\Program Files (x86)\Microsoft Azure Storage Explorer' and then reinstall using the installer from https://storageexplorer.com . Let us know if you don't see the choice appear after that.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you have any further questions on how to install in user-mode please open a new issue.
