### ISSUE TITLE
Can't upload files

### ISSUE THREAD

**Issue by kmitchell64** [microsoft/AzureStorageExplorer#5146]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Regression From

1.21.3

### Architecture

x64

### Storage Explorer Build Number

1.21.3

### Platform

Windows

### Bug Description

Unable to upload files or folders.  Bel;ow is the error that I am getting. I'll attachj the log file also
{
  "message": "\"UnexpectedCancel\""
[cityofneedles survey logfile.txt](https://github.com/microsoft/AzureStorageExplorer/files/7488400/cityofneedles.survey.logfile.txt)

}

### Steps to Reproduce

1> Launch Storage explorer
2.  Select Blob
3. Click upload button
4. Select file 
5. Upload file
6. Then I get the error message after 3 seconds Unexpected Cancel
7. This file needs to be submitted by 11/8/2021

### Actual Experience

File I upload doesn't upload and I get an error message

### Expected Experience

That I should be able to upload file and it would be tranferred to the right company

### Additional Context

None

**Comment by MRayermannMSFT** [comment]
@kmitchell64 apologies for the unhelpful error, this is something we're working with the AzCopy team on to improve.

For your specific issue though it looks like:

- You have signed in and are either accessing your container from beneath a subscription or you attached the container directly using Azure AD
- You are relying on Azure AD/RBAC permissions to perform the upload
- AzCopy is failing to perform the upload because you are lacking read permissions

Therefore can you:

1. Go to the Azure portal and check what permissions you have on the container. You can do this by navigating to the container or storage account, going to the IAM blade, and then entering your name/username into the Find section under Check access:
![image](https://user-images.githubusercontent.com/21112697/140799098-3698f262-3f34-4487-9916-7fe61ce7cf63.png)
Once you have confirmed what roles you have, please share the list with us and we can help you determine what you are missing.

2. You can try uploading your file via the Azure portal.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still facing this issue, we recommend opening a support ticket via the Azure Portal.
