### ISSUE TITLE
Able to access pinned storage blobs even after Azure PIM (at a resource group level) expires

### ISSUE THREAD

**Issue by karthikrao-microsoft** [microsoft/AzureStorageExplorer#5152]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.21.3

### Architecture

x64

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I am able to continue accessing storage blobs pinned to quick access even after my Azure PIM (Privileged Identity Management) access to the resource group containing such blobs has expired. 

### Steps to Reproduce

1. Configure and Activate Azure PIM at a resource group level.
2. Access any storage blob under the activated resource group and corresponding storage account by using the tree view in Storage Explorer.
3. Pin the above accessed storage blob.
4. Wait for PIM access to expire/timeout.
5. Use the pinned tab in Storage Explorer to double click the pinned storage blob.
6. The blob opens up as expected on the right.
7. Further file/folder operations go through successfully without raising concerns about the PIM having been expired.

### Actual Experience

If the user's Azure PIM access for a given resource group expires, pinned storage blobs in Storage Explorer under storage accounts for that resource group continue to be fully read/write accessible. 

### Expected Experience

If the user's Azure PIM access for a given resource group expires, pinned storage blobs in Storage Explorer under storage accounts for that resource group should be inaccessible and hidden from the user view. 

The experience should be similar to the scenario wherein the user tries to access these blobs if they had not been pinned, i.e., by navigating down the subscription tree view. In such cases, the storage accounts under PIM expired resource groups are not visible by default and the user cannot further interact with it. 

If the user re-activates PIM for a specific resource group, the pinned storage blobs under that resource group should be accessible and visible as expected.

**Comment by MRayermannMSFT** [comment]
@karthikrao-microsoft based on your description, it is likely that the temporary access you were granted included the ability to list storage account keys. When you pinned the container to quick access the keys, Storage Explorer saved those keys as the credentials to use in order to "quickly access" the container. After your temporary access expired, those keys were still valid, and therefore the quick access entry still worked.

Having quick access attachments not directly save the keys is something on our backlog, but ultimately it will not solve the real underlying security issue with the temporary access you were given! **Giving people access to the keys for a storage account is not temporary unless you rotate the keys after revoking their access.** Therefore we recommend the following:

- If possible, do not give list keys permissions when giving someone temporary access to a storage resource. Instead use RBAC/Azure AD backed permissions. Such permissions are checked on the server and are much easier to grant & revoke on a per user basis.
- If not possible to do the first bullet, then make sure to rotate your account keys after revoking the temporary access.
- If not possible to do the first bullet, consider using SAS tokens to grant temporary access. Using SAS tokens will allow you to specifically time-box the access, or if you generate the SAS with an access policy, you can immediately revoke the SAS by deleting the policy.

**Comment by karthikrao-microsoft** [comment]
@MRayermannMSFT Thanks for clearing that up! It makes much more sense to me now. Thanks for the recommendations as well - got me curious enough to explore all the options.
