### ISSUE TITLE
Expired token won

### ISSUE THREAD

**Issue by mrcatfish** [microsoft/AzureStorageExplorer#5172]

**Comment by MRayermannMSFT** [comment]
@mrcatfish can you please provide any additional info? Are you seeing any errors? What version of Storage Explorer are you using?

**Comment by mrcatfish** [comment]
Was using the very latest versionn 1.21.3.  I believe you can do all you
need now in the Azure Portal?  Prior to updating this, it had worked in the
past, but admittedly I had not used it in at least 90 days.  I looked for
about an hour and found nothing on how to force this to get a new toke, so
I just gave up.

**Comment by MRayermannMSFT** [comment]
@mrcatfish yes, there are multiple ways for you to manage and access your storage, include the portal! However, Storage Explorer will have better upload/download performance versus the portal. Something to consider if you ever need to upload very large amounts of data.

Since you gave up though, I'll go ahead and close this, but if you ever need to use Storage Explorer again feel free to open a new issue and we'll help you out. Have a good day!
