### ISSUE TITLE
Double-click should resize data grid column to fit contents

### ISSUE THREAD

**Issue by OzBob** [microsoft/AzureStorageExplorer#5199]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

resizing column in Queue window does not reduce in size after it has been dragged to be very big

### Desired Solution

double click => maximise width; dblclick when max => shrink to 'default' size.

### Additional Context

#4508

**Comment by MRayermannMSFT** [comment]
@OzBob thanks for sharing this feedback. We agree that the resizing columns behavior can be fairly wonky at times. Unfortunately the core of our column resizing behavior belongs to the data table library we are using and it is not going to be feasible for us to address your feature request with that library. We are in the process of investigating alternative libraries, and we will take your feature request into account when evaluating our options.

**Comment by craxal** [comment]
This should be done for all other data grids.

**Comment by craxal** [comment]
With some testing, I've found that getting accurate measurements from an initial rendering is difficult if the column width isn't known beforehand. We could just render all columns, but this can have performance problems if the data grid has a lot of columns. We solved the performance problem early on by only rendering columns that are visible. We insert leading and trailing regions with the same width as the unrendered columns to preserve natural scrolling behavior as though the columns were rendered. But we need an accurate measure of the columns widths to get the proper widths for these blank regions, which we can only get if we either render the columns (which gets expensive) or we know the width of the column ahead of time (which we don't have if the size is determined by the contents). This, of course, is problematic for content-fitting column sizes, because we won't know the column's width until it's rendered.

I have a few ideas for working around these issues:
* Internally keep track of the known column widths. Column widths are initialized with fixed columns widths. This will be updated after each render pass.
* Initially render a fixed number of columns. This number can be a constant or can be calculated by taking the available width of the view and dividing it by the default column size.
* Subsequent renders should become more efficient as the user scrolls and more column widths are updated.
* There may still be some error in calculating the column widths and the blank area, but the internal tracking should help minimize that.
* Calculating column widths will require refs to all cells, and max calculations for each column.

**Comment by craxal** [comment]
I found a much simpler approach, which has been implemented. Auto-sizing only really needs to be applied when double-clicking the column sizer. So, when that happens, we can briefly construct a "probe" element containing the column being resized and attach it to the DOM. Its width becomes the column's new width, and we proceed with resizing as normal.
