### ISSUE TITLE
Unable to retrieve child resources

### ISSUE THREAD

**Issue by crewpay** [microsoft/AzureStorageExplorer#5224]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.19.0, 1.21.3

### Regression From

1.19.0

### Architecture

i86

### Storage Explorer Build Number

20211020.2

### Platform

Windows

### OS Version

windows 10

### Bug Description

When trying to open Tables under any storage account, I am getting the below error. This was working fine as of a few days ago and no updates were made to Azure Tables until I tried the latest version and trying to revert back to 19.

Unable to retrieve child resources.

Details:
unable to get local issuer certificate

### Steps to Reproduce

1. Launch Azure Storage Explorer
2. Open Storage Container
3. Click on Tables to expand (or try refresh)
4. Receive "Unable to Retrieve Child Resources" message

### Actual Experience

Error details message pops up with these details:

Unable to retrieve child resources.

Details:
unable to get local issuer certificate

### Expected Experience

A list of Tables should be provided in the UI

### Additional Context

None, azure tables are not returned

**Comment by MRayermannMSFT** [comment]
@crewpay this issue is almost certainly caused by a change in your networking situation. Something is injecting a not-common SSL certificate into the web requests your machine is making. This could be software running on your machine, or off your machine. Examples include proxy and anti virus software.

We've been making some headway on making this a non-issue, but unfortunately that work has not quite yet reached tables (though hopefully it will later this month 🤞). Until then, I'll have to point you to our troubleshooting guide. Please given that a look and see if it can be of any help for now: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#ssl-certificate-issues

**Comment by crewpay** [comment]
@MRayermannMSFT thank you for your reply. I reviewed the documentation and tried reinstalling several times, going through some of the fiddler steps in the document, etc. and nothing worked. I perfomed the steps to configure Fiddler .CER and that didn't work. Oddly though, I installed previously generated .CER file that I was using for some Visual Studio development into the tool and everything started working again. No idea what happened and the .CER that I installed isn't remotely related to one of my environments, but happy to report that they are both working again. Anyway, I wanted to provide in case it helps you with these issues and will provide more details if it helps you. Thanks again for your assistance, Michael

**Comment by novotechsoftware** [comment]
@MRayermannMSFT I am receiving the same error message today. I don't use my account every day so not sure when this started. Nothing has changed and I can't even do a backup from SQL. Once I select the BLOB it just exits on the SQL window (in Azure storage explorer I get the same error as the OP)
