### ISSUE TITLE
There is an error 'AuthorizationPermissionMismatch' when updating one entity under an attached table (SAS permissions 'Query, Update')

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5333]
**Storage Explorer Version**: 1.22.1
**Build Number**: 20220113.2
**Branch**: hotfix/1.22.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.21.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create one table -> Add one entity.
3. Right click the table -> Click 'Get Shared Access Signature...'.
4. Select 'Query & Update' permissions -> Create the SAS URL -> Copy the URL.
5. Attach the table using the copied URL.
6. Go to the attached table -> Click 'Edit' on the toolbar -> Click 'Update' on the Edit Entity dialog.
7. Check there is no error.

## Expected Experience ##
There is no error.

## Actual Experience ##
There is an error indicating 'AuthorizationPermissionMismatch'.
![image](https://user-images.githubusercontent.com/41351993/149473613-68dca000-81c0-4942-9f8c-6169ec5770d3.png)

## Additional Context ##
This issue also reproduces for one table which is attached by the SAS URL (generated via access policy).

**Comment by craxal** [comment]
According to the [Azure documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#permissions-for-a-table), both Add and Update permissions are required for "upsert" operations (updates an existing entity or adds a new entity if it doesn't already exist). We are using upsert for editing entities, which is why the operation doesn't work in this case. We can fix that by switching to explicit update operations, since we already know we are editing an existing entity.

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220114.4. Fixed.
