### ISSUE TITLE
There is a duplicate item when clicking the item on the address bar back to its parent folder with running a valid search in the file share explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5339]
**Storage Explorer Version**: 1.22.1
**Build Number**: 20220114.4
**Branch**: hotfix/1.22.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Big Sur 11.6.1
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Create a folder name 'New Folder'-> Upload a file to the folder.
3. Type the first character of the file name to the 'Search by prefix' field.
4. Click the folder name on the address bar -> Click the file share name on the address bar.
5. Check there is no duplicate folder.

## Expected Experience ##
There is no duplicate folder.

## Actual Experience ##
There is a duplicate folder.

Here is the record:
![issue](https://user-images.githubusercontent.com/41351993/149734942-2a80bc87-0100-4439-a12a-8d1c0619f959.gif)

## Additional Context ##
1. This issue can't be reproduced consistently.
2. The duplicate item disappears after manually refreshing.

**Comment by JasonYeMSFT** [comment]
The problem is caused by a race condition in our existing data table implementation. Theoretically all existing data tables may run into this problem but the chances are low and they can all be mitigated by perform an additional refresh. I am currently working on a data table component to replace the existing implementations and this problem will be addressed there.
