### ISSUE TITLE
Azure Storage Explorer - Issue in Delete  Blob

### ISSUE THREAD

**Issue by Jigar191089** [microsoft/AzureStorageExplorer#5399]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.22.1

### Architecture

i86

### Storage Explorer Build Number

20220122.3

### Platform

Windows

### OS Version

Windows 10

### Bug Description

when I am trying to delete a blob in ADLS gen 2,although the blob is getting deleted in the activites tab is showing as 0 completed
[Uploading azure storage explorer delete issue.docx…]()

### Steps to Reproduce

1. launch the explorer
2. attempt to delete the blob from one of the container

### Actual Experience

in the activites tab it is shown '0 completed'

### Expected Experience

in the activities tab it should be shown '1 completed successfully'

**Comment by Jigar191089** [comment]
[azure storage explorer delete issue.docx](https://github.com/microsoft/AzureStorageExplorer/files/8022127/azure.storage.explorer.delete.issue.docx)

**Comment by Jigar191089** [comment]
@MRayermannMSFT I have attached the broken link, can you please check

**Comment by MRayermannMSFT** [comment]
@Jigar191089 can you share the AzCopy log with us from that delete? The AzCopy log files can be found in `<your home directory>/.azcopy/logs`. From your screenshot the delete happened on Feb 3 2022, so you'll want to find the log file from around there. Thanks.

**Comment by Jigar191089** [comment]
I don't have the log for Feb 3, so I recreated the issue and sending the log for that.
[azcopy_log.zip](https://github.com/microsoft/AzureStorageExplorer/files/8065565/azcopy_log.zip)

**Comment by JasonYeMSFT** [comment]
From the log a blob named "jigar/Temp/t123" is detected and deleted in container "dev" and it is successful. Is that correct? 

There are two possible explanations for the screenshots. One is that the delete actually works but the result is presented incorrectly. The other one is that something has externally deleted the directory and when AzCopy tries too delete it, it sees nothing and thus report a failure. If you can consistently repro this issue, it can only be the first case then. I would recommend retrying the operation with just AzCopy in the command line and check its output. Please add --output-type=json when running the AzCopy command since we are listening to the json output to determine the result of AzCopy jobs.

**Comment by Jigar191089** [comment]
HI @JasonYeMSFT it is the fist case only. Also I don't know how to execute AzCopy in command line. If you agree then we can have a call for this issue. Since this issue is not solved even after uninstalling and installing again

**Comment by Jigar191089** [comment]
issue resolved with latest version 1.23.0
