### ISSUE TITLE
"Clone" should allow a destination outside the source's directory

### ISSUE THREAD

**Issue by fgaonet** [microsoft/AzureStorageExplorer#5509]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

i86

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows 10

### Bug Description

I realized the "Copy" replaced by "Clone". As the description on popups, "Cloning works by copying to a new location." However, the "New name" box said "Name must not be empty or containing slashes". I wonder how to enter a folder name or container name to a new location?

I have tried to use ">" instead of "/", but it only changes the blob name and still in the same location.

Is it a bug??

### Steps to Reproduce

1. create a container with name of "container1".
2. upload a file "blob1" into "container1".
3. Try to clone "blob1" to a folder "folder1".
4. What name should be entered into the "New name" box?

### Actual Experience

Whatever you entered, the new "cloned" blob is still in the original location.

### Expected Experience

I expect "blob1" in "folder1", i.e. folder1/blob1, if show blobs in container with Flat mode.

**Comment by JasonYeMSFT** [comment]
"Clone" replaces "rename", not "copy". Are you saying that you want to move "blob1" to be in a sibling folder "folder1" so that it ends up being "folder1/blob1"? If that's the case, you can right click "blob1", choose "copy", open "folder1" and "paste" there. This should be very similar to how to copy paste files in the file explorer.

**Comment by fgaonet** [comment]
Thank you for the explanation! You are right on remote Azure storage. I just realized the “copy”, “paste” functions still there.

However, there are no such buttons on my local emulator blob containers. I tried right-clicking the “blob1” which is in my local emulator blob container, but cannot find “copy” “paste” options on the popup menu. How do I move a blob in a folder in local emulator?

By the way, I am still confused with the description on the Clone popup, “Cloning works by copying to a new location”. What does “new location” mean?

Frank

**Comment by JasonYeMSFT** [comment]
Copy and Paste aren't supported by our emulator related code because we don't have the implementation to tell if the copied blobs can be visible from the destination. As of today, clone's destination is limited to the same directory the source blob is in. I can update the title to turn this issue into a feature request.

**Comment by JasonYeMSFT** [comment]
This is totally except that it will significantly complicate validation on the new blob name.

**Comment by richardMSFT** [comment]
This feature will be shipping with 1.29.0.
