### ISSUE TITLE
Fail to import one .csv file in one SAS attached table with permissions 'Query, Add'

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#5544]
**Storage Explorer Version:** 1.24.0-dev
**Build Number:** 20220322.15
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.1 (Apple M1 Pro)
**Architecture:** ia32\x64
**How Found:** Ad-hoc testing
**Regression From:** Previous release (1.22.1)

## Steps to Reproduce ##

1. Expand one storage account -> Tables -> Create a table.
2. Right click the table -> Click 'Get Shared Access Signature...'.
3. Select 'Query, Add' permissions -> Create the SAS URL and copy it.
4. Attach the table using the SAS URL.
5. Go to the attached table -> Try to import one .csv file.
6. Check whether succeeds to import the file.

## Expected Experience ##

Succeed to import the file.

## Actual Experience ##
Fail to import the file.
![image](https://user-images.githubusercontent.com/87792676/159649021-d55a7df7-968f-4239-b8e4-c0624d006c84.png)

**Comment by craxal** [comment]
@v-kellyluo This is by design. You have to have Update permissions for the SAS as well. This is by design. If you didn't have Update permissions, we'd be limited to insert operations, and insertion throws an error if the entity you're trying to insert already exists. We had customers complain about this when their import files contained entities that already exist in the table.

For comparison, you may choose to verify this by attempting to import a CSV file that contains one or more entities that already exist in the table. Recent versions of Storage Explorer will throw an error, but they should succeed in current versions.
