### ISSUE TITLE
Storage Explorer from Server share to Blob container failed instantly all of a sudden

### ISSUE THREAD

**Issue by cassini1212** [microsoft/AzureStorageExplorer#5568]
hi and thank you! I have been migrating some data from server with storage explorer to our new blob containers in azure. It was a bit tricky at first since our shares have mapped drive location such as F:\data rather than just data  but it seemed to move the data so I was happy. Now I am trying to move data and i get an instant "unexpected Quit (used SDS, discovery not completed)  

 Any ideas why I would get this all of a sudden,  and also very important ask;

If I want to move SHARE A and ALL subfolders under this from onprem windows server to Azure Blob Container instead of only one single folder at a time, how can I do this?? 

THANK YOU! in advance for any help

**Comment by JasonYeMSFT** [comment]
The error message means AzCopy exited without returning a known response to us. That usually happens if the underlying AzCopy process crashed. I would recommend you get a detailed AzCopy log file for your data transfer so we can investigate what goes wrong.

In Storage Explorer app menu, open Edit -> Settings, in the Transfers page, set AzCopy log level to Debug (the highest possible one).

![image](https://user-images.githubusercontent.com/39359541/160712371-5704bbbd-3fac-46be-9ea8-4f6fba936c84.png)

![image](https://user-images.githubusercontent.com/39359541/160712338-45139e31-1fcf-4c4d-8864-598eca4bb84b.png)

Then open Storage Explorer and try to reproduce the transfer problem with a subset of your data. Ideally the smaller dataset you have in the reproduction, the easier it will be to figure out what goes wrong. Once the error occurs again, you can go to the logs directory and get the most recent log file. You can share it with us here so we can take a look at it.

If you cannot see the AzCopy log file, it means AzCopy might not even be able to start. Another option is to download an AzCopy command line executable and execute a command for your data transfer. The command line tool will print all the runtime exceptions to your terminal.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still having this problem we recommend opening an Azure support ticket. Alternatively you can open a new issue here.
