### ISSUE TITLE
Wrong row in Tree is selected after deleting a table

### ISSUE THREAD

**Issue by RickDMyers** [microsoft/AzureStorageExplorer#5615]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Regression From

no

### Architecture

x64

### Storage Explorer Build Number

 20220223.14 

### Platform

macOS

### OS Version

macOS Monterey

### Bug Description

Select a table to delete in the tree and delete it. 

The tree is refreshed, but the next table in the list is not selected.  Selection is seems to be random. Sometimes a different storage account is displayed and active element is some other table.  Also seen it position to a blob.  I'm not sure what's directing where it returns.

I was expecting that if the you have list of TABLES, that the table underneath the deleted table would become active.  Much like what happens in Windows Explorer.   

### Steps to Reproduce

1. Launch Explorer
2. Make sure Explorer has many storage accounts list in the TREEE.
3. Expand "TABLE" under a storage account and delete a TABLE.

Verify the active row in the tree is still positioned so some element under TABLE.

### Actual Experience

<img width="615" alt="image" src="https://user-images.githubusercontent.com/7906441/163007327-041c7331-f7a6-4e21-b040-465b806d4c0e.png">

Right click and delete "DeleteMeToo"

<img width="510" alt="image" src="https://user-images.githubusercontent.com/7906441/163007572-e5d4654b-81ae-41d8-a9b3-7da1f450d3fd.png">

System this time, jumped to the Emulator blob directory.

### Expected Experience

Expected the next table in the list "ProjectChange" would have been selected.

### Additional Context

None.  

Really have been unable to determine where it will  jump.  I get different results.

**Comment by MRayermannMSFT** [comment]
@RickDMyers what other tabs did you have open at the time you did the delete? The behavior should be:
1. Table is deleted
2. Node is removed

From here the's a couple of possibilities:

1. If there was a tab opened with an explorer for the deleted node and other tabs exist -> that explorer is closed, next tab in the list is switched to -> if that tab is for an explorer, the node associated with that explorer is focused, otherwise the parent of the deleted node is focused
2. If there was a tab opened with an explorer for the deleted node but no other tabs  exist -> that explorer is closed ->  the parent of the deleted node is focused
3. If there was not an explorer for the deleted node -> the parent of the deleted node is focused

So for your situation, I'm guessing you were in situation 1. That is you deleted your table, it was deleted, Storage Explorer changed the active tab to the explorer for rick-test, and then the rick-test node was focused. Can you confirm if this was the case?

Assuming that was the case, this is currently by design. Feel free to let us know more about your thoughts on this. One thing that would be helpful is if you could elaborate on why you want the behavior to be different. Thanks!
