### ISSUE TITLE
Add native Apple Silicon support (native darwin_arm64 binary)

### ISSUE THREAD

**Issue by AdamCoulterOz** [microsoft/AzureStorageExplorer#5616]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I'm forced to install rosetta 2 compatibility to support the storage explorer on a Mac running Apple Silicon

### Desired Solution

Have the Storage Explorer for Mac compiled for native darwin_arm64 architecture

### Alternatives and Workarounds

I can continue to use rosetta 2, but all my other programs are native already

**Comment by MRayermannMSFT** [comment]
Hi @AdamCoulterOz thanks for raising this issue! You are the first person we've had ask us to support Apple Silicon/macOS ARM64 natively.

While we could get the Electron portion of Storage Explorer built against macOS ARM64 pretty quickly, there's a couple of native dependencies we have which would also need to complete the work first.

We've had talks with those dependencies before, and right now they/we are just waiting on more requests like yours before we can prioritize the work. So thank you again for opening this issue. We'll keep an eye on it for hopefully more people to thumbs up/comment. We appreciate your patience.

**Comment by Slyrc** [comment]
+1 arm64 build would be awesome 🙏🏼

**Comment by StanUpply** [comment]
It would be great if you add native arm64 support :)

**Comment by MRayermannMSFT** [comment]
@Slyrc @StanUpply @AdamCoulterOz and all others interested in this, right now the biggest blocker is probably going to be AzCopy. As long as they aren't shipping a native or universal binary you will need Rosetta 2 when running Storage Explorer. I recommend y'all go make your voices heard with them.

You can do so by:

- Opening an issue here: https://github.com/Azure/azure-storage-azcopy/issues
- Sending feedback via the portal: 
![image](https://user-images.githubusercontent.com/21112697/169922561-5261ecfa-e6ee-443e-b410-8b8cd05c5bd1.png)
- Sending feedback via any other channels you normally use with Azure.

Also, if you can:

- Elaborate on why it is annoying to have to install Rosetta 2
- Give other reasons for wanting Storage Explorer/AzCopy to target Apple Silicon natively beyond it being annoying to install Rosetta 2

Both here and when you give feedback to AzCopy, that would be very helpful.

**Comment by Slyrc** [comment]
It looks like there is already a native version for AzCopy:

![image](https://user-images.githubusercontent.com/62191325/169974270-69f7ab09-7bba-4608-ac08-4c847a8cb687.png)

![image](https://user-images.githubusercontent.com/62191325/169974406-f53e675d-0c31-4774-a5d1-b22b5494d73c.png)

[https://formulae.brew.sh/formula/azcopy](https://formulae.brew.sh/formula/azcopy)

Are there any other dependencies which are blocking the StorageExplorer?

**Comment by MRayermannMSFT** [comment]
> It looks like there is already a native version for AzCopy:

Whatever that is, it is not an official release of AzCopy v10. The official bits can be found here:

<img width="338" alt="image" src="https://user-images.githubusercontent.com/21112697/170083091-c9ddd5df-31e2-4036-ad03-923a920664c4.png">

**Comment by Wicked-Weasel** [comment]
I am also eagerly awaiting an AS / Universal version here. Support will stop at some point down the line for future macOS for anything other than AS Native (and obviously universal) apps so makes sense to tackle this one sooner rather than later. Appreciate it relies on other elements here but the key aspect of AZCopy has already got a head start. Guess it just needs more of us to raise awareness of the requirement...

**Comment by ppanyukov** [comment]
The reason to have ARM64 version is Rosetta version is incredibly laggy and slow on Apple M1. It's so laggy it's almost unusable. I had to dig out my Intel Mac just to use the explorer.

**Comment by ramzzzay** [comment]
I'm here to say: we are all waiting for m1 native version of Azure Storage Explorer. Right now it really very laggy. Let's cross fingers for faster az-copy m1 arm64 release. :)

**Comment by louisoftokyo** [comment]
Adding my voice to this request. I like Storage Explorer but it's a pain to use at the moment on my Mac.

**Comment by RFdeGroot** [comment]
+1 to this request

**Comment by MRayermannMSFT** [comment]
Thank you @AdamCoulterOz @Slyrc @StanUpply @Wicked-Weasel @ppanyukov @ramzzzay @louistokyo @RFdeGroot (and anyone else who I may have missed 😬, sorry if so!) for passing along feedback to the AzCopy team.

We recently met with the AzCopy team and because of y'all's feedbac, they are now convinced of the need to get an official AzCopy for macOS ARM64 build. 🥳

They will first provide us with a preview build in the near future, which we will ship as part of a "Storage Explorer for macOS ARM64 preview". We'll put that out there for y'all to get feedback on. Then, sometime in the more distant, yet still relatively near future, the AzCopy team will be figuring out a way to get a non-preview version of AzCopy for macos ARM64 available, at which point we can ship a non-preview as well.

While I'm not hardcore promising any dates here, I do want y'all to know that progress has definitely been made towards closing this issue as "merged" a reality. Thanks again for staying engaged!

**Comment by MRayermannMSFT** [comment]
As an FYI to everyone, today we shipped version 1.28.0 of Storage Explorer. With this release we have a macOS ARM64 preview build. We had to do a preview because unfortunately we were not able to get an AzCopy macOS ARM64 build in time for this release, however they are working on it. Once we have that we will move towards making our macOS ARM64 build GA. Thanks for the continued patience. If you'd like to try the preview you can download it here: https://aka.ms/storageexplorer/downloadmacosarm64

**Comment by Slyrc** [comment]
> As an FYI to everyone, today we shipped version 1.28.0 of Storage Explorer. With this release we have a macOS ARM64 preview build. We had to do a preview because unfortunately we were not able to get an AzCopy macOS ARM64 build in time for this release, however they are working on it. Once we have that we will move towards making our macOS ARM64 build GA. Thanks for the continued patience. If you'd like to try the preview you can download it here: https://aka.ms/storageexplorer/downloadmacosarm64

I just tried it today. This version just perfect. Now startup is almost instant. I love it. Thank you for your efforts!

**Comment by ramzzzay** [comment]
> As an FYI to everyone, today we shipped version 1.28.0 of Storage Explorer. With this release we have a macOS ARM64 preview build. We had to do a preview because unfortunately we were not able to get an AzCopy macOS ARM64 build in time for this release, however they are working on it. Once we have that we will move towards making our macOS ARM64 build GA. Thanks for the continued patience. If you'd like to try the preview you can download it here: https://aka.ms/storageexplorer/downloadmacosarm64

Feels x10 times faster then x86 version on m1 pro 16/512. Thanks!

**Comment by MRayermannMSFT** [comment]
FYI, today we shipped update 1.28.1. Everyone using the 1.28.0 arm64 preview should get the update. Please let us know if you do not get an update notification. Thanks!

**Comment by MikeNicholls** [comment]
It looks like 1.28.1 is not yet using an ARM64 version of azcopy, so it will fail to work properly unless Rosetta is installed.

**Comment by MRayermannMSFT** [comment]
> It looks like 1.28.1 is not yet using an ARM64 version of azcopy, so it will fail to work properly unless Rosetta is installed.

Yes. As mentioned [here](https://github.com/microsoft/AzureStorageExplorer/issues/5616#issuecomment-1430499877) and [here](https://github.com/microsoft/AzureStorageExplorer/releases#:~:text=All%20binaries%20and%20executables%20other%20than%20AzCopy%20now%20natively%20target%20ARM64.), AzCopy is still not ARM64.

**Comment by MRayermannMSFT** [comment]
As an FYI, while the macOS ARM64 version Storage Explorer 1.30.0 will still be preview, **it will contain an ARM64 AzCopy binary**. This should hopefully mean moving the macOS ARM64 version out of preview in the very near future. Thanks to all for the continued patience.

**Comment by MRayermannMSFT** [comment]
AzCopy has GA'd their macOS ARM64 support: https://github.com/Azure/azure-storage-azcopy/releases/tag/v10.20.0#:~:text=New%20Features-,Mac%20M1/M2%20Support,-Force%20small%20blobs

😁😁😁😁
