### ISSUE TITLE
Minor glitch on Azure Tables export count

### ISSUE THREAD

**Issue by JCKodel** [microsoft/AzureStorageExplorer#5636]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.0

### Architecture

ia32

### Storage Explorer Build Number

20220223.14

### Platform

Windows

### OS Version

Windows 10

### Bug Description

![image](https://user-images.githubusercontent.com/379339/163848562-fbb4ee2f-f268-4535-800b-8dfef00b3ee2.png)

Minor count issue when exporting an entire table (5,882,334 of 5,881,930 entities exported).

### Steps to Reproduce

1. Export a table (in my scenario, a very old and highly populated one (5.8 million rows))
2. Check the conclusion message

### Actual Experience

Count is wrong (more rows were exported than reported as existent).
Not sure which one is wrong.

**Comment by craxal** [comment]
@JCKodel Don't treat the counts as an accurate measurement. Technically, neither is right or wrong. But the first number is likely more accurate.

Table export occurs in two phases. The first phase is the discovery phase, where we walk the table looking for property names. We need to know all the property names so we can write the CSV file correctly. While searching for properties, we count the number of entities so that we can report a reasonably accurate progress.

The second phase walks the table again to transform each entity to a CSV row.

If you have a large, active table (that is, multiple clients are accessing and manipulating the table data), the accuracy of the counts tends to degrade. It's highly probable that the count from the first phase is out of date when we're in the second phase, because someone else has added or deleted entities from the table.

Since counts shouldn't be treated as accurate measurements, we can consider matching up the numbers towards the end of the export in order to avoid further confusion.

**Comment by JCKodel** [comment]
Makes sense.
