### ISSUE TITLE
failed: 0 items transferred, error: UnexpectedQuit (used SAS, discovery not completed)

### ISSUE THREAD

**Issue by bedwards-abc** [microsoft/AzureStorageExplorer#5638]
Getting the above error when trying to copy from a Windows 2019 server to Azure storage via AZCopy. Can someone would one be able to assist with this? any help would be greatly appreciated!

**Comment by JasonYeMSFT** [comment]
Is there a "Copy AzCopy Command" action or a "Go to AzCopy Logs" action on the activity? If so, there are steps you can take to help us investigate:

- Get the azcopy log for the failed transfer and send it to us. You can send it to sehelp at microsoft dot com instead of posting it here.
- Download an AzCopy executable. Copy the AzCopy command and try directly invoking the AzCopy executable for the same transfer. The command line may be able to give error info that occurs before AzCopy starts logging. Share with us the console output.
