### ISSUE TITLE
There is no way to close the sign-in (authentication) panel on MacOS

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5668]
**Storage Explorer Version**: 1.24.0
**Build Number**: 20220427.2
**Branch**: rel/1.24.0
**Platform/OS**: MacOS Monterey 12.3 (Apple M1 Pro)
**Architecture** x64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Select 'Integrated Sign-in'.
2. Open the connect dialog -> Select 'Subscriptions -> Azure' -> Click 'Next'.
3. Enter one azure account -> Click 'Next'.
4. Observe the current panel-> Check whether there is a way to close the current sign-in panel.

## Expected Experience ##
There is a way to close the current sign-in panel.
![image](https://user-images.githubusercontent.com/41351993/165469137-2cffd11d-a00c-4ef1-86e2-d762655451fd.png)

## Actual Experience ##
There is no way to close the current sign-in panel.
![image](https://user-images.githubusercontent.com/41351993/165469005-0d7f817b-1227-41a8-a9ea-625158ad8a42.png)

**Comment by MRayermannMSFT** [comment]
For macOS, this is intentional. The window is a modal child of our app window. Therefore it is displayed as a "sheet". Sheets do not have the traffic light buttons.
https://www.electronjs.org/docs/latest/api/browser-window#:~:text=On%20macOS%20modal%20windows%20will%20be%20displayed%20as%20sheets%20attached%20to%20the%20parent%20window.
