### ISSUE TITLE
Using the snap version in Linux Mint: "Copy command and quit" in response to "service plug has not been connected yet" does not copy nor quit

### ISSUE THREAD

**Issue by milepost183** [microsoft/AzureStorageExplorer#5710]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.23.1

### Regression From

Unknown

### Architecture

x64

### Storage Explorer Build Number

Help->About does not work either

### Platform

Linux (snap)

### OS Version

Linux Mint 20.3 una

### Bug Description

When I launch the Explorer from the Linux Mint desktop, it produces the diagnostic shown in the attached .jpg file. Clicking on "Copy command and quit" does neither. Also, I can't scrape the command text from the graphic, so I'll have to type it in.
![DataExplorerDiagnostic](https://user-images.githubusercontent.com/32940732/167911780-0a041235-77d4-467c-9051-deab2bfa69e4.jpg)
 

### Steps to Reproduce

Install snap version of Data Explorer, add the app to the desktop, launch from desktop

### Actual Experience

A screen scrape is included in the Bug Description

### Expected Experience

I expected that a click on "Copy command and quit" would put the text of the required command into the copy/paste buffer and quit the app, but it didn't--Explorer continued its execution.

**Comment by JasonYeMSFT** [comment]
I was able to reproduce this problem in a Linux Mint VM. Based on my finding, the application eventually closes. However, since we have a few clean up logic to execute on quit, it may not immediately close and some initialization code can still have a chance to run after the button is clicked.

As for the clipboard issue, I believe it was due to the design of Linux Mint's clipboard manager. On linux, a traditional copy works by letting the source application declare that it owns something in the clipboard. When you paste, it calls to the system's clipboard manager and retrieves the actual data from the source application. As a result, if the source application is closed. The clipboard manager won't get any data. Other linux distributions (e.g. Ubuntu) uses a different implementation and allows simple data types like plain text to remain in the clipboard even if the source application has been closed. 

Unfortunately I don't think there is anything we can do for this problem right now. We added that button because we realized that the command cannot be selected/copied and it's hard to memorize the whole command. We will consider printing it in the terminal output to help you access the command in case the clipboard doesn't work.
