### ISSUE TITLE
The query builder is not opened when clicking 'Query' on the toolbar of one empty table

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5793]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220602.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture** ia32\x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.24.2)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a new table -> Click 'Query' on the table toolbar.
3. Check whether the query builder is opened.

## Expected Experience ##
The query builder is opened.
![image](https://user-images.githubusercontent.com/41351993/171569381-0083b11a-3c58-48f3-8002-a19bed79e237.png)

## Actual Experience ##
The query builder is not opened.
![0601](https://user-images.githubusercontent.com/41351993/171569266-129ca875-66b4-4cba-8962-a872cc419300.gif)

**Comment by craxal** [comment]
@v-xianya I am only able to reproduce this with a table that is empty. Can you verify if this still happens:
* With a non-empty table
* After at least one entity has been added or imported to an empty table
* After at least one entity has been added or imported and refreshing
* After at least one entity has been added or imported and opening a new tab

This due to the fact that the query builder is attempting to get some initial column information from the entities in the table, but because there are no entities, it's trying to access an empty list. That's weird that this is a regression, as the code more or less the same, and I would expect the query builder to still have this problem...

**Comment by v-xianya** [comment]
@craxal Hi Craig, 
Verified this issue on the build main 20220605.1. This issue still reproduces.

- With a non-empty table -> Not reproduce
- After at least one entity has been added or imported to an empty table -> Not reproduce
- After at least one entity has been added or imported and refreshing -> Not reproduce
- After at least one entity has been added or imported and opening a new tab -> Not reproduce

**Comment by v-xianya** [comment]
Verified this issue on the build main/20220608.1. Fixed. So close it.
