### ISSUE TITLE
1.4.0 upgrade removes local storage

### ISSUE THREAD

**Issue by OzBob** [Microsoft/AzureStorageExplorer#585]
**Storage Explorer Version**: 1.4.0
**Platform/OS Version**: Windows
**Architecture**: 32
**Regression From**: n-1

#### Steps to Reproduce: ####
1. Upgrade/Install 1.4.0
2. Local Storage Account has dissapeared.

#### Expected Experience: ####
Auto-add Emulators that were attached before the upgrade.

#### Actual Experience: ####
I've had Local storage (127.0.0.1) since version 0.x and now it's gone, I had to add it manually as if it's a brand new type of emulator.
1
Check local emulator:
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator>AzureStorageEmulator.exe status
Windows Azure Storage Emulator 5.6.0.0 command line tool
IsRunning: True
BlobEndpoint: http://127.0.0.1:10000/
QueueEndpoint: http://127.0.0.1:10001/
TableEndpoint: http://127.0.0.1:10002/

2 Open MAZExplorer, Right click on Local&Attached|'Storage Accounts', choose 'Azure Storage' (which is NOT intuitive) | choose 'Attach to a local emulator'.

**Comment by jinglouMSFT** [comment]
What you described above is actually an intentional design in 1.4.0 and on.  The new way to work with local emulators is to attach emulators from the connect dialog. This change lets you attach multiple emulators and customize what ports are used. Please see these docs here for more help: https://docs.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=macos#work-with-local-development-storage
