### ISSUE TITLE
Creating table in Azurite with Azure Storage Explorer

### ISSUE THREAD

**Issue by RashdaM** [microsoft/AzureStorageExplorer#5936]
Hi 
I am getting the following error when trying to create a Table Storage in Azurite using the Azure Storage Explorer

![azurite](https://user-images.githubusercontent.com/75433987/179226204-97c1a3d6-c5e4-4f2e-b202-8c21f7dee6c2.PNG)

**Comment by MRayermannMSFT** [comment]
@RashdaM Since you're using https with Azurite please either:
1. Try using system proxy (can be found under Settings (gear on the left hand side -> application -> proxy)
2. Following what this user did: https://github.com/microsoft/AzureStorageExplorer/issues/2598#issuecomment-616765993
3. Switch to using Azurite with http

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this problem we recommend opening a support ticket via the Azure Portal. Alternatively you can open a new issue here. Thanks.
