### ISSUE TITLE
The selected entities are not highlighted if using 'Select All' action

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#5958]
**Storage Explorer Version**: 1.25.0-dev
**Build Number**: 20220722.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.4 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.24.3)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Open one non-empty table -> Click 'Select All'.
3. Check whether the selected entities are highlighted.

## Expected Experience ##
The selected entities are highlighted.
![image](https://user-images.githubusercontent.com/41351993/180385537-e7179a66-05b1-4f57-b3fd-bd3a3be22bd0.png)

## Actual Experience ##
The selected entities are not highlighted.
![image](https://user-images.githubusercontent.com/41351993/180385575-9f807580-8a8e-4fdc-af2f-366a91a93b63.png)

**Comment by craxal** [comment]
@v-xianya Actually, all of the items are highlighted. The only difference is the table doesn't have focus. The color used for selected, unfocused items is different for selected, focused items. I don't think swapping focus to the table is a good idea, especially for keyboard users, because they usually want to perform some action on those items, but focusing on the table moves users away from the toolbar which contains those actions.

**Comment by JasonYeMSFT** [comment]
I need to check if this is due to us not setting the class on selection update.

**Comment by JasonYeMSFT** [comment]
The selection class name is updated correctly but the we are not initializing the state of "current active explorer" correctly.

**Comment by v-xianya** [comment]
Verified this issue on the build 20220725.1. Fixed. So, we close it.
