### ISSUE TITLE
All storage account keys deleted upon application restart

### ISSUE THREAD

**Issue by bakoontz2** [microsoft/AzureStorageExplorer#5962]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.24.3

### Architecture

x64

### Storage Explorer Build Number

22020617.2

### Platform

Windows

### Bug Description

All storage account keys are deleted upon restart.  Unable to reset keys without re-creating storage accounts.  Tried Help->Reset as pointed out in docs, does not seem to prompt for any type of re-authentication.  

If this is a user error, then the documentation is lacking as to exactly what to do here.

### Steps to Reproduce

1. Create a storage account using Key 1.
2. Ensure access to account.
3. Reboot machine.
4. Bring up Storage Explorer.  Key is now deleted.

### Actual Experience

Keys are delete upon restart.  "Logout on exit" is disabled.

### Expected Experience

I expect to be able to access the storage accounts that were set up in the previous session.

### Additional Context

I followed the instructions here to log in: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-sign-in Storage accounts are still inaccessible (without re-creating them).  This is the error message received:

Unable to retrieve child resources.

Details:
{
  "name": "Error",
  "message": "Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.",
  "stack": "Error: Unable to perform operation 'FileServiceClient.listSharesSegment'. No suitable credentials provided.\n    at FileServiceClient.runOperation

**Comment by MRayermannMSFT** [comment]
@bakoontz2 we have some clarifying questions for you:
1. When you say "Create a storage account using Key 1", does that mean you are going to the connect dialog in Storage Explorer and attaching a storage account? When I say connect dialog I am referring to this:
![image](https://user-images.githubusercontent.com/21112697/180840447-60645915-2730-49b4-85f8-c179fe2fe3c8.png)
2. Under additional context you say you followed the instructions on the sign in doc page. So are you trying to say that you also tried signing into Azure and then listing accounts under your subscription/s?
3. What leads you to believe the keys are deleted after you restart your computer and relaunch Storage Explorer?
4. Do you know what type of access you have to your storage accounts? Do you have permissions to list keys? Do you have any other RBAC roles?

**Comment by JasonYeMSFT** [comment]
The storage accounts under "Local & Attached" are the ones attached by entering the credentials (e.g. name and key) while the ones under subscription nodes are listed under your signed-in azure account. They are technically not duplicates since you can attached a storage account that is not under any of your subscriptions and they may be using different types of credentials.

I am not sure why we won't be able to get your storage account's key after restart. I am going to close this issue as mitigated since you can work with the attached storage account. If you would like to figure out why the storage account under subscription doesn't work, you can capture a network trace using Fiddler to see what happens to the List Keys request we make for your storage account. https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?tabs=Windows%2C2004#network-logs. Once we get such a log we can do some investigation to see what goes wrong.

**Comment by bakoontz2** [comment]
It's unclear from the documentation why I would have to sign in to access the accounts under "Local & Attached", or why even if I do sign in I'm unable to access certain accounts under the subscriptions.  There's something not quite syncing up here, and it's not very-well documented.

Nevertheless, I'm able to access using one of the two entries for storage accounts, so that will do for now.  When I get some time I'll try to do the trace you suggest and repost if I find anything significant.
