### ISSUE TITLE
Cancelled Classic Storage Table Export self-restarts

### ISSUE THREAD

**Issue by pilcherd** [microsoft/AzureStorageExplorer#6080]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.25.1

### Architecture

x64

### Storage Explorer Build Number

20220809.7

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I have some large Table Storage tables stored in older Classic Storage resources. Was trying to use ASE to Export All on these tables.  Connect, select Export All in the menu.  Sits taking hours checking properties so I cancel the export. Shows cancelled. Come back an hour or two later. They are running again!!! Cancel.  Come back in the morning, again running.

A cancelled download should not self-restart.

### Steps to Reproduce

Launch. 
Connect
Locate Classic Storage Table
Select Export All.  
Sits taking hours checking properties
cancel the export
Shows cancelled
Come back an hour or two later
They are running again

### Actual Experience

Self-restarts the cancelled table download process

### Expected Experience

Cancelled download should stay cancelled.

**Comment by JasonYeMSFT** [comment]
Moved to 1.27.0 since 1.26.0 is closed. @craxal Please do the investigation if it's not done yet.

**Comment by craxal** [comment]
@pilcherd Jobs are automatically restarted if the worker process fails to respond within a certain amount of time. It sounds likes, even though your job has been cancelled, the worker process isn't properly cleaning up and signaling that the job is done. The job is probably being resumed at least an hour later, because we give work-heavy jobs up to an hour to respond before trying again. Can you run through your repro steps again in a fresh Storage Explorer session and provide your log files here? We'll continue to investigate on our end as well.

**Comment by craxal** [comment]
We're unable to repro, and we have not observed any more activity on this item, so we're going to close. If you continue to encounter this issue, please respond with the log files we asked for, and we will review.
