### ISSUE TITLE
Version 1.0.0 is broken for US Government

### ISSUE THREAD

**Issue by smichelotti** [Microsoft/AzureStorageExplorer#61]
**Storage Explorer Version:**
1.0.0

**OS Version:**
Windows 10 

**Steps to Reproduce:**

1. Try to connect normally for **any** Azure US Government account
2.

**Expected Experience:**
Should connect successfully. Instead it shows error that I can't get subscriptions. Here is the error from the F12 Dev tools console: Could not load subscriptions for tenant ee288926-3dba-450a-ab95-348da135500a, error: [object Object]

**Actual Experience:**
Unable to connect. Even if you remove the account and restart Storage Explorer. Prior to version 1.0.0, this works fine for US Government. We've verified this for multiple people/account/machines for the people on our team.

**Comment by smichelotti** [comment]
Thanks. I have verified the suggested patch works successfully as a short-term fix until the next update ships.

**Comment by MRayermannMSFT** [comment]
Apologies, a few other values need to be updated. Please make sure that the `"fairfax"` object matches the below screenshot:
![image](https://user-images.githubusercontent.com/21112697/39145684-5ba58974-46e9-11e8-8862-6605957ec91d.png)

**Comment by MRayermannMSFT** [comment]
Another easy workaround:
1. Open connect dialog
2. Choose "Create Custom Environment" in the "Azure environment:" dropdown
3. Input "US Govt" as the "Environment name:" and `https://management.usgovcloudapi.net/` as the "ARM endpoint:"
4. Click "Sign in..."

Anytime you want to add another govt account, choose "Use Custom Environment" in the "Azure environment" dropdown, and use the "US Govt" environment. Also, we'll be shipping the fix for this issue in 1.1.0.

**Comment by MRayermannMSFT** [comment]
Fix has been merged into master.
