### ISSUE TITLE
Wish blob option to enable "Accept-Ranges: bytes"

### ISSUE THREAD

**Issue by jphiljohnston** [microsoft/AzureStorageExplorer#6108]
A common complaint from our customers is: "Why can't I move back and forth in a recording? For example, in order to get 1 hour in, you have to let it play for an hour. You cannot click and drag and have it just go to the point in the future."

A manager in another department within our company stated, "The marketing department has not switched to Azure for this specific reason."

We have 5 divisions in our company that we are encouraging to move to Azure Storage, but this is the key roadblock.

The workaround is to download the mp4 before playing it, but most don't want to be bothered.

**Comment by JasonYeMSFT** [comment]
@jphiljohnston Could you elaborate a little more on what your use case is and how the header would work in that scenario? Our current support for Azure Blob storage is only targeting generic binary storage and we haven't thought about any optimization for blobs of specific types.

**Comment by MRayermannMSFT** [comment]
Also, can we get more specifics on how this involves Azure Storage Explorer? Are you wanting to be able to set that property on blobs...?

**Comment by jphiljohnston** [comment]
Yes, I would like to be able to set that property on blobs to then allow mp4 files to support playback from selected point on the progress bar.

**Comment by JasonYeMSFT** [comment]
@jphiljohnston The Accept-Ranges header is determined by the server instead of something the client should be modifying. According to my search, Azure Blob service has added support using that header for video streaming a long time ago so this shouldn't be an issue today. To help figure out why your streaming doesn't work, please verify the following conditions and make sure they are satisfied.

- The blob to stream needs to be a block blob.
- The blob needs to have the correct content type set.
- The API version needs to be higher than 2011-08-18. This is a very old API version, it's very unlikely you are still on an older version than this.

Besides, could you also share how you stream the blob? I can stream one of my mp4 blob by creating a SAS url and putting it in a `<video>` tag in an html document. From the network tab, I can see the correct Accept-Ranges header in the response and the video can be streamed with the progress bar working properly.

**Comment by MRayermannMSFT** [comment]
@jphiljohnston ?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Hopefully the explanation by @JasonYeMSFT was helpful. If you still have questions, you can either open a support ticket via the Azure Portal or you can open a new issue here.

**Comment by nguyenlamlll** [comment]
Thank you, [JasonYeMSFT](https://github.com/JasonYeMSFT).
In my case, our Azure blob storage accounts have the default version of `2009-09-19`. Not sure why because we have only created these recently. 

So we follow the help from this person on [StackOverflow here](https://stackoverflow.com/a/49286412/7248435), using:
```
PS Azure:\> $ctx = New-AzureStorageContext -StorageAccountName <account-name> -StorageAccountKey <key>

PS Azure:\> Update-AzureStorageServiceProperty -ServiceType Blob -DefaultServiceVersion 2023-08-03 -Context $ctx
```

**Comment by Bukharee** [comment]
As usual Microsoft doing something stupid defaulting to 2009 here is another alternate command if the above doesn't work
https://github.com/microsoft/PlanetaryComputerDataCatalog/issues/479#issuecomment-2780963992
