### ISSUE TITLE
Video previewing support

### ISSUE THREAD

**Issue by linkinchow** [microsoft/AzureStorageExplorer#6169]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Storage Explorer version 1.26.0 introduces file previewing feature. Currently only text and image files are supported. I have a customer who uploads a lot of videos to Azure Blob Storage. End users are UX designers and they produce a lot of images and videos every day. Now there are only two options for them to view those videos, either "downloading it first" or "creating a sas token and leveraging browser to play the video". They want an easier way to preview video like image previewing in Storage Explorer.

### Desired Solution

Video previewing is supported in Storage Explorer

**Comment by JasonYeMSFT** [comment]
I merged support for playing video blob/files with content type video/mp4, video/ogg or video/webm.

**Comment by JasonYeMSFT** [comment]
Because of some complicated royalty obligation, we'll have to make the video preview work by attempting to play the video in your default browser. We are a free tool and unfortunately we cannot afford the price for decoding non-free codecs.

**Comment by JasonYeMSFT** [comment]
Here is the full list of video formats and their content types that we will support for play in browser.
- .mp4 (video/mp4)
- .m4v (video/mp4)
- .mov (video/mp4)
- .webm (video/webm)
- .ogv (video/ogg)
- .opus (video/ogg)
- .ogg (video/ogg)

There are a few caveats. ".mov" files can only play in Safari and FireFox. Since File Share service doesn't support Condition headers (e.g. If-Range), "video/ogg" files cannot play in browsers that attempt to use the Condition header.
