### ISSUE TITLE
Connection string error when connecting to account with Reader RBAC role

### ISSUE THREAD

**Issue by schh** [Microsoft/AzureStorageExplorer#620]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**:  Windows 10
**Architecture**: x64
**Regression From**: No

#### Steps to Reproduce: ####
1. Login with azure account with reader access
2. When trying to expand the Blob containers node i get the below error.

#### Expected Experience: ####
Be able to read blobs

#### Actual Experience: ####
Whn i try to open the blob i get this:

![5e2683fc](https://user-images.githubusercontent.com/23355281/44848171-17b98800-ac56-11e8-86cc-f2abdff1d57d.PNG)

**Comment by craxal** [comment]
Can you explain your scenario in a little more detail?

Has your Azure account has been granted read access at the storage account level or to a specific blob container? How was this access assigned? Are you talking about [role-based access control](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview)?

**Comment by schh** [comment]
I have assigned a user as Reader on the storage account. My goal is to give download access to all resources in the storage account.

**Comment by craxal** [comment]
Storage Explorer does not yet support RBAC connections yet. That's a feature we're currently working on.

You're only options now are to supply the account key (not recommended, not secure) or to generate a SAS token/URL and give that to the user.

**Comment by schh** [comment]
Ok thanks, and about these sas tokens, ive generated a few of the but i cant see them anywhere. How does this work, can i only have one active at at time? How do i revoke access for old tokens? Can i view wich ones are active somewhere?

**Comment by craxal** [comment]
There's no limit to how many SAS tokens you can generate. SAS tokens should help you get by, but they are limited by what you can control, which is why we're working to get RBAC support in soon. For example, there's no mechanism tracking how many SAS tokens you've generated. And they can't be revoked, so once you hand them out, they're valid until they expire.

Alternatively, you can generate SAS tokens from access policies, which _can_ be revoked at any time by deleting the policy. You can create as many SAS tokens from access policies as you need, but you can only store up to 5 policies. Note that access policies are not supported for account-level SAS tokens.

You can go [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1) to learn more.

Here's the process for creating a SAS URI:

1. If you want to use an access policy, right-click the container you need to grant access for and select "Manage Access Policies...".
2. Create up to 5 policies granting the permissions you want to hand out and click **Save**.
3. Right-click the container again and select "Generate Shared Access Signature...".
4. Select one of the access policies you created in step 2, then click **Create**.
5. The "URL" box will contain the URL. Give this to whomever needs access.

Here's what they should do to use it:

1. Click the Add Account (plug icon) button on the far left.
2. Select "Use a shared access signature URI" and click **Next**.
3. Give the connection a unique name and paste the URI into the corresponding input box. Click **Next**.
4. Verify the information is correct, then click **Connect**.
5. The connection should appear under **Local & Attached** > **Storage Accounts** > **(SAS-Attached Services)** under the node corresponding to the type of service.

**Comment by schh** [comment]
Ok thank you for the detailed answer. I will try this out. 

But just to verify, i generated a SAS token that lasted for a very long time with full access and gave to someone that shouldnt have access anymore for whatever reason, i really cant stop this person from accessing my storageaccount!? That simply cannot be right....thats truly horrible if thats the case. 

Thats really not acceptable at all. So what happens if i delete the storageaccount and create it again with the same name? Will these tokens still work?

**Comment by craxal** [comment]
SAS tokens are ultimately based on the keys of your storage account. You should be very judicious about the SAS URIs you hand out. If you need to revoke any and all tokens that have been issued, including ones not based on an access policy, **you have to regenerate your account's keys**.

I'm sure you can see why Azure is working on and encouraging RBAC support over keys or SAS.

**Comment by schh** [comment]
Yes this would be very welcome change im looking forward too. Thank you for your help. Generating the keys sounds easy enough so i guess its not that bad. 

Whats are the implications to regenerating the keys. Anything i should consider before i do that?

**Comment by craxal** [comment]
Anything that uses the keys to connect to the count will obviously stop working. SAS tokens and connection strings are the two biggest things that come to mind. There may be others, but I can't think of any.
