### ISSUE TITLE
Table CSV Export does not honor local Regional Settings

### ISSUE THREAD

**Issue by mtrmmsoftware** [microsoft/AzureStorageExplorer#6247]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.26.1

### Architecture

x64

### Storage Explorer Build Number

20221018.5

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Have some regional settings chosen in windows besides En-US e.g. German (here the list separator is ";" ).

Implementation hint in C# use this separator: `CultureInfo.CurrentCulture.TextInfo.ListSeparator` instead of the hardcoded comma

### Steps to Reproduce

1. Go to Storage explorer
2. Select & open a table
3. Export the data from the table
4. Check the exported file, the list separator is comma (",") not the system list separator semicolon (;)

### Actual Experience

The CSV file is always exported with comma

### Expected Experience

The CSV file is exported with the list separator configured in the operating system

**Comment by JasonYeMSFT** [comment]
Let's do the investigation to see if there is any solution we can provide in 1.29.0.

**Comment by craxal** [comment]
There's a very good reason for using the list separator from regional settings. In the example put here, the locale is German, which uses a comma as the decimal point. If someone is writing a CSV file, they will likely want to use commas for numbers. But if commas are also used to delineate columns in a CSV file, there's no way to parse out the numbers from the separate columns.

I also can't think of a good workaround. One could put numbers in quotes, which would at least differentiate the numbers from the columns, but I'm not sure JavaScript will parse the numbers back correctly if using anything but a period (.) as the decimal point.

Getting the system's list separator character is even trickier than formatting numbers or dates with the system's regional settings, because it requires using different APIs depending on the system, and there are no straightforward methods for getting the character as opposed to just formatting data.

**Comment by MRayermannMSFT** [comment]
Let's go with C++ for now on this.
