### ISSUE TITLE
It is better to update 'Rename connection...' to 'Rename Connection...' for one attached file share/queue/table

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6261]
**Storage Explorer Version:** 1.27.0-dev
**Build Number:** 20221108.3
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Monterey 12.6 (Apple M1 Pro)
**Architecture:** ia32/x64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> File Shares.
2. Create a file share -> Attach the file share.
3. Right click the attached file share.
4. Observe the context menu.

## Expected Experience ##
It is better to display 'Rename Connection...'.

## Actual Experience ##
Display 'Rename connection...'.
![image](https://user-images.githubusercontent.com/87792676/200783237-0a00ac65-c30f-4623-8f04-0d14806d54a6.png)

## Additional Context ##
The first letter of real words for other actions is capitalized.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20221113.2. 
1. This issue is fixed for one Attached file share/queue/table/storage account.
![image](https://user-images.githubusercontent.com/41351993/201596671-048e348f-546e-4a0b-a5d0-ff3edea1c6b0.png)
2. For one attached blob containers, It shows 'Rename connection...'.
![image](https://user-images.githubusercontent.com/41351993/201597700-430030ce-911b-4af0-8e5a-fb0f74acdef9.png)

**Comment by craxal** [comment]
Should be resolved for blob containers as well now.

**Comment by v-xianya** [comment]
Verified on the new build main/20221114.4. Fixed for blob containers.

![image](https://user-images.githubusercontent.com/41351993/201807806-8301b25e-1f39-4738-917e-d7a1249d30aa.png)
