### ISSUE TITLE
Error on download file from Azure Storage Exploerer

### ISSUE THREAD

**Issue by alascheck** [microsoft/AzureStorageExplorer#6279]
I'm trying to download files from Azure Storage Explorer (1.26.1) to a local directory. 

I get the error
{
  "message": "\"UnexpectedQuit\""
}
for every file and any directory specified for the download.

Any help on this is highly appreciated.

**Comment by MRayermannMSFT** [comment]
@alascheck can you please share your AzCopy log file for the transfer? You can find them under `<your user directory>/.azcopy/`. If this failed transfer if the most recent one you did, then the log file will be the newest one in that directory. If you have done other transfers since this one, then it'd probably be best for you to try it again and then if it fails, grab the new log.

**Comment by mguerrerof** [comment]
I have the same issue but my directory .azcopy is empty.

I am using macOs 13.0 and Azure Storage Explorer (1.26.1)

**Comment by MRayermannMSFT** [comment]
@mguerrerof can you download AzCopy v10 and try to run the transfer on the command line yourself, and look for additional output from AzCopy? You can find the command storage explorer tried to use by invoking the download/upload/copy, and then clicking on "Copy AzCopy Command to Clipboard".

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still running into this problem we recommend you open an Azure support ticket via the portal. Alternatively you can open a new issue here.

**Comment by mguerrerof** [comment]
Hi,

I had a wrong proxy configuration in the OS. It worked pefectly when I removed it.
