### ISSUE TITLE
AzureStorageExplorer does not start due to authentification issues

### ISSUE THREAD

**Issue by WaltherWachenfeld** [microsoft/AzureStorageExplorer#6296]
I had the AzureStorageExplorer installed on Win10 and was using it already.
Now when starting the application, I get this error message:

**German:**
_Die von Speicher-Explorer verwendete Authentifizierungsbibliothek konnte nicht ordnungsgemäß gestartet werden. Stellen Sie sicher, dass .NET Framework 4.7.2 oder höher installiert ist. Wenn .NET Framework 4.7.2 oder höher bereits installiert ist, finden Sie weitere Informationen im Leitfaden zur Problembehandlung. Die ausführliche Authentifizierungsprotokollierung wurde aktiviert. Error:spawn UNKNOWN_

**English:**
_The authentication library used by Storage Explorer failed to start properly. Make sure .NET Framework 4.7.2 or higher is installed. If .NET Framework 4.7.2 or later is already installed, see the troubleshooting guide for more information. Verbose authentication logging has been enabled. Error: spawn UNKNOWN_

I reinstalled but didn't help. I do not have admin rights and only installed it for my user.
Log files are attached.

Can you please help me with that?

[logs.zip](https://github.com/microsoft/AzureStorageExplorer/files/10057375/logs.zip)

**Comment by MRayermannMSFT** [comment]
@WaltherWachenfeld unfortunately the logs are pretty sparse....can you try uninstalling and installing for all users?

**Comment by WaltherWachenfeld** [comment]
@MRayermannMSFT thanks for the answer. 

The goal would be to use it without admin rights and respectively only installed for the one user. Company consraints... And actually, it worked before. I can't recap if AzureStorageExplorer update or Win update or any other change lead to that issue.

Additionally, I also tried this one #4418 but it didn't help.

**Comment by MRayermannMSFT** [comment]
@WaltherWachenfeld , as an FYI, today we shipped version 1.30 of Storage Explorer. This new version makes use of .NET 6 instead of framework 4.7.2, although .NET is a separate dependency install which requires admin rights. The Storage Explorer installer will install it for you if needed, but doing so will require admin rights. I wanted to let you know since you mentioned not having admin rights before.

I encourage you to:
1. Have an admin at your company install .NET 6
2. Yourself upgrade to version 1.30: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.30.0
3. Try signing in, and open a new issue if you have trouble with sign in on 1.30

Thanks!
