### ISSUE TITLE
Unable to load storage account: "Error loading property"

### ISSUE THREAD

**Issue by arogers89** [Microsoft/AzureStorageExplorer#632]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**:  Windows 7
**Architecture**: Unknown
**Regression From**: Yes

#### Steps to Reproduce: ####
1. Open Microsoft Azure Storage Explorer
2. Expand account > storage accounts > cavenders

#### Expected Experience: ####
Should load blob container with multiple repositories. 

#### Actual Experience: ####
Unable to load properties: 

![image](https://user-images.githubusercontent.com/42983631/45060414-4b851b00-b065-11e8-8618-38445bb916e8.png)

**Comment by craxal** [comment]
The first thing we try to retrieve from the storage account are the account keys (Primary Key and Secondary Key). Without those, nothing else works.


Unless Azure was just down for a little while, the only reason I can think you weren't able to get keys is because the account administrator removed your permissions to list account keys.

One way to be sure is to check the result of the operation:
1. Launch Storage Explorer.
2. Expand the tree until your account appears.
3. Hit F12 to open the dev tools. Expand the console window and share any error messages you see.
4. In the Sources tab, hit Ctrl+P and enter "AzureStorageAccountAttributeLoader.js"
5. Find the `getKeys` function and drop a breakpoint on line 182:
   ```ts
   if (!!result.keys) {
   ```
6. Refresh the account node (right-click and select Refresh).
7. Examine the value of the `result` variable by hovering your mouse cursor over it. Look for values, such as `keys` or `primaryKey`.

If you're not seeing anything, or the breakpoint isn't being hit at all, let us know!.

**Comment by arogers89** [comment]
This resolved the issue, thank you!

**Comment by craxal** [comment]
@arogers89, can you explain what exactly fixed the issue so that others finding their way here can benefit?

**Comment by dfknowles** [comment]
I am experiencing this issue with reader accounts.  The reader accounts do not load the primary or secondary key properties.  Per the debug instructions from @craxal the reader accounts never hit line 182.  However, the owner accounts do hit line 182.  

Any help in trying to resolve this would be appreciated.

**Comment by craxal** [comment]
@dfknowles, it looks very much like role-based access control (RBAC) may have been enabled on the subscriptions/accounts you're trying to connect to. Unless you the List Account Keys permission, Storage Explorer won't work, because RBAC support is not yet implemented. Can you verify whether RBAC is enabled in your subscriptions/accounts?

**Comment by dfknowles** [comment]
@craxal thanks for the reply.  After experimenting with permissions I needed to assign the user to the "Reader and Data Access" role in order for them to see the containers and blobs.  The "Reader" role allows the user to see the container, but they cannot access the blobs in the container.

**Comment by craxal** [comment]
Good to hear! If there's nothing else, I'll go ahead and close this issue.
