### ISSUE TITLE
Support for NFS File Share to browse from Azure portal 

### ISSUE THREAD

**Issue by saswatmohanty01** [microsoft/AzureStorageExplorer#6450]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

Azure File storage explorer is not able to access NFS file share 

### Desired Solution

Able to access NFS file share from browser using Azure Storage Explorer 

### Additional Context

Requested by multiple customer

**Comment by MRayermannMSFT** [comment]
To be clear, are you asking for:

1. The ability to connect to any given share over NFS, regardless of if the target share is an Azure file share (e.g., a file share in an Azure storage account)?
2. The ability to connect to only Azure file shares over NFS?

**Comment by MRayermannMSFT** [comment]
@saswatmohanty01 ah ok. We will pass your feedback along to the service team. I would suggest you also provide this feedback to any sort of other MSFT sales/feedback channels you have access to. For example, you could search for this feedback/add this feedback to the Azure feedback site: https://feedback.azure.com/d365community

All that said, I do need to go ahead and close this issue since it is a feature request for the service itself and not Storage Explorer.
