### ISSUE TITLE
The upload location is incorrect in the activity log when uploading files/importing entities if Storage Explorer is installed by snap on Ubuntu 20.04

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#6539]
**Storage Explorer Version:** 1.28.0
**Build Number:** 20230209.2
**Branch:** rel/1.28.0
**Platform/OS:** Linux Ubuntu 20.04
**Architecture:** x64
**How Found:** From running test case
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Install Storage Explorer on Ubuntu 20.04 by snap.
2. Expand one storage account -> Blob Containers.
3. Create a blob container.
4. Click 'Upload-> Upload Files...' -> Click 'No files selected' box.
5. Select a file from the default location (under /home//Downloads).
6. Click 'Open' -> Observe the upload activity log.
7. Check whether the upload location is correct.

## Expected Experience ##
The upload location is correct.
![image](https://user-images.githubusercontent.com/87792676/217764655-e348647d-3814-4d5c-981b-2df31b0c037e.png)

## Actual Experience ##
The upload location is incorrect.
![image](https://user-images.githubusercontent.com/87792676/217764230-701b017c-7643-4909-8c21-a993bb42e7e8.png)

## Additional Context ##

1. This issue doesn't reproduce when downloading files/blobs.
2. This issue doesn't reproduce when Storage Explorer is installed by tar.gz.
3. This issue doesn't reproduce when uploading folders.
4. This issue doesn't reproduce on Ubuntu 22.04.

**Comment by MRayermannMSFT** [comment]
@v-kellyluo, is the uploaded file the correct file?

**Comment by v-kellyluo** [comment]
@MRayermannMSFT , yes, the uploaded file is a correct file under the default location (/home//Downloads).

**Comment by MRayermannMSFT** [comment]
@richardmsft , please research if this is expected on this version of ubuntu. Perhaps the file path the app sees is odd because of some sort of containerization the app is placed in by the snap runtime?

**Comment by richardMSFT** [comment]
From what I've researched, this seems to be the expected behavior for a confined application in snap using xdg desktop portals (https://forum.snapcraft.io/t/home-path-is-translated-into-run-user-1000/15415/6).

From the snapcraft documentation on portals: "Files are fuse-mounted to /run/user/<uid>/doc/<hash>/ in order to give your application access to it. So the path your application sees is different from the path a user chose, even though both are the same file." (https://snapcraft.io/docs/xdg-desktop-portals). This seems to be inline with what we're seeing for the upload location.

I don't see anywhere we're explicitly enabling portal support in our snap, but electron supports native file chooser dialogs using XDG Desktop Portal (https://github.com/electron/electron/pull/19159). Since we use electron's dialog module (which displays native system dialogs) and `showOpenDialog` function for our file picker, this could be why we are getting these paths.
