### ISSUE TITLE
Display a warning message that the connection has expired if attaching a resource with the expire time set to 2025

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6586]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230219.3
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.27.2)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container -> Select 'Get Shared Access Signature...'.
3. Change the expire time as below:
![image](https://user-images.githubusercontent.com/41351993/220265066-ac1ec541-c53b-40f8-85b0-84a13c939f01.png)
4. Click 'Create' -> Click 'Copy'.
5. Open the connect dialog -> Attach the blob container using the copied SAS URL.
6. The SAS attached blob container auto opens.
7. Check there is no warning message.

## Expected Experience ##
There is no warning message.

## Actual Experience ##
There is a warning message 'The SAS used to connect to this blob container has expired'.
![image](https://user-images.githubusercontent.com/41351993/220265403-2f3ae5a2-b2f6-4a03-9488-cad82a4c145b.png)

## Additional Context ##
This issue also reproduces for ADLS Gen2 blob containers/file shares/queues/tables/storage accounts.

**Comment by craxal** [comment]
@v-xianya The reason this happens is because the SAS expiration is far enough into the future, that the number of milliseconds between now and the expiration is greater than 2 ^ 32. The `setTimeout` function we're using to determine when to show the expiration warning only accepts numbers less than 2 ^ 32, otherwise it defaults to 1, meaning a timeout of 1ms. That's why you're seeing the warning. Discussing with team what we should do here, as I'm not sure how often SAS with expirations that far into the future are created.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230226.1. Fixed. So, we are going to close it.
