### ISSUE TITLE
Add support for Azure Files REST API

### ISSUE THREAD

**Issue by MedAnd** [microsoft/AzureStorageExplorer#6589]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I am unable to access an Azure Files share via the Azure Files REST API

### Desired Solution

I propose support for the Azure Files REST API be added, allowing the use of primary & secondary keys, in addition to SAS and Identity Based (Azure AD) auth.

### Additional Context

https://learn.microsoft.com/en-us/rest/api/storageservices/file-service-rest-api

**Comment by MRayermannMSFT** [comment]
Hi @MedAnd, Storage Explorer already supports accessing file shares. The only part of your request which is not supported is accessing file shares of Azure AD OAuth, but this is because the service does not currently support it. You can find your file shares underneath your storage accounts:
![image](https://user-images.githubusercontent.com/21112697/221690328-d8cfcba5-5a8a-42f5-86fa-d460514b041d.png)

Let us know if you have any other questions.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. If you are still encountering this and would like more help, we recommend opening a support ticket from the Azure Portal. Alternatively you can open a new issue here.
