### ISSUE TITLE
The deleted custom property column doesn't disappear after manually refreshing

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6600]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230222.6
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.2.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: Ad-hoc testing
**Regression From**: Previous release (1.25.0)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Add' -> Add one entity which contains one custom property. Like below:
![image](https://user-images.githubusercontent.com/41351993/220875419-0ced38b1-6429-45e6-ba6b-d7bba1fc016f.png)

3. Right click the entity -> Click 'Edit...' -> Delete the custom property 'str' -> Click 'Update'.
4. Click 'Refresh'.
5. Check whether the custom property disappears.

## Expected Experience ##
The custom property disappears.
![image](https://user-images.githubusercontent.com/41351993/220875107-612ab0ae-0e7b-4596-a465-ebd1c09ac1f0.png)

## Actual Experience ##
The custom property doesn't disappear.
![image](https://user-images.githubusercontent.com/41351993/220875281-6a5e6da0-ac80-4f6c-9e35-f9b9484e1559.png)

## Additional Context ##
The custom property doesn't disappear even though reopening the table.

**Comment by craxal** [comment]
@v-xianya Let me look into this, but I think this was intentional. I'm trying to remember why. I think it was because we didn't want to reset column order when refreshing, as that was kind of frustrating. If you want to clear empty columns, try the Reset Columns command.

**Comment by craxal** [comment]
@v-xianya Yes, this is by design. Here are some of the reasons we elected to no reset columns at refresh:
- Refreshing the table would reset column order and sizes, which could disorient users.
- Most tables have entities that remain fairly uniform throughout. Table column flux is expected to be low, so these "blank" columns are expected to be an edge case.
- Columns that are known to be in the table, especially after loading more items, are still relevant, as per the points mentioned above.

If users post any issues, we can revist.
