### ISSUE TITLE
Be able to unzip natively within the storage explorer gui

### ISSUE THREAD

**Issue by yusuf-jkhan1** [microsoft/AzureStorageExplorer#6603]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I often zip files before uploading them to compress the file size to make the network transfer faster. To unzip them however I have to log into a client and then run unzip.

### Desired Solution

It would be great to be able to do an extract all right from the GUI itself, or have an option in the settings where when you upload it first zips the file transfers it, then unzips it on landing.

### Alternatives and Workarounds

A workaround would be to create a event grid notification hooked up to an azure function but its a lot of overhead.

**Comment by MRayermannMSFT** [comment]
> I have to log into a client and then run unzip.

@yusuf-jkhan1 what do you mean by "log into a client"?

To clarify, which of these two are you asking for:

Option 1:
1. You select a file to upload
2. Storage Explorer zips the file
3. Storage Explorer uploads the zip to Azure
4. You select the zip to download
5. Storage Explorer downloads the zip
6. Storage Explorer unzips the zip
7. The file is on your machine

OR

Option 2:
1. You select a file to upload
2. Storage Explorer zips the file
3. Storage Explorer uploads the zip to Azure
4. Storage Explorer unzips the file in Azure

**Comment by yusuf-jkhan1** [comment]
Hey here when I say client I mean something that can download and upload to the storage account and also do unzipping. More specifically, I log into Databricks which is mounted to the storage account and unzip the file and remove the zip files using shell commands. This is of course essentially downloading and uploading again from the databricks driver node but there's less of a network constraint when it's all azure traffic within the same VNET vs me pushing the file from my laptop or on premise machine.

For the options it would be almost what you described in Option 1 so something like:
1. I have a zipped file in my workspace
2. I select  'Upload' or I select to 'Upload and Unzip' (and maybe 'Unzip recursively')
3. Azcopy transfers the zipped file, then it unzips it in storage explorer and removes the zipped file.
4. If I want to download a set of files I can similarly do either just 'Download' or I can do 'Download as zip'
5. I would then just unzip it myself on my local client I don't think storage explorer would do it

This is mostly stemming from the need of moving data to and from azure from relatively bandwidth constrained environments.

**Comment by MRayermannMSFT** [comment]
The set of steps you are asking for isn't really possible. The issues are with steps 3 and 4.

For step 3, what does it "it unzips it in storage explorer" mean? Storage Explorer is just a tool running on your computer. Once the zip is uploaded it exists in Azure, so Azure would need to be the thing to unzip your data. This would mean there needs to be an Azure storage feature that involves Azure storage using computing power on unzipping your data.

For step 4, if you're talking about selecting a file which is not zipped and using "Download as zip", then that means Azure storage would need to zip your data for you. So same as above, there needs to be an Azure storage feature that involves Azure storage using computing power on zipping your data, and then that is what Storage Explorer/AzCopy downloads.

Ultimately since this is what you're asking for, I'm going to close this as dupe to this, which is the same ask: https://github.com/microsoft/AzureStorageExplorer/issues/4998

We've brough this up with the service team before, and they are aware of people's desires for it. But as of now it is not possible.
