### ISSUE TITLE
Development Storage Account not being displayed in Storage Explorer after upgrading to 1.4.1

### ISSUE THREAD

**Issue by techie55** [Microsoft/AzureStorageExplorer#669]
**Storage Explorer Version**: 1.4.1
**Platform/OS Version**: Windows 10
**Architecture**: ia32
**Regression From**: 1.0.0. Not sure if it worked on other versions prior to 1.4.1.

#### Steps to Reproduce: ####
1. Upgrade to version 1.4.1. 
2. Open Storage Explorer. Expand the **Local & Attached** subscription. 
3. Expand **Storage Accounts**
4. (Development) storage account is **NOT** visible

1. Downgrade to version 1.0.0. 
2. Open Storage Explorer. Expand the **Local & Attached** subscription. 
3. Expand **Storage Accounts**
4. (Development) storage account is visible

#### Expected Experience: ####
(Development) storage account is visible
#### Actual Experience: ####
(Development) storage account is **NOT** visible
**Image with Version 1.0.0**
![storageexplorer1 0 0](https://user-images.githubusercontent.com/4335795/45574903-576f9a80-b826-11e8-9d33-e1d5c3a98edc.png)
**Image with Version 1.4.1**
![storageexplorer1 4 1](https://user-images.githubusercontent.com/4335795/45574904-576f9a80-b826-11e8-8a02-35ff7b72fb34.png)

**Comment by MRayermannMSFT** [comment]
Hey @techie55 , this is due to a recent change regarding emulators. You now attach emulators via the Connect Dialog (plug icon on the vertical toolbar). Choose the "Attach to a local emulator" option in the dialog to start working with your emulator.

That said, we do realize that this change in behavior was not discoverable! We're working on adding something that should improve this experience. Apologies for the interruption in workflow.

**Comment by mehowq** [comment]
Indeed, there's no hint at all. At least I was able to see the '(Development)' in VS Cloud Explorer...

**Comment by MRayermannMSFT** [comment]
Hey @mehowq , in our upcoming release, we have returned the "always there" emulator node. It is now called "Emulator - Default Ports". That work has been merged into our master branch for the next release. I'm going to go ahead and close this now that we've addressed it for the next version. :)
