### ISSUE TITLE
We Should Disable Copy When Multi-Selecting Blob Snapshots

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/AzureStorageExplorer#67]
**Steps to reproduce:**
1. Manage a blobs snapshots
2. Select multiple items
3. Copy
4. Paste them clipboard into an empty container

**Actual result:**
only one of the pastes succeeds. Initially I was confused as to what had happened. I then realized that only one succeeded because I was trying to paste the same file multiple times into the same place, which you obviously can't do.

This is TFS bug 591429.

**Comment by Bartolomeus-649** [comment]
I digress, you should ask the user what he wants:
1. Paste the latest snapshot
2. Paste all snapshots as individual blobs, with the snapshot time appended to the name

**Comment by JakeRadMSFT** [comment]
@Bartolomeus-649, Do you have an example use case? I'm not sure it would be that common but perhaps we can offer it in the future.

**Comment by Bartolomeus-649** [comment]
All lists should always support (unless it obviously doesn't make sense)
 - single click selections
 - ctrl + click to select several individual items in the list
 - shift + click to select ranges of items in the list
 - columns should be clickable for sorting (asc/desc), which should not affect current selection.
 - position active item based on keyboard input.

All operations should always operate on the current selections, no matter if it is a single item, several independent items or a range of items.
It has been like this in Windows since I started working with c application in windows in 1991.

Some of the principles at work here are;
 - The principle of least asonishment
 - you never know what the user wants to do, so provide flexibility in the way tools can be used, don't assume you can figure out all the use cases out there in the real world.
 - it's the application developers responsibility to take on crap from the end user, and by doing so making the life of the end user easier.
