### ISSUE TITLE
A query string shows in the table statistics activity log even though the query is not executed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6748]
**Storage Explorer Version**: 1.29.0-dev
**Build Number**: 20230407.2
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Click 'Query'.
3. Add a clause -> Click 'Table Statistics'.
4. Check no query string shows in the activity log.

## Expected Experience ##
No query string shows in the activity log.
![image](https://user-images.githubusercontent.com/41351993/230549293-77573592-0d0f-4fd5-acc3-9aef829f3de2.png)

## Actual Experience ##
A query string shows in the activity log.
![image](https://user-images.githubusercontent.com/41351993/230549178-c1f3b7cb-f92f-4a93-83de-54e58cacd4b7.png)

**Comment by craxal** [comment]
@v-xianya This is by design. It would be too confusing to allow a query to be "active" or not when the query panel is open. So we now just assume that if the query panel is open, a query is "active". That means that any successive actions (refresh, table stats, etc.) will use the query if the panel is open. If the panel is closed, all subsequent actions will _not_ use the query.
