### ISSUE TITLE
"Reset Columns" doesn't work as expected when query select parameter is active

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6820]
**Storage Explorer Version**: 1.29.0
**Build Number**: 20230422.8
**Branch**: rel/1.29.0
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64
**How Found**: ad-hoc testing
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Click 'Query' -> Remove the clauses.
4. Expand 'Advanced Options' -> Click 'Select Columns...'.
5. Click 'Clear All' -> Click 'OK'.
6. Execute query -> Right click the entity -> Click 'Reset Columns'.
7. Check the string '2 of 3 columns selected' shows.

## Expected Experience ##
The string '2 of 3 columns selected' shows.
![image](https://user-images.githubusercontent.com/41351993/233829983-014c1220-e740-47b3-9ed3-8aa9069c59e7.png)

## Actual Experience ##
The string '2 of 3 columns selected' disappears.
![image](https://user-images.githubusercontent.com/41351993/233830031-3c4bdab4-0a03-47cb-b04f-e71c8305db15.png)

**Comment by craxal** [comment]
By design. The column selection is part of the query, and therefore clearing the query should also clear the "select" as well as the "top" parameters.

**Comment by v-xianya** [comment]
@craxal 

> By design. The column selection is part of the query, and therefore clearing the query should also clear the "select" as well as the "top" parameters.

In this issue, the 'select string' is cleared by executing 'Reset Columns.' instead of clearing the query.
Could you help to confirm it?

**Comment by craxal** [comment]
The reason the columns disappear is because, when the query is run with a "select" parameter, the server returns entities with only those properties. When you reset the columns, the explorer only sees the properties that were selected, and the missing columns are dropped. I consider this expected behavior.

That said, it's tricky to get things back into the correct state due to the query select parameter. I think the proper fix is to reset the select parameter when resetting the columns. The reason for this that the select parameter might include columns that are no longer present or that it might exclude new columns.

**Comment by v-xianya** [comment]
@craxal 

 Verified this issue on the build 20230427.5. The selected parameter is reset when resetting the columns.
