### ISSUE TITLE
Investigate preview support for Avro

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#6844]

**Comment by craxal** [comment]
JavaScript libraries exist for reading from an Avro file. Once parsed, it should be easy to format it for display in a table.

Questions that need answers:
- Is it possible to partially read an Avro file? If yes, we don't have to download the entire file just to parse it, like we do for Parquet.
- Do existing libraries allow us to parse Avro data from an existing string or buffer instead of from the file directly?

**Comment by craxal** [comment]
Answers to questions:
* Yes, it is possible to partially read an Avro file. As described in the documentation, Avro files come in variable-sized blocks. The parsing library does not include incomplete blocks when parsing, which works very well for previewing purposes.
* Yes, existing libraries let you parse from an existing buffer by using `BlockDecoder`.
