### ISSUE TITLE
Succeed to use Int32 property to query one entity which has Double property

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6866]
**Storage Explorer Version**: 1.29.1
**Build Number**: 20230508.1
**Branch**: hotfix/1.29.1
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.3.1 (Apple M1 Pro)
**Architecture**: ia32/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> Tables.
2. Create a table -> Add an entity containing a custom property of type "Double" with a value of "123.45". Like below:
![image](https://user-images.githubusercontent.com/41351993/236788224-e568c740-7863-4326-bdf1-d8809f6c5267.png)

3. Click 'Query' -> Add a clause. As below:
![image](https://user-images.githubusercontent.com/41351993/236788380-6cdf4bdd-b1e0-49b0-969c-f04c0c7b66b0.png)
4. Execute query.
5. Check there is no queried entity.

## Expected Experience ##
There is no queried entity.

## Actual Experience ##
There is a queried entity.
![image](https://user-images.githubusercontent.com/41351993/236787587-905a9bdc-c5b1-4264-9f3a-a8f78b258392.png)

## Additional Context ##
1. This issue doesn't reproduce when selecting 'Int64'.
![image](https://user-images.githubusercontent.com/41351993/236787729-a9663b0a-584a-4236-95a8-a9ee08d32397.png)
2. A related issue [5346](https://github.com/microsoft/AzureStorageExplorer/issues/5346).

**Comment by craxal** [comment]
I believe this is expected behavior. Table queries do not contain types; only values. So when you are querying for "123.45", the query doesn't care what the type is. It will still return results.

The difference with Int64 is we append an "L" to the value. I'm not entirely sure why we do this, as I can't find any documentation or comments about it. Let me play around with some things to see if removing the "L" messes anything up. But I expect that if the "L" is removed, you'll start getting consistent behavior for all numeric types.

**Comment by v-xianya** [comment]
@craxal 
When remove 'L' from the Int64 value.
Succeed to use Int64 property to query the entity which has Double property.

**Comment by v-xianya** [comment]
@craxal 
Updates:
Succeed to use 'int32' type to query one entity which has 'Boolean' property.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/14ef8081-63d9-4c3e-9b1a-9bf00ed0c884)

**Comment by MRayermannMSFT** [comment]
This all sounds to be above board. Closing as won't fix.
