### ISSUE TITLE
Allow trusted Microsoft services to bypass network firewall

### ISSUE THREAD

**Issue by eric-mark** [microsoft/AzureStorageExplorer#6881]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

If we enabled the network firewall to allow public network access from public ip addresses, it does not allow us to allow trusted Microsoft services to bypass the network firewall

### Desired Solution

An option to allow an exception to bypass the network firewall settings to trusted Microsoft services such as Logic Apps

### Alternatives and Workarounds

We can manually add the IP addresses from our logic apps which call our ADX, but this is not an ideal solution as the IP addresses can change.

### Additional Context

We have Logic Apps deployed which use a service principal to read our ADX database to run various actions.  We want to lock down our ADX from other public IP ranges if possible.

**Comment by JasonYeMSFT** [comment]
Could you elaborate on how you use Storage Explorer and at which step are you blocked? Storage Explorer is a client software for Azure Storage which won't be able to bypass the network firewall on its own. I would recommend you to contact the Azure Network team to figure out if they allow configuring such bypass policies. If it turns out that Storage Explorer needs to make any changes to take advantage of those policies, feel free to come back and let us know.

**Comment by eric-mark** [comment]
@JasonYeMSFT -- sorry, i have posted into the incorrect repo.  this was for Azure "Data" Explorer.
