### ISSUE TITLE
Where is the manage Access tab/option to give the manage access to the Containers.

### ISSUE THREAD

**Issue by Afakedev** [microsoft/AzureStorageExplorer#6892]
How Can i add manage access to the containers in Azure Storage Explorer. I am not getting any option to give manage access. Please let me help me in that.
![Capture](https://github.com/microsoft/AzureStorageExplorer/assets/93173336/8fdc47d6-5910-41fe-b2b4-277aef10c18c)

**Comment by MRayermannMSFT** [comment]
@Afakedev are you asking why you don't see the "Manage ACLs" button with the person icon? This:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/18d14e27-b4e9-4488-8bff-7628f7e704cd)

If yes, then that is because you have attached your container as a normal/non-gen2 blob container. In order to have access to gen2 features, you will need to use the gen2 option in the connect dialog when attaching:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/4686f241-19f0-4842-abff-1761eafc20fc)

**Comment by Afakedev** [comment]
Hi,

Thank you so much for your reply. Now I got it.

Thanks,
Shashi Kant
