### ISSUE TITLE
Latest version does not allow users to sign into a subscription associated with Azure Gov

### ISSUE THREAD

**Issue by morrisjoe0327** [Microsoft/AzureStorageExplorer#69]
**Storage Explorer Version:**
1.0.0

**OS Version:**
Windows Server 2016

**Steps to Reproduce:**

1. Launch Storage Explorer
2. Add a new account
3. Choose Azure Gov
4. Authenticate

**Expected Experience:**
View resources from subscription

**Actual Experience:**
Receive a message stating the resources could not be retrieved and to try to authenticate again.

**Comment by MRayermannMSFT** [comment]
Hi @morrisjoe0327 , apologies that you have been affected by this issue. We will be shipping a fix for it in our next release, which will be shipped relatively soon. Until then, we recommend 2 workarounds:

## Create a US Govt custom environment
1. Open connect dialog (plug icon)
2. Choose "Create Custom Environment" in the "Azure environment:" dropdown
3. Input "US Govt" as the "Environment name:" and `https://management.usgovcloudapi.net/` as the "ARM endpoint:"
4. Click "Sign in..."

Anytime you want to add another govt account, choose "Use Custom Environment" in the "Azure environment" dropdown, and use the "US Govt" environment. Also, we'll be shipping the fix for this issue in 1.1.0.

## Downgrade to version 0.9.6
You can download the previous version of Storage Explorer here: https://go.microsoft.com/fwlink/?LinkId=809306&clcid=0x409 (do not install 1.0.0 when prompted)

Also, we already have an existing issue tracking this bug, so I am closing this as a duplicate. 

Existing issue: https://github.com/Microsoft/AzureStorageExplorer/issues/61
