### ISSUE TITLE
Fail to preview files whose parent folder name ends with a dot and the setting "Disable file sharing trailing dot support" is not checked

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#6946]
**Storage Explorer Version**: 1.30.0
**Build Number**: 20230603.6
**Branch**: rel/1.30.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture**: x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch storage explorer -> Uncheck the setting 'Disable File Share Trailing Dot Support'.
2. Expand one storage account -> File Shares.
3. Create a file share -> Create a new folder named 'test.' -> Upload one file to the folder.
4. Right click the file -> Click 'Preview'.
5. Check whether succeeds to preview the file.
  
## Expected Experience ##
Succeed to preview the file.
  
## Actual Experience ##
Fail to preview the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/b1bd0233-2042-44e4-bc60-08250f4d62d7)

Error details:
`  "name": "RestError",
  "message": "The specified parent path does not exist.\nRequestId:42c48d23-701a-0038-737b-9723de000000\nTime:2023-06-05T06:58:27.9069749Z",`

**Comment by richardMSFT** [comment]
For this milestone, fixing pdf preview for trailing dot directories is out of scope because it requires intercepting the request and attaching the right header for trialing dot. Video preview is not possible because it is out of our control. I will open an issue for fixing pdf preview for 1.31.0.

However, the all other file previews should be available to preview when inside a trailing dot directory.

**Comment by v-xianya** [comment]
@richardMSFT thanks for your update! Verified this issue on the rel build 20230608.6. Succeed to preview supported files. (Not include pdf preview and play video in browser)
