### ISSUE TITLE
Stop the upgrade notice

### ISSUE THREAD

**Issue by GoEddie** [microsoft/AzureStorageExplorer#6985]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I can't upgrade to the latest and have disabled automatic updates but still it nags to upgrade

### Desired Solution

I still have to deal with ADLS Gen 1 accounts so cant upgrade - can you have a "dont check for updates" or "dont nag" button, thanks.

**Comment by MRayermannMSFT** [comment]
Hi @GoEddie thanks for the feedback. Ultimately, we want people to stay up to date with Storage Explorer. That's why there is no button to stop update notifications, only to not download. However, I do sympathize with your plight here. You haven't migrated from Gen1 to Gen2, and therefore need to stay on version 1.28.x. So in that case, would you mind me emailing you at the address on the site you have linked with your GitHub profile? I think perhaps I can share a work around with you.

**Comment by GoEddie** [comment]
Yes please that would be great!
