### ISSUE TITLE
The icons of the services and service nodes show incorrectly

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7025]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230627.1
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.4 (Apple M1 Pro)
**Architecture:** x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.30.0)

## Steps to Reproduce ##

1. Expand one storage account.
2. Check whether the icons of the services and service nodes show correctly.

## Expected Experience ##
The icons of the services and service nodes show correctly.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/563f51a6-d795-435b-8f43-40cc97b21aef)

## Actual Experience ##
The icons of the services and service nodes show incorrectly.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/a6cabc7c-3640-458e-bdda-a7220cfc6f20)

## Additional Context ##

1. This issue cannot be reproduced consistently.
2. This issue doesn't reproduce for file shares.
3. When the first storage account is collapsed, this issue can be reproduced more easily.

**Comment by craxal** [comment]
I saw this earlier, but wasn't able to reproduce. I'm able to reproduce now. This due to the fact that some of these icons have gradients. Gradients in SVG need IDs so they can be referenced and used by other elements. IDs are supposed to be unique. But because we are putting in SVG icons inline, we are essentially duplicating element IDs. Hence the missing gradients. I'll need to add some code that generates and injects unique IDs.

**Comment by v-xianya** [comment]
Verified this issue on the build main 20230707.6. Fixed.
