### ISSUE TITLE
The action 'Play in Browser' is visible instead of 'Preview' for .ogg files under file shares

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7135]
**Storage Explorer Version**: 1.31.0-dev
**Build Number**: 20230801.4
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Create a file share -> Upload one .ogg file.
3. Select the file.
4. Check whether the action 'Preview' is visible for the file.

## Expected Experience ##
The action 'Preview' is visible for the file.

## Actual Experience ##
The action 'Play in Browser' is visible for the file.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/7dd34f41-d2db-45e5-ad54-f3af638ac2c3)

## Additional Context ##
1. Nothing happens if double click the .ogg file when the setting 'Open Operation' is set to 'Preview'.
2. This issue doesn't reproduce for blob containers/ADLS Gen2 blob containers.

**Comment by richardMSFT** [comment]
The action 'Play in Browser' being visible instead of 'Preview' for .ogg files under file shares we won't fix. This is because to differentiate between a video .ogg or audio .ogg file we need to make an API call to get the properties of the file. But this would have to be done upon every file selection which can be expensive.

However, for double clicking a .ogg file when the setting 'Open Operation' is set to 'Preview' we will fix and make the expected behavior to download and open in external program.

**Comment by v-xianya** [comment]
Hi @richardMSFT Verified this issue on the build 20230803.5. 
The current behaviors as below:
1. Show 'Play in Browser' for one .ogg file under file shares.
2. Setting 'Open Operation' is set to 'Preview'. Double clicking a .ogg file will download and open in external program.

The current behaviors match the comments you added. So, we are going to close this issue.
