### ISSUE TITLE
The 'Delete' action is enabled in one SAS attached queue which SAS URL is created by access policy (Read, Add, Process)

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7143]
**Storage Explorer Version:** 1.31.0-dev
**Build Number:** 20230803.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture:** x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Expand one storage account -> Queues.
2. Create a queue -> Add two messages -> Right click the queue.
3. Click 'Manage Stored Access Policies...' -> Add one access policy with 'Read, Add, Process' permissions.
4. Generate a SAS URL via the access policy.
5. Attach the queue via the SAS URL -> Select one message.
6. Check whether the 'Delete' action is disabled.

## Expected Experience ##
The 'Delete' action is disabled.

## Actual Experience ##
The 'Delete' action is enabled.
 
## Additional Context ##

1. According to bug #[6857](https://github.com/microsoft/AzureStorageExplorer/issues/6857), the 'Delete' action should be disabled in one SAS attached queue which doesn't have 'Update & Process' permissions.
2. All messages disappear when deleting one message.
3. This issue doesn't reproduce when attaching via SAS permissions.

**Comment by MRayermannMSFT** [comment]
@richardmsft

1. It seems like perhaps the process permission is enough to delete queues, so I think delete working is expected: https://learn.microsoft.com/en-us/rest/api/storageservices/create-service-sas#:~:text=want%20to%20update.-,Process,-p
2. Since the attached SAS has no explicit permissions, we cannot know what the permissions are, therefore I am ok with keeping the action enabled in such a case.

Let's not worry about re-opening `queue-extension` right now, and save taking care of fixing the button conditions in 1.32.

**Comment by richardMSFT** [comment]
A fix for this has been merged. 'Delete' action no longer needs the update permission and only the process permission. Therefore, it is expected for the 'Delete' action to be enabled and working for SAS attached queue if the access policy has "Read, Add, Process" permissions

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231013.4. Fixed.
