### ISSUE TITLE
StorageExplorer.exe - Entry Point Not Found

### ISSUE THREAD

**Issue by DavidAtASNT** [microsoft/AzureStorageExplorer#7167]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.30.2

### Regression From

1.28.1

### Architecture

x64

### Storage Explorer Build Number

Unable to open ASE

### Platform

Windows

### OS Version

Windows Server 2012 R2 Standard

### Bug Description

Error indicates:

Error title: 
StorageExplorer.exe - Entry point Not Found

Message:  
The procedure entry point DiscardVirtualMemory could not be loaced in the dynalim link library C:\Program Files\Microsoft Azure Storage Explorer\StorageExplorer.exe

Full event log entry:
Log Name:      Application
Source:        Application Error
Date:          8/9/2023 1:13:40 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      VMSQL.asnt.local
Description:
Faulting application name: StorageExplorer.exe, version: 1.30.2.0, time stamp: 0x6452ada8
Faulting module name: ge Explorer\StorageExplorer.exe!DiscardVirtualMemory, version: 6.3.9600.21074, time stamp: 0x64a390bd
Exception code: 0xc0000139
Fault offset: 0x00000000000ed1b0
Faulting process id: 0xbf9c
Faulting application start time: 0x01d9cae495f9b45f
Faulting application path: C:\Program Files\Microsoft Azure Storage Explorer\StorageExplorer.exe
Faulting module path: ge Explorer\StorageExplorer.exe
Report Id: 159d21d4-36d8-11ee-818a-0050560101dd
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-08-09T17:13:40.000000000Z" />
    <EventRecordID>5953953</EventRecordID>
    <Channel>Application</Channel>
    <Computer>VMSQL.asnt.local</Computer>
    <Security />
  </System>
  <EventData>
    <Data>StorageExplorer.exe</Data>
    <Data>1.30.2.0</Data>
    <Data>6452ada8</Data>
    <Data>ge Explorer\StorageExplorer.exe!DiscardVirtualMemory</Data>
    <Data>6.3.9600.21074</Data>
    <Data>64a390bd</Data>
    <Data>c0000139</Data>
    <Data>00000000000ed1b0</Data>
    <Data>bf9c</Data>
    <Data>01d9cae495f9b45f</Data>
    <Data>C:\Program Files\Microsoft Azure Storage Explorer\StorageExplorer.exe</Data>
    <Data>ge Explorer\StorageExplorer.exe</Data>
    <Data>159d21d4-36d8-11ee-818a-0050560101dd</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

### Steps to Reproduce

1.  Launch Storage Explorer

### Actual Experience

Almost immediately get the error message.

### Expected Experience

Launching Azure Storage Explorer

### Additional Context

I've been running ASE a couple of years, and always accept the upgrades as I am notified of them.  I have call to run it once or twice a month.  

I wasn't unsure of the version before this update, so uninstalled, and reinstalled and still got the error.  That version has a timestamp from Microsoft Corp of July 21, 2023, 2:52:45PM with a product version of 1.30.2.  

I dug up June's 1.30.0 release, and after install it launches with the same error.  I uninstalled and went back to February's 1.28.1 release and it ran fine.

**Comment by MRayermannMSFT** [comment]
Hi. This is by design. Storage Explorer no longer supports Windows Server 2012, due to Electron not supporting it: https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

The last version of Storage Explorer to use an Electron that supported server 2012 was 1.28. You can find that version here: https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.28.1

**Comment by DavidAtASNT** [comment]
Ah, thanks for the information.  I did search for "requirements" and didn't get a hit.  I did find 1.28.1 though.

**Comment by MRayermannMSFT** [comment]
No worries. We have the supported list of Windows versions listed here: https://learn.microsoft.com/en-us/azure/vs-azure-tools-storage-manage-with-storage-explorer?tabs=windows#:~:text=The%20following%20versions%20of%20Windows%20support%20the%20latest%20versions%20of%20Storage%20Explorer%3A

We don't actively test on Windows Server variants so we don't list them explicitly. However, since Server 2012  is based on Windows 8, and Windows 8 is no longer listed, then it should be inferred that Server 2012 is not supported.

We also do our best to announce these things in release notes as well, and for 1.28, there was something written, though again, you need to infer the Server 2012 drop based on the Windows 8 drop: https://github.com/microsoft/AzureStorageExplorer/releases#:~:text=New%20Electron%20Version%20%26%20Windows%207/8/8.1%20Support

Good luck upgrading to Server 2016. 😊

**Comment by mbourgon** [comment]
For future people: I'm getting this on 2012 R2, which is apparently based on the Windows 8.1 kernel.
