### ISSUE TITLE
Replace node-keytar

### ISSUE THREAD

**Issue by JasonYeMSFT** [microsoft/AzureStorageExplorer#7185]
node-keytar project has been publicly archived and according to this announcement, it won't receive any new maintenance.
https://github.blog/2022-06-08-sunsetting-atom/

**Comment by MRayermannMSFT** [comment]
We should investigate this sooner rather than later, as depending on what we go with, we may need to have a transition period where we need to be able to keep keytar around so we can migrate data. If we wait until we cannot use keytar for some reason, migrating data might become impossible.

We should explore:
1. Forking keytar
2. Using keytar as a guide to make our own "interact with OS secret store library" using the same APIs (could combine with macOS keychain component)
3. Creating an entirely new auth library that has no relation to keytar/the APIs it uses

**Comment by craxal** [comment]
A replacement module that combines `keytar` source with our own `macos-keychain` module is now available and in use.
