### ISSUE TITLE
Table Storage: Import does not retain CSV column order

### ISSUE THREAD

**Issue by varismii** [microsoft/AzureStorageExplorer#7260]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.31.1

### Architecture

x64

### Storage Explorer Build Number

20230822.1

### Platform

Windows

### OS Version

Windows 10

### Bug Description

CSV has a logical column order for us. Our developers and support needs to use the documented columns in correct order.
Import Entities wizard shows correct column order per our CSV file.
**Imported rows change the column order!** 
For example 'active' column is column #4 in CSV becomes column #9 after import.
Different checkbox options of the wizard have no effect.
Testing with only few CSV data rows has no effect.
Testing with different CSV delimiters has no effect.
Importing to a new clean table does not help.

Please assist. Our Tables important control tables to maintain process flow and contain certain logic per column groups. Maintaining processing logic with these tables and seeing differences in them in three different environments requires diligence from the developers and support personnel. Releasing from environment to environment is done by importing latest CSV files from Git. Random column order and post re-ordering columns manually in tool makes this tedious and error prone. 

Our minimal CSV attached:
[ltdpconfigraworchestration3-mod-5.csv](https://github.com/microsoft/AzureStorageExplorer/files/12535287/ltdpconfigraworchestration3-mod-5.csv)

### Steps to Reproduce

1. Launch Storage Explorer
2. Open Tables
3. Create new table
4. Import a CSV file. Use delimiter ; (does not affect to the bug, our example uses that delimiter).
5. Check column order from Import Entities wizard. No changes needed to columns and checkboxes (use defaults).
6. Check column order from imported rows. It should show that some columns have changed order from the CSV file and the Import Entities wizard.

### Actual Experience

Our example CSV file (attached) has 'active' column as column #4 (the first custom column after default column Timestamp). This is shown correct in the Import Entities wizard. After import the column has been moved six columns to the right. 

### Expected Experience

Columns order is retained from Import Entities wizard.

**Comment by varismii** [comment]
Our testing shows that column name case affects the column creation order. Columns with pascal case (first letter in caps) get created first, in alphabetical order. Then columns with lower case, in alphabetical order. I.e. column 'Active' retains column order per wizard preview, but column 'active' does not. 

This is clearly a bug. Please fix. Our tables have names with mixed case (some are lower case, some pascal case). Changing column names in our Tables would require us to do code changes to data pipelines and custom code.

**Comment by craxal** [comment]
@varismii Unfortunately, this a limitation of the Azure Tables service. It does not have any features for enforcing any ordering on entity properties, and so this is not something we can fix in Storage Explorer at this time.

The order you see in the Import dialog is simply the order of the columns as Storage Explorer reads from the file. When importing CSV files, ordering is important only because the order in which values appears determines which properties the values are assigned to.

However, once data is uploaded to Azure, even if everything is ordered the way you want, that ordering is lost; property names do not have any ordering outside of comparing their ASCII values. Therefore, there is no way for Storage Explorer to know what order you intended your properties/columns to appear in.

There are some potential workarounds you can try get some ordering back:
1. You can drag and drop the column headers to reorder the displayed columns. Storage Explorer will remember the column order for each unique table between sessions. Keep in mind that this is merely a _display_ ordering, not a _structured_ ordering on the data itself.
2. If column order is important to your process, consider modifying the property names such that they are in the expected order when comparing ASCII values. For example, if "ColB" should come before "ColA", you could rename them to "_01_ColB" and "_02_ColB".

For more information, you can view the [service data model page](https://learn.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#tables-entities-and-properties).

**Comment by varismii** [comment]
Ok, thanks @craxal. Logic behind the scenes understood. So ASCII ordering was the underlying reason.

Display ordering is what we are after, as it's important to interpret the columns in correct order.

Just wondering that if you are able to store and remember the manual column re-ordering, why it's not possible to remember it from the Import wizard (it displays columns in correct order in the import preview)? Pre-storing the selected display order from there would be good UX.

If this cannot be fixed, then we'll resort to renaming columns, test their ASCII ordering and do the required code changes in our data pipelines. 

Sidenote: I think that ASCII ordering is not very international way to handle things nowadays. Creates surprises. Unicode would be better.

**Comment by craxal** [comment]
@varismii

> Just wondering that if you are able to store and remember the manual column re-ordering, why it's not possible to remember it from the Import wizard (it displays columns in correct order in the import preview)?

It's not impossible, just not something we've considered. Feel free to open a feature request if you'd like. Let us know how you'd like this feature to be made available (such as an app setting or an option in the Import dialog).

> I think that ASCII ordering is not very international way to handle things nowadays. Creates surprises. Unicode would be better.

You are most certainly correct. But even that is out of our control for several reasons:
1. Objects in most popular programming languages are effectively unordered key/value pairs, meaning the order in which properties are enumerated isn't, in theory, predictable or configurable. In practice, languages often list properties in alphanumeric order. Since table entities are essentially C#/.NET objects, this is why columns are listed in the order they come in.
2. Table entity property names conform to [C# identifier naming rules](https://learn.microsoft.com/dotnet/csharp/fundamentals/coding-style/identifier-names#naming-rules), which include the use of Unicode characters. But ASCII is a subset of Unicode (that is, the first 128 code points in Unicode are exactly the same as ASCII), so even when sorting by Unicode, characters found in ASCII will still come before others. Sorting by more conventional language semantics requires additional locale information.

**Comment by varismii** [comment]
Ok, thanks @craxal

I'm considering creating a feature request. The Azure Storage Explorer has proven to be a good tool for handling Table Storage content in our customer projects and project maintenance. And I presume it continues to do so. But modern CI/CD release management between app environments requires that Table Storage content resides as CSV data in version control (Git), thus making import/export ever more important. Especially in projects where you cannot create ADF/Synapse data pipelines to rollout and sync Table Storages, but need to resort to manual import/export operations in the tool itself for the application lifetime. Which means any CSV import/export related hickups should be smoothed out from the tool.

Thanks for the additional technical info from behind the scenes. As a C# developer I understand this. And also the need to retain the order mapping in some external storage, since it's not part of typical C# ienumerable structures. We need to be extra careful with Table Storage column names in the future projects, so they conform ASCII characters and sort order, and retain of using scandinavian or other special character in them, as it obviously affects import/export column ordering.
