### ISSUE TITLE
It loads 9999 items in the react file explorer when setting 5000 or no value for 'Load Batch Size'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7290]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230912.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.31.1)

## Steps to Reproduce ##
1. Expand one storage account ->File Shares.
2. Select one file share which contains more than 10000 items.
3. Make sure there is no value set for the 'Load Batch Size'.
4. Right click the file share -> Click '[NEW] Open'.
5. Check whether it loads 5000 items.

## Expected Experience ##
It loads 5000 items.

## Actual Experience ##
It loads 9999 items.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5d790f6a-3461-4167-9f45-bfe1facabc62)

## Additional Context ##
In the old file explorer, it loads 4999 items.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9d41ea99-ad4e-48b5-9978-793850e1d211)

**Comment by craxal** [comment]
@v-xianya I am unable to reproduce. Can you share the file share that you used to test? Can you also share your settings file?

**Comment by v-xianya** [comment]
Hi @craxal I shared the file share and settings file on teams.

**Comment by craxal** [comment]
@v-xianya I am able to reproduce. However, this is not a bug. The "Load Batch Size" setting does not control how many items are loaded. Rather, it controls the _minimum number of items per UI load_ that should be retrieved.

In this case here, we're trying to load _at least_ 5,000 items (the default). The maximum number of file share items Azure can send per request is 5,000, but we may sometimes get less than that for whatever reason. Indeed, what happens is that Storage Explorer sends a request, which returns 4,999 items. Since 4,999 is less than the desired 5,000, Storage Explorer sends another request. This second request returns another 5,000 items, which brings the total number of items retrieved to 9,999. While a bit unpredictable, it is expected behavior.

**Comment by v-xianya** [comment]
Got it. thank you for the details!
