### ISSUE TITLE
The Op field is required

### ISSUE THREAD

**Issue by Seenergi** [microsoft/AzureStorageExplorer#730]
**Storage Explorer Version**: 4.2 
**Platform/OS Version**: Win7

#### Steps to Reproduce: ####
1. Upload a file with the ' #' character in the filename.
2. Try to download it 

#### Expected Experience: ####
Get the file.

#### Actual Experience: ####
File containing the following message : "{"Message":"The request is invalid.","ModelState":{"Op":["The Op field is required."]}}

**Comment by Seenergi** [comment]
any suggestion..?

**Comment by MRayermannMSFT** [comment]
Hmmmmm I'm not seeing this. What do you mean by the file contains that message?

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. Please open a new issue if you are still having problems.

**Comment by et1h** [comment]
@MRayermannMSFT I am getting this error as well.

I am downloading the file from the this path:

/Databank/Publish/Fagdata/#KEID/Datafordeler#2092/raw/Ejerskab_med_stamoplysninger_fortrolig.json

This results in a small 1kb json file, with only the contents: 

{"Message":"The request is invalid.","ModelState":{"Op":["The Op field is required."]}}

The UI claims the file is downloaded succesfully:

![UI Succesfull download](https://user-images.githubusercontent.com/95682452/145002084-1277ccf7-f85b-4174-b44b-2c5135371116.png)

However since the file is 10GB, and the download took less than 5 seconds, you can begin to suspekt that something is wrong, already.

Here you can see it open in Visual Studio Code:

![Contents in Visual Studio Code](https://user-images.githubusercontent.com/95682452/145002315-99514ff0-de8d-42ca-b21b-16f50d1d5a0f.png)
