### ISSUE TITLE
Save filter in Explorer / Select Favorites.

### ISSUE THREAD

**Issue by Nickxsch** [microsoft/AzureStorageExplorer#7311]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

In a long list of storage accounts, in my role I only use a select few.

### Desired Solution

I can filter the explorer, but have to do this manually every time. Could I save and use a filter by default, or select favorites to show by default instead of showing everything?

### Alternatives and Workarounds

Right now I always manually filter all Storage Accounts with a keyword. This takes a few seconds and it searches through all resources every time I filter. The names don't regularly change, so this is kind of a wast of energy / resources.

### Additional Context

My filter returns about 40 Storage Accounts, of the 1500 total.

**Comment by JasonYeMSFT** [comment]
@Nickxsch We are currently working on a new feature called "view all", which will allow you to list your storage accounts in a right-hand-side explorer instead of in the tree view. Storage Explorer currently offers a featured called "Preserve Explorer Session". Once enabled, your right-hand-side explorers will be persisted and will be automatically restored when Storage Explorer restarts. What we can do is let the Storage Accounts view all explorer offer the search capability and persist the search criteria so each time Storage Explorer restarts, the explorer automatically applies the same search criteria. Does that sound like a potential solution to your problem?

**Comment by craxal** [comment]
@Nickxsch You should be able to "Pin to Quick Access" any storage accounts you'd use regularly. Do you need more functionality than this?

**Comment by Nickxsch** [comment]
> @Nickxsch You should be able to "Pin to Quick Access" any storage accounts you use regularly. Do you need more functionality than this?

You brilliant man, I don't know how I missed that.

@JasonYeMSFT, this was all I needed. Thanks!
