### ISSUE TITLE
No warning 'A blob with the same name already exists' shows in the 'Clone and Rehydrate' dialog for one archive blob version

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7314]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20230922.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Ventura 13.5.2 (Apple M1 Pro)
**Architecture**: x64/arm64/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.28.1)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers (Blob Versioning is enabled).
2. Create a blob container -> Upload one blob.
3. Delete the blob to get a blob version -> Switch to the context view 'All blobs and blobs without current version'.
4. Change the access of the blob version to archive.
5. Right click the archive blob version -> Click 'Clone and Rehydrate...'.
6. There is a 'Clone and Rehydrate' dialog.
7. Check whether a warning shows in the dialog.

## Expected Experience ##
A warning shows in the dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5b81834c-b414-4418-ae06-9b6ca491e653)

## Actual Experience ##
No warning shows in the dialog.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/30248873-301f-42c6-a1f6-e16ea547852b)

**Comment by JasonYeMSFT** [comment]
The problem is due to a limitation of the copy blob service. You cannot copy an archived version to its non-existent base blob but you can copy it to its hot/cool/cold base blob, which might be another blob who also has non-current versions. What we need to change in the validation logic is

- If the source is a version, also invalidate the operation if the destination is its own base blob and it doesn't exist.

 https:// learn.microsoft.com/en-us/rest/api/storageservices/copy-blob?tabs=azure-ad#copying-blob-versions

This issue doesn't block anyone. We can do it in 1.33.0.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20231109.3. Fixed. So, we are going to close it.
