### ISSUE TITLE
Format date times during avro preview

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7334]
Related to: https://github.com/microsoft/AzureStorageExplorer/issues/7159

**Comment by craxal** [comment]
Doing this properly will require passing `Date` objects between processes, but those don't get deserialized properly. We need to do some digging into the root cause. I've tested Node and Electron individually, and they both seem to deserialize `Date` objects as expected. So, there it may be some middleman that's messing things up.

**Comment by craxal** [comment]
Supporting timestamp types is possible with deprecated `TIME_MILLIS`, `TIME_MICROS`, `TIMESTAMP_MILLIS`, and `TIMESTAMP_MICROS`. Additional support for `TIME` and `TIMESTAMP` is forthcoming (LibertyDSNP/parquetjs#99).

**Comment by craxal** [comment]
For anyone that's interested, we have a private build that adds date formatting to preview for Avro files. Keep in mind that this only works for `TIME_MILLIS`, `TIME_MICROS`, `TIMESTAMP_MILLIS`, and `TIMESTAMP_MICROS` types.

https://cralvordtest02.blob.core.windows.net/share/1.32.1-datepreview.1/StorageExplorer-windows-x64.exe?sv=2023-01-03&st=2023-12-07T18%3A38%3A14Z&se=2023-12-22T18%3A38%3A00Z&sr=b&sp=r&sig=DJPjcxkltVwrP7oSR74KGzf%2B3NxY1jOvi6%2FG783F45U%3D
