### ISSUE TITLE
The 'Selected columns' and 'Show top results' are not reset if execute query then click refresh

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7384]
**Storage Explorer Version**: 1.32.0-dev (93)
**Build Number**: 20231009.1
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test case
**Regression From**: Previous release (1.31.0)

## Steps to Reproduce ##

1. Expand one storage account -> Tables.
2. Create a table -> Add one entity.
3. Click 'Query' -> Expand 'Advanced Options' -> Type '1' into 'Show top results' field.
4. Click 'Select Columns...' -> Click 'Clear All' -> Click 'OK'.
5. Execute 'Query' -> Click 'Refresh'.
6. Check whether the 'Selected columns' and 'Show top results' are reset.

## Expected Experience ##
The 'Selected columns' and 'Show top results' are reset.

## Actual Experience ##
The 'Selected columns' and 'Show top results' are not reset.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/ecb8fb3d-2a7c-4261-9b4a-e9959fbf3651)

## Additional Context ##
In previous release, clicking 'Refresh' doesn't exit query.
Here is the screenshot on the 1.31.0 version following the repro steps.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/24630389-daf4-4ea5-b663-6763791f84d4)

**Comment by craxal** [comment]
@v-xianya I am assuming that if you add any clauses, they also are not cleared? This is by design. Refresh clears the _applied_ query, but it should not change the _working_ query.

If you recall, we recently changed things such that there is now an _applied_ query and a _working_ query. The query builder shows the _working_ query, whereas the _applied_ query is the one that actually modifies which entities are shown or used in commands.

See
