### ISSUE TITLE
Log user actions in Azure Storage Explorer.

### ISSUE THREAD

**Issue by DOH-MBR0303** [microsoft/AzureStorageExplorer#7386]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I cannot recover user details for blob actions performed in Azure Storage Explorer. 

### Desired Solution

I would be able to tell who performed blob actions from Azure Storage Container.

### Alternatives and Workarounds

 No current work arounds. Created issue#6299 (closed)

### Additional Context

Example: What user performed the following actions on blob xyz.csv : Read Write Delete Update

**Comment by MRayermannMSFT** [comment]
Hi @DOH-MBR0303. While this issue is a bit out of scope for what issues in this repo are for, I can try to give you some advice on how to get what you want. For futher help, you'll want to reach out to support, perhaps to an Azure Advisor or something like that: https://azure.microsoft.com/en-us/support

First, if you're wanting to track user actions in your blob containers, the first thing you need to do is make sure all of your users are not accessing your containers anonymously. This means:
- Ideally disallowing key access to the storage account. Note: this may break various things until you get all your users and apps using OAuth, so you may need to hold off on it, or perhaps not turn it on at all.
- Give users RBAC roles like "Blob Data Contributor" so they can use OAuth instead of key to make API calls, thus tying the authentication in their API calls directly to them
- If you were unable to turn off disallowing key access, you should have your users enable settings in tools to prefer using OAuth credentials. I believe you can do this in portal (though I don't recall how), and in Storage Explorer you can find the setting under Settings > Services > Storage Accounts > Disable Usage of Keys

Once you have that all done, I believe you should be able to enable monitoring on your storage account, and then through Azure Monitor, track what users are doing. However, I have never done this, so no guarantees. As I said earlier, more research on your end is probably needed, either web research or by talking to experts (e.g. Azure support/advisors).
