### ISSUE TITLE
View All Feedback

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7417]

**Comment by markstensgaard** [comment]
The "Settings → Services → Storage Accounts → Storage Nodes Trailing Action → View all" option opening in a separate view is not really much better than the existing "Load more" method for storage accounts with hundreds/thousands of containers, because the view only lists 100 containers per page. It is still a lot of manual clicking to find what you want. What would be nice is a "Load all" option that will just fill out the full list in the Explorer pane, as though the user repeatedly clicked the "Load more" button until the end of the list. Scrolling down a single list is much faster than repeatedly clicking through pages.

**Comment by MRayermannMSFT** [comment]
Hi @markstensgaard some questions for you:

1. Does being able to filter the list of containers in the right-hand side explorer by prefix not help you find your containers? If so, why not?
2. Does being able to sort the list of containers in the right-hand side explorer by the various columns not help you find your containers? If so, why not?
3. Assuming neither of the above things help you find the containers you want, what type of functionality might help you find the containers you want, without having to do lots of scrolling/clicking through pages?

Thanks!

**Comment by MRayermannMSFT** [comment]
@markstensgaard thanks for answering these questions! I have a few follow-ups for you:

1. That's great you already knew about open container by name. Yes, the new functionality is an evolution of that. Did you use that feature often prior to this latest release?
2. How many containers do y'all typically have in the storage account/s that you work with?
3. If you could only pick one, would you prefer to have all containers instantly loaded in the left side tree view, or the right side data explorer view?
4. Do you ever wish you could do actions on multiple containers at once, for example, delete containers in batches?

**Comment by markstensgaard** [comment]
1. Yes, we use the "Open container by name..." feature frequently, ever since it was first introduced. I use it probably two or three times per day, on average. Others use it more frequently. But it would still often be easier and faster to just scroll down the full list in the Explorer pane.
2. We have 200-700 containers in our most frequently-used storage accounts. Our largest storage account is our legacy data with about 3500 containers in it, though this is not used frequently.
3. We'd rather have the left side tree view fully loaded. We'd preferably have an option in the settings so that it can default to loading all items in the Explorer pane when a field is expanded (not just blob container names, but also the storage accounts in a subscription and everything else).
4. We usually use Storage Explorer for exploring the contents of individual blob containers. I'll usually use AzCLI or the PowerShell Azure module or one of my apps using the Azure SDK if I need to manage multiple containers or a large amount of blobs. At most, I will delete a single container in Storage Explorer after cloning it to another name. But it is perhaps because of the difficulty in being able to do things like delete several containers at once in Storage Explorer that I developed other habits and tools for doing these things.

**Comment by MRayermannMSFT** [comment]
@markstensgaard thank you for the time you took to answer my questions, for now, that is all I have.

**Comment by MRayermannMSFT** [comment]
For any further feedback on view all, please open a new issue. Thanks everyone.
