### ISSUE TITLE
No item displays in file/table explorer if set the setting 'Load Batch Size' to '0'

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7436]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231019.3
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/x64
**How Found**: Exploratory testing
**Regression From**: Previous release (1.31.2)

## Steps to Reproduce ##
1. Open 'Settings' -> Set the setting 'Load Batch Size' to '0'.
2. Expand one storage account -> File Shares.
3. Open one file share which contains items.
4. Check whether the items display in the file explorer.

## Expected Experience ##
The items display in the file explorer.

## Actual Experience ##
No item displays in the file explorer.

## Additional Context ##
This issue doesn't reproduce for blob/queue explorer.

**Comment by craxal** [comment]
Blobs is technically cheating by always loading a batch regardless of the batch size setting (or even if there aren't any more items to load).

Zero is a bad value to have, so we also need to update all explorers so that they use their default batch sizes instead of zero.

This is not a problem for queue, because it only ever loads 32 items max and doesn't use that setting.

**Comment by v-xianya** [comment]
Verified this issue on the rel build 20231021.1. Fixed.
