### ISSUE TITLE
Fail to change access policies for one blob container whose public read access is container and 'Blob anonymous access' is disabled

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7448]
**Storage Explorer Version**: 1.32.0-dev (95)
**Build Number**: 20231020.6
**Branch**: rel/1.32.0
**Platform/OS**: Windows 10/Linux Ubuntu 20.04/MacOS Sonoma 14.0(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open Portal -> Create a storage account (Enable 'Blob anonymous access').
2. Expand the storage account in Storage Explorer.
3. Create a blob container -> Right click the blob container.
4. Click 'Set Public Access Level...' -> Apply the option 'Public read access for container and blobs'.
5. Go to Portal -> Disable 'Blob anonymous access' for the storage account.
6. Right click the blob container -> Click 'Manage Stored Access Policies...'.
7. Click 'Save' on the opened dialog.
8. Check whether there is a successful activity log.

## Expected Experience ##
There is a successful activity log.

## Actual Experience ##
There is a failed activity log.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/5d39463e-d7d3-4387-a382-195d15aafd7d)

Error details:
`Public access is not permitted on this storage account`
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/09aab280-ccdc-4b36-98db-88f6ad2ca217)

## Additional Context ##
Succeed to add access policies for the blob container on Portal.

**Comment by MRayermannMSFT** [comment]
@v-xianya when you say 

> Succeed to add access policies for the blob container on Portal.

Does that mean you were able to add a policy to the list of policies, which pops up a message like this:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/1b37d705-6295-4448-9096-45ac29732415)

Or were you able to click save and get a successful message?

Because when I click save I get this message:
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/accba0d1-cd36-4af1-a23a-fab53114f375)


Also, please make sure to wait at least 30 seconds after changing the values for:
- Allow Blob anonymous access for the storage account
- The public access level of a specific container in the storage account

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT thank you for the response! I got the error message after saving the access policy on Portal.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/1a087852-c941-4110-99de-d27622d32535)
Now, the behaviors are consistent between Storage Explorer and Portal.

The error message doesn't make sense to me. I tried to save access policy for the account, the error says 'Public access' is not permitted on the account. Could you help to elaborate it?

**Comment by MRayermannMSFT** [comment]
> The error message doesn't make sense to me. I tried to save access policy for the account, the error says 'Public access' is not permitted on the account. Could you help to elaborate it?

@v-xianya, no worries, the answer is non obvious. Setting access policies and changing public access level use the same API. So when you try to save new access policies the portal/Storage Explorer call that API, but in doing so, they have to re-set/re-affirm that the public access level should be "public". However, this is not allowed due to the account level setting.

Does that make sense?

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Yes, that makes sense to me. thank you for the clarification.
