### ISSUE TITLE
CSV preview provides unexpected results when viewing a file with UTF16 BOM Encoding

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/AzureStorageExplorer#7546]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1(96)

### Architecture

i86

### Storage Explorer Build Number

20231114.10

### Platform

All

### Bug Description

when trying to preview a csv file that is saved as UTF16 BOM the preview displays garbled characters:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/7981510/95dab23c-cbff-4a0b-9da7-efbd4e93afe7)

### Steps to Reproduce

see bug description

### Actual Experience

when trying to preview a csv file that is saved as UTF16 BOM the preview displays garbled characters:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/7981510/95dab23c-cbff-4a0b-9da7-efbd4e93afe7)

### Expected Experience

It would be ideal if the preview could automatically detect the encoding and display the file preview "correctly". it should also display the detected file encoding in the U/I to provide additional context.

### Additional Context

also it is interesting that the encoding isn't set in the file properties dialog. Not sure if this is by design or not:

![image](https://github.com/microsoft/AzureStorageExplorer/assets/7981510/d9a2d36a-3a25-4ca0-b561-8a4376f5e64a)

**Comment by craxal** [comment]
Support for UTF-16 was never considered. We always assumed UTF-8. Decoding UTF-16 is very simple. The trick is telling which encoding to be used.

@jasonhorner Do you know how the file was created/saved? Does your CSV UTF-16 file have a byte-order mark (BOM) at the beginning? If so, we should be able to automatically detect the encoding regardless of the Content-Encoding header. Otherwise, would an option that lets you select the encoding be sufficient for your needs?

**Comment by jasonhorner** [comment]
@craxal correct. It does have a BOM.. short story long I believe the files were copied from an FTP server via either .net or PowerShell and that process is changing the encoding.
what would be helpful would be to make a best effort autodetect and display the encoding. allow an option to select / change the encoding as a preview option in case it gets it wrong.

it would be awesome if there was a way to convert the encoding of a set of selected files with storage explorer but not sure if this would be a valid feature request for storage explorer or not. (if there is a chance the team would take this on as a feature request I'm happy to create an issue within github).... currently I have to download the files from Storage Explorer run a PowerShell script to fix the encoding and then re-upload them. this is cumbersome and takes a ton of time and generates unneeded data movement.

Hope this helps happy to share any additional info or answer and other questions. Thanks again for looking into this. The preview features have been a total game changer for me. I use them almost daily.

**Comment by craxal** [comment]
@jasonhorner I suspect PowerShell, because from my research PowerShell is known to insert a BOM unless an `-Encoding` option is provided (this was for Windows backwards compatibility purposes), and changing encodings via transfers is a highly discouraged practice.

I just wanted to make sure the BOM was present, because that's the best way we have of autodetecting the coding. We will also include an option for showing the encoding and manually changing it for those cases where autodetection gets it wrong.

Unfortunately, Storage Explorer wouldn't be able to do much better than what you're already doing to change your file encodings. I'm not sure the "unneeded" data movement is avoidable. Storage Explorer would still have to download the entire blob to change the encoding. In fact, Storage Explorer has to download a portion of the blob for preview to work.

**Comment by craxal** [comment]
Working prototype:

![Image](https://github.com/microsoft/AzureStorageExplorer/assets/3473026/fc42f414-8f5c-48a5-9d34-f35b4cb0eeac)

**Comment by jasonhorner** [comment]
@craxal Quick Question. It looks like the tabular preview U/I only renders when the content type is **text/csv**? is that a correct assumption and is this by design? If content type is set as: **application/vnd.ms-excel** or **application/octet-stream** even though the file name ends .csv and isa valid csv file.. We just get a plain text dump. 

Additionally, it seems like *.txt or .tsv or other common variants for files that could potentially be text delimited. Is this worthy of a separate feature request or bug?

**Comment by craxal** [comment]
@jasonhorner

> It looks like the tabular preview U/I only renders when the content type is text/csv? is that a correct assumption and is this by design?

Sort of. Storage Explorer first checks for certain content types. If the content type is not recognized, it checks the file extension. Neither of the content types you mentioned are one of the types that Storage Explorer checks, so I'm not sure why your preview is showing plaintext. If you're comfortable, can you share an example file?

I recently discovered that CSV files will get uploaded with a content type of `application/vnd.ms-excel` rather than the expected `text/csv` (see #7596). It could be the cause, but considering the above, it's hard to say why.

> Additionally, it seems like *.txt or .tsv or other common variants for files that could potentially be text delimited. Is this worthy of a separate feature request or bug?

You can always feel free to open a feature request for us to review/investigate.
