### ISSUE TITLE
Sign in your account: empty page

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [Microsoft/AzureStorageExplorer#763]
**Storage Explorer Version**: 1.4.4
**Platform/OS Version**: macOS
**Architecture**: x64
**Regression From**: yes, 0.96, old version of macOS

#### Steps to Reproduce: ####
1. Add an Azure Account
2. put foobar@slb.com account

#### Expected Experience: ####
Ask me for login page

#### Actual Experience: ####
<img width="632" alt="image" src="https://user-images.githubusercontent.com/8209940/46963007-363edb80-d06a-11e8-8b20-d5e8e0260269.png">

**Comment by craxal** [comment]
Bug is getting stale, numerous duplicates, and we've updated several times since 1.4.4. We also have [troubleshooting tips](https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-troubleshooting?toc=%2fazure%2fstorage%2fblobs%2ftoc.json#mac-keychain-errors) for Mac users in this area. Closing for now. If problem persists, please provide additional info.
