### ISSUE TITLE
Azure Storage Explorer must be reauthenticated everyday.

### ISSUE THREAD

**Issue by wangkenpu** [microsoft/AzureStorageExplorer#7639]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20231114.10

### Platform

Windows

### OS Version

Windows 11

### Bug Description

I have to reauthenticate the account to access the data blob container. The errors are like below:
```
{
  "name": null,
  "message": "{\"source\":{\"accountId\":\"xxxxxxxxxx\",\"tenantId\":\"xxxxxxxx\"},\"resourceId\":\"https://management.core.windows.net/\",\"code\":\"AADSTS70043\",\"message\":\"\"}"
}
```

### Steps to Reproduce

1. Launch Storage Explorer.
2. Expand a blob container node.

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/15028609/e5f2c554-d11d-4a47-9c4b-15d654e12b9c)

### Expected Experience

Just need auth one time.

**Comment by MRayermannMSFT** [comment]
Hi @ wangkenpu , unfortunately there's not a lot we (the Storage Explorer team) can do in this situation. This is the message behind the error code you shared:

>  BadTokenDueToSignInFrequency - The refresh token has expired or is invalid due to sign-in frequency checks by Conditional Access. The token was issued on {issueDate} and the maximum allowed lifetime for this request is {time}.

Source: https://learn.microsoft.com/en-us/entra/identity-platform/reference-error-codes#:~:text=the%20sign%2Din.-,AADSTS70043,-BadTokenDueToSignInFrequency%20%2D%20The%20refresh

This basically means your tenant is configured such that after some period of time (in your case, sounds like less than on day) you have to reenter your credentials.

This is likely because your tenant admins have configured one of these properties: https://learn.microsoft.com/en-us/entra/identity-platform/configurable-token-lifetimes#refresh-and-session-token-lifetime-policy-properties

If they want to change it, following these steps might be how they'd get started: https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-conditional-access-session-lifetime#policy-1-sign-in-frequency-control

I'm not an expert in conditonal access policies though, so I may be wrong about that. Regardless, you'll need to talk to your tenant's administrators to reduce how often you reauthenticate.

**Comment by wangkenpu** [comment]
There are lots of my colleagues in Microsoft also use Azure Storage Explore and I think the tenant configures should be the same. However, some of them did not face this issue.

**Comment by MRayermannMSFT** [comment]
@wangkenpu ah ok you are internal. Ya I don't see this issue and I don't think anyone else on our team does. You'll probably want to reach out to MSFT IT to dig into this more. They'll be able to look at the various conditional access policies on the MSFT tenant and help determine why your refresh token doesn't last longer than a day.

**Comment by wangkenpu** [comment]
I've created a ticket (https://support.github.com/ticket/personal/0/2517797) as suggested by IT.

**Comment by wdpankow** [comment]
Please open a ticket with Microsoft IT Azure Support. This does not seem to be related to GitHub.

https://portal.azure.com/#view/Microsoft_Azure_Support/HelpAndSupportBlade/~/overview

**Comment by wangkenpu** [comment]
I've created another ticket. https://ms.portal.azure.com/#view/Microsoft_Azure_Support/SupportRequestDetails.ReactView/id/%2Fsubscriptions%2F3a96ef56-41a9-40a0-b0f3-fb125c2b8798%2Fproviders%2FMicrosoft.Support%2FsupportTickets%2Ff3dc5421-a98115a3-49026b69-0e0c-42f7-9439-0811ec0f2107

**Comment by MRayermannMSFT** [comment]
Closing since issue is being handled internally.
