### ISSUE TITLE
Try to make it so we can use memcpy_s and strnlen on macOS and Linux

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7699]
Modify native code for macOS and Linux to use memcpy_s and strnlen if they are defined.

**Comment by JasonYeMSFT** [comment]
I did much more thorough investigation around the secure version of functions on Mac and Linux. I am confident that the secure version of functions are not implemented by any version of gcc or Apple clang that we may use. Given the limited usage of memcpy in our code, we can confidently say that our limited usage of these functions are secure since we always initialize the destination buffer right before the memcpy call and we guarantee that we always copy less bytes to the buffer than its size.
