### ISSUE TITLE
Update Generated Resource Classes To Take Params for Templated Resources

### ISSUE THREAD

**Issue by MRayermannMSFT** [microsoft/AzureStorageExplorer#7713]
Instead of:

```ts
public static get ChangeAccessTierActiveStateTitle(): string {
   return BlobActionsResources.#getResource("ChangeAccessTierActiveStateTitle");
}
```

Could we have:

```ts
public static ChangeAccessTierActiveStateTitle(templateItem1: any): string {
   return sprintf(BlobActionsResources.#getResource("ChangeAccessTierActiveStateTitle"), templateItem1);
}
```

**Comment by craxal** [comment]
Getters cannot take parameters. They will have to be converted to vanilla functions.

**Comment by MRayermannMSFT** [comment]
> Getters cannot take parameters. They will have to be converted to vanilla functions.

That was a typo. Fixed.
 
> If the arguments are weakly typed (typed as `any`), I think it's better to use variadic arguments (`...args: any[]`). This will make the generation code simpler, as it wouldn't have to parse strings for formatting placeholders.

Sure. They need to have some sort of typing, probably `number | string`.

**Comment by craxal** [comment]
Proposed changes:
* For each string resource containing placeholders, we use a method templated instead of an accessor template.
* For each string resource containing no placeholders, we use the accessor template as we currently do today. In other words, we don't convert them to methods (to minimize code churn).
* The members will continue to appear in the same alphabetical order--now with a mix of accessors and templates (again, to minimize code churn).
