### ISSUE TITLE
The blob container name shows instead of full path when hovering over one blob container tab which is opened from a restored view all containers explorer

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#7802]
**Storage Explorer Version:** 1.34.0-dev (98)
**Build Number:** 20240306.5
**Branch:** main
**Platform/OS:** Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.3(Apple M1 Pro)
**Architecture:** x64/x64/x64
**How Found:** Ad-hoc testing
**Regression From:** Not a regression

## Steps to Reproduce ##

1. Open ’Settings' panel -> Check the setting 'Preserve Explorer Session'.
2. Expand one storage account.
3. Right click 'Blob Containers' node -> Click 'View All'.
4. Restart Storage Explorer.
5. Open one blob container from the restored view all containers explorer.
6. Hover over the opened tab.
7. Check whether a full path shows.

## Expected Experience ##
A full path shows.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/add0612b-9976-4539-a55a-7aa687886876)

## Actual Experience ##
Only show the blob container name.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/87792676/229c760c-8388-420a-869d-ab7c5421785a)

**Comment by JasonYeMSFT** [comment]
This is not by design. The full path is a part of the tab data stored. The restored tab should still show the full path regardless of the state of the tree view. It's meant to help people distinguish tabs with identical names (e.g. blob container with the same name in different storage accounts).

**Comment by MRayermannMSFT** [comment]
This is in fact by design. In a non-restart/restore scenario here's how things work:

1. View all explorer is opened, it has an association with a "Blob Containers" node
2. Container is double clicked in view all
3. View all code queries the children of the associated "Blob Containers" node to find the container node for the double clicked container
4. Blob container explorer is opened, with an association to the queried container node

However, in a view all explorer that is restored, it does not have a working association with a "Blob Containers" node. Therefore the query for the child container node cannot be accomplished.
