### ISSUE TITLE
Disable new version check

### ISSUE THREAD

**Issue by syllanglois** [microsoft/AzureStorageExplorer#7811]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

We would like to be able to disable the notification that a new version is available.

### Desired Solution

Add a setting to "settings.json" that would disable the new version check.

### Additional Context

We are deploying Azure Storage Explorer with SCCM and it is installed to C:\Program Files for every users on a PC.  Because the users get a new version notification that is pretty flagrant, most of the time, they will try to update the software. Because the users do not have admin rights to the PC, the software will be installed to the user profile and that user will now have two shortcuts in the start menu.  One shortcut to the old version in Program Files and another to the latest version in the user profile.

**Comment by syllanglois** [comment]
As suggested here:  https://learn.microsoft.com/en-us/answers/questions/1348205/how-to-disable-autoupdate-of-azure-storage-explore

**Comment by MRayermannMSFT** [comment]
Duplicate of https://github.com/microsoft/AzureStorageExplorer/issues/1227

We'll re-bring up this topic as a team, but generally speaking, we have not implemented this request because ultimately it is important for us that users update to new versions.

If we provide a way to disable update checks then sure, that will be useful for folks who, for example, work somewhere that have an IT team which manages keeping software up-to-date from them. However, it would not be useful for someone who doesn't, because they may never go check, and then get stuck on an older version with security issues/bad bugs/etc.

Perhaps we can think about a setting that would allow a delay in when you receive update notifications. That would at least give "update administrators" time to do their own thing before their users get bothered, but would still eventually sound out a notification.

Any updates to this feature request will occur at the linked issue.

**Comment by syllanglois** [comment]
Couple of suggestions:

- Do not show the setting in the interface, that way it has to be configured manually in the settings.json file.  This extra step would deter most of the users from disabling the update notification.

- Perhaps make this setting only usable in a managed environment?  As an example, managing the updates settings for Google Chrome requires that the PC be "domain-joined" or "MDM-managed" (https://support.google.com/chrome/a/answer/6350036?hl=en).
