### ISSUE TITLE
There are three extra actions for one OAuth attached file share

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7840]
**Storage Explorer Version**: 1.34.0-dev (98)
**Build Number**: 20240327.12
**Branch**: main
**Platform/OS**: Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.4(Apple M1 Pro)
**Architecture**: x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Expand one storage account -> File Shares.
2. Select one file share then attach it via OAuth.
3. After attaching successfully.
4. Right click the attachment -> Observe its context menu.
5. Check whether there is no extra action.

## Expected Experience ##
There is no extra action.

## Actual Experience ##
There are three extra actions.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/9b9352eb-bf39-425a-8580-b86ef7b2f00c)

**Comment by MRayermannMSFT** [comment]
@v-xianya I understand why Clone and Delete are "extra", but why do you consider create snapshot to be extra?

**Comment by v-xianya** [comment]
@MRayermannMSFT Refer to one SAS attached file share. there is no 'Create Snapshot' action. So, we guess it might be an extra action for OAuth attached file share.

**Comment by MRayermannMSFT** [comment]
@v-xianya a couple of things I've learned today:

1. Delete and clone should be hidden for directly attached file shares and blob containers as a design choice. That is to say, no matter how you authorize a directly attached file share or blob container, we always disable delete and clone. That is because we do not believe something directly attached should be deleted or cloned. A user should be doing that from the context of the storage account (e.g., attaching the storage account, listing the storage account under a subscription, etc.). This is currently broken for file shares.

2. Create share snapshot is not always hidden for directly attached file shares. If you attach one using an account level SAS, the action is available and works (assuming the right account SAS permissions):
![image](https://github.com/microsoft/AzureStorageExplorer/assets/21112697/ff14d0fe-93fa-4eab-864e-732c0b64be62)

3. For an OAuth authenticated direct attached file share, create share snapshot will work if you have an RBAC role that grants the necessary permission (example: Owner).

So, I'm going to: 
1. Fix clone and delete not always being disabled for file shares.
2. Leave create share snapshot alone, that is:
   - We hide it if we know you can't do it
   - We show it if it looks possible for you to do it

**Comment by v-xianya** [comment]
Hi @MRayermannMSFT Succeed to create snapshot if have Owner role.

**Comment by MRayermannMSFT** [comment]
Ok. On builds for `main`, the actions for clone and delete should be gone now.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240726.3. Fixed. Clone and Delete actions have been removed.
![image](https://github.com/user-attachments/assets/9c13b323-9258-49ed-bf90-57390b8892e9)
