### ISSUE TITLE
Bug after upgrade in Azure Explorer app.

### ISSUE THREAD

**Issue by aleitao-leit7777** [microsoft/AzureStorageExplorer#7880]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Regression From

1.26.1

### Architecture

x64

### Storage Explorer Build Number

1.33.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

The following error received after upgrading to the latest version.

---------------------------
Unable to retrieve child resources

ProducerError:{
  "message": "{}"
}

### Steps to Reproduce

1. Launched Storage Explorer.
2. Downloaded upgrade.
3. Installed upgrade.
4. Expanded Blob Container.

### Actual Experience

received the following error opening Azure Explorer and trying to expand the Blob container..

Unable to retrieve child resources

ProducerError:{
  "message": "{}"
}

### Expected Experience

Expected to have Blob  with no errors.

### Additional Context

No additional details.

**Comment by JasonYeMSFT** [comment]
@aleitao-leit7777 Could you please follow the instructions and get the Storage Explorer logs for us after reproducing this issue one more time? https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#storage-explorer-logs

**Comment by jimboyuk** [comment]
Hi, I have been having the same problem connecting to my storage accounts when trying to connect to my subscription. 

It's been happening since I upgraded to your previous release and has now made Azure Storage Explorer an unusable tool. Please fix as this must be affecting many people.

Unable to retrieve child resources

ProducerError:{
  "name": "RestError",
  "message": "{\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:de8e84d4-1002-0069-4d29-948b93000000\\nTime:2024-04-21T20:23:16.3743994Z\"}}}",
  "stack": "RestError: {\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:de8e84d4-1002-0069-4d29-948b93000000\\nTime:2024-04-21T20:23:16.3743994Z\"}}}\n    at handleErrorResponse (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:33:21833)\n    at deserializeResponseBody (C:\\Program Files\\Microsoft Azure Storage Explorer\\resources\\app\\node_modules\\@storage-explorer\\table-extension\\dist\\src\\index.js:33:20653)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
  "statusCode": 403,
  "request": {

**Comment by MRayermannMSFT** [comment]
@jimboyuk we'll communicate with you about your specific issue in the issue that you opened (#7890). Thanks.

**Comment by MRayermannMSFT** [comment]
Closing due to lack of response. This issue will no longer be monitored. If you need further help, we recommend opening a support ticket via the Azure portal. Alternatively you can open a new issue here.
