### ISSUE TITLE
Bug after upgrade. Cannot connect to storage resources when signing in to subscription.

### ISSUE THREAD

**Issue by jimboyuk** [microsoft/AzureStorageExplorer#7890]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.33.1

### Regression From

1.32.1

### Architecture

x64

### Storage Explorer Build Number

20240410.2

### Platform

Windows

### OS Version

Windows 11 Home

### Bug Description

Cannot Connect to Azure Storage Resources:

When I try and Connect to my azure resource subscription, I can see my storage resource but if i try and expand any tables, Blob Container or Queue nodes I get an error dialog saying cannot open child resource. Therefore I cannot see the contents of any my resources

### Steps to Reproduce

Launch Storage Explorer

1. From Get Started Page click on Connect to Azure Resources
2. What kind of Azure resource do you want to connect to? --> Select Azure Subsciption
3. Which Azure environment will you use to sign in?   Azure radio button is selected
4. Click Next
5. Enter sign in credentials on new browser window which automatically opens
6. Browser window now says I am automatically signed in
7. In Azure Storage Explorer I click on Open Explorer button in left side of screen
8. I see my storage resource (under Storage Accounts (classic)
9. I try and expand Tables node I get following error:
Unable to retrieve child resources . Authentication failed.

### Actual Experience

![image](https://github.com/microsoft/AzureStorageExplorer/assets/8208714/a5882ecf-319d-44ca-8f4b-135f22de9d57)

### Expected Experience

I expect to be able to browse my storage resources when click on a node (such as table node) in the explorer window

**Comment by MRayermannMSFT** [comment]
@jimboyuk can you confirm that:
1. Can you access the tables of the storage account via the Azure Portal, via the same machine? If no, then you likely have a networking or permission error. For those, it would be best to open a support ticket via the Azure Portal.
2. If accessing the tables worked via portal, can you check if you have System Proxy enabled? If no can you try enabling it via settings (Settings > search for system proxy > select system proxy in the proxy source dropdown)
3. If system proxy didn't help, you can try downloading and installing 1.32.1 (https://github.com/microsoft/AzureStorageExplorer/releases/tag/v1.32.1), and try viewing your tables, in order to confirm that this is really a regression in Storage Explorer version. After doing so, you can go ba

Please let us know how that all goes! Specifically:
- Were you able to access the tables from the same machine via Portal?
- If yes, did enabling system proxy in Storage Explorer help?
- If no, did downgrading to 1.32.1 help?

**Comment by smil2k** [comment]
I can confirm, that the previous version works fine: 1.33.0.

Additionally after upgrading back to 1.33.1, the bug is gone.

**Comment by MRayermannMSFT** [comment]
Soooo I guess nothing to do then if you can no longer repro?👀 Please feel free to open another issue if this happens again I guess.
