### ISSUE TITLE
New Feature for Azure Queue - Export button

### ISSUE THREAD

**Issue by viennamari** [microsoft/AzureStorageExplorer#7980]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I cannot export all of my queue messages

### Desired Solution

Add a functionality to export all of my queue messages to a csv file and an option to choose a delimiter

### Additional Context

So that the same csv file can be used for the import function in Azure Queue.

**Comment by craxal** [comment]
@viennamari When you say "all" of your messages, do you mean up to the maximum of 32 messages that can be peeked at?

Here's the problem with exporting all messages in your queue. The maximum number of messages that can be looked at _nondestructively_ is 32 (that's why you can only see the first 32 messages in Storage Explorer). The only way to get at more messages is to dequeue and delete messages. Assuming you don't want to remove the messages during export, the only possible way I can think of to export all messages is to repeat these steps for every message:

1. Get the message.
2. Write the message to the export file.
3. Delete the message.
4. Requeue the message.

To prevent an endless export cycle, we would get the approximate number of messages in the queue at the start of the operation as a count for the number of messages to export.

This all comes with some risks:
* If the queue is fairly active, with messages being added or dequeued, we cannot guarantee export will get every message, nor that messages will be in the same order after export completes.
* If an error occurs that halts the export, you could be left with a mangled queue, with some messages being pushed to the end of the queue or missing entirely.

Conversely, limiting export to the top 32 messages is much safer and easier to work with.

Please let us know your thoughts.

**Comment by craxal** [comment]
@viennamari Have you had a chance to review my previous comment?

I think what we will do is we will proceed with the top 32 import regardless. If you need more than that, we need your thoughts for further consideration, otherwise we probably won't risk it for the reasons sited above.

**Comment by viennamari** [comment]
I am contented with the reason or answer as to why it was set to 32 messages max. Thanks!
