### ISSUE TITLE
Cannot import queue message in Azure Queue

### ISSUE THREAD

**Issue by viennamari** [microsoft/AzureStorageExplorer#7981]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.34.0

### Regression From

1.34.0

### Architecture

x64

### Storage Explorer Build Number

20240532.2

### Platform

Windows

### OS Version

Windows 10

### Bug Description

Cannot parse queue message with double quotes or quoation marks but can be inserted in add new queue message option.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/40122060/d20b83ff-6253-4ab7-b425-afa0c88c27cf)

### Steps to Reproduce

1. Launch Azure Storage Explorer.
2. Go to Azure Queues.
3. Click Import button to import csv file
4. Unable to parse error resulted due to double quotes or quotation marks.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/40122060/a8e51405-632a-4a63-9cde-9eb935df81c0)

### Actual Experience

Error happened in importing a csv file to insert to Queues.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/40122060/21a8a094-3ea0-4d97-b827-97d5672982ad)

### Expected Experience

Should accept the csv file as valid and should continue normally with the import.

**Comment by craxal** [comment]
@RichardMSFT CSV parsing should be consistent. Can you make sure parsing for queue import functions the same way as table import?

@viennamari Can you provide a sample CSV file for us?

**Comment by viennamari** [comment]
[sampleimportCSV.csv](https://github.com/user-attachments/files/15699325/sampleimportCSV.csv)
here is the sample csv I created based on the queue messages I can insert which contains two queue messages seperated by "||". Thanks!

**Comment by viennamari** [comment]
Hello, yes because our queue messages are in xml format but I saved two queue messages separated by "||" in csv file

**Comment by richardMSFT** [comment]
@viennamari If I'm understanding correctly, it looks like what you're intending to do is not possible with how import queue message is setup as of today. Currently importing messages into a queue from a .csv file behaves where each row is a message and the value in the first column is the message text. This was done to give room for the future where other columns could specify properties like time to live and visibility timeout if there was a demand for it.

So as it stands, when importing from a .csv file the delimiter string is what separates columns and line breaks are what separates the rows. In the case of the .csv file you shared, because each "XML document" spans multiple lines they will be inserted into the queue as multiple messages, one per line. I don't think this is what you intended, but instead I believe you are trying to insert only two messages separated by the `||` characters.

For today, you have either the option of having each "XML document" be contained within one line for queue import or continue to use the add message action. If you think that import queue message functionality should be changed, please [open an issue on GitHub](https://github.com/microsoft/AzureStorageExplorer/issues/new/choose)

**Comment by richardMSFT** [comment]
Parsing queue messages with quotes will however be fixed in the upcoming release 1.35.0.
