### ISSUE TITLE
It would be better to add an action 'Pin to Quick Access' for resource groups that located under 'Storage Accounts' node

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#7990]
**Storage Explorer Version**: 1.35.0-dev (98)
**Build Number**: 20240607.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.5(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Ad-hoc testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Open ‘Settings -> Services' -> Enable the setting 'Organize by Resource Group'.
2. Refresh the tree view.
3. Expand 'Storage Accounts' node -> Right click one resource group.
4. Check whether there is an action 'Pin to Quick Access'.

## Expected Experience ##
It would be better to add an action 'Pin to Quick Access'.
## Actual Experience ##
There is no action 'Pin to Quick Access'.
![image](https://github.com/microsoft/AzureStorageExplorer/assets/41351993/017f4ff2-c0a2-49b9-982b-4730f9f1fe3e)

**Comment by craxal** [comment]
@v-xianya We discussed this as a team and decided not to add this option for the time being. If users ask for it, then we can reconsider.

**Comment by vladimir-kunt** [comment]
Hi. First thing after reading about 'Group Storage Accounts by Resource Group' feature (after celebrating a bit) was to try to pin a resource group to my quick access.

This feature of pinning the whole resource group would indeed be appreciated.

We have over 200 storage accounts in production subscription organized in the ~80 resource groups. Each team responsible for several resource groups. It would make things much cleaner and easier if we could just pin our resource groups instead of various storage accounts.

**Comment by craxal** [comment]
@vladimir-kunt We'll review and see if we can work it into 1.36.0. If not, we'll plan for 1.37.0.

**Comment by v-xianya** [comment]
Verified this issue on the main build 20240913.1. Fixed. So, we are going to close it.
![image](https://github.com/user-attachments/assets/c70f0b79-9032-40ea-ad64-37d04c6663b2)
