### ISSUE TITLE
Skipping the blob uploading displays inconsistent icon for checking/unchecking 'Use AzCopy for Improved Blob Upload and Download'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/AzureStorageExplorer#805]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181025.6
**Commit**: a287009c
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Check 'Use AzCopy for Improved Blob Upload and Download'.
2. Upload one blob.
3. Repeat Step2 with same blob.
4. Check the log in 'Activities' window.

#### Expected Experience: ####
Skipping the blob uploading displays consistent icon when unchecking 'Use AzCopy for Improved Blob Upload and Download'.

#### Actual Experience: ####
Display inconsistent icon when checking/unchecking 'Use AzCopy for Improved Blob Upload and Download'.
![image](https://user-images.githubusercontent.com/34729092/47490643-c0ade900-d87b-11e8-9c8e-93b3e408e64a.png)

#### More Info: ####
This issue also reproduces when downloading blobs.
![image](https://user-images.githubusercontent.com/34729092/47490679-d1f6f580-d87b-11e8-91af-be3f622e8c8d.png)

**Comment by MRayermannMSFT** [comment]
Hi @v-dantch , good eyes noticing the difference. 😄 The decision to use a red x was intentional though. For the normal upload/download case, a skip only occurs because the user chose to skip. So there is no reason to make the user think there's something they need to do. But for AzCopy, if there's a skip, I really wanted the user's eyes to be drawn to that fact, hence using the red X. I may switch to the red ! icon later though, depending on user feedback. Thanks!
