### ISSUE TITLE
Storage Explorer only shows up to 32 messages in Azure Queue 

### ISSUE THREAD

**Issue by kjoshi-rubikloud** [Microsoft/AzureStorageExplorer#81]
**Storage Explorer Version:**
0.9.6
**OS Version:**
Linux
**Steps to Reproduce:**

1. Queue more than 32 messages in Azure Queue
2. View via Storage Explorer

**Expected Experience:**
Should be able to view all messages in the queue.

**Actual Experience:**
Only up-to 32 messages are seen, no way to view all the messages in the queue.

**Comment by grahamoriley** [comment]
I agree this is a real limiting factor.

**Comment by MRayermannMSFT** [comment]
Tagging everyone who thumbed down...

@robert, @jonjander, @grzegorzbrelski, @mradcliffe, @pkellz, @akorkiatupa, @Zjokke, @kiranpradeep, @philippeLarocque, @im-alikhan, @mrfrigerio what if this was implemented in such a way that it incremented the DequeueCount of the messages in your queues. Does that matter to y'all?

**Comment by mradcliffe** [comment]
Thank you for reaching out. :-)

> What if this was implemented in such a way that it incremented the DequeueCount of the messages in your queues.

This wouldn't have made any difference for what I was trying to use Azure Storage Explorer for.

At the time, I was writing a client to consume messages of various complex data types created in bulk by another service. These messages were somewhat ordered in a way where all of a certain "type" were among the first of messages to consume.

It would have been more efficient to be able to page through and inspect the messages in Azure Storage Explorer. I found, at the time, that the only use for Azure Storage Explorer was to confirm that there were in fact N messages in the queue. Instead I had to rely on a more inefficient method of development: routinely re-create messages in the queue as I developed and ran what I was writing over and over again so I could confirm the data structures I was working with.

**Comment by MRayermannMSFT** [comment]
> Thank you for reaching out. :-)

No problem, thank you for replying!

> This wouldn't have made any difference for what I was trying to use Azure Storage Explorer for.

Ok, that's interesting to hear. The reason I suddenly posted my reply was because I had the thought "What if people don't care about the dequeue count of their messages? Because if they don't care, hypothetically we could support looking at more than 32 messages in the queue." So I decided to come here and pose the question to y'all.

If it seems like most people don't care about dequeue count, then I think this issue could potentially be worth revisiting. I think we'd still have to make it an opt-in feature, and the opt-in process would need to be clear that dequeue count would be incremented for any message beyond the 32nd which is viewed. So ya, we'll see what others have to say!

**Comment by luismanez** [comment]
Not completely sure, but I´d say Durable functions take some decisions based on that DequeueCount, so not sure if it´s a good idea to increase it when using the Storage Explorer, though would be an opt-in feature...
PS: got here following an issue with Durable Functions and saw the DequeueCount in Durable control queue has a big number

**Comment by jonrobinsdev** [comment]
Also here because of Durable Functions and the want to be able to view more than the 32 messages to get a sort-of timeline of where my orchestrator is at. Not necessarily needed but would be nice, perhaps as opt-in as was suggested.
