### ISSUE TITLE
The cloned file share under one attached storage account doesn't auto display on the tree view

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8115]
**Storage Explorer Version**: 1.35.0-dev (100)
**Build Number**: 20240808.2
**Branch**: rel/1.35.0
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.32.1)

## Steps to Reproduce ##
1. Select one storage account -> Attach the storage account using SAS or 'name and key'.
2. Expand the attached storage account -> File Shares.
3. Create a file share -> Right click the file share.
4. Clone the file share.
5. Check whether the cloned file share auto displays on the tree view.

## Expected Experience ##
The cloned file share auto displays on the tree view.

## Actual Experience ##
The cloned file share doesn't auto display on the tree view.

## Additional Context ##
The cloned file share displays on the tree view after manually refreshing.

**Comment by craxal** [comment]
@RichardMSFT Can you look into this? If you don't have time, you can reassign to me or someone else.

**Comment by craxal** [comment]
A new node is not being inserted into the tree because the code is querying for subscription and account ID attributes and expects them to be defined, but they're coming back undefined. That's expected for a SAS-connected account, but it seems odd to add a node only if those values are known. Introduced in [PR 514951](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/StorageExplorer/pullrequest/514951?_a=files&path=/src/components/file-extension/src/Actions/CopyFileShare.ts).

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240810.1. Fixed. So, we are going to close it.
