### ISSUE TITLE
Blob Metadata is lost when files are exported.

### ISSUE THREAD

**Issue by GeneralAlgorithm** [microsoft/AzureStorageExplorer#8144]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0 (100)

### Architecture

x64

### Storage Explorer Build Number

20240810.1

### Platform

All

### OS Version

Windows 11

### Bug Description

Downloading Blobs and dragging and dropping them erases all Metadata without warning.

### Steps to Reproduce

Create a blob with metadata.
Right click its blob storage folder.
Download the blobs to your system.
Delete the folder.
Drag and drop the downloaded folder.
Inspect metadata, find none.

### Actual Experience

My metadata is gone.

### Expected Experience

I'm not sure how to keep track of it but the metadata could be exported to a dictionary file or made part of the extended filesystem properties or something?

**Comment by craxal** [comment]
@GeneralAlgorthim This sounds like it's by design. Metadata is an Azure platform feature and not something that translates to your local file system. I would suggest transferring blobs directly to their intended destination instead of downloading them first. If you move/copy blobs directly to another container, you _can_ preserve metadata, assuming you have the necessary permissions to read metadata from the source location.

**Comment by GeneralAlgorithm** [comment]
I'll just avoid this feature, thanks.
