### ISSUE TITLE
Preview pane - split screen issue - second tab is opening in the preview area.

### ISSUE THREAD

**Issue by LaughingJohn** [microsoft/AzureStorageExplorer#8154]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0

### Architecture

i86

### Storage Explorer Build Number

20240810.1

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Subsequent 'explorers' open in the right hand part of the split screen if Storage Explorer is showing a preview. Put another way they open in the "preview" part.

I think this might only happen the first time you double click or right click/open an 'explorer' tab from the menu.

### Steps to Reproduce

Open a blob container tab.
Select a file which can be previewed and open the preview screen.
Double click or right click/open another 'explorer' tab (e.g. table or blob).

### Actual Experience

The second 'explorer' tab opens in the right hand portion of the screen where the window from the previous preview is located.

### Expected Experience

I would expect this window to open in the left hand pane where the first "explorer" tab lives

### Additional Context

![Storage Explorer Issue](https://github.com/user-attachments/assets/48dd9e32-df2a-4eef-aa3d-f78cc8659725)

**Comment by craxal** [comment]
@LaughingJohn It depends on how you open the seconds explorer, but I think this is by design. The left and right splits do not have any particular distinctions (one is not considered the "explorer" side and the other the "preview" side). I suspect that when the preview tab opens, the right panel becomes the active side, and so that's where new tabs will normally open. What happens if you move focus back to the first explorer and then try opening the second explorer?

Whatever the outcome, I agree this can be annoying, tabs not opening where you'd expect them. We can review the behavior and see if it makes sense to keep focus on the tab from which previews are opened.

**Comment by LaughingJohn** [comment]
@craxal Thanks for looking, the focus does work as you suggest and I think you're right that after opening a preview the right hand split has focus which is why it opens there.
It's not a major issue, I guess I'm just used to UIs where the "preview pane" is a separate element and I found the behaviour a bit weird.
