### ISSUE TITLE
AzureStorageExplorer Build on .net Maui

### ISSUE THREAD

**Issue by danielpastoor** [microsoft/AzureStorageExplorer#8157]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

I have a question. Why is this app not build on .net Maui. I understand that Maui is maybe to new to be converted to now. And is it even on the road map?

### Desired Solution

See my question

**Comment by MRayermannMSFT** [comment]
@danielpastoor Storage Explorer was started around 2015, while .NET MAUI was released in 2022. So that is of course going to be the primary reason Storage Explorer isn't written in it.

As for is it on the road map? I would say the answer is definitively no. The amount of work to rewrite to to use .NET MAUI is probably huge (and that word is even likely an understatement), with likely very little gains, especially compared to the cost of the work.

If you think there's some area/s of the product that is lacking, and you were thinking a rewrite to .NET MAUI would help with those, please feel free to an open specific to those areas (e.g. startup speed, app size, etc.) detailing the issue/problem/defect you see.

For this issue specifically though, I'm going to close it as won't fix since, like I said, a rewrite just isn't something we would consider. Though I promise to come back at least once and read any initial follow-up thoughts you might have to what I've said. 😊
