### ISSUE TITLE
It shows 'Secondary' instead of 'secondary' next to a secondary blob container

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8162]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240902.1
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container.
3. Click 'Open Secondary Location' -> Observe the secondary blob container.
4. Check whether it shows 'secondary' next to the secondary blob container.

## Expected Experience ##
It shows 'secondary' next to the secondary blob container.
![image](https://github.com/user-attachments/assets/7fab3eea-0e30-4415-bca6-a6a20820c593)

## Actual Experience ##
It shows 'Secondary' next to the secondary blob container.
![image](https://github.com/user-attachments/assets/049e2f8a-297f-495c-abdf-10fdfc7f744a)

**Comment by v-xianya** [comment]
It shows 'secondary' in the opened tab.
![image](https://github.com/user-attachments/assets/693dc722-02f5-4a92-8607-9a8438681c77)

**Comment by richardMSFT** [comment]
> @richardMSFT Was this intentional?

The change to have secondary tag be capitalized was intentional after moving it to be part of the status of a node. It is capitalized to be consistent with other parts of the status. For example:

<img width="519" alt="Screenshot 2024-09-04 at 8 39 04 AM" src="https://github.com/user-attachments/assets/8d75760d-7003-40f1-bd7a-26a61052733f">

However, I do agree that then having 'secondary' in the opened tab is inconsistent. I will update the 'secondary' in the opened tabs to also be capitalized.

**Comment by craxal** [comment]
@richardMSFT Based in [Visual Studio UX guidelines](https://learn.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/fonts-and-formatting-for-visual-studio?view=vs-2022#BKMK_TextStyle), it seems that in general sentence case is preferred (situations not explicitly called out for title case).

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240923.1. Fixed. It shows 'secondary' in the tree view and tab.
![image](https://github.com/user-attachments/assets/9fbfc59d-8c54-49fa-8e33-5faf074579df)
