### ISSUE TITLE
Storage Explorer is stuck when clicking 'Close All/Close Others/Close to the Right' actions for tabs

### ISSUE THREAD

**Issue by v-kellyluo** [microsoft/AzureStorageExplorer#8172]
**Storage Explorer Version:** 1.36.0-dev (100)
**Build Number:** 20240905.2
**Branch:** main
**Platform/OS:** Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture:** arm64/x64/x64/arm64
**How Found:** From running test cases
**Regression From:** Previous release (1.35.0)

## Steps to Reproduce ##

1. Expand one storage account -> Blob Containers.
2. Create a blob container -> Right click the blob container tab.
3. Click 'Close All'.
4. Check whether the tab is closed successfully.

## Expected Experience ##
The tab is closed successfully.

## Actual Experience ##
Storage Explorer is stuck.

## Additional Context ##
This issue also reproduces for 'Close Others/Close to the Right' actions.

**Comment by craxal** [comment]
The problem appears to be due to a race condition. Multiple tab closures need to wait for the management code to clean up before trying to remove any other tabs, otherwise the state can become invalid, hence why other tabs don't appear to close. This is fixed by making `close()` async and awaiting the result, making it sequential.

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20240910.1. Fixed.
