### ISSUE TITLE
The toolbar size is not always correct when resizing one service explorer

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8174]
**Storage Explorer Version**: 1.36.0-dev (100)
**Build Number**: 20240905.2
**Branch**: main
**Platform/OS**: Windows11/Windows 10/Linux Ubuntu 22.04/MacOS Sonoma 14.6.1(Apple M1 Pro)
**Architecture**: arm64/x64/x64/x64
**How Found**: From running test cases
**Regression From**: Previous release (1.35.0)

## Steps to Reproduce ##
1. Launch storage explorer -> Open 'Settings' -> Make sure the 'Toolbar Size' is set to 'Auto'.
2. Expand one storage account -> Blob Containers.
3. Open one blob container -> Make sure the current toolbar size is regular.
4.  Reduce the size of the explorer vertically.
5. Check whether the toolbar size keeps regular.

## Expected Experience ##
The toolbar size keeps regular.
![image](https://github.com/user-attachments/assets/945bd26e-fb43-4bca-8578-1c28fc098c60)

## Actual Experience ##
The toolbar size becomes small.
![image](https://github.com/user-attachments/assets/b582c670-a827-44fe-815d-068b6bd0acde)

## Additional Context ##
This issue also reproduces when resizing the blob container explorer horizontally.
![test1](https://github.com/user-attachments/assets/04f65c97-cb61-45a0-87a6-001bf11fa7e8)

**Comment by craxal** [comment]
I am able to reproduce this in 1.35.0, so this not a regression.

This issue is caused by the calculations made to determine the toolbar size. The problem is the toolbar size is the same for both splits. When one is considered small, so is the other. So, when one split is shrunk such that it transitions to the small toolbar setting, it is also applied to the other split. What we need do is have separate sizes for each split.
