### ISSUE TITLE
Open Container by Name feature does not search all containers

### ISSUE THREAD

**Issue by marcelvb** [microsoft/AzureStorageExplorer#8212]
### Preflight Checklist

- [X] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [X] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [X] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.35.0

### Architecture

x64

### Storage Explorer Build Number

20240810.1

### Platform

All

### Bug Description

When I search for a container using the _Open Container by Name_ feature from the tree view, it seems like it will only search the containers loaded in the tree view. When I use the View All feature, I can search for _all_  of my containers.

### Steps to Reproduce

1. Launch explorer
2. Go to Blob Containers node of a storage account
3. Select Open Container by Name
4. Search for container that exists

### Actual Experience

1. Message is displayed: "No results were found"
2. Be scared shitless because you think your data is gone

### Expected Experience

I expect Open Container by Name to search within all containers in your storage account, and not some subset.

### Additional Context

We have hundreds of containers of which the names are basically GUIDs.

**Comment by craxal** [comment]
@marcelvb Open Container by Name does indeed search all containers in your account, not a subset. What search terms were you using, and what were the names of the containers you were expecting to see? Please note that it searches containers by _prefix_. This is due to a limitation of the List Containers API only searching by prefix. Anything more than that would require client-side functionality and has a detrimental effect on performance. Also check your casing. I'm not sure if prefix search is case sensitive.

**Comment by ebudimlic** [comment]
Workaround that seems to do the job is to click on View All first.  After that Open Container by Name seems to work fine.

**Comment by craxal** [comment]
@ebudimlic Are you saying you also experience this issue? Can you share a GIF or video of you reproducing the issue? I am not able to reproduce on my end.
