### ISSUE TITLE
Sign-in Error: Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found

### ISSUE THREAD

**Issue by SSG11082** [microsoft/AzureStorageExplorer#8247]
Below is the error I am facing when trying to sign-in to Azure Storage explorer. It was working fine earlier and started getting this error after a week of not logging in.

{
  "message": "\"Only loopback redirect uri is supported, but urn:ietf:wg:oauth:2.0:oob was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details\""
}

**Comment by MRayermannMSFT** [comment]
@SSG11082 

- What version of Storage Explorer are you using?
- What Azure environment are you signing into? (Azure, Azure China, etc.)
- What sign-in method do you have selected in settings? (Auth broker, default browser, integrated sign-in, etc.)

**Comment by simonfox** [comment]
I'm having the same problem after updating:

![Image](https://github.com/user-attachments/assets/5257e226-17c6-4f0b-9c77-d6bdf7eb456e)

Signing into Azure:

![Image](https://github.com/user-attachments/assets/6d2976e3-05f6-4786-9c16-8ebc9d8325c7)

**Comment by SSG11082** [comment]
> [@SSG11082](https://github.com/SSG11082)
> 
> * What version of Storage Explorer are you using?  1.36.0
> * What Azure environment are you signing into? (Azure, Azure China, etc.) Azure
> * What sign-in method do you have selected in settings? (Auth broker, default browser, integrated sign-in, etc.)  - After I select Subscription and Azure, it redirects me to direct sign-in and then error. not giving any option to choose sign in method
> * Can you try doing "Help" -> "Reset" -> choose only authentication -> select reset/ok -> restart Storage Explorer and try signing in again : Tried it and did not work. Still facing the same error.

Hello


![Image](https://github.com/user-attachments/assets/bab52dc6-ad4b-48fe-87d9-7661be4c8d8f)

**Comment by JasonYeMSFT** [comment]
If you are still able to reproduce the issue, could you please do us a favor to turn on the verbose logging, collect the authentication logs and share the logs with us? The logs may help us locate the cause of the issue and make a fix.

There are detailed instructions in this section of our troubleshooting guide
https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs

**Comment by JasonYeMSFT** [comment]
While we are investigating the issue, could you try changing the sign-in method to "default browser" and see if allows you to work around the issue as suggested by comments in this issue https://github.com/microsoft/AzureStorageExplorer/issues/8237? It would be very appreciated if you can reproduce the issue one more time and share the log with us.

**Comment by craxal** [comment]
Due to how widespread this issue is, we will be releasing 1.36.2 very soon to revert the default authentication method for Windows users.

For anyone having this issue, we invite you to do the following:

## Help us diagnose

1. Install Storage Explorer 1.36.x.
2. Ensure you are signed out and that the "Sign in with:" setting is set to "Authentication Broker".
3. Follow the [troubleshooting docs](https://learn.microsoft.com/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs) to gather authentication logs.
4. Please clear out any existing logs from the logs folder if you can.
5. Share your logs by posting a comment in #8237!

## Unblock yourself

1. Install Storage Explorer 1.36.x.
2. Change the value for the "Sign In with:" setting to be "Default Web Browser".
3. Try signing in.

Thank you everyone for your patience and your help in diagnosing this issue!
