### ISSUE TITLE
Unable to login via Azure on Azure Storage Explorer

### ISSUE THREAD

**Issue by riyazmunsoori** [microsoft/AzureStorageExplorer#8264]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Storage Explorer Version

1.36.1

### Architecture

x64

### Storage Explorer Build Number

20241023.2

### Platform

Windows

### OS Version

Windows 11

### Bug Description

Error Details
If you cannot resolve this issue on your own, you may open an issue on the Storage Explorer GitHub site. Please include the details below to help us diagnose your issue. Make sure to redact any personal information you do not wish to make public before posting.
{
  "name": null,
  "message": "{\"source\":{\"accountId\":\"00000000-0000-0000-6eb4-f5c7611e9c29.9188040d-6c67-4c5b-b112-36a304b66dad:666446FFA39D8AF9E3F8ADB1ACD75DE573935F2F62E51D8AFD6362BDDCA142C3\",\"tenantId\":\"cd2257a2-56c4-4d00-a7aa-14da6496f3b0\"},\"resourceId\":\"https://management.core.windows.net/\",\"code\":\"AADSTS50076\",\"message\":\"Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '797f4846-ba00-4fd7-ba43-dac1f8f63013'. Trace ID: 179aa3fa-15fb-47ca-8c34-b43b3674a100 Correlation ID: bffed923-32ac-4fac-9387-71354121f424 Timestamp: 2024-10-28 12:24:29Z\"}"
}
Copy and Report Issue
Close

### Steps to Reproduce

1. Launch Storage Explorer
2. On Get Started page, use Sign in with Azure.
3. Follow the steps to sign in.
4. Unfilter the "default directory" option and it starts loading the resources.
5. Then the issue occurs.

### Actual Experience

Unable to sign in: WAM Error
Error Code: 0
Error Message: ApiContractViolation
WAM Error Message: Disallowed additional query parameter was used: 'domain_hint'
Internal Error Code: 590899090
Possible causes:
- Invalid redirect uri - ensure you have configured the following url in the application registration in Azure Portal: ms-appx-web://microsoft.aad.brokerplugin/e0001ebd-e920-49b8-a27e-92e573ec0af6

**Comment by MRayermannMSFT** [comment]
Thank you for raising this issue. We have steps that:
 
- We'd like y'all to follow to help us gain further information on why WAM isn't working for you
- You can follow to unblock yourself
 
## Steps to help us gain information
 
1. Install Storage Explorer 1.36
1. Ensure you are signed out, and that "Authentication Broker" is the value for the "Sign In with:" setting
1. Follow these docs to gather authentication logs: https://learn.microsoft.com/en-us/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs
   - Please clear out any existing logs from the logs folder if you can.
1. Share your logs here!
 
## Steps to unblock yourself
 
1. Install Storage Explorer 1.36
1. Change the value for the "Sign In with:" setting to be "Default Web Browser"
1. Try signing in
 
Thanks!

**Comment by craxal** [comment]
Due to how widespread this issue is, we will be releasing 1.36.2 very soon to revert the default authentication method for Windows users.

For anyone having this issue, we invite you to do the following:

## Help us diagnose

1. Install Storage Explorer 1.36.x.
2. Ensure you are signed out and that the "Sign in with:" setting is set to "Authentication Broker".
3. Follow the [troubleshooting docs](https://learn.microsoft.com/troubleshoot/azure/azure-storage/blobs/alerts/storage-explorer-troubleshooting?tabs=Windows#authentication-logs) to gather authentication logs.
4. Please clear out any existing logs from the logs folder if you can.
5. Share your logs by posting a comment in #8237!

## Unblock yourself

1. Install Storage Explorer 1.36.x.
2. Change the value for the "Sign In with:" setting to be "Default Web Browser".
3. Try signing in.

Thank you everyone for your patience and your help in diagnosing this issue!
