### ISSUE TITLE
Creating a thumb.db file and showing icons of images in an Azure file server

### ISSUE THREAD

**Issue by joel74** [microsoft/AzureStorageExplorer#8265]
### Preflight Checklist

- [x] I have installed the [latest version of Storage Explorer](https://github.com/Microsoft/AzureStorageExplorer/releases/latest).
- [x] I have checked existing resources, including the [troubleshooting guide](https://docs.microsoft.com/azure/storage/common/storage-explorer-troubleshooting) and the [release notes](https://github.com/microsoft/AzureStorageExplorer/releases).
- [x] I have searched for [similar issues](https://github.com/Microsoft/AzureStorageExplorer/issues).

### Problem

We use Azure Storage Explorer to store graphic files. Would it be possible to replicate the functionality in File Explorer that creates icons and stores them in a thumbs.db file, and then allow changing the view for a folder to show them?

### Desired Solution

I'd like the option to set the view for a folder to an icon view, to see icons of graphics files.

**Comment by craxal** [comment]
This sort of feature is really out of scope for Storage Explorer and isn't very suitable for a cloud environment. Should we consider it, we would have to take into account a lot of factors:
* Since all the images are in the cloud, we'd have to download all of them to form the thumbnails. Image processing isn't cheap on performance.
* We have to consider multiple use cases for containers. Many containers have large numbers of files and are read from and written to constantly. Trying to keep a thumbnail file up to date for situations like this would be a difficult problem all on its own.
* Containers or folders with many, many blobs would result in a very large thumbnail file. Downloading, processing, and rendering contents from this thumbnail file will take time and could significantly impact performance.

If you need thumbnails for quick browsing, if your files are stored in an Azure File Share, you could mount the file share onto your local machine and navigate using Windows File Explorer directly. That way, you'd get all of the thumbnail support right from the OS.
