### ISSUE TITLE
The editors of restored tabs (except for the first tab) will display as blank if the tabs have a relevant parts of the node path

### ISSUE THREAD

**Issue by v-xianya** [microsoft/AzureStorageExplorer#8273]
**Storage Explorer Version**: 1.37.0-dev (102)
**Build Number**: 20241029.5
**Branch**: main
**Platform/OS**: Windows 11/Windows 11/Linux Ubuntu 22.04/MacOS Sequoia 15.0(Apple M1 Pro)
**Architecture**: arm64/x64/x64/arm64
**How Found**: Exploratory testing
**Regression From**: Not a regression

## Steps to Reproduce ##
1. Launch Storage Explorer -> Make sure the setting 'Preserve Explorer Session' is checked.
2. Expand one storage account -> Blob Containers.
3. Select one blob container -> Pin it to Quick Access.
4. Open the blob container and then open the QA blob container.
5. Restart Storage Explorer.
6. Check whether the editors of the restored tabs display correctly.

## Expected Experience ##
The editors of the restored tabs display correctly.

## Actual Experience ##
The editors of the restored tabs display as blank.
![Image](https://github.com/user-attachments/assets/d234c68c-a756-4153-95b9-0df043db60c5)

**Comment by v-xianya** [comment]
Hi @craxal @richardMSFT 

Today, we discovered that if there are two tabs with the same display name, all restored tabs except the first one will display as blank.
 T**his issue is a regression bug from version 1.35.0.**

![Image](https://github.com/user-attachments/assets/2448b9d7-9b19-4475-8ebd-826621854ad8)

**Comment by craxal** [comment]
In my case, I don't think any of the tabs have to have matching names. I've noticed it happens specifically to tables and queues.

@richardMSFT Let's make absolutely sure tab restoration is working correctly with or without differentiation data. Let's also make sure in upgrade scenarios that tabs aren't breaking.

**Comment by maps-mike** [comment]
Similar issue here - tabs blank possibly because my IP has changed & I no longer have access to a storage account due to storage firewall.

However, once my IP is added to the Storage firewall all preserved tabs remain blank - it feels like a refresh would resolve but the tool bar is not present on the blank tabs.

**Comment by craxal** [comment]
@maps-mike This is unrelated related to your IP address changing or the need for a refresh.

We looked into it and found a subtle bug in our UI code. We defer loading any panel UI for tabs until the tab is selected and its content is to be shown. A variable that triggers loading wasn't getting updated as expected, so the tab content wasn't getting loaded. Hence why the tab would appear blank.

The fix is relatively easy. We will update you on progress and when to expect a fix.

**Comment by maps-mike** [comment]
Awesome - glad its an easy fix! 

Version 1.36.2 (103)

**Comment by v-kellyluo** [comment]
Verified this issue on the build 20241109.1. Reproduce. Will verify it on the newer build.
