### ISSUE TITLE
Display blob metadata in object list

### ISSUE THREAD

**Issue by superstator** [Microsoft/AzureStorageExplorer#829]
We make use of metadata properties in our blob containers, and it would be very helpful to be able to select one or more properties to display as custom columns when viewing a blob container. 

#### Steps to Reproduce: ####
Navigate to a blob container, note that only "standard" properties like Name, Size, or Last Modified are visible in the list view, and no customization options are available.

#### Desired Experience: ####

Right-click header row to show/hide standard columns, and add columns for custom metadata properties.

**Comment by MRayermannMSFT** [comment]
Hi @superstator , although we like this idea, due to API limitations, doing this would have huge performance impacts. We'd need to call get blob properties on every blob before being able to display them in the table. We're going to go ahead and close this issue for now, but if anything with the API changes we can look back into it. Thanks for the good suggestion!
