### ISSUE TITLE
Fail to save the added properties on Properties dialog

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#917]
**Storage Explorer Version**: 1.5.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20181128.5
**Commit**: 21f66e3b
**Regression From:** Not a regression

#### Steps to Reproduce: ####
1. Add '**Reader**' and '**Storage Blob Data Contributor(Preview)**' roles on storage account scope.
2. Expand this account -> Create a blob container -> Upload one blob to it.
3. Open the Properties dialog for this blob -> Try to add properties or metadata for it.
4. Check the result.

#### Expected Experience: ####
Succeed to save the added properties for the blob.

#### Actual Experience: ####
Fail to save the added properties for the blob with the error.
![save](https://user-images.githubusercontent.com/34729022/49146246-b41a2600-f33c-11e8-955c-4a0fce640b2d.png)

**Comment by jinglouMSFT** [comment]
If the account only has the RBAC permissions without the name/key permission, you then only have READ permissions, so you should not be able to add/save properties, which means this is an expected behavior.  The error message is not very clear which we are currently working on modifying the error message.

**Comment by v-xuanzh** [comment]
Updates the assigned roles as **Reader**' and '**Storage Blob Data Contributor(Preview)**.
