### ISSUE TITLE
Unable to perform Delete action for one ADLS Gen2 blob which name contains non-English characters

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/AzureStorageExplorer#980]
**Storage Explorer Version**: 1.7.0
**Platform/OS Version**: Windows 10/ MacOS High Sierra/ Linux Ubuntu 16.04
**Architecture**: ia32
**Build Number**: 20190312.3
**Regression From**: Not a regression

#### Steps to Reproduce: ####
1. Expand one ADLS Gen2 account -> Blob Containers node.
2. Open one blob container ->Upload one blob which name contains non-English like '五星红旗'.
3. Right click the uploaded blob then try to delete it.

#### Expected Experience: ####
The uploaded blob can be deleted successfully.

#### Actual Experience: ####
Unable to delete the uploaded blob with the error.
![image](https://user-images.githubusercontent.com/34729022/54262789-5d6fdb00-452c-11e9-9553-5fbda809278d.png)

#### More info: ####
This issue doesn't reproduce for non - ADLS Gen2 blobs.

**Comment by larrylieberman** [comment]
I am seeing this exact error today, on attempting to open "Manage Access" on an object, with this version:

Version: 1.6.2
Platform: macOS
Architecture: x64
Build Number: 20190108.2
Commit: b3158558
Support Id: b01b4d84-35e5-b355-9f36-fc1fb42908dd

The file object has a name with square brackets in it " [ ] ". This is problematic, because Azure Data Factory, when orchestrating files out of a relational DB, defaults to using a filename with these characters.

If I change the filename to remove the [] characters, "Manage Access" works as expected.

**Comment by MRayermannMSFT** [comment]
Hi @larrylieberman , just wanted to update you on this issue. There appears to be a bug in the Storage SDK we are using. We're looking to either find a workaround or get the SDK update in time for 1.8.0. Thank you for your patience!

**Comment by arrayelement** [comment]
I am seeing this issue, but with a file that contain all English characters. 
The json returned from Storage Explorer 1.7.0 is attached
[ase_delete_blob_error_json.txt](https://github.com/Microsoft/AzureStorageExplorer/files/2980712/ase_delete_blob_error_json.txt)

**Comment by jinglouMSFT** [comment]
@arrayelement Are you running behind a proxy and using ADLS Gen2?  If so, you might have run into a bug in delete that uses axios, which is a different bug.  Please let us know if this is the case.  Thanks.

**Comment by arrayelement** [comment]
@jinglouMSFT  Yes I am running behind a proxy and using ADLS Gen2 via Storage Explorer 1.7.0  I saw in the SE 1.7.0 release notes that some proxy issues were being addressed but that they are sill being refined. Hope the next release of storage explorer has these issues fixed.  Looks like @MRayermannMSFT previous post might be addressing this issue in SE 1.8.0.

**Comment by jinglouMSFT** [comment]
@arrayelement yes, the fix will be in 1.8.0 for sure.  Let us know if you are interested in a private build to unblock you from deleting.  Thanks.

**Comment by MRayermannMSFT** [comment]
A fix for the issue where some things don't work for ADLS Gen2 blobs that have unicode chars in the name has been checked into master and will be available in 1.8.0. This fix does not address any of remaining proxy issues with ADLS Gen2. A fix for those is still a ways away/depdendent on other teams unfortunately. Anyway, closing this issue since it is fixed.
